### ISSUE TITLE
WOWZA with restricted access

### ISSUE THREAD

**Issue by johnnyrlq** [mikaku/Monitorix#100]
First of all thank you for the great job with MONITORIX.
I have installed MONITORIX to monitor my WOWZA server but I have some observations:
When I set up the wowza URL with "http://wowzaIPserver:8086/connectioncounts"
 It works great. 

    <wowza>
        list = http://wowzaIPserver:8086/connectioncounts
        <desc>
                http://wowzaIPserver:8086/connectioncounts = live1, live2
        </desc>
        rigid = 0, 0, 0, 0, 0
        limit = 100, 100, 100, 100, 100
    </wowza>

But if I use the next URL "http://username:password@wowzaIPserver:8086/connectioncounts" the monitorix can not monitor my server. 

    <wowza>
        list = http://username:password@wowzaIPserver:8086/connectioncounts
        <desc>
                http://username:password@wowzaIPserver:8086/connectioncounts = live1, live2
        </desc>
        rigid = 0, 0, 0, 0, 0
        limit = 100, 100, 100, 100, 100
    </wowza>
 Is there another config I have to do?
Thank you in advance.

**Comment by mikaku** [comment]
Can you, please, paste the error messages in the log file?
Thanks.

**Comment by johnnyrlq** [comment]
Dear @mikaku thank you for your response.
Finally it works but I have to make some changes.
I found some reference here:
    http://www.wowza.com/forums/showthread.php?15165-get-connectioncounts-from-perl-for-accumulation

In the file /usr/lib/monitorix/wowza.pm, I hardcoded with parameters "username" and "password".
It could be much betther adding this parameters in the config file (/etc/monitorix/monitorix.conf).

Thank you very much.

**Comment by mikaku** [comment]
I think that modifying yourself the code isn't the best approach since it will be force you to modify it again on every Monitorix update.

I'm working on a patch that will work just sub-classing LWP::UserAgent without changing the current configuration in `monitorix.conf`. It's based on this <http://perlmaven.com/lwp-useragent-and-basic-authentication>.

I'll update `wowza.pm` in the next hours. Stay tuned.
Regards.
