### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by Tarjaizaid** [mikaku/Monitorix#105]
Hello Mikaku

i've some issue 

I've a Debian jessie recently installed.

After have installed Monitorix from git, i've some issue

- error on startup

i have not changed configuration file and no file in conf.d but when monitorix start :

Sun Aug 23 17:30:38 2015 - Starting Monitorix version 3.7.0 (pid 10843).
Sun Aug 23 17:30:38 2015 - Loaded main configuration file '/etc/monitorix/monitorix.conf'.
Sun Aug 23 17:30:38 2015 - Loading extra configuration file '/etc/monitorix/conf.d/00-debian.conf'.
Use of uninitialized value in lc at /usr/lib/monitorix/Monitorix.pm line 361.
Use of uninitialized value in lc at /usr/lib/monitorix/Monitorix.pm line 420.
Use of uninitialized value in lc at /usr/lib/monitorix/Monitorix.pm line 444.

this issue disappears when the option ipv6_disabled is present in configuration file.

- ipv6 

i use "port" feature with ipv6, and, when i start monitorix :

Use of uninitialized value in lc at /usr/lib/monitorix/port.pm line 150.
Sun Aug 23 17:46:56 2015 - port::port_init: IPv6 is explicitly disabled, you shouldn't want to monitor 'tcp6' or 'udp6' protocols.

IPv6 is explicitly disabled ? however, https://github.com/mikaku/Monitorix/commit/065f09588fa1e3e0f612c88b2782ffa6be0d16b4 say ipv6_disable is default set to no.

i add ipv6_disabled = no to my configuration file : no lc value error but ipv6 always disabled
if i set ipv6_disabled = yes i've the same error.

Sun Aug 23 17:53:47 2015 - Initializing graphs.
Sun Aug 23 17:53:47 2015 - port::port_init: IPv6 is explicitly disabled, you shouldn't want to monitor 'tcp6' or 'udp6' protocols.
Sun Aug 23 17:53:47 2015 - port::port_init: IPv6 is explicitly disabled, you shouldn't want to monitor 'tcp6' or 'udp6' protocols.

Graph are available on web page but ip6tables rules are not generated

port feature are not aware with this new option ?

- Configuration file parsing

To avoid to edit monitorix.conf file, i prefer use a file in conf.d directory.
I think that you add this feature for that

But, with "process" the monitorix.conf enable this graph. I've add process in my personnal configuration file, and i've 2 process statitics graph.

If i edit the monitorix.conf, i must reedit it when this file will be modified and updated by Git.

So, it's normal or do you think to add some code to avoid this ?

- Installation with MakeFile

With debian, the stable distribution use systemd.

When i install Monitorix, i must use :

make install-debian-all
make install-systemd

For newcomer, this is not easy :)

I think that add a "install-debian-systemd" option can clarify this.

Thank you :)
++
Tarjaizaid

**Comment by mikaku** [comment]
The above commit should fix the first sub-issue.

**Comment by mikaku** [comment]
The commit below should fix the second sub-issue **ipv6**

**Comment by mikaku** [comment]
Regarding your third sub-issue **Configuration file parsing**, I don't understand what are you trying to say. Keep in mind that extra configuration files are loaded **after** the main configuration file, so it means that any option in the main configuration file will be overwritten by the same option in the extra configuration file.

Regarding your last sub-issue **Installation with MakeFile**, you should address it directly to @graysky2 who created such Makefile. Anyway, I recommend you using the default package manager (**aptget**) on Debian systems when installing Monitorix.

Thanks.

**Comment by graysky2** [comment]
Well, the problem with Ubuntu/Debian in this context is there are older, legacy build out there that do not use systemd even though current ones do.  The Makefile should be flexible enough to allow users both options (systemd or legacy init systems).

**Comment by mikaku** [comment]
@graysky2,

Thanks for your quick answer, I'm agree with you.
Regards.

**Comment by Tarjaizaid** [comment]
@graysky2 good idea :+1: 

@mikaku 
For "Configuration file parsing", ok for your explanation, however, i think there are a issue.

I've settings for process module on my own configuration file.
process = y 
and custom conf 
<process>
        <list>...
</process>

when i look http page, i see the graph provided by monitorix.conf
<process>
        <list>
                0 = httpd, sshd,....
</process>

it's a issue ?

Sorry for the delay of my reply

**Comment by Tarjaizaid** [comment]
this is weird, i have the same options on another server but without the issue.

**Comment by mikaku** [comment]
Oh, now I understand it.

It could be indeed a problem when showing graphs and having multiple configuration files, because `monitorix.cgi` only loads the main configuration file based in the file `/var/lib/monitorix/www/cgi/monitorix.conf.path`.

This is indeed a bug.

I'll fix that bug just appending all extra configuration files in `monitorix.conf.path`.

**Comment by mikaku** [comment]
Nah ... sorry. That was a false alarm, I don't see any bug here.

The file `monitorix.cgi` loads correctly the extra configuration files right after loading the main configuration file using the path provided in `/var/lib/monitorix/www/cgi/monitorix.conf.path`.

Please, double-check your Monitorix installation and your Monitorix log file to see if there are some error messages on this.

Thanks.

**Comment by Tarjaizaid** [comment]
Hello,
I've found :), I made a mistake.  i used the number "1" for "<process> <list>"on my own configuration file and monitorix parse the 0 "sequence" on the monitorix.conf.
this isn't an issue :) Sorry

**Comment by mikaku** [comment]
OK, so if all is correct, please, close this issue.
Thanks.
