### ISSUE TITLE
Icecast 2.4.x

### ISSUE THREAD

**Issue by Evrus** [mikaku/Monitorix#108]
Icecast Streaming Media Server (icecast.rrd) not work.
http://radio.eve-play.ru:8000/status.xsl

**Comment by mikaku** [comment]
@Evrus,

It works for me:

![icecast](https://cloud.githubusercontent.com/assets/829885/9847402/e454f444-5ad8-11e5-9466-7390c0823d05.png)

This is my setup:

```
<icecast>
        list = http://radio.eve-play.ru:8000/status.xsl
        <desc>
                http://radio.eve-play.ru:8000/status.xsl = /everadio32, /ruseveradio
        </desc>
        graph_mode = r
        rigid = 0, 0
        limit = 100, 100
</icecast>
```

**Comment by mikaku** [comment]
I've seen that the color of some values in the `Current listeners` are hidden (covered) by the color of the first value (this picture has the colors fixed):

![icecast](https://cloud.githubusercontent.com/assets/829885/9847855/6d19702c-5adc-11e5-9165-9670118ec3f9.png)


The following commit fixes this bug.
Regards.

**Comment by undee123** [comment]
Hi folks,

I've installed monitorix to check my icacast server, but I don't get real time statistics, it takes several minutes to show the current listeners. Refresh rate is set to 20 (was 150), but didn't change anything.

Config is same as mikakus.

**Comment by mikaku** [comment]
> but I don't get real time statistics, it takes several minutes to show the current listeners

I don't understand this, you mean that you don't get stats but at the same time it seems you finally see the current listeners?

What you see in the Monitorix graphs are average values, and of course, they might take a few minutes to start showing results. That's completely normal.

In the other hand, the sampling rate of Monitorix is 60 seconds, so any refresh in the web site less than this time is useless. Also, the quicker you refresh your web site the more it will impact in the load average statistics. 150 seconds or more is fine.

**Comment by undee123** [comment]
Ok, I'll make an example to make it clear.
This is my actual statistic:

![image](https://cloud.githubusercontent.com/assets/7920265/20748301/e5683220-b6ed-11e6-94f6-7edf4f8b20ec.png)

Now when I open the streams on some devices to get more listeners, the status page on the icecast servers shows them instantly, while the monitorix server needs a few minutes just to show the correct number of the actual listeners (I don't mean the graph, just the number of the current users).

**Comment by mikaku** [comment]
Yes, as I said before, the Monitorix sampling rate is 60 seconds (1 minute), this means that Monitorix will take up to 1 minute to get the new value of listeners, and that value, if it's constant enough, will appear in the graph in the next 2 or 3 minutes. This is how it works in most monitoring programs.

In the other case, if that new listener only was there for about 1 minute, then Monitorix probably will show a fraction of that listener, that is, instead of 2 listeners probably will show 2.5 listeners during the next minute, and will return to 2 listeners later.

I hope that clear up things to you.
