### ISSUE TITLE
Use of uninitialized value in lc at /usr/lib/monitorix/port.pm

### ISSUE THREAD

**Issue by skibbipl** [mikaku/Monitorix#110]
Hello,
After upgrading to 3.8.0 on my debian server I started getting follwoing errors in monitorix.log:
`Use of uninitialized value in lc at /usr/lib/monitorix/port.pm line 222.`
`Use of uninitialized value in lc at /usr/lib/monitorix/port.pm line 252.`
There are no other errors that might direct me what is wrong. I doublecheck my ports config, and it seems to be correct according to documentation.

**Comment by mikaku** [comment]
@skibbipl,

The following commit should fix that annoying message, please let me know.
Thanks.

**Comment by skibbipl** [comment]
Yes, this seems to fix this issue. Thanks!
