### ISSUE TITLE
Icecast - single graphic per mountpoint / mountpoints order

### ISSUE THREAD

**Issue by marcgbs** [mikaku/Monitorix#113]
Hello and thanks for sharing this project. I'm testing Monitorix as a monitoring tool for Icecast. I have it running on a local test server with Ubuntu 14.04 and Icecast 2.3.3.

I would like to generate a single graph for every single mountpoint. Is it possible?

Also, I would like to ask what happens if one of the mountpoints disconnects. I assume when one of the streams get disconnected and automaticly reconnects after a while, the order of the mountpoints would change and the statistics would crash. Right?

**Comment by mikaku** [comment]
Hello,

Having a single graph for every single mount point is a waste of screen space, but of course, you are able to do it.

The problem is that each mount point must have a different URL to be defined in the `list` option, otherwise you won't be able to do that because you'll end up repeating the same URLs, which would be a configuration error.

I hope that helped you.
Regards.

**Comment by marcgbs** [comment]
It helped!! Thank you Jordi.

I've set as much subdomains as mountpoints, all pointing to the same server. Now Monitorix is tracking every mountpoint's statistics in a separate graph.

I send you a copy of my configuration just in case anyone else is wondering how it works. 

-----------------------------------


# ICECAST graph
# -----------------------------------------------------------------------------
<icecast>

        list = http://radio.domain.com:8000/status.xsl, http://radio1.domain.com:8000/status.xsl, http://radio2.domain.com:8000/status.xsl
        <desc>
                http://radio.domain.com:8000/status.xsl = /radio.mp3
                http://radio1.domain.com:8000/status.xsl = /radio1.mp3
                http://radio2.domain.com:8000/status.xsl = /radio2.mp3

        </desc>

        graph_mode = r
        rigid = 0, 0
        limit = 1000,1000000000
</icecast>

**Comment by mikaku** [comment]
Glad to be of help.
Thanks.
