### ISSUE TITLE
Mail Graph enhancements

### ISSUE THREAD

**Issue by IzzySoft** [mikaku/Monitorix#118]
Taking a look at the "Mail Statistics" graph, I miss a few "lines" – which could be either integrated into the "main graph" (top-left), or outsourced to a new graph: Details on rejected messages. I'm using Postfix, so my examples will refer to that.
- **Spamtraps:** Thanks to my little honeypot (and some "old abused addresses"), I've setup spamtraps via `smtpd_recipient_restrictions` with `check_recipient_access regexp:/etc/postfix/spamtraps`. To identify the corresponding lines in the logs, this would need a config setting for the matching log entry, as that's user-defined in this case (e.g. `triggers spamtrap`)
- **RBL:** how many msgs get rejected via blacklists? On my old server (running a different mail software and now being migrated), those made up 80%+ of all traffic, so it's definitely nothing to be ignored. RBL is a built-in feature of Postfix (same place, `reject_rbl_client` keyword). I'd recommend a config setting nevertheless (so it can be overridden if needed). Default pattern with Postfix looks like `Client host [204.12.225.53] blocked using zen.spamhaus.org`

If "outsourced" to a separate graph, you might consider taking "Spam" and "Virus" along – to have the "bad guys" all grouped together. Spamtraps & RBL should reflect in the main graph's "Rejected" item, so Spam/Virus could be replaced there e.g. as a summary "Filtered" (those with a high enough spam level would most likely even fall into the "Discarded" section).

---

While being on it: SPF graph lacks the "errors", e.g.

```
postfix/policy-spf[11994]: Policy action=PREPEND Received-SPF: permerror
```

Currently, that would be matched as "softfail" in line 383, so before the `else` in 381 it might need:

```
} elsif(/: permerror/) {
```

Not sure for the "other SPF handlers" block below, probably it's something like `SPF permerror` there.

**Comment by mikaku** [comment]
I don't see room for another small graph without breaking the layout, so I think that the best approach would be to include the new stats in the *main graph* (top-lef) which there are some blank lines waiting for more data.

Currently stats for Postfix MTA are collected using the command `pflogsumm`, so as long as those new values (**Spamtraps** and **RBL**) appear in its output it shouldn't be much difficult to include them.

**Comment by IzzySoft** [comment]
I doubt the Spamtraps will appear (custom rules), while I think RBL might. I'm aware it's currently done via `pflogsumm` (as an error message told me Monitorix needed it) – so if you let me know a command to test with, I can do so as soon as both are hit (which I expect will start next week, when I've migrated the next domain to the new server).

**Comment by IzzySoft** [comment]
Update: My doubts were correct: Spamtraps show just in their action (e.g. "6   discarded (4%)" with my configuration). To figure it was a Spamtrap would require parsing the maillog. I assume for RBL it will be similar, and those would only turn up in the "rejected" sum.

If you consider parsing the logs:

~~~
postfix/smtpd\[\d+\]: NOQUEUE: reject: RCPT from .+: 554 5.7.1 Service unavailable; Client host \[[\d+\.]+\] blocked using
~~~

would be the regex for RBL with Postfix. Spamtraps are realized via custom config, and in my case be matched by something like `postfix/smtpd\[\d+\]: NOQUEUE:.+Recipient address triggers spamtrap`. It's set up using `check_recipient_access regexp:<file>`:

~~~
# Syntax:
#   <regex matching address> <action> <logstring>
/.foobar@.+/i                 DISCARD triggers spamtrap
~~~

So if you want to parse that from the logs, "action" and "logstring" must be configurable (though I don't see why something other than DISCARD should be used here, others might wish to REJECT instead).

Yo, 3rd domain moved to my Banana – graphs start filling up. With the first two together I had less than 30 mails per day on average – now I need to prefix that with another digit. Spam percentage was below 20% until yesterday – now it's up to almost 90%, yuck …

… and thanks for the SPF graph! That gave me the right trigger to avoid more of that spam, setting up a policy daemon for that. Cool thing, already saw several hard fails which kept the bad guys out with their P* enlargers (too big, you can't PASS here, LOL)

As for "another graph won't fit": for me personally, it could replace the greylist one. But I'm afraid not everyone agrees with that … Alternatively: make the "network traffic" graph another small one, resize "mail statistics" in its height, and have a row of 3 small graphs at the bottom of this block, with "Greylisting" being the right-most one?

**Comment by IzzySoft** [comment]
@mikaku I've added another item to my initial post about the missing "SPF permerror" in the SPF graph. At least with that it's clear where it should go. As I pointed out there, with the Postfix `postfix-policyd-spf-perl` solution, those are currently dealt with as "softfail" – which is better than not being dealt with at all, but not really correct.

**Comment by mikaku** [comment]
Monitorix already parses the logs in order to collect specific entries like `MailScanner`, `Amavis`, SPF stuff, etc. Therefore it shouldn't be difficult to collect RBL entries if they are consistent and belong to a specific MTA (Sendmail, Postfix, etc.).

Just, please, specify which log entries Monitorix should collect for RBL and I'll add that value in the graph.

**Comment by IzzySoft** [comment]
As specified in [this post](https://github.com/mikaku/Monitorix/issues/118#issuecomment-149042392), an RBL regex for Postfix looks like this:

~~~
postfix/smtpd\[\d+\]: NOQUEUE: reject: RCPT from .+: 554 5.7.1 Service unavailable; Client host \[[\d+\.]+\] blocked using
~~~

with the first `\d+` being the pid, and the second the client IP. Example for an SPF permerror:

~~~
postfix/policy-spf[11994]: Policy action=PREPEND Received-SPF: permerror
~~~

(only the relevant part). Again, Postfix – and `postfix-policyd-spf-perl` as SPF policy daemon in this case. Spamtraps would need either a config var in Monitorix – or Monitorix using a fixed term, forcing the user to adjust that in the Postfix config. I'd prefer the former (more flexible, and could be used for other mailers without your intervention hopefully).

**Comment by mikaku** [comment]
>
@mikaku I've added another item to my initial post about the missing "SPF permerror" in the SPF graph. At least with that it's clear where it should go. As I pointed out there, with the Postfix postfix-policyd-spf-perl solution, those are currently dealt with as "softfail" – which is better than not being dealt with at all, but not really correct.
>

I don't see enough room for a fifth value in the SPF graph right now, so adding the line 381 as you suggested in a previous post won't fix anything.

If you want I might include these *SPF permerror* into the *Fail* value instead of *Softfail*.
Just let me know.

**Comment by mikaku** [comment]
Regarding RBL, as long as Postfix reports the same line for these rejected RBL hits:

```
postfix/smtpd\[\d+\]: NOQUEUE: reject: RCPT from .+: 554 5.7.1 Service unavailable; Client host \[[\d+\.]+\] blocked using
```

it should be relatively simple to add the new value in the Postfix graph.

**Comment by IzzySoft** [comment]
> If you want I might include these SPF permerror into the Fail value instead of Softfail.

Quite a while ago, so I'm just wondering what's the difference between "fail" and "permerror". No, if given that choice, softfail is the better fit (and probably close to what it's really dealt with like). Especially with my configuration: hard fails get rejected immediately, while everything else is passed to the next level (SpamAssassin). So a permerror (failed to do a proper lookup due to DNS issues or invalid SPF records) either counts as "no SPF record found" or "softfail". Ergo: If there's no space for a separate value, better leave it as is (but maybe document the what and why somewhere ;)

----

RBL: I give you a few lines of my latest logs to chose from :)

~~~
Jan 18 16:53:39 mailserver postfix/smtpd[14452]: NOQUEUE: reject: RCPT from unknown[185.106.92.69]: 554 5.7.1 <test@gmail.com>: Relay access denied; from=<test@t-ipconnect.de> to=<test@gmail.com> proto=SMTP helo=<win-s264a3p7km0.domain>
Jan 19 14:42:26 mailserver postfix/smtpd[17891]: NOQUEUE: reject: RCPT from unknown[112.197.190.220]: 554 5.7.1 Service unavailable; Client host [112.197.190.220] blocked using zen.spamhaus.org; https://www.spamhaus.org/query/ip/112.197.190.220 / https://www.spamhaus.org/sbl/query/SBLCSS; from=<> to=<someuser@domain.tld> proto=SMTP helo=<112.197.190.220>
Jan 19 19:31:51 mailserver postfix/smtpd[390]: NOQUEUE: reject: RCPT from unknown[201.164.200.146]: 554 5.7.1 <sharon@topele.com>: Relay access denied; from=<York_Nannie@genesismn.com> to=<sharon@topele.com> proto=SMTP helo=<customer-GDL-200-146.megared.net.mx>
Jan 24 11:36:33 mailserver postfix/smtpd[30781]: NOQUEUE: reject: RCPT from unknown[219.239.24.85]: 554 5.7.1 Service unavailable; Client host [219.239.24.85] blocked using zen.spamhaus.org; https://www.spamhaus.org/query/ip/219.239.24.85; from=<liwj@pepris.com> to=<izzy@qumran.org> proto=ESMTP helo=<mail.pepris.com>
Jan 24 17:55:12 mailserver postfix/smtpd[18981]: NOQUEUE: reject: RCPT from unknown[85.204.49.222]: 554 5.7.1 Service unavailable; Client host [85.204.49.222] blocked using ix.dnsbl.manitu.net; Your e-mail service was detected by relay.heise.de (NiX Spam) as spamming at Sun, 24 Jan 2016 17:45:53 +0100. Your admin should visit http://www.dnsbl.manitu.net/lookup.php?value=85.204.49.222; from=<PianoforAll@newlessons.download> to=<someuser@domain.tld> proto=ESMTP helo=<0087e2fd.newlessons.download>
Jan 25 02:15:20 mailserver postfix/smtpd[12271]: NOQUEUE: reject: RCPT from ec2-107-21-116-28.compute-1.amazonaws.com[107.21.116.28]: 554 5.7.1 Service unavailable; Client host [107.21.116.28] blocked using zen.spamhaus.org; https://www.spamhaus.org/query/ip/107.21.116.28; from=<elizabeth_morrison@staging.recruiting.com> to=<someuser@domain.tld> proto=ESMTP helo=<ip-10-9-128-55.ec2.internal>
Jan 26 19:41:51 mailserver postfix/smtpd[10914]: NOQUEUE: reject: RCPT from unknown[91.236.75.196]: 554 5.7.1 <mydrivec@freemailhost.ru>: Relay access denied; from=<smtp2001soho@yahoo.com> to=<mydrivec@freemailhost.ru> proto=SMTP helo=<93.205.121.118>
~~~

Note I've done some sanitizing: server host name is replaced by "mailserver", and "real recipients" on my domains by "someuser@domain.tld". Let me know if you need some more lines :)

**Comment by mikaku** [comment]
Please, check the latest `mail.pm` and let me know if it works as expected.

**Comment by mikaku** [comment]
@IzzySoft, do you think we can close this issue?

**Comment by IzzySoft** [comment]
Ugh, was it still open? Apologies for not answering your last question, but I'm not using Greylisting (thought about it initially, but then dropped the idea).

And yes, let's close this. If I had no issues for 3 years, new ones should go to new issues if any come up, and I always can reference this one if it seems helpful. Thanks again!

**Comment by mikaku** [comment]
Thanks!
