### ISSUE TITLE
Supported RAID controller with smartctl argument in disk module returns no data

### ISSUE THREAD

**Issue by wuffleton** [mikaku/Monitorix#12]
Hi! I threw monitorix on my server a couple weeks ago, and just noticed that the disk module is behaving inconsistently with the FAQ page. It states that I can use my RAID controller and its respective disks if it is supported by smartctl by supplying the appropriate argument for smartctl along with my controller's device. However, my monitorix log file reports that the device is invalid. It's running with a CCISS controller, which is the very example shown on the FAQ page that I was modeling with my config. 
#### Log Entries Produced on Monitorix Start

```
Sun Apr 28 12:21:27 2013 - Starting Monitorix version 3.1.0 (pid 19668).
Sun Apr 28 12:21:27 2013 - ERROR: disk::disk_init: invalid or inexistent device name '/dev/cciss/c0d0 -d cciss,0'.
```
#### Disk Module Config

```
<disk>
        <list>
                0 = "/dev/cciss/c0d0 -d cciss,0", "/dev/cciss/c0d0 -d cciss,1", "/dev/cciss/c0d0 -d cciss,2", "/dev/cciss/c0d0 -d cciss,3", "/dev/cciss/c0d0 -d cciss,4", "/dev/cciss/c0d0 -d cciss,5"
       </list>
</disk>
```
#### Smartctl Working Perfectly Fine, Indicating some Issue with Monitorix

```
[root@WuffServer /etc]# for i in $(seq 0 5); do smartctl /dev/cciss/c0d0 -d cciss,${i} -a | grep 'Current Drive Temperature'; done 
Current Drive Temperature:     20 C
Current Drive Temperature:     20 C
Current Drive Temperature:     20 C
Current Drive Temperature:     20 C
Current Drive Temperature:     20 C
Current Drive Temperature:     19 C
```
#### System Information

OS: Arch Linux
Monitorix Version: 3.1.0-8
Smartmontools Version: 6.1-2
Hardware: Proliant DL380 G3
#### Example of Graph Output

![Screenshot 2013-04-28 - 12 43 27](https://f.cloud.github.com/assets/4283099/436290/60fd0f1c-b03c-11e2-8342-72189ccf1fc5.png)

**Comment by ostasevych** [comment]
Hi! Meanwhile, I have a hp p410i raid controller with 2 arrays (SSD and HDD). I tried to put them into the config file:
```
<disk>
        <list>
                0 = /dev/disk/by-path/pci-0000:00:14.1-ata-1.1
               1 = "/dev/disk/by-path/pci-0000:02:00.0-scsi-0:1:0:0 -d cciss,0", "/dev/disk/by-path/pci-0000:02:00.0-scsi-0:1:0:0 -d cciss,1"
#               2 = "/dev/disk/by-path/pci-0000:02:00.0-scsi-0:1:0:2 -d cciss,2", "/dev/disk/by-path/pci-0000:02:00.0-scsi-0:1:0:2 -d cciss,3"
        </list>
        <desc>
                0 = individual drive /dev/sdc system disk 256GB
                1 = RAID1 /dev/sda data sdd array 500GB
                2 = RAID1 /dev/sdb backup hdd array 2TB
        </desc>
        <map>
               pci-0000:02:00.0-scsi-0:1:0:0 = "data sdd array 500GB"
               pci-0000:02:00.0-scsi-0:1:0:2 = "backup hdd array 2TB"
               pci-0000:00:14.1-ata-1.1 = "system disk"
        </map>
```

So, this is not working, as the monitorix doesn't want to recognise the devices `/dev/disk/by-path/pci-0000:02:00.0-scsi-0:1:0:0 -d cciss,N`

```
<disk>
        <list>
                0 = /dev/disk/by-path/pci-0000:00:14.1-ata-1.1
                1 = "/dev/sda -d cciss,0", "/dev/sda -d cciss,1"
                2 = "/dev/sdb -d cciss,2", "/dev/sdb -d cciss,3"
        </list>
        <desc>
                0 = individual drive /dev/sdc system disk 256GB
                1 = RAID1 /dev/sda data sdd array 500GB
                2 = RAID1 /dev/sdb backup hdd array 2TB
        </desc>
        <map>
                /dev/sda = "data sdd array 500GB"
                /dev/sdb = "backup hdd array 2TB"
                pci-0000:00:14.1-ata-1.1 = "system disk"
        </map>
```
This is working, except mapping 
![image](https://github.com/mikaku/Monitorix/assets/5199030/72087204-bfca-44e5-9d8c-3109626a9f0c)

So, is that possible to fix both issues?

**Comment by mikaku** [comment]
> This is working, except mapping

Mapping keys with spaces and symbols can be tricky. Have you tried to use the complete key, instead of only `/dev/sda`?
I mean something like this:

```
<map>
                /dev/sda -d cciss,0 = "data sdd array 500GB"
                /dev/sdb -d cciss,2 = "backup hdd array 2TB"
                pci-0000:00:14.1-ata-1.1 = "system disk"
</map>
```

**Comment by ostasevych** [comment]
> > This is working, except mapping
> 
> Mapping keys with spaces and symbols can be tricky. Have you tried to use the complete key, instead of only `/dev/sda`? I mean something like this:
> 
> ```
> <map>
>                 /dev/sda -d cciss,0 = "data sdd array 500GB"
>                 /dev/sdb -d cciss,2 = "backup hdd array 2TB"
>                 pci-0000:00:14.1-ata-1.1 = "system disk"
> </map>
> ```

No, that didn't help: any changes.

**Comment by mikaku** [comment]
Let's continue talking in #463.
