### ISSUE TITLE
Minor reminder: deprecated pflogsumm parameters

### ISSUE THREAD

**Issue by IzzySoft** [mikaku/Monitorix#125]
I was just debugging the issue why my mail graphs remained empty (yuck, it's `/var/log/mail.log` on Debian at least, not `/var/log/maillog` – is it really `maillog` anywhere or is that a typo? If typo, please fix – otherwise have me fix it for the `debian.conf` ;). Running the precise command as used in `mail.pm` yields some warnings (nothing fatal *yet* – everything keeps working):

~~~
# pflogsumm -d today -h 0 -u 0 --smtpd_stats --no_bounce_detail --no_deferral_detail --no_reject_detail --no_no_msg_size --no_smtpd_warnings /var/log/mail.log > pflog.txt
pflogsumm: "no_bounce_detail" is deprecated, use "bounce-detail=0" instead
pflogsumm: "no_deferral_detail" is deprecated, use "deferral-detail=0" instead
pflogsumm: "no_reject_detail" is deprecated, use "reject-detail=0" instead
pflogsumm: "no_smtpd_warnings" is deprecated, use "smtpd-warning-detail=0" instead
~~~

You might wish to address this with some future version, so I thought I leave you a reminder here :)

**Comment by mikaku** [comment]
On RedHat Linux systems (RHEL) and derivatives (CentOS, Fedora, SEL, etc.) the filename of the mail log is `/var/log/maillog`. Just change your configuration file and set the `mail_log` option accordingly to your system.

Regarding the deprecated options, could you please provide the version of your `pflogsumm` tool.
Thanks.

**Comment by IzzySoft** [comment]
`pflogsumm` version: 1.1.5-1 (on Debian ARMHF) – and I've adjusted the `debian.conf` accordingly, as I already figured the same (i.e. that `/var/log/maillog` is not a typo but indeed used on several systems). So the `.deb` for the next release will have that fixed without affecting other systems :)

**Comment by mikaku** [comment]
RHEL 6 (genuine) systems (and derivatives) still are using `pflogsumm` version 1.1.1 which wouldn't work anymore if we change to the newer parameters.

If these *warning* messages are not annoying you much I'd prefer to not change them for now, otherwise that would break a lot of current systems running Postfix.

> So the .deb for the next release will have that fixed without affecting other systems :)

That's great! :)

**Comment by IzzySoft** [comment]
> If these *warning* messages are not annoying you much I'd prefer to not change them for now, otherwise that would break a lot of current systems running Postfix.

Fine with me – and no, they don't annoy me as I usually don't see them (you have them `/dev/null`ed, I just encountered them executing the commands manually without the "devnulling"). I'd say just leave the issue open and set a "higher milestone" (or label), so it doesn't get lost – then check again in a year or so?

**Comment by mikaku** [comment]
Well, in fact as soon as these old parameters are not more accepted by `pflogsumm` I'll know it immediately by people using Postfix. Anyway, let's keep it open.

**Comment by mikaku** [comment]
After one year, I think we can close this.
