### ISSUE TITLE
Issues with reading from smartctl in the disk graph

### ISSUE THREAD

**Issue by Darkhand81** [mikaku/Monitorix#127]
The disk graph reads from smartctl to get drive temps, reallocated sector counts, etc.  Per the [smartctl man page](http://linux.die.net/man/8/smartctl), certain device types need to be manually specified in the smartctl command line in order for them to be read.  The Monitorix drive module needs the ability to optionally specify switches that can be passed to smartctl.

For example, I have SATA drives that need the `-d sat` switch to be specified in order for them to be read by smartctl.  Currently Monitorix displays no data for these drives, but does when the switch is manually added to disk.pm

Right now, disk.pm line 211 contains the call to smartctl:

```perl
 open(IN, "smartctl -A $d |");
```

If I manually hard code the switch, smartctl can read from the drives and Monitorix graphs the data:

```perl
 open(IN, "smartctl -A -d sat $d |");
```

The drive section of monitorix.conf could be used to pass optional switches to smartctl and/or hddtemp (though I'm not familiar with the requirements for that one) and would solve the issue.

Thanks for all your efforts, Monitorix is fantastic!

**Comment by mikaku** [comment]
You can already do this as stated in FAQ <http://www.monitorix.org/faq.html#Q117>

```
<list>
	0 = "/dev/cciss/c0d0 -d cciss,0", /dev/sda
</list>
```

**Comment by Darkhand81** [comment]
Well shoot, how did I not see that. :)  Thank you!  Issue can be closed!

**Comment by mikaku** [comment]
OK, thanks anyway for your feedback.
