### ISSUE TITLE
Petabytes

### ISSUE THREAD

**Issue by lewyx8** [mikaku/Monitorix#133]
Hi, 
i have problem with my network usage graphs ( re0 ) indicate that I get petabyte/s transfer speeds. How can I resolve this issue? FreeBSD 10.2

```
# NET graph
# -----------------------------------------------------------------------------
<net>
        list = re0
        <desc>
                re0 = Gigabit Ethernet, WAN, 0, 10000000
        </desc>
        gateway = re0

</net>
```

**Comment by mikaku** [comment]
Hi,

Without a picture to get an idea of what is really happening there will be difficult.
First of all, make sure you are using the latest and greatest 3.8.1, because in 3.6.0 was fixed a problem with unexpected peaks in the network graph:

```
- Changed all DST from COUNTER to GAUGE in 'net' module to avoid unexpected huge
  peaks.
```

Check the `Changes` file.
Regards.
