### ISSUE TITLE
Graph zoom

### ISSUE THREAD

**Issue by vanko69** [mikaku/Monitorix#134]
Hello, 
Incredible tool, exactly what I was looking for. Just one thing: when I change the value of "global_zoom" of my host to 2 and I enable multihost, and select the host with "global_zoom" that I have changed I see only the left top corner of the graph. Is there a way to show full graph? I attached a img. Awesome tool once again.
PS: Excuse my english  I am a foreigner.
![img](https://cloud.githubusercontent.com/assets/9149938/12480740/3e8b6356-c04d-11e5-9354-9aa11141d4b8.png)

**Comment by mikaku** [comment]
@vanko69,

This is not possible to fix right now, I'm sorry.

Multihost feature is planned to have a complete rewrite which will include numerous new features.
I hope I can start developing its new version soon.

Regards.

**Comment by vanko69** [comment]
Ok. Thanks :) And one more question I don't see memory graph (overview of the memory of the whole system). Is there one and I cannot find it or it is not implemented ?

**Comment by mikaku** [comment]
You should find it enabling the `system` graph (the first one in the screen) which it's already enabled by default.

<http://linux:8080/monitorix-cgi/monitorix.cgi?mode=localhost&graph=_system1&when=1day&color=black>

The memory graph is in the right-bottom part of the `system` graph.

**Comment by vanko69** [comment]
yes thank you once again :)

**Comment by mikaku** [comment]
You're welcome.
