### ISSUE TITLE
ERROR: while updating /var/lib/monitorix/zfs.rrd

### ISSUE THREAD

**Issue by Tagnard** [mikaku/Monitorix#138]
I like this project but I have a problem that i get no data for the zfs graphs and in the logs I get the  following messages.

`Sat Feb 20 01:06:42 2016 - Starting Monitorix version 3.8.1 (pid 27255).
Sat Feb 20 01:06:42 2016 - Loaded main configuration file '/etc/monitorix/monitorix.conf'.
Sat Feb 20 01:06:42 2016 - Initializing graphs.
Sat Feb 20 01:06:42 2016 - Generating the 'index.html' file.
Sat Feb 20 01:06:42 2016 - Started built-in HTTP server (pid 27305).
Sat Feb 20 01:06:42 2016 - Ok, ready.
Sat Feb 20 01:08:00 2016 - ERROR: while updating /var/lib/monitorix/zfs.rrd: /var/lib/monitorix/zfs.rrd: Function update_pdp_prep, case DST_GAUGE - Cannot convert '-' to float`

**Comment by mikaku** [comment]
Looks like the output of one of the ZFS commands used to get statistics don't matches with what Monitorix is expecting, so let's debug a bit more this.

Please, restart your Monitorix but this time adding the argument `-d zfs` in the command line, then let it run for a while (2 or 3 minutes) and pastebin here the complete log since that new restart.

Also, what ZFS version you have there?
Thanks.

**Comment by Tagnard** [comment]
The zfs version is 0.6.5.4 and here are the [logs](http://paste.fedoraproject.org/327205/45613376/).

**Comment by mikaku** [comment]
Thanks for your quick response.

I need more information, please paste the `<zfs>` section of your `monitorix.conf` file.

It seems that Monitorix has problems to get the value FRA (*fragmentation*, if that still exist in the listing), of your pools. So let me see the output of the following command (used by Monitorix to get ZFS pool stats):

```
# zpool list -H $pool
```

Please substitute `$pool` by the name of each pool you have defined.
Thanks.

**Comment by Tagnard** [comment]
Here are [zfs:monitorix.conf](http://paste.fedoraproject.org/327210/13574814/) and `tank    32,5T   28,3T   4,17T   -       -       87%     1.00x   ONLINE  -`

**Comment by mikaku** [comment]
Sorry, can you please paste the output of the same command but without the `-H`? I need to get an idea of which headers are still valid.
Thanks.

**Comment by Tagnard** [comment]
[Sure](http://paste.fedoraproject.org/327211/36479145/), I can do that.

**Comment by mikaku** [comment]
OK, it seems that, for an unknown reason, your FRAG value is not used and the hyphen character (`-`) is not indeed acceptable as a numeric value.

So, to work-around that problem, you manually could change the line 273 in the `zfs.pm` file:

<https://github.com/mikaku/Monitorix/blob/master/lib/zfs.pm#L273>

change this line:

```
	$fra =~ s/%//;
```

by this one:

```
	$fra =~ s/[%-]//g;
```

And just let me know if that fixes the issue and your ZFS graphs are all working fine,
Thanks.

**Comment by Tagnard** [comment]
It don't complain as much but the graphs don't update. [New logs](http://paste.fedoraproject.org/327205/45613376/)

**Comment by mikaku** [comment]
You pasted the same logs as in your first test. :)

**Comment by Tagnard** [comment]
Sorry about that.

[Logs](http://paste.fedoraproject.org/327349/14561592/)

**Comment by mikaku** [comment]
OK I see, it still needs a value. A simple 0 will suffice.

Change the same line:

```
    $fra =~ s/[%-]//g;
```

by this one:

```
    $fra =~ s/[%-]//g;  $fra = $fra || 0;
```

And just let me know.
Thanks.

**Comment by Tagnard** [comment]
Now it works perfectly, thanks for fixing this issue quick and efficiently. :D

**Comment by mikaku** [comment]
Great, thanks for your feedback!
