### ISSUE TITLE
Merge port graphs for better comparison

### ISSUE THREAD

**Issue by aminmazi** [mikaku/Monitorix#139]
Hi, good job.
In Port monitoring, it could be useful if there was an option to merge graphs of different ports in one graph for better traffic usage comparison.

**Comment by mikaku** [comment]
Considering that each port uses two colors (for input and for output) it would be pretty difficult to scale up.
Thanks anyway for your feedback.

**Comment by aminmazi** [comment]
Yes you right, my suggestion works only in few number of ports to be monitored.
What if the y axis of all port graphs have the same scale (for example the average of all traffics) , in this way the graphs can be compared with a glance.
In my use case, every user has a port so I need to compare every port(user)'s traffic usage. I know this is not a common need but it can be an optional feature for better comparison.

**Comment by mikaku** [comment]
You can already fix the y-axis at the same scale for all the network ports being monitored, just assign a `2` to all *rigid* values.

**Comment by aminmazi** [comment]
oh thanks, i missed "rigid and limits" part of documentation.
cross-links in documentation could make this tool more fantastic.
thanks for your help.

**Comment by mikaku** [comment]
Yeah, I know, the documentation is not the best part of Monitorix indeed.
But hey!, that's why we have Github issues, IRC, Mailing Lists, etc.! ;)
Thanks for your feedback.
