### ISSUE TITLE
Request: Add Redis

### ISSUE THREAD

**Issue by blindpet** [mikaku/Monitorix#140]
Since memcached is part of Monitorix, I was hoping to see Redis as well in a future update if possible

**Comment by Almtesh** [comment]
Please, be more precise in your titles, you can put something like "Add Redis" or "memcached present, but why not Redis?"  or something like that.

**Comment by nicktang1983** [comment]
support

**Comment by stratege1401** [comment]
whoa, is this still open ?? 

any how too since 2016 ?

**Comment by mikaku** [comment]
I've a new server and I plan to install Redis on it.  
So I'll be able to start playing with it and develop the new 'redis.pm' module.

**Comment by mikaku** [comment]
OK, this is a screen shot of what will be, probably, the final aspect:

![redis](https://user-images.githubusercontent.com/829885/97030889-beacbc80-155f-11eb-9f3a-be8f3e634602.png)

I believe that it's a fairly complete graph which includes, hopefully, the most relevant values of the Redis statistics.
Any thoughts?
