### ISSUE TITLE
Feature request: hourly graphs

### ISSUE THREAD

**Issue by milandamen** [mikaku/Monitorix#141]
Would it be possible to show graphs for the last hour, instead of the last day?

**Comment by mikaku** [comment]
You can do this already by changing the value of the `when=' parameter, just like this:

```
http://linux:8080/monitorix-cgi/monitorix.cgi?mode=localhost&graph=_system1&when=1hour&color=black
```

**Comment by milandamen** [comment]
Wouldn't it be nice if that option was added in the combobox on /monitorix?

**Comment by mikaku** [comment]
Ah, well, I don't see the need to have that option in the main screen but if you really need it then it's not a problem for me to add a new option to enable it (but will be disabled by default).

Stay around, I'll keep you informed.

**Comment by milandamen** [comment]
I can do without it, just editing the URL, but I thought other less-savy people might want to be able to easily select it.

**Comment by mikaku** [comment]
I've added the new option `enable_hourly_view`, you can test it and let me know if if works as expected.

**Comment by milandamen** [comment]
It works! Thank you. Are you going to update the izzysoft.de repository with the new code?

**Comment by IzzySoft** [comment]
@milandamen mikaku won't. But I will, as soon as mikaku declares it ready (i.e. makes a release) :stuck_out_tongue_winking_eye:

**Comment by milandamen** [comment]
@IzzySoft Ah good. Thanks!

**Comment by gsouf** [comment]
@IzzySoft Is it updated on izzysoft ?

Thanks

**Comment by IzzySoft** [comment]
@gsouf Did I miss a release? According to [the releases page](/mikaku/Monitorix/releases), the last one was v3.8.1 from 11/2015. So unless Mikaku makes a new release, there won't be an update on my end, sorry.

**Comment by mikaku** [comment]
I plan to release 3.9.0 tomorrow.

**Comment by IzzySoft** [comment]
Thanks for the hint, @mikaku – not sure if I'll have the packages ready immediately thereafter, but I'll do my best to have them in place before the weekend is over then (remember I might need some testing before I can push the packages :) I should receive a "ping" from GH as soon as the tag has been pushed.

**Comment by mikaku** [comment]
@IzzySoft no problem, take your time. :wink:

**Comment by IzzySoft** [comment]
@mikaku @gsouf @milandamen Monitorix 3.9.0 is now updated in the repo. Successfully tested (quick-test) on Ubuntu 12.04, Debian Wheezy 64bit, Debian Wheezy ARM / Bananian (Jordi: There's still one issue waiting for a year now concerning Bananian. Hope you didn't forget that feature-request :)

Another suggestion: If you've plans to integrate the unbound name server and need some input, let me know (I'd open a new issue then). Should be easy (using it on my local network: caching, validating (DNSSec), blacklisting (AdBlocking a la AdBlock+ using lists one can "subscribe" to via Cron). Worth it :)

**Comment by mikaku** [comment]
@IzzySoft, thanks for the build is now reflected in the official web site. :+1:

> ... Bananian (Jordi: There's still one issue waiting for a year now concerning Bananian. Hope you didn't forget that feature-request :)

You mean the issue with be able to reload certain graphs instead of all?. Well, since the `refresh_rate` option affects the whole page and all graphs, it means that we need to make this as something completely optional.

> Another suggestion: If you've plans to integrate the unbound name server and need some input, let me know (I'd open a new issue then). Should be easy (using it on my local network: caching, validating (DNSSec), blacklisting (AdBlocking a la AdBlock+ using lists one can "subscribe" to via Cron). Worth it :)

I haven't heard anything about `unbound` name server, sorry.

**Comment by mikaku** [comment]
We should stop as the commentaries here are completely unrelated and might disturb @milandamen.

@IzzySoft email me directly or better open a new issue, thanks :wink:

**Comment by milandamen** [comment]
No problem :) I'm glad this project is still being worked on.

**Comment by pakair** [comment]
I have 3.12.0, there is no enable_hourly_view in the config file.

**Comment by mikaku** [comment]
@pakair, not all the options appear in the config file, but that doesn't mean that they aren't supported.
