### ISSUE TITLE
Wrong image urls when using nginx

### ISSUE THREAD

**Issue by nagyf** [mikaku/Monitorix#143]
Hi!

I'm trying to configure Monitorix on a Raspberry Pi with Arch linux. I've installed monitorix, and nginx.
Nginx config(only the relevant part):
```
server {
        listen       80;
        server_name  10.0.0.2;

        location /monitorix {
            proxy_pass http://127.0.0.1:8080/monitorix;
            allow 127.0.0.0/8;

            location ~ ^/monitorix/(.+\.png)$ {
                alias /srv/http/monitorix/$1;
            }
        }
    }
```

Monitorix config:
```
title = Raspberry Pi
hostname = 10.0.0.2
theme_color = black
refresh_rate = 150
iface_mode = graph
enable_zoom = y
netstats_in_bps = n
disable_javascript_void = n
temperature_scale = c
show_gaps = n
global_zoom = 1
max_historic_years = 1
accept_selfsigned_certs = y
include_dir = /etc/monitorix/conf.d

base_dir = /srv/http/monitorix/
base_lib = /var/lib/monitorix/
base_url = /monitorix
base_cgi = /monitorix-cgi
url_prefix_proxy = 10.0.0.2

<httpd_builtin>
        enabled = y
        host =
        port = 8080
        user = nobody
        group = nobody
        log_file = /var/log/monitorix-httpd
        hosts_deny =
        hosts_allow =
        <auth>
                enabled = n
                msg = Monitorix: Restricted access
                htpasswd = /var/lib/monitorix/htpasswd
        </auth>
</httpd_builtin>
```

The server is running on **10.0.0.2**, and when I delete the line ```url_prefix_proxy = 10.0.0.2``` from Monitorix config, and try to access the application through a web browser on url http://10.0.0.2/monitorix I get image urls like: ```http://127.0.0.1:8080/monitorix/imgs/nginx3.1day.png```

If I add ```url_prefix_proxy = 10.0.0.2``` I see image urls like: ```http://10.0.0.2/monitorix-cgi/10.0.0.2/monitorix/imgs/nginx2.1day.png```

The good image url would be e.g.: ```http://10.0.0.2/monitorix/imgs/nginx3.1day.png``` (I can access the images on this url)

What am I missing? How should I configure Monitorix to work correctly?

**Comment by mikaku** [comment]
Is the any special reason why are you using Nginx to connect to the built-in HTTP server of Monitorix? I mean, why not just use the built-in HTTP og Monitorix or Nginx with the built-in HTTP disabled?

**Comment by nagyf** [comment]
I'm want to use nginx because I will have other applications as well, on the same system, and I want to serve everything through nginx.
I will try to disable the built in server and configure nginx

**Comment by mikaku** [comment]
Ok, and please, let me know if you still have problems.
Regards.
