### ISSUE TITLE
Config hosts_deny and hosts_allow precedence

### ISSUE THREAD

**Issue by robjens** [mikaku/Monitorix#146]
Hi,

This might be the result of some (tcpwrapper-ish) basic information/experience lacking on my side; the documentation doesn't state this very explicitly but I was under the impression that:

```
<httpd_builtin>
   hosts_deny = all
   hosts_allow = __.__.____.____ 
   ...
```

Where `__...` is my public IP address, would deny access to all IP's by default but would allow my own public IP access. I presume this assumption, after some tryout, is not correct? Something I don't get about the rule precedence might be the cause, could anyone clarify this?

**Comment by mikaku** [comment]
Hi,

It works exactly as you said, just putting your public IP in the `hosts_allow` option and it will be the only one allowed to access your Monitorix. The rest of IPs will be denied because you specified `all` in the `hosts_deny` option.

Please, make sure your public IP is correct.
I've just tested it here and it works.

**Comment by melito00** [comment]
I have same issue.
I copied IP Address from "monitorix-httpd" log that was recorded as "Access not allowed: ".

I tried to set "hosts_allow = all". but I also coundn't access. and it logged same message "[x.x.x.x] Access not allowed ...."

**Comment by mikaku** [comment]
OK, here is my test:

I have the following in my `monitorix.conf`:
```
<httpd_builtin>
        enabled = y
        host =
        port = 8080
        user = nobody
        group = nobody
        log_file = /var/log/monitorix-httpd
        hosts_deny = all
        hosts_allow =
```
Now I try to access from another PC with IP 192.168.1.11 and obviously that's what I get in `/var/log/monitorix-httpd`:
```
Wed May 18 15:10:01 2016 - NOTALLOWED - [192.168.1.11] Access not allowed: /monitorix
```
Now I change the following line in my `monitorix.conf` and restart Monitorix:
```
        hosts_allow = 192.168.1.11
```
And in the next try I get the following in `/var/log/monitorix-httpd`:
```
Wed May 18 15:10:48 2016 - OK - [192.168.1.11] "GET /monitorix - ELinks/0.12pre5 (textmode; Linux; 80x24-2)"
```
So, all is working fine. I'm unable to reproduce your problem.

**Comment by robjens** [comment]
This must have something to do with nginx reverse proxy in my case, I'm fairly sure it is trying to see if its own ip address matches and nginx won't pass it along just anytime. Anyway, I'll stick with the password protection for now but pretty certain this would be the cause on my end.

**Comment by mikaku** [comment]
@robjens,

Then perhaps the best place to put those `host_allow` and `host_deny` directives is in the proxy server.

**Comment by robjens** [comment]
@mikaku Yeah..stupid I didn't realize it back then. I'll close this, thanks for checking back with me :+1:
