### ISSUE TITLE
Yaws default file conflict after installation from .deb

### ISSUE THREAD

**Issue by lordslair** [mikaku/Monitorix#150]
Hello everyone,

I checked previously if there's already an opened issue about it before posting this one

I'm trying for a project to embed monitorix, so I wanted first to understand better how it works.
I started an "easy" install on a fresh debian VM

```
root@monito00:~# uname -a
Linux monito00 3.16.0-4-amd64 #1 SMP Debian 3.16.7 (2015-04-24) x86_64 GNU/Linux
root@monito00:~# cat /etc/issue.net 
Debian GNU/Linux 8
```

It seems there's something wrong about the /monitorix alias.
It looks like it doesn't redirect stright away in the right folder (base_dir = /var/lib/monitorix/www/)

And the return from the request on the built-in server

```
root@monito00:~# lynx -dump localhost:8080
   If you can see this, it means that the installation of the [1]Yaws web
   server software on this system was successful. You may now add content
   to this directory and replace this page.
[...]
root@monito00:~# 
root@monito00:~# lynx -dump localhost:8080/monitorix
                                   Not Found

   The requested URL /monitorix was not found on this server.
[...]
```

It looks like it's because yaws, the server used, is already shipped with a conf file who listens on 0.0.0.0:8080 and has precedence

```
root@monito00:~# tail -7 /etc/yaws/conf.avail/localhost.conf 
<server localhost>
    port = 8080
    listen = 0.0.0.0
    docroot = /usr/share/yaws
    # dir_listings = true
</server>
```

I saw it inside the monitorix logs

```
root@monito00:~# tail /var/log/monitorix
[...]
Thu May 26 16:17:58 2016 - Generating the 'index.html' file.
bind to *:8080: Address already in use at /usr/lib/monitorix/Monitorix.pm line 159.
Thu May 26 16:17:58 2016 - WARNING: the built-in HTTP server has authentication disabled.
```

I had to manually stop yaws, and restart monitorix to be able to access monitorix webpages

```
root@monito00:~# service yaws restart
root@monito00:~# service monitorix restart
root@monito00:~# lynx -dump localhost:8080/monitorix
   [1][logo_top.png]
                                                                       v3.8.1

                   Hostname    Graph
                  [localhost] [All graphs________________]
[...]
```

Now, everything's fine
So, maybe that's something that should figure in the Installation wiki
(Or a fix during the installation of monitorix, to restart both of them at the end)

Feel free to tell me if I could do something more, or try something
I can re-install a fresh machine to make more tests.

Thanks,

**Comment by IzzySoft** [comment]
Only one service can be bound per port AFAIK. So if 8080 is already in use, a second service cannot be attached to it. So IMHO you'd either have to reconfigure Yaws or Monitorix.

**Comment by mikaku** [comment]
@lordslair 

> I checked previously if there's already an opened issue about it before posting this one

Thank you!

And, as @IzzySoft already said, it's just a matter to configure either Yaws or Monitorix to avoid both applications from listening on the same network port.

**Comment by lordslair** [comment]
Thanks for the answer, I should explain better in order to be clearer.

Yes, I saw that yaws was in conflict with monitorix as you can only bound one service per port.
But, I didn't install yaws myself, I don't need it, yaws was installed as a monitorix dependency.

From what I'm seeing, yaws is shipped with monitorix (using IzzySoft repo)
To illustrate, I've installed using apt all the needed lib-*, and I still have the yaws dependency.

```
root@monito00:~# apt-get install monitorix
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  yaws
Suggested packages: [...]
```

Yaws seems to be unused in the code, and into the debian package. I don't understand why yaws should be installed. 
I had a look into the DEBIAN/control and install scripts shipped with the .deb package as well.

Maybe you have an idea, it could be helpful to avoid an unneeded package installation.
I can provide you more info if needed, just ask.

Thanks,

**Comment by mikaku** [comment]
@lordslair,

Indeed, Yaws or any other web server shouldn't be a required dependency since Monitorix already has its own built-in web server. Of course, you can install an external web server (Apache, Nginx, Yaws, etc.) if you don't want to use the built-in HTTP, but that must be your decision.

Perhaps there is something special in your Debian that makes that package a required dependency.

I don't use Debian, so I can't bring much help on this. Let's see if @IzzySoft can shred some light on this.

**Comment by IzzySoft** [comment]
@mikaku you have `httpd` in the `recommends` section of the spec file (and so it's in the same place for Debian packages). This usually doesn't cause a conflict, as web servers normally use port 80. Why in the case of @lordslair it picked yaws, and why yaws uses port 8080 as default, I can't tell.

We could move `httpd` to the `suggests` part (most distris, if not told differently, automatically install all `recommends` – and only few users turn that off, because only few know about this), thus avoiding conflicts like that. Up to you, I'd follow suit then :)

**Comment by lordslair** [comment]
To see if it's Debian 8 related, I'll make some tests on a Debian 7, and if needed the latest Ubuntu
(to exclude some weird things on my Deb8 setup)

**Comment by IzzySoft** [comment]
@lordslair I'm running it on Wheezy and Jessie (both ARM, BananaPi) and didn't notice the issue. But in both cases, `apt` was told to not auto-install recommends, so it couldn't become an issue. Moreover, in both cases Apache2 was already installed, so the `httpd` dependency was already met. You will have the very same issue on Wheezy as well unless you've configured `apt` with `APT::Install-Recommends "0";`.

**Comment by mikaku** [comment]
@IzzySoft 

> @mikaku you have httpd in the recommends section of the spec file (and so it's in the same place for Debian packages). This usually doesn't cause a conflict, as web servers normally use port 80. Why in the case of @lordslair it picked yaws, and why yaws uses port 8080 as default, I can't tell.

I'm not aware of that *recommends* section in the .spec file (`docs/monitorix.spec`). Where did you see that?


> We could move httpd to the suggests part (most distris, if not told differently, automatically install all recommends – and only few users turn that off, because only few know about this), thus avoiding conflicts like that. Up to you, I'd follow suit then :)

Those that mean that Debian package has some kind of mechanism to auto install any *recommended* package in the .deb file?

I didn't know that feature of .deb files, and AFAIK that feature doesn't exist in the -rpm files.

**Comment by IzzySoft** [comment]
@mikaku 

> I'm not aware of that recommends section in the .spec file (docs/monitorix.spec). Where did you see that?

I need to check again when I'm home. But I cannot remember having added recommends. Nevertheless, I'd say it's safe to remove (`httpd`) as Monitorix brings its built-in httpd, so we should remove it.

> Those that mean that Debian package has some kind of mechanism to auto install any recommended package in the .deb file?

Depending on the distribution, that's enabled by default (e.g. on Ubuntu, while at least Debian Wheezy and Jessie on my BananaPi had it disabled by default). It's an option of the APT package manager.

So as you're not aware of that "recommends", I take it as "agreement" to remove it from the `.deb` for the next release?

**Comment by mikaku** [comment]
> So as you're not aware of that "recommends", I take it as "agreement" to remove it from the .deb for the next release?

Yes, as you said, it's safe to remove `httpd` since Monitorix already brings a built-in HTTP server.
Thanks.

**Comment by IzzySoft** [comment]
@mikaku 

Removed it from the "spec4deb". Quick check: another recommends which I've let remain is `iptables`. If that's OK, I'd say this issue can be closed. I won't make another `.deb` just for that – guess there will be a new version soon? ;)

**Comment by mikaku** [comment]
Yes, I think we can close this issue.

> guess there will be a new version soon? ;)

I'm still pretty busy at work that prevents me to finalize some new graphs that I'd want to include for the next version, so it will be delayed a bit more.

Feel free to make a maintenance `.deb` release if you think it's really needed.
Thanks Izzy!

**Comment by IzzySoft** [comment]
I don't think that little spec change justifies a maintenance release. And I don't want to pick something else unless it's declared stable by you :) So we'll wait until the next release is ready. Thanks alot!
