### ISSUE TITLE
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.

### ISSUE THREAD

**Issue by rolandwells** [mikaku/Monitorix#151]
I get the following errors in the monitorix log, along with the broken disk monitoring section (pic attached). This is on a fresh install and I have confirmed hddtemp works as expected.

`hello@hub-16:/var/log$ sudo hddtemp /dev/sda`
`/dev/sda: MKNSSDEC60GB: 30°C`

Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.

This is on a new Ubuntu 16.04 install (kernel 4.4.0-22-generic

#77 or #149 are similar but was not clear if duplicate

![image](https://cloud.githubusercontent.com/assets/8055681/15626579/02621908-24c8-11e6-91ef-8806098a7cb8.png)

**Comment by mikaku** [comment]
@rolandwells,

Thanks for checking first if your problem is already opened for someone else, which is not as you well said.

After seeing the graphs, I noticed that there is an error message that says `/var/lib/monitorix/disk.rrd: No such file or directory`. This means that your `disk.rrd` is missing for an unknown reason.

Can you, please, check the Monitorix log file `/var/log/monitorix` to see if there are more error messages that can help us?

Thanks.

**Comment by rolandwells** [comment]
Thank you Jordi. Below is `/var/log/monitorix`, it includes a restart of monitorix via "service monitorix restart" which you can see towards the end.

Maybe some info in these lines?:
Mon May 30 12:37:15 2016 - disk::disk_init: ERROR: invalid or inexistent device name '/dev/sdb'.
Mon May 30 12:37:15 2016 - disk::disk_init: 'accept_invalid_disk' option is not set.

-------------------

hello@hub-16:/var/log$ tail -n 200 monitorix
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Use of uninitialized value $color in hash element at ./monitorix.cgi line 303.
Use of uninitialized value $when in pattern match (m//) at ./monitorix.cgi line 335.
Use of uninitialized value $val in string ne at ./monitorix.cgi line 430.
Use of uninitialized value $mode in string ne at ./monitorix.cgi line 430.
Use of uninitialized value $val in pattern match (m//) at ./monitorix.cgi line 438.
Use of uninitialized value $mode in string eq at ./monitorix.cgi line 451.
Use of uninitialized value $mode in string eq at ./monitorix.cgi line 451.
Use of uninitialized value $mode in string eq at ./monitorix.cgi line 453.
Use of uninitialized value $title in substitution (s///) at ./monitorix.cgi line 467.
Use of uninitialized value $title in concatenation (.) or string at ./monitorix.cgi line 468.
Use of uninitialized value $mode in string eq at ./monitorix.cgi line 493.
Use of uninitialized value $mode in string eq at ./monitorix.cgi line 516.
Use of uninitialized value $mode in string eq at ./monitorix.cgi line 518.
Use of uninitialized value $color in hash element at ./monitorix.cgi line 303.
Use of uninitialized value $when in pattern match (m//) at ./monitorix.cgi line 335.
Use of uninitialized value $val in string ne at ./monitorix.cgi line 430.
Use of uninitialized value $mode in string ne at ./monitorix.cgi line 430.
Use of uninitialized value $val in pattern match (m//) at ./monitorix.cgi line 438.
Use of uninitialized value $mode in string eq at ./monitorix.cgi line 451.
Use of uninitialized value $mode in string eq at ./monitorix.cgi line 451.
Use of uninitialized value $mode in string eq at ./monitorix.cgi line 453.
Use of uninitialized value $title in substitution (s///) at ./monitorix.cgi line 467.
Use of uninitialized value $title in concatenation (.) or string at ./monitorix.cgi line 468.
Use of uninitialized value $mode in string eq at ./monitorix.cgi line 493.
Use of uninitialized value $mode in string eq at ./monitorix.cgi line 516.
Use of uninitialized value $mode in string eq at ./monitorix.cgi line 518.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.
Mon May 30 12:37:14 2016 - SIGTERM caught.
Mon May 30 12:37:15 2016 - Exiting.
Mon May 30 12:37:15 2016 - Starting Monitorix version 3.8.1 (pid 11611).
Mon May 30 12:37:15 2016 - Loaded main configuration file '/etc/monitorix/monitorix.conf'.
Mon May 30 12:37:15 2016 - Loading extra configuration file '/etc/monitorix/conf.d/00-debian.conf'.
Use of uninitialized value in lc at /usr/lib/monitorix/disk.pm line 60.
Mon May 30 12:37:15 2016 - Initializing graphs.
Mon May 30 12:37:15 2016 - disk::disk_init: ERROR: invalid or inexistent device name '/dev/sdb'.
Mon May 30 12:37:15 2016 - disk::disk_init: 'accept_invalid_disk' option is not set.
Mon May 30 12:37:15 2016 - fs::fs_init: Unable to detect the device name of '/boot'. I/O stats for this filesystem won't be shown in graph. If this is really a mount point then consider using <devmap> to map it manually to a device name.
Mon May 30 12:37:15 2016 - Generating the 'index.html' file.
Mon May 30 12:37:15 2016 - Started built-in HTTP server (pid 11661).
Mon May 30 12:37:15 2016 - Ok, ready.
Mon May 30 12:37:15 2016 - WARNING: the built-in HTTP server has authentication disabled.
HTTPServer: You can connect to your server at http://localhost:8080/
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 581.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 582.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 712.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 713.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 839.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/disk.pm line 840.

**Comment by mikaku** [comment]
> Maybe some info in these lines?:
> ```
> Mon May 30 12:37:15 2016 - disk::disk_init: ERROR: invalid or inexistent device name '/dev/sdb'.
> Mon May 30 12:37:15 2016 - disk::disk_init: 'accept_invalid_disk' option is not set.
> ```

Yup, that's indeed is the problem. Look at the code that does it:

```Perl
logger("$myself: ERROR: invalid or inexistent device name '$d'.");
        if(lc($disk->{accept_invalid_disk}) ne "y") {
                logger("$myself: 'accept_invalid_disk' option is not set.");
                return;
        }
```

So, if if finds a disk that doesn't exists it refuses to continue initializing the Disk graph and so the `disk.rrd` file is not created.

I should introduce a WARNING here just to denote that such graph won't be active until you fix that problem.

Meanwhile, you could remove the devices that don't exist in your system.

**Comment by rolandwells** [comment]
Thank you. I removed sdb and sdc from <disk> section in /etc/monitorix/monitorix.conf and all seems to be working well.

![image](https://cloud.githubusercontent.com/assets/8055681/15646895/9a4f442c-2660-11e6-9808-6c6b3cd38f6f.png)

**Comment by mikaku** [comment]
Perfect!
