### ISSUE TITLE
syntax error at Monitorix/monitorix line 687, near "my "

### ISSUE THREAD

**Issue by beyoungwoo** [mikaku/Monitorix#152]
if(lc($config{traffacct}->{enabled}) eq "y"    **# missing ) {'**

* working 
 * if(lc($config{traffacct}->{enabled}) eq "y") {

**Comment by mikaku** [comment]
Oops!, you're right.
Let me fix that right now.

**Comment by mikaku** [comment]
@beyoungwoo,
Thanks a lot!

**Comment by beyoungwoo** [comment]
Thank you
