### ISSUE TITLE
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/port.pm line 312.

### ISSUE THREAD

**Issue by yshinkarev** [mikaku/Monitorix#154]
I install last version of monitorix to my nas My Book Live.
File monitorix.log filled with line:

Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/port.pm line 312.

**Comment by mikaku** [comment]
@yshinkarev,

This issue is already covered in #77.
