### ISSUE TITLE
Wrong processor number value parsed from /proc/cpuinfo in proc.pm

### ISSUE THREAD

**Issue by emilio-aburto** [mikaku/Monitorix#155]
While looking into the log file there is a lot of this error lines: 
`Argument ":" isn't numeric in preincrement (++) at /usr/lib/monitorix/proc.pm line 293.`
so, I looked the faulty line and the problem is [here](https://github.com/mikaku/Monitorix/blob/6d16857ce95589c3791e9aac2f25d7be3cb1f61e/lib/proc.pm#L293), copying lines 291-293: 
```perl
$ncpu = `grep -w processor /proc/cpuinfo | tail -1 | awk '{ print \$3 }'`;
chomp($ncpu);
$ncpu++;
```

The problem is that in my current system (Archlinux ARM in a Raspberry Pi model B), the output of `grep -w processor /proc/cpuinfo` is: 
```
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
```
so `$ncpu` takes the value ":" and then fails the increment. 
I'll send a PR with what I consider a proper fix. :+1:

**Comment by mikaku** [comment]
Thanks!
