### ISSUE TITLE
Define 2 NICs in the Net section?

### ISSUE THREAD

**Issue by graysky2** [mikaku/Monitorix#158]
Can one define 2 NICs in the net section?  `enp0s10` and `wlp4s0` for example?

**Comment by mikaku** [comment]
As stated in the man page you can define (comma separated) up to 10 network interfaces.

Check the section *Network traffic and usage (net.rrd)* in `monitorix.conf(5)`.

**Comment by graysky2** [comment]
My bad... I just read the comments in `/etc/monitorix/monitorix.conf` itself.  Thanks!
