### ISSUE TITLE
Official support for ODROID board's CPU temp

### ISSUE THREAD

**Issue by graysky2** [mikaku/Monitorix#159]
Is it possible for you to include support for the ODROID-C1 and C2 in the existing CPU temp plot?  Using lm-sensors will not work (like Raspberry Pi https://github.com/mikaku/Monitorix/issues/10) but the CPU core temp is available but needs to be divided by 1000 and units are centigrade:
```
% cat /sys/devices/virtual/thermal/thermal_zone0/temp
40000
```
There are no others sensors on the board (vcore or other temp sensors).

**Comment by mikaku** [comment]
Hey,

It's a pity that ODROID doesn't have other sensors since I could create an specific graph for it, having only the CPU temperature value wouldn't be enough for the typical layout of Monitorix.

So, where do you suggest we could put that temp value? I mean, in which graph?
You talked about *CPU temp plot*, which exactly graph are you referring to?

Thanks.

**Comment by graysky2** [comment]
I was thinking a very simple ODROID plot.  You can add the current cpu frequency too like you did for raspberry pi. So 1 for CPU temp and 1 for CPU freq.

Frequency here is displayed in Hz:
```
% cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
250000
```

**Comment by mikaku** [comment]
Two values?, nice, that would be a double-graph layout, just like the Fail2ban graph.
I'm a bit busy at work now (server migration), once finished I'll begin coding on it.

**Comment by graysky2** [comment]
Great, looking forward to it and thank you as always for the great support!

**Comment by mikaku** [comment]
@graysky2,

It looks like these sensors are pretty generic, I mean, they are not specific of ODROID.
I have them in my Asus motherboard:

```
$ cat /sys/devices/virtual/thermal/thermal_zone0/temp 
27800
$ cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
800000
```

I think we should rename that graph to something like `gensens`.
What do you think?

**Comment by mikaku** [comment]
I think that this graph could be more generic in the sense that it could be scale up to unlimited sensors being monitored on different graphs, Something like this:

```
<gensens>
        <list>
                0 = temp
                1 = cpuf
        <desc>
                temp = /sys/devices/virtual/thermal/thermal_zone0/temp
                cpuf = /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
        </desc>
        <map>
                temp = Temperature
                cpuf = CPU frequency
        </map>
        rigid = 0, 0
        limit = 100, 100
</gensens>
```

With this configuration you set up two graphs which include the temperature sensor in the left one and the CPU frequency in the right one. Monitorix knows from where to get the value of each sensor thanks to the option `<desc>`, and you can even rename each name with the option `<map>` to be more readable.

**Comment by mikaku** [comment]
I have included the option `<unit>` in order to be able to make some simple math on the value. If its associated value is greater than zero then it will be divided by that value, else if it's lesser than zero it will be multiplied.

Hopefully this logic will cover almost all situations:

```
<gensens>
        <list>
                0 = temp
                1 = cpuf
        <desc>
                temp = /sys/devices/virtual/thermal/thermal_zone0/temp
                cpuf = /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
        </desc>
        <unit>
                temp = 1000
        </unit>
        <map>
                temp = Temperature
                cpuf = CPU frequency
        </map>
        rigid = 0, 0
        limit = 100, 100
</gensens>
```

**Comment by graysky2** [comment]
Did you commit and push to a dev branch or something I can try.  I do not see this code in the master branch.

**Comment by mikaku** [comment]
Hopefully today I'll be able to make a commit with a preliminary version.

**Comment by mikaku** [comment]
I've made some changes in order to have a more consistent graph. Now there is a limit in the number of graphs to 2; for temperatures and for CPU frequencies, and for each one you can define up to 9 sensors.

Here is a recent screen shot from my PC:

![gensens](https://cloud.githubusercontent.com/assets/829885/19114925/4d09d848-8b10-11e6-8ae5-0214d274b3ce.png)

**Comment by mikaku** [comment]
> Frequency here is displayed in Hz:
>
>```
>% cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
>1536000
>```

Are you sure? AFAIK it would mean you have a 1.5Mhz processor. :smiley: 

I think this is displayed in Mhz, which would bean 1.5Ghz processor. If so, we need to multiply this value by 1000 in order to have a more real scale in the graph.

**Comment by graysky2** [comment]
Pulled down 8a0b97c and running on my ODROID-C2.  Will provide feedback after a few hours of data collection.  Thanks!

**Comment by graysky2** [comment]
Is it possible to select a different color for the line?  Dark blue on black is a little tough to see... yellow would be a good default (or another bright color).

**Comment by mikaku** [comment]
> 1) Is it possible to select a different color for the line? Dark blue on black is a little tough to see... yellow would be a good default (or another bright color).

There is an array of 9 colors (one for each entry) and the first one is that blue. I can change the order to be the yellow the first one. Anyway, the same tone of blue is used in other graphs without any problem.

> 2) Can you fix the y-axis scale to display in MHz? Seems like the perfect units since most chips will be in the low to mid thousands of MHz.

If I change the y-axis to Mhz then you'll see values in `k` instead of `M` and you'll end up reading it as *NNNk of Mhz* instead as *NNNMhz* like now. I mean, the y-axis must have the unit and let the graph to scale it naturally.

**Comment by mikaku** [comment]
> The report seems to "smooth" these values though. Is there a setting you can apply to store or display them non-averaged?

The problem with that frequency values, unlike temperatures, is that they change their values from high to low in a second (even in less time). Monitorix acquires data at one minute intervals, which means that in order to see the real value on the graph it must have such value at the same time that Monitorix acquires the value, which indeed it makes it pretty difficult. Moreover, since the graphs shows average values, the value acquired by Monitorix need to be the same at least a minimal of two or three times to see it correctly in the graph.

**Comment by graysky2** [comment]
> There is an array of 9 colors (one for each entry) and the first one is that blue. I can change the order to be the yellow the first one. Anyway, the same tone of blue is used in other graphs without any problem.

That would be great, thanks!

> If I change the y-axis to Mhz then you'll see values in k instead of M and you'll end up reading it as NNNk of Mhz instead as NNNMhz like now. I mean, the y-axis must have the unit and let the graph to scale it naturally.

OK.  Thought I'd ask.

> Moreover, since the graphs shows average values, the value acquired by Monitorix need to be the same at least a minimal of two or three times to see it correctly in the graph.

OK.  I thought there was a setting to plot the raw values rather than averaging them on the plot.  I just googled for this but came up empty.

Overall, I think this is a great addition to the tool and seems to be working just fine (2 days now):

![screenshot_2016-10-07_07-28-06](https://cloud.githubusercontent.com/assets/534822/19188430/a0774ba0-8c5f-11e6-8367-4841bd43e0cb.png)

**Comment by mikaku** [comment]
> OK. CPU frequency as you pointed out, should not be averaged; just plotting the raw values is best but I am unsure how to do this with rrdtool. I just googled for this but came up empty. Do you know if that is possible?

I think that's not possible. If you use time with values you'll get averages.

**Comment by graysky2** [comment]
>I think that's not possible. If you use time with values you'll get averages.

OK... just wanted to check.  I think this feature is "working" just fine.

**Comment by mikaku** [comment]
OK ... closing, thanks for your feedback!

**Comment by graysky2** [comment]
> There is an array of 9 colors (one for each entry) and the first one is that blue. I can change the order to be the yellow the first one. Anyway, the same tone of blue is used in other graphs without any problem.

How can we accomplish this?  BTW, a week's worth of data:
![screenshot_2016-10-13_18-25-35](https://cloud.githubusercontent.com/assets/534822/19369281/7564daf0-9172-11e6-8ebc-3275ddf2df61.png)

**Comment by mikaku** [comment]
test this last commit:

<https://github.com/mikaku/Monitorix/commit/297397f347fdc12f777c11bbd6bb671800416167>

**Comment by graysky2** [comment]
Just updated to 3.9.0 which includes that commit.  Looks very nice!  Thanks for the great tool and for the great relationship you foster with your user base!

![screenshot_2016-10-14_14-25-42](https://cloud.githubusercontent.com/assets/534822/19398338/2d80bba2-921a-11e6-95f3-f6e8c5412346.png)

**Comment by mikaku** [comment]
I'm glad to hear your are satisfied, really.
Thanks!
