### ISSUE TITLE
Show real names in lmsens module

### ISSUE THREAD

**Issue by kyak** [mikaku/Monitorix#161]
It would be great to show real names of sensors in lmsens module.
Currently the names are fixed, like Fan 0 or CPU 0 to make sure that they will fit into the graph.

However, if the number of fans is less than four, there is enough space on graph to display the real name (as configured in lmsens config section).

It should be possible to modify code to use real names when there is enough space on graph.

**Comment by mikaku** [comment]
Please, download the development version of **lmsens.pm** and let me know if it works as expected.
Thanks.
