### ISSUE TITLE
Understanding Changed Graphs [SOLVED]

### ISSUE THREAD

**Issue by bluegroper** [mikaku/Monitorix#169]
Hi Jordi
Thx for email.
I've had a deeper look at our recent Mail Statistics graphs, and suspect I made a mistake.
It seems that new monitorix is now graphing RBL rejections (in purple).  Thats great.
It seems that new monitorix is no longer graphing greylisted emails.  These were previously included as Rejected (in Red on graph).  Thats ok.
It seems I had misread the new graph, was accustomed to seeing greylisted emails in red, and mistakenly assumed the now (purple) graph was greylisting.
I had also missed the big clue coming from the changed scale on y axis.
If my improved understanding is correct, then I'm sorry for troubling you.  
(I too know what its like to be busy.)
Hope this explanation helps somebody else, which is why I post here rather than sending email directly.  Mea culpa included.
As you know, postfix uses postgrey server.
Sometime, I'd like to try and help you with locating suitable data from postfix (via pflogsumm ?) for the (separate) Greylisting graph.  There's already a separate issue ticket for this topic.
Cheers

**Comment by mikaku** [comment]
@bluegroper,

Thanks for your clarification, this indeed might be of help to other people.

And yes, you're right. There is an opened issue #102 to be able to include support of Postgrey (the Postfix Greylisting), buy I'm not getting much information form the person who opened such issue.

Perhaps you can bring more information on the subject in that issue.
Thanks.
