### ISSUE TITLE
Feature request: Port graph - add port range

### ISSUE THREAD

**Issue by gibzer** [mikaku/Monitorix#172]
Make possible to define port range. Now it's possible to add only single port for monitoring.

For example:
```
# PORT graph
# -----------------------------------------------------------------------------
<port>
        max = 3
        rule = 24000
        list = 25, 30000:30100, 40000u:40100u
        <desc>
                25            = SMTP,    tcp, in, 0, 1000
                30000:30100   = FTP PSV, tcp, in, 0, 1000
                40000u:40100u = SIP RTP, udp, in, 0, 1000
        </desc>
        graphs_per_row = 3
</port>
```

**Comment by mikaku** [comment]
This is interesting, but keep in mind that using this configuration Monitorix would show all network activity of ports 30000 through 30100 into one single graph, and all network activity of ports 40000 through 40100 also in another single graph.

This is fine to me, otherwise creating a graph for each port in every range would be a complete mess.

**Comment by gibzer** [comment]
Yes, I meant all activity of ports 30000 through 30100 on one single graph. No need to do separated graph for each port in range.

**Comment by kitekkitek** [comment]
Any ideas if this is even considered ? Port range on a single graph would be great.

**Comment by IzzySoft** [comment]
An animated GIF maybe? 💨

(just to make absolutely sure: I was KIDDING!)

**Comment by IzzySoft** [comment]
`<kidding>`Using an animated GIF?`</kidding>`

**Comment by kitekkitek** [comment]
The way I understand port range in this graph would be single line - treat them as a single position. In my current app I would actually want to know whats the summarised traffic on ports. i.e. 10000:15000 as a single position. Many applications use ports range i.e. for udp traffic.

**Comment by mikaku** [comment]
@IzzySoft
> An animated GIF maybe?

Damn, I can't paste here a rolling on the floor laughing animated GIF! :wink: 

@kitekkitek,
> I would actually want to know whats the summarised traffic on ports.

Well, that's indeed a more acceptable solution.

**Comment by mikaku** [comment]
The final syntax would be like this:

```
# PORT graph
# -----------------------------------------------------------------------------
<port>
        max = 3
        rule = 24000
        list = 25, 30000:30100, 40000:40100u
        <desc>
                25            = SMTP,    tcp, in, 0, 1000
                30000:30100   = FTP PSV, tcp, in, 0, 1000
                40000:40100u = SIP RTP, udp, in, 0, 1000
        </desc>
        graphs_per_row = 3
</port>
```

That is, keep the port range compact and put the extra character at the end. This is because the range value is also used in the `iptables` command.

**Comment by mikaku** [comment]
@kitekkitek and @gibzer, the previous commit should introduce support for port ranges. The sixth parameter (`L`), won't have any effect on entries with a port range.

Please, download the `port.pm` file and let me know how it works.
