### ISSUE TITLE
icecast not data

### ISSUE THREAD

**Issue by Klef** [mikaku/Monitorix#173]
Good day
icecast version 2.4.0
monitorix version 3.9.0
config for icecast
`<icecast>
        list = http://radio.wasteland.su:8080/status.xsl
        <desc>
                http://radio.wasteland.su:8080/status.xsl = /radio, /radio.aac, /fall, /fall.aac, /last, /zf_wr, /zf_lw
        </desc>
        graph_mode = r
        rigid = 0, 0
        limit = 100, 100
</icecast>
`
from machine uri http://radio.wasteland.su:8080/status.xsl available.
but, not data in grafh

![icecast01 1day](https://cloud.githubusercontent.com/assets/5559962/21846117/94dd3db6-d806-11e6-81f6-c0348f5ed0d0.png)

errors in the log file does not

**Comment by mikaku** [comment]
@Klef,

It works perfectly well here:

![icecast](https://cloud.githubusercontent.com/assets/829885/21856012/b355b2ae-d820-11e6-8e35-fc59935256a4.png)

My setup
------------

```
<desc>
        http://radio.wasteland.su:8080/status.xsl = /fall, /fall.aac, /last, /zf_lw, /zf_wr
</desc>
```

Your problem
-----------------
Your setup includes nonexistent Mount Points, and also they are specified in a different order as they appear in the URL.

As stated in the Monitorix man page:

```
desc
              This  is  a  comma-separated list of Mount Points configured for
              every URL specified in the list  option.  IMPORTANT:  the  Mount
              Points  must  be specified in the same order that appears in the
              Icecast Server Status page.
```

**Comment by Klef** [comment]
oh, thx
sorry, my fault
