### ISSUE TITLE
Doesn't work with Safari 10 on OS X 10.12

### ISSUE THREAD

**Issue by RichieB2B** [mikaku/Monitorix#177]
When using 3.9.0-izzy1 (Debian package) with Safari 10 on OS X 10.12.3 the builtin Monitorix web server always returns a 400 error. This is probably because Safari attempts an HTTP/2 (h2) handshake. When I visit the same URL with Firefox everything is fine.

**Comment by RichieB2B** [comment]
Never mind, I have an HTTPS server on the same server that sends HSTS headers. As a result Safari will always force an HTTPS connection (and attempt HTTP/2 first). Using a different hostname all is fine.

**Comment by mikaku** [comment]
Thanks for clearing this up.
