### ISSUE TITLE
is ipmi supported ? or is it coming ?

### ISSUE THREAD

**Issue by frollic** [mikaku/Monitorix#179]
I found traces of it here on the github (.conf file, etc) ... 

and how does it work ? 
does it use the ipmi-sensors binary from FreeIPMI ?

**Comment by mikaku** [comment]
Hi,

This is a new graph that will be available in the next version (or you can download the current development version if you don't want to wait for it).

This graphs uses the command line `ipmitool sdr` to collect data from fans, temperatures and battery volts. Here is a screen shot:

![ipmi](https://cloud.githubusercontent.com/assets/829885/24601532/814a7e2e-1859-11e7-987c-1307aaa1ea37.png)

`monitorix.conf(5)` should contain all the information.

**Comment by frollic** [comment]
That's great news !

and thank you for the info.
Grabbed the ipmi.pm file, made the adjustments required in the conf, and works lite a charm!

**Comment by mikaku** [comment]
Perfect!
:+1:
