### ISSUE TITLE
<desc> are not properly shown in <lmsens> graphs

### ISSUE THREAD

**Issue by WyRe** [mikaku/Monitorix#183]
I am having got issues to show properly the lmsensors descriptions in the graphs, that's my monitorix.conf

```

# -----------------------------------------------------------------------------
<lmsens>
        <list>
                core0   = Core 0
                core1   = Core 1
                mb0     = temp1
                mb1     = temp2
                fan0    = fan1
                fan1    = fan2
                fan2    = fan3
                volt0   = in0
                volt1   = in1
                volt2   = in2
                volt3   = \+5V
                volt4   = in6
                volt5   = in7
                volt6   = Vbat
        </list>
        <desc>
                core0   = Temp C0
                core1   = Temp C1
                mb0     = MBThe
                mb1     = MBDio
                volt0   = VCore0
                volt1   = Vcore1
                volt2   = +3.3V
                volt3   = +5V
                volt4   = +4V
                volt5   = +3V
                volt6   = Battery
        </desc>
</lmsens>

```
And this is my `sensors` output:

```
┌—————[wyre]—————[~] 
└> $ sensors
coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +31.0°C  (high = +76.0°C, crit = +100.0°C)
Core 1:       +26.0°C  (high = +76.0°C, crit = +100.0°C)

it8718-isa-0290
Adapter: ISA adapter
in0:          +1.10 V  (min =  +0.00 V, max =  +4.08 V)
in1:          +1.82 V  (min =  +0.00 V, max =  +4.08 V)
in2:          +3.28 V  (min =  +0.00 V, max =  +4.08 V)
+5V:          +2.94 V  (min =  +0.00 V, max =  +4.08 V)
in4:          +0.00 V  (min =  +0.00 V, max =  +4.08 V)  ALARM
in5:          +0.00 V  (min =  +0.00 V, max =  +4.08 V)  ALARM
in6:          +4.08 V  (min =  +0.00 V, max =  +4.08 V)  ALARM
in7:          +3.09 V  (min =  +0.00 V, max =  +4.08 V)
Vbat:         +3.10 V  
fan1:           0 RPM  (min =    0 RPM)
fan2:           0 RPM  (min =    0 RPM)
fan3:           0 RPM  (min =    0 RPM)
temp1:        +36.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = thermistor
temp2:        +27.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = thermal diode
temp3:         -2.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = thermistor
intrusion0:  ALARM
```
Finally these are the graphs what I get:
![captura de pantalla de 2017-05-11 11-26-22](https://cloud.githubusercontent.com/assets/4059108/25942294/c37fed78-363c-11e7-8132-0d55b686de64.png)

Also as you can see, the `temp1` output is not working either.
Thank you so much.

**Comment by mikaku** [comment]
> Also as you can see, the temp1 output is not working either.

The only I see is that **temp1** has 0 degrees. Can you please check your Monitorix log file to see if there are some error messages?

If the **temp1** value came from zero, it might take some minutes to start showing the real value.

**Comment by WyRe** [comment]
> If the temp1 value came from zero, it might take some minutes to start showing the real value.

Yes, you are right, that's fixed but what do you think about descriptions? 
![captura de pantalla de 2017-05-11 11-41-43](https://cloud.githubusercontent.com/assets/4059108/25943063/eebec318-363e-11e7-9a68-709964bb4e4d.png)

**Comment by mikaku** [comment]
> Yes, you are right, that's fixed but what do you think about descriptions?

If you mean why you don't see your descriptions in the Voltage graph, then keep in mind that the `<desc>` section is not applicable to that graph: 

```
desc
      This list complements the list option only for the graphs: MB and CPU temperatures, Fans  speeds  and  GPU temperatures.
```

(Besides this, I see now that this sentence does not include the Core graph. Fixed now.)

**Comment by WyRe** [comment]
mmm I would suggest you to include also that grap xD
