### ISSUE TITLE
Incorrect and misconfigured file paths in Monitorix

### ISSUE THREAD

**Issue by Alkaris** [mikaku/Monitorix#184]
it seems by default somehow this comes packaged misconfigured and has incorrect file path issues. I installed this from Debian source and it has issues with loading the missing image files or it has incorrect directory names that have a double slash in the file paths particularly with `/var/lib/monitorixdisk.rrd` specifically. All the other ones are there except that one. and then you also got missing image files for `/var/lib/monitorix/www/imgs/diskX` PNG files.

[![Error][1]][1]

  [1]: http://i.imgur.com/PHZFiU3.png

There are some incorrect misconfigured file paths are also like this `/var/lib/monitorix/www//imgs/` with their `//` double slashes in the paths. Not sure if that was done intentionally when you made this but, just something to point out there. Easy fix in the config file and a reload of the service of course. Can't seem to do anything about those missing files however.

**Comment by mikaku** [comment]
I don't see any problems installing Monitorix on Debian and using the default configuration. Also, the double slash is never a problem since the kernel obviates it automatically.

It looks like you have modified the configuration file and you removed a trailing slash in the option `base_lib`.

Please check your configuration file and compare it with the default that comes with the original package.

**Comment by Alkaris** [comment]
I have to say you are wrong @mikaku, I looked in the directories where those files are suppose to be and they do not exist at all. I've checked it many times. those files it mentions do not exist in the default configuration that was installed. I haven't removed any trailing slashes at the option for `base_lib` either, I only removed the double slashes that were causing it not to find the other directory properly in `/var/lib/monitorix/www//imgs/` because it was causing the other stuff to not load in properly..

**Comment by mikaku** [comment]
Can you, please, pastebin your current configuration file?
(*please hide before any sensible information!*)

**Comment by IzzySoft** [comment]
@Alkaris To make things easier: You wrote you've installed from "Debian source". I'm not sure what source you point to there, and which steps you performed to install (maybe you update that into your initial post – including the permissions monitorix has on `/var/lib/monitorix`? Maybe you've missed some step during installation, and monitorix e.g. lacks write permission there). The path in your screenshot also looks strange: note the missing `/` in `/var/lib/monitorixdisk.rdd`.

You could also try installing from the `.deb` package and see if that solves the issue. You can find it linked from the Monitorix download page. I'm using it that way on multiple machines without any issues (Debian 7/8 64bit and ARM, Ubuntu 12.04 and Mint 18.1 64bit) – and my guess is that's what mikaku also used for verification.
