### ISSUE TITLE
Lot of Use of uninitialized value $pnum errrors

### ISSUE THREAD

**Issue by msaus** [mikaku/Monitorix#186]
Do you know why I am getting following errors?

Wide character in print at ./monitorix.cgi line 487.
Use of uninitialized value $pnum in scalar chomp at /usr/lib/monitorix/port.pm line 527, <IN> line 1.
Use of uninitialized value $pnum in substitution (s///) at /usr/lib/monitorix/port.pm line 528, <IN> line 1.
Use of uninitialized value $pnum in string eq at /usr/lib/monitorix/port.pm line 529, <IN> line 1.
Use of uninitialized value $pnum in scalar chomp at /usr/lib/monitorix/port.pm line 527, <IN> line 1.
Use of uninitialized value $pnum in substitution (s///) at /usr/lib/monitorix/port.pm line 528, <IN> line 1.
Use of uninitialized value $pnum in string eq at /usr/lib/monitorix/port.pm line 529, <IN> line 1.
Use of uninitialized value $pnum in scalar chomp at /usr/lib/monitorix/port.pm line 527, <IN> line 1.
Use of uninitialized value $pnum in substitution (s///) at /usr/lib/monitorix/port.pm line 528, <IN> line 1.
Use of uninitialized value $pnum in string eq at /usr/lib/monitorix/port.pm line 529, <IN> line 1.
Use of uninitialized value $pnum in scalar chomp at /usr/lib/monitorix/port.pm line 527, <IN> line 1.
Use of uninitialized value $pnum in substitution (s///) at /usr/lib/monitorix/port.pm line 528, <IN> line 1.
Use of uninitialized value $pnum in string eq at /usr/lib/monitorix/port.pm line 529, <IN> line 1.
Use of uninitialized value $pnum in scalar chomp at /usr/lib/monitorix/port.pm line 527, <IN> line 1.
Use of uninitialized value $pnum in substitution (s///) at /usr/lib/monitorix/port.pm line 528, <IN> line 1.
Use of uninitialized value $pnum in string eq at /usr/lib/monitorix/port.pm line 529, <IN> line 1.
Use of uninitialized value $pnum in scalar chomp at /usr/lib/monitorix/port.pm line 527, <IN> line 1.
Use of uninitialized value $pnum in substitution (s///) at /usr/lib/monitorix/port.pm line 528, <IN> line 1.
Use of uninitialized value $pnum in string eq at /usr/lib/monitorix/port.pm line 529, <IN> line 1.
Use of uninitialized value $pnum in scalar chomp at /usr/lib/monitorix/port.pm line 527, <IN> line 1.
Use of uninitialized value $pnum in substitution (s///) at /usr/lib/monitorix/port.pm line 528, <IN> line 1.
Use of uninitialized value $pnum in string eq at /usr/lib/monitorix/port.pm line 529, <IN> line 1.
Use of uninitialized value $pnum in scalar chomp at /usr/lib/monitorix/port.pm line 527, <IN> line 1.
Use of uninitialized value $pnum in substitution (s///) at /usr/lib/monitorix/port.pm line 528, <IN> line 1.
Use of uninitialized value $pnum in string eq at /usr/lib/monitorix/port.pm line 529, <IN> line 1.
Use of uninitialized value $pnum in scalar chomp at /usr/lib/monitorix/port.pm line 527, <IN> line 1.
Use of uninitialized value $pnum in substitution (s///) at /usr/lib/monitorix/port.pm line 528, <IN> line 1.
Use of uninitialized value $pnum in string eq at /usr/lib/monitorix/port.pm line 529, <IN> line 1.

The monitorix version is 3.9.0 the latest one.

I just freshly install monitorix today.

**Comment by mikaku** [comment]
Can you, please, pastebin the contents of the `<port>` section of your current configuration file?
Thanks.

**Comment by mikaku** [comment]
Oh wait!

Check first if you have the `netstat` command in your system. This command seems to start being deprecated in some Linux distributions, so you might have to install an specific package called `net-tools`.

**Comment by msaus** [comment]
Thank you very much for your reply.

I have netstat command installed on my ubuntu.

Here is the content of the <port>.

  max = 9                                                                                                                                                                      
  rule = 24000                                                                                                                                                                 
  list = 25, 21, 80, 22, 110, 139, 3306, 53, 143                                                                                                                               
  <desc>                                                                                                                                                                       
    25  = SMTP,    tcp, in, 0, 1000                                                                                                                                            
    21  = FTP,     tcp, in, 0, 1000                                                                                                                                            
    80  = HTTP,    tcp, in, 0, 1000                                                                                                                                            
    22  = SSH,     tcp, in, 0, 1000                                                                                                                                            
    110 = POP3,    tcp, in, 0, 1000                                                                                                                                            
    139 = NETBIOS, tcp, in, 0, 1000                                                                                                                                            
    3306  = MYSQL,   tcp, in, 0, 1000                                                                                                                                          
    53  = DNS,     udp, in, 0, 1000                                                                                                                                            
    143 = IMAP,    tcp, in, 0, 1000                                                                                                                                            
  </desc>                                                                                                                                                                      
  graphs_per_row = 3                                                                                                                                                           
</port>

**Comment by mikaku** [comment]
Where are the `<desc>` tags?

Please, enclose with backticks your pastebin.

**Comment by msaus** [comment]
<port>                                                                                                                                                                         
  max = 9                                                                                                                                                                      
  rule = 24000                                                                                                                                                                 
  list = 21, 80, 24318,3306                                                                                                                                                    
  <desc>                                                                                                                                                                       
#   25  = SMTP,    tcp, in, 0, 1000                                                                                                                                            
    21  = FTP,     tcp, in, 0, 1000                                                                                                                                            
    80  = HTTP,    tcp, in, 0, 1000                                                                                                                                            
    24318 = SSH,     tcp, in, 0, 1000                                                                                                                                          
#   110 = POP3,    tcp, in, 0, 1000                                                                                                                                            
#   139 = NETBIOS, tcp, in, 0, 1000                                                                                                                                            
    3306  = MYSQL,   tcp, in, 0, 1000                                                                                                                                          
#   53  = DNS,     udp, in, 0, 1000                                                                                                                                            
#   143 = IMAP,    tcp, in, 0, 1000                                                                                                                                            
  </desc>                                                                                                                                                                      
  graphs_per_row = 3                                                                                                                                                           
</port>

**Comment by msaus** [comment]
I forgot to paste desc tag.

**Comment by mikaku** [comment]
What's that?

**Comment by mikaku** [comment]
Please, format your message accordingly, otherwise it will be difficult to read it.

**Comment by msaus** [comment]
Sorry for that.
I reformat it.

**Comment by mikaku** [comment]
Well, your last paste is different from the fist one, should I assume that the last one if your current configuration?

If so, and as you probably can notice, you have defined ports that are missing in the `list` option. So please, remove them and restart Monitorix.

Your configuration should look something like this:
```
<port>
   max = 9
   rule = 24000
   list = 21, 80, 24318, 3306
   <desc>
      21 = FTP, tcp, in, 0, 1000
      80 = HTTP, tcp, in, 0, 1000
      24318 = SSH, tcp, in, 0, 1000
      3306 = MYSQL, tcp, in, 0, 1000
   </desc>
   graphs_per_row = 3
</port>
```

Also, please, pastebin the output of the commands `netstat -nl --tcp` and `netstat -nl --udp` in your PC.

Thanks.

**Comment by msaus** [comment]
root@sub0000545311:/home/maint# netstat -nl --tcp
稼働中のインターネット接続 (サーバのみ)
Proto 受信-Q 送信-Q 内部アドレス            外部アドレス            状態      
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:24318           0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:587           0.0.0.0:*               LISTEN     
tcp6       0      0 :::80                   :::*                    LISTEN     
tcp6       0      0 :::24318                :::*                    LISTEN  

root@sub0000545311:/home/maint# netstat -nl --udp
稼働中のインターネット接続 (サーバのみ)
Proto 受信-Q 送信-Q 内部アドレス            外部アドレス            状態      
udp        0      0 211.125.67.23:123       0.0.0.0:*                          
udp        0      0 127.0.0.1:123           0.0.0.0:*                          
udp        0      0 0.0.0.0:123             0.0.0.0:*                          
udp6       0      0 fe80::216:3eff:fe00:123 :::*                               
udp6       0      0 ::1:123                 :::*                               
udp6       0      0 :::123                  :::*

**Comment by mikaku** [comment]
Looks like you only read the last line of my post.

**Comment by msaus** [comment]
Hello there,
Thank you for your reply.
I set the port as you told me.

Also, I added "export LANG=en_US;" into line 524 like following in the monitorix.cgi.

open(IN, "export LANG=en_US;netstat -nl --$pp |");

Then, lots of errors are gone.

Is that okay to set like that?

After adding that, I still have following errors.
Wide character in print at ./monitorix.cgi line 487.
Wide character in print at ./monitorix.cgi line 487.
Wide character in print at ./monitorix.cgi line 487.
Wide character in print at ./monitorix.cgi line 487.

So, I added this on the top of monitorix.cgi.
use Encode;

Also, I modified line 487 to following.
print encode('utf-8',"    <h4><font color='#888888'>" . strftime("%a %b %e %H:%M:%S %Z %Y", localtime) . "</font></h4>\n");

Then, all errors are gone.

**Comment by mikaku** [comment]
This is interesting.

Before I include these modifications, can you please, change `export LANG=en_US` by `LC_ALL=C`? I'd like to know if it also works.

Like this: `open(IN, "LC_ALL=C ;netstat -nl --$pp |");`

I'll include your `Encode` modifications.
Thanks a lot!

**Comment by msaus** [comment]
Following code give me lots of errors that I had.
`open(IN, "LC_ALL=C ;netstat -nl --$pp |");`

So, I set back to this: `export LANG=en_US;`

**Comment by mikaku** [comment]
Wait, perhaps you should prefix it with `export`:

`open(IN, "export LC_ALL=C ; netstat -nl --$pp |");`

Try again, and let me know.
Thanks.

**Comment by msaus** [comment]
It looks like following is working.

`open(IN, "export LC_ALL=C ; netstat -nl --$pp |");`

**Comment by msaus** [comment]
But, following is used for sh system.

`export LC_ALL=C`

So, if the system is csh then someone might have to include 'setenv'.

**Comment by mikaku** [comment]
Perhaps a universal alternative could be:

`open(IN, "export LANG=C ; netstat -nl --$pp |");`

not sure if it would work.

**Comment by mikaku** [comment]
Another more elegant alternative would be putting the following lines in the top of `port.pm` module:

```
use strict;
use warnings;
use Monitorix;
use RRDs;
use POSIX;
use Exporter 'import';
our @EXPORT = qw(port_init port_update port_cgi);

# Force a standard locale
$ENV{LANG} = "";
setlocale(LC_ALL, "C");
```
Also, leave the original line:

`open(IN, "netstat -nl --$pp |");`

Test it, and let me now if that suffices.

**Comment by msaus** [comment]
Hello there,

The above source code gives me following error.

`WARNING: unable to load module 'port'. Bareword "LC_ALL" not allowed while "strict subs" in use at /usr/lib/monitorix/port.pm`

So, I was looking for different solution for that this morning and found one below.

`use POSIX qw(setlocale LC_ALL);
setlocale(LC_ALL, "C");`

**Comment by msaus** [comment]
I am not perl engineer, so, if there is another way to configure the locale then please let me know.

**Comment by msaus** [comment]
Possibly, we can just add like this?

`use POSIX qw(strftime), qw(setlocale LC_ALL);`
`setlocale(LC_ALL, "C");`

**Comment by mikaku** [comment]
Oh yes, that was my fault. I've already this setup in `monitorix` collector, but with `LC_TIME`.

So, my question is:

With the following lines:

```
use POSIX qw(setlocale LC_ALL);
setlocale(LC_ALL, "C");
```

is all working fine?

**Comment by msaus** [comment]
Yes, it is working on my environment.
I just found that 2 lines in Japanese website.

here: [http://d.hatena.ne.jp/hide_o_55/20111125/1322223051](url)

As I told you, I am not perl engineer.
If your one is better then I will add your solution.

**Comment by msaus** [comment]
Oh...well
That website is too old.

**Comment by mikaku** [comment]
OK, I'll add these two lines in the `port.pm` module, so you won't have to add them manually on the next Monitorix version.

Please, let me know if other `.pm` modules require also these two lines.
Thanks for your feedback!

**Comment by msaus** [comment]
no worries :)
I will tell you if other .pm modules require those two lines.
Anyways, thanks for your help.
