### ISSUE TITLE
Request: Monitor more than 10 network interfaces

### ISSUE THREAD

**Issue by delphir-com** [mikaku/Monitorix#188]
Monitor more than 10 network interfaces, or did I miss some way it can be done with current implementation?

**Comment by mikaku** [comment]
I thought that 10 network interfaces would be enough for everybody (did I have a Bill Gates moment?).

**Comment by delphir-com** [comment]
Not enough when you have virtual-machines ;)

**Comment by mikaku** [comment]
I hope now it will cover any wish ;-)

**Comment by delphir-com** [comment]
Will this update be available through IzzySoft ? I don`t see any right now..

**Comment by mikaku** [comment]
This is available only in the devel (Github) version, it will be for GA in the next official version.
Of course, you can download the current devel version, it's functional enough. Check the Changelog to know what's new and what has been changed and update your configuration file.

**Comment by delphir-com** [comment]
Great, thanks!
