### ISSUE TITLE
Feature Request: ZFS iostat per Pool

### ISSUE THREAD

**Issue by netleader** [mikaku/Monitorix#190]
As stated it would be nice to have an zpool iostat graph.

BTW.: Thanks for the nice and easy to use software!

**Comment by mikaku** [comment]
I've included two new graphs: Operations and Bandwidth.
Check the following screen shot

![zfs](https://user-images.githubusercontent.com/829885/37824703-c85e74be-2e8d-11e8-99fe-0359f73bdfee.png)

Please, download the latest `zfs.pm` module, update your current `monitorix.conf`, restart Monitorix and check if all is fine.

Let me know.

**Comment by netleader** [comment]
Perfect! Thank you!
