### ISSUE TITLE
Active processes graph wrong

### ISSUE THREAD

**Issue by StephenAtty** [mikaku/Monitorix#191]
The Active processes graph seems to show a lot more processes than I actually have.

top shows between 150 and 170 processes running ;

top - 17:27:05 up  7:19,  2 users,  load average: 0.90, 0.54, 0.40
Tasks: 155 total,   2 running, 151 sleeping,   0 stopped,   2 zombie
%Cpu(s): 29.2 us,  6.6 sy,  0.0 ni, 62.5 id,  1.0 wa,  0.0 hi,  0.7 si,  0.0 st
KiB Mem:   7338588 total,  7051304 used,   287284 free,   485436 buffers
KiB Swap:  3344380 total,    19076 used,  3325304 free.  2131868 cached Mem

The graph shows over 300

![system2 1day](https://user-images.githubusercontent.com/251449/31577368-f333c3d0-b104-11e7-8f90-7e536e1476ea.png)

**Comment by mikaku** [comment]
Hi,

In `system.pm` Monitorix creates a list of all numeric directories in `/proc` filesystem to count the number of current processes in the system.

The following command should give you a number almost identical as what `top` says as the number of current Tasks:

```
# ls -1d /proc/[0-9]* | wc -l
```

Please, let me know.
Regards.

**Comment by StephenAtty** [comment]
ls -1d /proc/[0-9]* | wc -l

produces a count of 151

Active processes graph shows  360
![system2z 1day](https://user-images.githubusercontent.com/251449/31625104-ca0f198e-b29c-11e7-973e-f32e94405f05.png)

**Comment by mikaku** [comment]
I assumed you were using the latest Monitorix version, but I think you are using an older version. Next time, please read more carefully my posts.

In the versions previous of 3.10.0 Monitorix used the contents of the file `/proc/loadavg` to get the total of running and sleeping processes, and that total also includes threads.

In the latest version and as I said, Monitorix use a different approach to get that total, and it looks like `top` also uses the same.

So, please, upgrade your Monitorix version.
