### ISSUE TITLE
Wrong window title in browser

### ISSUE THREAD

**Issue by MegaV0lt** [mikaku/Monitorix#192]
After update monitorix on debian 9.2 i see "place title here" as the name for the tab in FF:
![auswahl_20171021_15 57 02](https://user-images.githubusercontent.com/2804301/31852494-e1a82e02-b678-11e7-9a8a-c9f4fd410f1e.png)

**Comment by mikaku** [comment]
Can you, please, pastebin the first lines of your `monitorix.conf`?
Thanks.

**Comment by MegaV0lt** [comment]
I see:
`[~] # head /etc/monitorix/monitorix.conf
# Monitorix - configuration file
#
# See monitorix.conf(5) manpage for a detailed description of each option.
#
title = Place a title here
hostname =
theme_color = black
refresh_rate = 150
iface_mode = graph
`
So i just edited it...

**Comment by mikaku** [comment]
Yeah, just edit the option `title` and then restart Monitorix.
Also, at your convenience, close this issue.
Thanks.

**Comment by MegaV0lt** [comment]
Ok, worked even without restarting ;)

**Comment by mikaku** [comment]
You should restart Monitorix or you won't have the title in the main page.
If you want to appear the real hostname you can use the `hostname` option. The title is for something different.
