### ISSUE TITLE
Mixed Content with NGINX proxy

### ISSUE THREAD

**Issue by mendaxi** [mikaku/Monitorix#200]
When NGINX proxies the built-in server, references to HTTP objects in the CGI response create mixed content warnings/errors when the proxy serves using HTTPS. Can there be an option in the config/CGI file that changes HTTP references to HTTPS?

**Comment by mikaku** [comment]
Perhaps the global option `https_url = y` might of help for you.
Let me know.

**Comment by mendaxi** [comment]
worked perfectly. sorry for asking! i feel like i shouldnt have needed to ask in the first place :sob:

**Comment by mikaku** [comment]
Anyway, thanks for your feedback. 👍
