### ISSUE TITLE
Support conventions of 'free' from newer procps

### ISSUE THREAD

**Issue by kyak** [mikaku/Monitorix#204]
The output of 'free' utility from a newer procps package is different from what it used to be in previous versions. The article at https://www.linuxatemyram.com/ explains the output of new 'free' utility. Also, this article https://access.redhat.com/solutions/406773 explains how (some) fields of /proc/memory map to the output of 'free'.

For the users of newer 'free' version the mapping between "Memory allocation" graph and 'free' is not obvious.

As discussed in IRC, it might make sense to introduce a new option in <system> to be able to differentiate the output of 'free'.

Also, it makes sense to update this FAQ: http://www.monitorix.org/faq.html#Q112 to reflect this change.

**Comment by mikaku** [comment]
Just some links:

https://gitlab.com/procps-ng/procps/blob/master/free.c#L366
https://gitlab.com/procps-ng/procps/blob/master/proc/sysinfo.c#L696

**Comment by mikaku** [comment]
So, the value `used` in the Memory graph will be recalculated as:

`used = MemTotal - MemFree - Buffers - Cached - SReclaimable`

This will ensure that Monitorix will be in sync with the `Used` column in the new `free` command, and with the `-/+ buffers/cache` row in the old `free` command.

This change also obsoletes the new `memory_mode` option.

**Comment by mikaku** [comment]
Thanks!

**Comment by mikaku** [comment]
Finally, the value **used** in the Memory graph will be recalculated as:

used = MemTotal - MemFree - Buffers - Cached - SReclaimable - SUnreclaim
