### ISSUE TITLE
Large graphs seem to be missing all numerical data

### ISSUE THREAD

**Issue by WildPenquin** [mikaku/Monitorix#207]
Hi,

This used to work previously, but zoomed in graphs seem to be missing all numerical data!
Example:
Small pic (this is OK)
![kuva](https://user-images.githubusercontent.com/3398736/39407258-d19c7f70-4bcb-11e8-9ca6-18b42b833d9f.png)
Zoomed (clicked) pic (missing numerical data):
![kuva](https://user-images.githubusercontent.com/3398736/39407263-ee8c4d54-4bcb-11e8-963c-3548afa1b81f.png)

This is the case for all modules. The large (zoomed in) code must fail somewhere?

This happens both on 3.10.1-1 and current GIT.
**EDIT:** Arch Linux, perl 5.26.2
**EDIT2:** rrdtool 1.7.0 - in case that matters!

**Comment by mikaku** [comment]
You mean the picture legend?

If so, that's something never appeared in the zoomed in graphs.

**Comment by WildPenquin** [comment]
Yes, that's what I mean.

I must misremember then! If it is by design and there's nothing wrong with the screenshots (my memory says there used to be numbers), then this can be closed as invalid :-)

(one might argue that numbers in legend would be usefull in zoomed in pictures, though, but I don't actually need it, personally!)

**Comment by mikaku** [comment]
Yeah, it would be difficult to re-display all the legend in the zoomed in graphs since such graphs have different size and the layout is different.

Instead, you might want to play with the option `global_zoom` if you want bigger graphs with legend.
Anyway, thanks for your sincerity.
