### ISSUE TITLE
serv.pm uninitialized value in -r

### ISSUE THREAD

**Issue by dmgeurts** [mikaku/Monitorix#211]
First off: Thank you for a great monitoring tool.

Fresh install on Ubuntu 18.04 and checked the log file. Cleaned up my configuration a bit but am left with the following three lines. Any idea what could be causing this?

Use of uninitialized value in -r at /usr/lib/monitorix/serv.pm line 352.
Use of uninitialized value in -r at /usr/lib/monitorix/serv.pm line 363.
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/serv.pm line 430.

Thanks,

**Comment by mikaku** [comment]
Hi,

> First off: Thank you for a great monitoring tool.

Glad to know you are enjoying Monitorix! :smiley: 

It looks like you removed some log file definitions below the line:
```
# Log files pathnames
# -----------------------------------------------------------------------------
log_file        = /var/log/monitorix
[...]
```

You don't need to remove such log file definitions even when you know that your system won't  use them. Monitorix assumes that such definitions exist in the configuration file.

To suppress the error messages in the log file, I suggest you to reinsert the following log definitions:

```
hylafax_log     = /var/spool/hylafax/etc/xferfaxlog
cups_log        = /var/log/cups/page_log
cg_logdir       = /var/CommuniGate/SystemLogs/
```

Just let me know.

**Comment by dmgeurts** [comment]
Indeed, I'd commented out those lines. Now reinstated and all happy here. Thank you!
