### ISSUE TITLE
RPM command calls from Monitorix

### ISSUE THREAD

**Issue by goooroooX** [mikaku/Monitorix#212]
Hi!

Each time monitorix polling data for it's metrics, it seems to be running following command:
`rpm -q -a --queryformat "%{NAME}\n%{VERSION}-%{RELEASE}\n%{EPOCH}\n%{GROUP}\n%{ARCH}\n%{SUMMARY}\n\n"`
In audit.log I have two SYSCALLs, one successful and one failed (see below) related to RPM command execution.

As far as I see from Monitorix source code, it should not query RPM information, but it still do.
I dont want my audit.log to be spammed with this information. Can you suggest how to get rid of those RPM calls?

```
# sysdig -c spy_users

9828 16:32:58 root) df -k /
9830 16:32:58 root) df -i /
9832 16:32:58 root) df -k /boot
9834 16:32:58 root) df -i /boot
9836 16:32:58 root) df -k /home
9838 16:32:58 root) df -i /home
9840 16:32:58 root) df -k /storage
9842 16:32:58 root) df -i /storage
9844 16:32:58 root) df -k /storage/shared/8TB
9846 16:32:58 root) df -i /storage/shared/8TB
9848 16:32:58 root) rpm -q -a --queryformat %{NAME}\n%{VERSION}-%{RELEASE}\n%{EPOCH}\n%{GROUP}\n%{ARCH}\n%{SUMMARY}\n\n
9875 16:33:00 root) parted -v
9877 16:33:00 root) parted /dev/sdb unit cyl print
9877 16:33:00 root) parted /dev/sdc unit cyl print
9877 16:33:00 root) parted /dev/sdd unit cyl print
9877 16:33:00 root) parted /dev/sda unit cyl print
9892 16:33:00 root) smartctl --version
9895 16:33:00 root) smartctl -i /dev/sda
9899 16:33:00 root) smartctl -H /dev/sda
9903 16:33:00 root) smartctl -i /dev/sdb
9905 16:33:00 root) smartctl -H /dev/sdb
```

```
# cat /var/log/audit/audit.log

type=SYSCALL msg=audit(1537450378.824:274538): arch=c000003e syscall=59 success=yes exit=0 a0=1c4e790 a1=1c4f020 a2=1c4d210 a3=7ffeb913b8a0 items=2 ppid=9848 pid=9849 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0tty=(none) ses=4294967295 comm="rpm" exe="/usr/bin/rpm" key="software_mgmt"
type=EXECVE msg=audit(1537450378.824:274538): argc=5 a0="rpm" a1="-q" a2="-a" a3="--queryformat" a4="%{NAME}\n%{VERSION}-%{RELEASE}\n%{EPOCH}\n%{GROUP}\n%{ARCH}\n%{SUMMARY}\n\n"
type=PATH msg=audit(1537450378.824:274538): item=0 name="/bin/rpm" inode=977089 dev=fd:00 mode=0100755 ouid=0 ogid=0 rdev=00:00 objtype=NORMAL cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
type=PATH msg=audit(1537450378.824:274538): item=1 name="/lib64/ld-linux-x86-64.so.2" inode=33562915 dev=fd:00 mode=0100755 ouid=0 ogid=0 rdev=00:00 objtype=NORMAL cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
type=PROCTITLE msg=audit(1537450378.824:274538): proctitle=72706D002D71002D61002D2D7175657279666F726D617400257B4E414D457D5C6E257B56455253494F4E7D2D257B52454C454153457D5C6E257B45504F43487D5C6E257B47524F55507D5C6E257B415243487D5C6E257B53554D4D4152597D5C6E5C6E
type=SYSCALL msg=audit(1537450378.850:274539): arch=c000003e syscall=2 success=no exit=-17 a0=1b26380 a1=c2 a2=1a4 a3=7ffd7616ece0 items=2 ppid=9848 pid=9849 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="rpm" exe="/usr/bin/rpm" key="unauthedfileaccess"
type=PATH msg=audit(1537450378.850:274539): item=0 name="/var/lib/rpm/" inode=67160140 dev=fd:00 mode=040755 ouid=0 ogid=0 rdev=00:00 objtype=PARENT cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
type=PATH msg=audit(1537450378.850:274539): item=1 name="/var/lib/rpm/__db.001" inode=68527969 dev=fd:00 mode=0100644 ouid=0 ogid=0 rdev=00:00 objtype=NORMAL cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
type=PROCTITLE msg=audit(1537450378.850:274539): proctitle=72706D002D71002D61002D2D7175657279666F726D617400257B4E414D457D5C6E257B56455253494F4E7D2D257B52454C454153457D5C6E257B45504F43487D5C6E257B47524F55507D5C6E257B415243487D5C6E257B53554D4D4152597D5C6E5C6E
```

**Comment by mikaku** [comment]
> Each time monitorix polling data for it's metrics, it seems to be running following command:
rpm -q -a --queryformat "%{NAME}\n%{VERSION}-%{RELEASE}\n%{EPOCH}\n%{GROUP}\n%{ARCH}\n%{SUMMARY}\n\n"

What?

> As far as I see from Monitorix source code, it should not query RPM information, but it still do.

Why do you think Monitorix is executing such `rpm -q -a ...` command? I don't see anything related to Monitorix in your `audit.log`.

**Comment by goooroooX** [comment]
Yes, I know it sounds weird, but I was unable to find other potential sources of this noise. Please take a look on **sysdig** output. All those commands are executed by Monitorix, and they stuck for a second on _rpm_ query just after last _df_, then continue with _parted_ after a second. 
It would be great of you will be able to check **sysdig** output on your environment during the Monitorix execution (capturing metrics data). This should take few minutes.
Thank you!

**Comment by mikaku** [comment]
> 9828 16:32:58 root) df -k /
> 9832 16:32:58 root) df -k /boot
> 9836 16:32:58 root) df -k /home
> 9840 16:32:58 root) df -k /storage
> 9844 16:32:58 root) df -k /storage/shared/8TB
> 9848 16:32:58 root) rpm -q -a --queryformat %{NAME}\n%{VERSION}-%{RELEASE}\n%{EPOCH}\n%{GROUP}\n%{ARCH}\n%{SUMMARY}\n\n
> 9875 16:33:00 root) parted -v
> 9877 16:33:00 root) parted /dev/sdb unit cyl print
> 9877 16:33:00 root) parted /dev/sdc unit cyl print
> 9877 16:33:00 root) parted /dev/sdd unit cyl print
> 9877 16:33:00 root) parted /dev/sda unit cyl print
> 9892 16:33:00 root) smartctl --version
> 9895 16:33:00 root) smartctl -i /dev/sda
> 9899 16:33:00 root) smartctl -H /dev/sda
> 9903 16:33:00 root) smartctl -i /dev/sdb
> 9905 16:33:00 root) smartctl -H /dev/sdb

None of these commands are executed by Monitorix.
You have the source code, check it for your own.

**Comment by goooroooX** [comment]
My bad. Sorry for bothering. Please close the issue.
