### ISSUE TITLE
Feature request: Show all values from remote Monitorx agents (both multihost and single remotes)

### ISSUE THREAD

**Issue by zejjnt** [mikaku/Monitorix#216]
Right now, choosing a Monitorix server only gives you the results from a single module.
The same goes with multihosts.
I would very much appreciate:
* Be able to show all stats from a remote host, just like with localhost
* See all stats when choosing "All" multihosts, preferrably side to side but layout is not the most important thing here. Like this maybe?
![image](https://user-images.githubusercontent.com/20284369/50547152-ba9a0700-0c34-11e9-9488-824e97f8bb8f.png)
(Quick mockup but you get the idea.)

**Comment by mikaku** [comment]
Please, download the latest `monitorix.cgi`, test these changes and let me know.

**Comment by zejjnt** [comment]
> Please, download the latest `monitorix.cgi`, test these changes and let me know.

Since the reload time is just 2 minutes, the page doesn't have enough time to load everything before it refreshes. It really takes a long time to load, BUT that is very likely because I run it on such weak hardware. 
As master I have a Raspberry Pi 3 B+ and that is about as fast as it is when just using localhost, but the other nodes are Synology NAS devices @ 900 MHz single core, 256 MB RAM and 1.2 GHz dual core, 512 MB RAM respectively.

So unfortunately I can't help you a lot speedwise right now. Though I should be able to sneak it in on our three Pi's at work tomorrow though, those are two 3 B+ and one 1 B+ which should be more than enough to make a fair judgement since their only purpose right now is showing a simple website each.

Also the page doesn't care about which modules are loaded on which node, so I get a lot of "Not Found
The requested URL /monitorix-cgi/monitorix.cgi was not found on this server.".
I'll get back to you tomorrow.

**Comment by zejjnt** [comment]
Unfortunately the Synology's were rebooted because of a firmware update yesterday and apparently the Debian chroot packages I run on them doesn't start all services (like Monitorix) automatically but here's how far it gets before going for a reload
![screenshot-192 168 1 6-8070-2019 01 03-18-51-20](https://user-images.githubusercontent.com/20284369/50653236-1cd26f00-0f89-11e9-98ef-e947d97b2e4b.png)

**Comment by IzzySoft** [comment]
@zejjnt you know you can adjust the reload interval in the config, don't you? :wink:

**Comment by zejjnt** [comment]
> @zejjnt you know you can adjust the reload interval in the config, don't you? 😉

No because I can't brain after work, I have the dumb *facepalm* (as in me being stupid, not you)
Gonna tweak the interval and check how long the loading time is, thanks for the reminder

**Comment by zejjnt** [comment]
I can pretty much confirm my suspicion that the hardware is too weak to drive all of this correctly since the graphs load from fastest to slowest.
At 30 seconds the graphs for the "main node" start to show, they finish around 1 min.
Then at around 3 minutes all graphs from the second machine appear instantly.
The third and slowest machine still hasn't shown any graph after 7 minutes now so I'm sparing the poor machine and quitting the experiment for tonight.
It is barely responding to shell commands even; completely choked from perl processes (227 processes and ~60 load at the time I checked top and down to 80 processes and ~2 load after restarting the Monitorix service).

Maybe the loading can be made in stages/increments so that the load will not go from 0 to 100 to 0?
I realize that it would take lots of rewrites and that these test results are not very useful, as I said I will try to get some more more useful results tomorrow.
![image](https://user-images.githubusercontent.com/20284369/50664741-697c7100-0fae-11e9-97d8-fb614795a93e.png)

**Comment by IzzySoft** [comment]
@zejjnt I'm afraid it's not the *loading* driving the CPU – but generating the PNGs. AFAIK they are generated on-the-fly out of the RRD data. A weak machine might be pretty stressed by that indeed.

**Comment by zejjnt** [comment]
> @zejjnt I'm afraid it's not the _loading_ driving the CPU – but generating the PNGs. AFAIK they are generated on-the-fly out of the RRD data. A weak machine might be pretty stressed by that indeed.

And again you point out something that I should've thought of.
I was thinking that the web server was generating the files and passing them along in the same process but of course that's not how it works.
Tinkering with custom patch-work projects have clearly left me quite hollow when the first thing I think when I see perl is "rudimentary web server". But I was expecting rrdtool or something like that when looking for graph generation.
Since even GD can be taxing for an old CPU there's no wonder the 900 MHz single core is choking when passed 100+ processes in no time.

**Comment by zejjnt** [comment]
OK, I've set up 4 devices at the office now. Three of them load, and it's the same reason as with my home setup.
pileft = Raspberry Pi 3 B+
pimid = Raspberry Pi 1 B
piright = Raspberry Pi 3 B+
vpfsd = OnApp VPS with 3 cores and 2 GB RAM doing nothing at all except for running monitorix right now
I'm gonna merge this with the 3 I have at home and try to give you some more numbers (and a proper fullscreen screenshot)

whoa, just as I was about to post the RPi 1 loaded! The reload time on these devices are set to 180 seconds so for some reason it worked after a reload. Some cache thing going on with perl maybe?
![image](https://user-images.githubusercontent.com/20284369/50700817-d6921400-104b-11e9-921c-f6dd3d7f0b7e.png)

**Comment by zejjnt** [comment]
I removed the two slow nodes as they were just weighing everything down at the moment.
So here's a complete page when all the five nodes are done loading and generating.
pileft, piright and vpfsd have the original config except for the refresh interval, so I don't know what should be in the middle of the page where all five columns are empty.
It's clear that graphs_per_row isn't being used here :D 
![image](https://user-images.githubusercontent.com/20284369/50709037-cc314380-1066-11e9-82e9-b8a4e1fad7ac.png)
If I can assist in any way just let me know

**Comment by mikaku** [comment]
Have you read the three caveats I exposed in my previous [comment](https://github.com/mikaku/Monitorix/issues/216#issuecomment-450876576)? most of your questions are explained there.

As I said, loading some many graphs remotely can be exposed to a multiple issues, Internet speed, CPU load capability, etc.

If it works with just three remote servers, I don't a reason why it shouldn't work with five remote servers, unless some of these remote servers don't has enough CPU power to generate the PNG graphs so quickly, or they don't have the same configuration options (as stated in my comment).

**Comment by zejjnt** [comment]
> Have you read the three caveats I exposed in my previous [comment](https://github.com/mikaku/Monitorix/issues/216#issuecomment-450876576)? most of your questions are explained there.
> 
> As I said, loading some many graphs remotely can be exposed to a multiple issues, Internet speed, CPU load capability, etc.
> 
> If it works with just three remote servers, I don't see a reason why it shouldn't work with five remote servers, unless some of these remote servers don't have enough CPU power to generate the PNG graphs so quickly, or they don't have the same configuration options (as stated in my comment).

I missed the first one but the two others I have kept in mind.
I understand that different configurations on the machines are a problematic thing in this case but in the middle neither the master nor the other nodes have any configured measurements so I don't really understand why there are empty rows.

I understood that the whole page was going to take a while when asking for this, I'm just pointing out that the slowdowns are not because of everything taking its turn to load but graphs appearing here and there seemingly unrelated to the machine speed.

**Comment by mikaku** [comment]
OK, I'll do some testings with more remote machines just to make sure that there isn't something wrong in the code that I've just implemented.

**Comment by mikaku** [comment]
This is the result after applying the last commit:

![test](https://user-images.githubusercontent.com/829885/50843260-a35fc580-1368-11e9-89db-f3f45605c442.png)

As you can see, almost all graphs are shown correctly. The ones that are missing is because the remote server don't has enabled the graph.
