### ISSUE TITLE
Feature request: positive and negative values for RX/TX on network interfaces

### ISSUE THREAD

**Issue by Saentist** [mikaku/Monitorix#217]
Is there a option to be implemented as selectable option 
currently both values are positive
/as "netstats_in_bps y/n"/

**Comment by Saentist** [comment]
Any chance?

**Comment by mikaku** [comment]
Yes, sorry. I think I could introduce a new global option called `netstats_mode` with two possible values:

- overlapped
- separated

The `overlapped` option, being the default one, would refer to the current representation and `separated` would be with the way as you suggest.

Yet, I'd need to know which values should go in the bottom or in the top side.

I mean, incoming traffic in the bottom or in the top?

**Comment by Saentist** [comment]
Incoming = Positive = On Top
Outgoing = Negative = In Bottom

**Comment by mikaku** [comment]
Please, test this new feature and let me know if it works as expected.

Don't forget to include the new global option in your `monitorix.conf`, (e.g.: just below the option `netstats_in_bps`):

```
netstats_mode = separated
```

This is how appears the network graph after applying this new option:

![net](https://user-images.githubusercontent.com/829885/87016593-33393680-c1cf-11ea-9f8a-d79da27e0008.png)

**Comment by Saentist** [comment]
OK it work as expected

need to be added and enabled enable_hourly_view to see faster results
```
enable_back_button = y
enable_hourly_view = y
```

**Comment by mikaku** [comment]
Automatic addition of graphs is something not supported, and it's a very dangerous feature in some environments.

Instead, you might want to focus on the creation of an external (Perl-based, Shell-based, or whatever) tool that automatically configures your `monitorix.conf` according the devices found in your system.

**Comment by mikaku** [comment]
> OK it work as expected

In the next days I'll include support of that new option `netstats_mode` in other modules that include network graphs.
