### ISSUE TITLE
service stop responding while refreshing dashboard in browser

### ISSUE THREAD

**Issue by aminmazi** [mikaku/Monitorix#219]
Hi, thank you for such a good product.
sometimes I manually refresh the dashboard page :
`http://host_public_ip:8080/monitorix-cgi/monitorix.cgi?mode=localhost&graph=all&when=1week&color=black`
and the page shows an error on browser the service stops working until I restart service with systemctl in ubuntu!
this is the error that `/var/log/monitorix` shows:

`Use of uninitialized value in subroutine entry at /usr/share/perl5/HTTP/Server/Simple.pm line 422, <DATA> line 16. Bad arg length for Socket::sockaddr_family, length is 0, should be at least 2 at /usr/share/perl5/HTTP/Server/Simple.pm line 422, <DATA> line 16.`

**Comment by mikaku** [comment]
> Hi, thank you for such a good product.

Thanks, glad to know you are enjoying Monitorix.

As you now, Monitorix relies on the external Perl package [HTTP::Server::Simple](https://metacpan.org/pod/HTTP::Server::Simple) for the HTTP built-in service. I'm aware that after some specific heavy use that daemon looks like hung, and stops responding until the HTTP service is restarted by means of restarting Monitorix.

In the current (not released yet) development version, I've include a [patch](https://github.com/mikaku/Monitorix/commit/d4d76d775dd56db01a81620e4b7044e4b053c609) that work-around this problem by restarting the HTTP every time Monitorix receives a SIGHUP, which is normally sent during the logs rotation.

You can patch your current Monitorix with that work-around and let me know. Also, make sure you are using the latest version of that Perl module.

Thanks.

**Comment by aminmazi** [comment]
> You can patch your current Monitorix with that work-around and let me know.

I have installed monitorix manually from this documentation:
```
# apt-get update
# apt-get install rrdtool perl libwww-perl libmailtools-perl libmime-lite-perl librrds-perl libdbi-perl libxml-simple-perl libhttp-server-simple-perl libconfig-general-perl libio-socket-ssl-perl
# dpkg -i monitorix*.deb

# apt-get -f install
```
I prefer to wait for new release :)
