### ISSUE TITLE
Add a range to trigger alerts configuration option thus supporting above AND below threshold (aka out of range))

### ISSUE THREAD

**Issue by SodaMaker** [mikaku/Monitorix#221]
Not all alarms should go off when hot. Some users need cold/freeze alarms. It would nice to have a range alarm. If "value" is outside "range" then alarm and let the alarm-script decide if it is too hot, cold, or extreme.

**Comment by mikaku** [comment]
Something like this:

```
<alerts>
   temp0 = 3600, 40-60, /path/to/script
</alerts>
```

This configuration will activate the alarm if the value is out of the range between 40 and 60.

The new feature should also accept single value (no range) with the direction of threshold (above or below):

```
<alerts>
   temp0 = 3600, 60, /path/to/script, below
</alerts>
```

**Comment by mikaku** [comment]
I've added the first modification that supports the forth value `above` or `below` in the `<alerts>` section. In this commit the ranges are not supported yet, I'll work on it later.

Meanwhile, please, download the affected files by the commit, test it and let me know if it works as expected.
