### ISSUE TITLE
Raspberry PI data issues since switching to raspbian buster

### ISSUE THREAD

**Issue by nathanle** [mikaku/Monitorix#224]
I recently switched from stretch to buster, and I noticed some changes to the accuracy of my data.

![image](https://user-images.githubusercontent.com/16546036/52284021-a206c600-2931-11e9-9335-234ab5d02ca5.png)

Right after week 5, I switched to buster, and you can see that the CPU appears pegged at 1.2 Ghz. At first, I thought I had an application that was driving the CPU up. However, I do not think that is the case:

```
pi@pi3:~ $ vcgencmd measure_clock arm
frequency(45)=600000000
pi@pi3:~ $ vcgencmd measure_clock arm
frequency(45)=600000000
pi@pi3:~ $ vcgencmd measure_clock arm
frequency(45)=600000000
pi@pi3:~ $ vcgencmd measure_clock arm
frequency(45)=1200000000
pi@pi3:~ $ vcgencmd measure_clock arm
frequency(45)=1200000000
pi@pi3:~ $ vcgencmd measure_clock arm
frequency(45)=1200000000
pi@pi3:~ $ vcgencmd measure_clock arm
frequency(45)=1200000000
pi@pi3:~ $ vcgencmd measure_clock arm
frequency(45)=1200002000
pi@pi3:~ $ vcgencmd measure_clock arm
frequency(45)=1200000000
pi@pi3:~ $ vcgencmd measure_clock arm
frequency(45)=600000000

```

I forced it up to 1200000000 with stress-ng, but when stress-ng is not running, it is reporting 600 Mhz.

I do not know if the change to buster did it, but the timeline matches up. 

Thanks!

**Comment by nathanle** [comment]
Pretty much:

![image](https://user-images.githubusercontent.com/16546036/52289926-ffecdb00-293c-11e9-9b35-114220ab1be4.png)

pi@pi3:~ $ crontab -l | grep -v "^#"
0 1 * * 1 s3cmd put <a file> s3://<S3 bucket>
pi@pi3:~ $ sudo crontab -l | grep -v "^#"
0 1     *       1,3,6,9,12      *       certbot renew

I only have jobs that run at 1am on certain days.

**Comment by nathanle** [comment]
Well, I have been watching top, and I think you might be on to something. Monitorix is spiking the CPU every minute:

![image](https://user-images.githubusercontent.com/16546036/52290968-4e02de00-293f-11e9-9a68-089705d2ff03.png)

**Comment by mikaku** [comment]
I see small variations in your last graph. If the Monitorix version or its configuration didn't change as a result of your upgrade from stretch to buster, then I don't see a reason why Monitorix should affect to these values.

**Comment by nathanle** [comment]
Nothing in /etc/cron except for the cron.hourly,daily,weekly,monthly jobs standard with cron and cron.d has a php cleanup job that runs every 30 minutes. I agree that Monitorix should not affect these values, but the huge disparity in the graph and what I see in "vcgencmd measure_clock arm" brought me here. I will keep looking. Thanks for you time.

**Comment by nathanle** [comment]
Looks like turning off "bind" as a monitored service fixed it.

![image](https://user-images.githubusercontent.com/16546036/52293511-041cf680-2945-11e9-9e63-514261eaad06.png)

**Comment by nathanle** [comment]
![image](https://user-images.githubusercontent.com/16546036/52296330-151d3600-294c-11e9-8fe4-ab1d2a18424b.png)
Looks like that was it. I will turn it back on and report back if I find out why.

**Comment by mikaku** [comment]
Yeah, `bind` is a beast and parsing its, some times huge, .XML file can take some time.

**Comment by mikaku** [comment]
If your `bind` is serving statistics in the standard port, you can measure the size of its output with the following lines:

```
$ curl http://localhost:8053 -o bind.xml
$ ls -l bind.xml
```

Mine's size is around 130KB.

**Comment by mikaku** [comment]
Have you finally checked the size of the .XML file served by your `bind`?

**Comment by nathanle** [comment]
Hi Jordi,

Honestly, I have not had the time to check. It is working fine with the
BIND monitoring off, though.

Regards,
Nathan

**Comment by mikaku** [comment]
OK, let's close this since I suspect it's just a matter of the size of the .XML output of your `bind` and the low processor performance of a Raspberry Pi.
