### ISSUE TITLE
Unable to start APCUPS chart

### ISSUE THREAD

**Issue by modem7** [mikaku/Monitorix#225]
Hey guys, 

I'm on Fedora, and trying to get the APC graph working. 

I'm getting the following error:

![capture](https://user-images.githubusercontent.com/4349962/52440174-5876d080-2b15-11e9-8a74-f002f81ff654.JPG)

APCAccess is showing the following:

> APC      : 001,027,0673
> DATE     : 2019-02-07 20:16:44 +0000
> HOSTNAME : localhost.localdomain
> VERSION  : 3.14.14 (31 May 2016) redhat
> UPSNAME  : HDAUPS
> CABLE    : USB Cable
> DRIVER   : USB UPS Driver
> UPSMODE  : Stand Alone
> STARTTIME: 2019-02-07 19:57:33 +0000
> MODEL    : Smart-UPS 1500
> STATUS   : ONLINE
> BCHARGE  : 100.0 Percent
> TIMELEFT : 68.0 Minutes
> MBATTCHG : 5 Percent
> MINTIMEL : 3 Minutes
> MAXTIME  : 0 Seconds
> ALARMDEL : 30 Seconds
> BATTV    : 27.4 Volts
> NUMXFERS : 0
> TONBATT  : 0 Seconds
> CUMONBATT: 0 Seconds
> XOFFBATT : N/A
> STATFLAG : 0x05000008
> MANDATE  : 2011-05-08
> SERIALNO : AS1119123502
> NOMBATTV : 24.0 Volts
> FIRMWARE : COM 02.1 / UPS.05.I
> END APC  : 2019-02-07 20:17:44 +0000

The error in the screenshots:

 

> ERROR: while graphing /var/hda/web-apps/monitorix/html//imgs/apcupsd01.1day.png: opening '/var/hda/web-apps/monitorix/html/lib/apcupsd.rrd': No such file or directory ERROR: while graphing /var/hda/web-apps/monitorix/html//imgs/apcupsd01z.1day.png: opening '/var/hda/web-apps/monitorix/html/lib/apcupsd.rrd': No such file or directory ERROR: while graphing /var/hda/web-apps/monitorix/html//imgs/apcupsd02.1day.png: opening '/var/hda/web-apps/monitorix/html/lib/apcupsd.rrd': No such file or directory ERROR: while graphing /var/hda/web-apps/monitorix/html//imgs/apcupsd02z.1day.png: opening '/var/hda/web-apps/monitorix/html/lib/apcupsd.rrd': No such file or directory 

> ERROR: while graphing /var/hda/web-apps/monitorix/html//imgs/apcupsd03.1day.png: opening '/var/hda/web-apps/monitorix/html/lib/apcupsd.rrd': No such file or directory ERROR: while graphing /var/hda/web-apps/monitorix/html//imgs/apcupsd03z.1day.png: opening '/var/hda/web-apps/monitorix/html/lib/apcupsd.rrd': No such file or directory ERROR: while graphing /var/hda/web-apps/monitorix/html//imgs/apcupsd04.1day.png: opening '/var/hda/web-apps/monitorix/html/lib/apcupsd.rrd': No such file or directory ERROR: while graphing /var/hda/web-apps/monitorix/html//imgs/apcupsd04z.1day.png: opening '/var/hda/web-apps/monitorix/html/lib/apcupsd.rrd': No such file or directory ERROR: while graphing /var/hda/web-apps/monitorix/html//imgs/apcupsd05.1day.png: opening '/var/hda/web-apps/monitorix/html/lib/apcupsd.rrd': No such file or directory ERROR: while graphing /var/hda/web-apps/monitorix/html//imgs/apcupsd05z.1day.png: opening '/var/hda/web-apps/monitorix/html/lib/apcupsd.rrd': No such file or directory ERROR: while graphing /var/hda/web-apps/monitorix/html//imgs/apcupsd06.1day.png: opening '/var/hda/web-apps/monitorix/html/lib/apcupsd.rrd': No such file or directory ERROR: while graphing /var/hda/web-apps/monitorix/html//imgs/apcupsd06z.1day.png: opening '/var/hda/web-apps/monitorix/html/lib/apcupsd.rrd': No such file or directory 

Not quite sure how to proceed. 

Many thanks!

**Comment by mikaku** [comment]
Looks like Monitorix is unable to read the `apcupsd.rrd` file. Check the following:

1. make sure the file `var/hda/web-apps/monitorix/html/lib/apcupsd.rrd` does really exist.
1. check the Monitorix log file to see if there are error messages.

**Comment by modem7** [comment]
Looks like apcupsd.rrd doesn't exist.

Is there anywhere I can grab and replace it?

Many thanks!

**Comment by modem7** [comment]
OK, looks like I've resolved it. 

I deleted apcupsd.pm and recreated it from https://raw.githubusercontent.com/mikaku/Monitorix/master/lib/apcupsd.pm. 

This seems to have resolved the error. 

Thanks!
