### ISSUE TITLE
"/dev/null" permissions corruption using Monitorix

### ISSUE THREAD

**Issue by reluctantuser** [mikaku/Monitorix#228]
Monitorix version 3.11, current as available on it's Debian repo
Testing platform: Intel DH77 motherboard, i3-3245 CPU, 8GB RAM, 1xSSD

**Problem**
/dev/null permissions keep being corrupted every minute

**OS**
- Duplicated on Debian and Devuan
- Happens regardless of desktop environment (tested XFCE, MATE, LXDE) or simply "console only".

**Observations**
- A "console only" test was stripped of all "not needed" and "not desired" packages while keeping the packages needed to make the OS actually boot/work.

- Breaking permissions on "/dev/null" will impact various applications, utilities, and even prevent a desktop environment from auto-login for any user other than "root".

**Notes To Reproduce Problem**
Install Monitorix
Allowed Monitorix to pull in it's dependencies
Removed "iptables libnetfilter-conntrack3 libnfnetlink0 libxtables12" since I do not use/need them
Left Monitorix configuration at default and allowed it to run for a few minutes
Checked for "apt update". It was successful.

Waited a few minutes

Edited monitorix.conf so that all references to log writing destinations (near the very top of the config file) were changed to "/dev/null"
Examples:
log_file        = /dev/null
secure_log      = /dev/null
mail_log        = /dev/null
milter_gl       = /dev/null
imap_log        = /dev/null
hylafax_log     = /dev/null
cups_log        = /dev/null
ftp_log         = /dev/null
fail2ban_log    = /dev/null
spamassassin_log        = /dev/null
clamav_log      = /dev/null
cg_logdir       = /dev/null
squid_log       = /dev/null

Restarted Monitorix and allowed it to run for a few minutes
Checked for "apt update". It was NOT successful.

Rewrote permissions for "/dev/null" like this:
rm /dev/null && mknod -m 0666 /dev/null c 1 3 && chown root:root /dev/null
Checked "apt update" and it was successful.

Waited a few minutes.
Re-ran "apt update" and it failed.

Rewrote permissions for "/dev/null" like this:
rm /dev/null && mknod -m 0666 /dev/null c 1 3 && chown root:root /dev/null
Re-ran "apt update" and it worked.

Waited a few minutes.
Re-ran "apt update" and it failed.

Repeated invocation of "apt update" revealed that whatever was changing permissions on "/dev/null" happened in a process that repeated every minute.

NOTE: A Linux "test" system configured as "console only" (no desktop envirnment) and stripped down to the bare minimum packages needed by the OS, AND, does not have Monitorix installed, does not exhibit permission issues with "/dev/null", even after waiting an hour after installation is complete and the system is left running.

Did an "apt purge" to completely remove Monitorix and it's configuration file(s) from the system. Saving collected performance data is not important right now.

Reinstalled Monitorix
Notice that the dependencies are still installed on the system since they were not pulled in.

test ~ # apt install monitorix
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  iptables libnetfilter-conntrack3 libnfnetlink0 libxtables12
The following NEW packages will be installed:
  iptables libnetfilter-conntrack3 libnfnetlink0 libxtables12 monitorix
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 616 kB of archives.
After this operation, 1,903 kB of additional disk space will be used.
Do you want to continue? [Y/n]

In the time period between removing Monitorix with "apt purge" and then reinstalling it I confirmed that permissions for "/dev/null" did not change, even after letting the system sit and idle for a few minutes.

With Monitorix reinstalled and the system left to idle, AND with NO CHANGES to the Monitorix configuration file "apt update" still runs without errors

**Experiment**
Can these log entries simply be commented out with a "#" sysmbol?
Example:
<#       log_file = /var/log/monitorix-httpd>

<# Log files pathnames>
<# ----------------------------------------------------------------------->
#log_file       = /var/log/monitorix
#secure_log     = /var/log/secure
#mail_log       = /var/log/maillog
#milter_gl      = /var/milter-greylist/greylist.db
#imap_log       = /var/log/imap
#hylafax_log    = /var/spool/hylafax/etc/xferfaxlog
#cups_log       = /var/log/cups/page_log
#ftp_log                = /var/log/proftpd/access.log
#fail2ban_log   = /var/log/fail2ban.log
#spamassassin_log       = /var/log/maillog
#clamav_log     = /var/log/clamav/clamav.log
#cg_logdir      = /var/CommuniGate/SystemLogs/
#squid_log      = /var/log/squid/access.log>

Answer: No. Monitorix will fail to start with this error:

test /etc/monitorix # service monitorix restart 
. ok 
Use of uninitialized value $config{"log_file"} in concatenation (.) or string at /usr/bin/monitorix line 99.
Can't write to LOG: No such file or directory at /usr/bin/monitorix line 99.
 failed!

**Experiment**
Change log entries to a "blank", nothing entered after the "=" symbol.
Example:

<log_file =>
[http stuff removed]

<# Log files pathnames>
<# --------------------------------------------------------------------->
log_file        =
secure_log      =
mail_log        =
milter_gl       =
imap_log        =
hylafax_log     =
cups_log        =
ftp_log         =
fail2ban_log    =
spamassassin_log        =
clamav_log      =
cg_logdir       =
squid_log       =>

Answer:

test /etc/monitorix # service monitorix restart
Can't write to LOG: No such file or directory at /usr/bin/monitorix line 99.
 failed!

**Experiment**
Determine which log file entry has to be present so Monitorix will start

Answer:
<log_file =>
<[http stuff removed]>

<# Log files pathnames>
<# ------------------------------------------------------->
<log_file        = /dev/null>
<secure_log      =>
<mail_log        =>
<milter_gl       =>
<imap_log        =>
<hylafax_log     =>
<cups_log        =>
<ftp_log         =>
<fail2ban_log    =>
<spamassassin_log        =>
<clamav_log      =>
<cg_logdir       =>
<squid_log       =>

If the "/dev/null' entry is changed to a file on the filesystem, then Monitorix will start normally and that log file will be created and written to. I checked "apt update" in this configuration and 'apt update" still works correctly; permissions on "/dev/null" are not altered.

**Conclusion**
There is no way to configure Monitorix to simply not create logs, nor will it simply throw away log data to "/dev/null" without corrupting the permissions of "/dev/null"

I checked the Monitorix online documentation for any references to changing the destinations of various log files. It showed the defaults but did not describe any method to PREVENT LOG FILES FROM BEING CREATED.

I do not want/need log files. I do not want to write a cronjob to periodically truncate a log file that I do not want/need just so I can run an application

Normally when an application or utility, or even the console output, is redirected to "/dev/null", the output is silently thrown away by the OS without creating any entries in the filesystem. That was my expectation when I changed the log destinations in the Monitorix configuration file to point to "/dev/null". Sadly it seems to work while corrupting permissions on "/dev/null" at the same time.

**Interim solution**
- Stop using Monitorix since I do not want/need log files more than I want performance data.
- "fix" permissions on the corrupted "/dev/null" file.
- Monitor the situation for a "fix" from the developer of Monitorix and also monitor permissions on "/dev/null" for any further corruption (which could absolved Monitorix of fault).

Perhaps Monitorix needs a configuration flag that tells the application to not create log files of any kind since I think I have shown that it requires at least 1 specific log file destination in it's configuration in order to start as a service.

**Comment by mikaku** [comment]
You are wrong in almost everything you said, you seem you don't know and don't even wanted to learn how Monitorix actually works.

To change the Monitorix configuration file you need `root` permissions, and so under 'root' user you are also able to fuck up completely your system with any other installed application. You can experience spectacular results if you change crazily the `grub.conf` contents.

>I checked the Monitorix online documentation for any references to changing the destinations of various log files. It showed the defaults but did not describe any method to PREVENT LOG FILES FROM BEING CREATED.

The log files you are saying that Monitorix is writing on is false, all those log options (except the `log_file`) are options to include the path from where Monitorix will **read** (not write) its contents:

```
$ cd <monitorix_source_code>
$ for log in secure_log mail_log milter_gl imap_log hylafax_log cups_log ftp_log fail2ban_log spamassassin_log clamav_log cg_logdir squid_log ; do grep -r $log * | grep open ; done
lib/serv.pm:		open(IN, "$config->{secure_log}");
lib/mail.pm:				if(open(IN, "pflogsumm -d today -h 0 -u 0 --smtpd_stats --no_bounce_detail --no_deferral_detail --no_reject_detail --no_no_msg_size --no_smtpd_warnings $config->{mail_log} 2>/dev/null |")) {
lib/mail.pm:				if(open(IN, "pflogsumm.pl -d today -h 0 -u 0 --smtpd_stats --no_bounce_detail --no_deferral_detail --no_reject_detail --no_no_msg_size --no_smtpd_warnings $config->{mail_log} 2>/dev/null |")) {
lib/mail.pm:		open(IN, $config->{mail_log});
lib/serv.pm:		open(IN, "$config->{mail_log}");
lib/mail.pm:			open(IN, $config->{milter_gl});
lib/serv.pm:		open(IN, "$config->{imap_log}");
lib/serv.pm:		open(IN, "$config->{hylafax_log}");
lib/serv.pm:		open(IN, "$config->{cups_log}");
lib/ftp.pm:	open(IN, $config->{ftp_log});
lib/serv.pm:		open(IN, $config->{fail2ban_log});
lib/fail2ban.pm:	open(IN, $config->{fail2ban_log});
lib/mail.pm:		open(IN, $config->{spamassassin_log});
lib/serv.pm:		open(IN, "$config->{spamassassin_log}");
lib/mail.pm:		open(IN, $config->{clamav_log});
lib/serv.pm:		open(IN, "$config->{clamav_log}");
lib/serv.pm:		open(IN, "$config->{cg_logdir}/$date.log");
lib/squid.pm:	open(IN, $config->{squid_log});
```

As you can see, all these log file are opened in **read** mode.

>I do not want/need log files. I do not want to write a cronjob to periodically truncate a log file that I do not want/need just so I can run an application

You don't need a `crond` job to truncate (rotate) the log files, there is already the `logrotate` tool (installed by default in almost every Linux distribution) that rotates periodically a set of log files, including the Monitorix one.

>Normally when an application or utility, or even the console output, is redirected to "/dev/null", the output is silently thrown away by the OS without creating any entries in the filesystem. That was my expectation when I changed the log destinations in the Monitorix configuration file to point to "/dev/null". Sadly it seems to work while corrupting permissions on "/dev/null" at the same time.

Yes, but this is because a **foreground** application is unaware where its STDOUT descriptor is pointing to. Most of daemon (**background** applications), need to know which file will act as its STDOUT (the log file), and you can set whatever you want there, as long as you have the right permissions to do so.

In order to increase security, Monitorix sets the permission mode of its log file to 0600, that's the reason why if you set `/dev/null` as the log file, Monitorix will change the permission of that device.

>Perhaps Monitorix needs a configuration flag that tells the application to not create log files of any kind 

That's the first thing with common sense you said in your post. And you are right.

Currently there is not way to say to Monitorix to not log anything, but, sincerely, I think that it's much easier (and elegant) to just file an issue like *Feature request: be able to disable the log file*. :smiley: 

In all, not having a log file where to check if everythihg is going good is weird. How would you know if Monitorix will be running fine?

Anyway, I thank you for the energy you put to make such detailed post.

**Comment by reluctantuser** [comment]
When I read your reply I thought "such hatred and vitriol".

All I can say to you in reply to your spiteful response is "LET TO CODE".

**Comment by reluctantuser** [comment]
LEARN TO CODE
