### ISSUE TITLE
Version 3.11.0 still shows "Copyright © 2005-2017 Jordi Sanfeliu"

### ISSUE THREAD

**Issue by mmattel** [mikaku/Monitorix#229]
If you open a monitorx page you get this message at the bottom.

You may want to updated this 😄

**Comment by mikaku** [comment]
Yeah, you're right. You have keen eyes :smiley:

I noticed this right after the release of the 3.11.0, so it was too late. The commit 9648a3d787de6b2834120cb54587163dbe931c7f already fixed it.

I think is not necessary to release a specific version of Monitorix for such minor issue, so as long as the next release will be in 2019, that will be definitely fixed. :wink: 

Thanks for your feedback!

**Comment by mmattel** [comment]
Thanks for all the effort you take maintaining monitorix !
This issue can be closed if you agree.

**Comment by mikaku** [comment]
Thank you very much.
