### ISSUE TITLE
Fail2Ban not working

### ISSUE THREAD

**Issue by Deepcuts** [mikaku/Monitorix#23]
Hello

I have setup everything and got my Monitorix install to work as I want.
I also have a working installation of Fail2Ban which is working fine. It is blocking and logging to the required log file.
I cannot get Monitorix to graph Fail2Ban at all. 
I have plenty of entries in the log file.
Defined jails correctly.
But Monitorix shows only 2 SSH jails max and no entries for the other jails
![fail2ban](https://f.cloud.github.com/assets/4704834/658113/58344b8a-d5bb-11e2-94d8-a7843cb504b6.jpg)

**Comment by Hostile** [comment]
Is this fixed?

**Comment by Hostile** [comment]
Where is rdd file to delete?

**Comment by mikaku** [comment]
`fail2ban.pm` module is working finely.

Your `*.rrd` files should be located in the path of the option `base_dir` (normally `/var/lib/monitorix/www/`) of your configuration file.
