### ISSUE TITLE
Feature request: adding HP ProLiant System Health fan speeds

### ISSUE THREAD

**Issue by heps15** [mikaku/Monitorix#233]
I'm currently using the HP ProLiant System Health temperature monitoring from hplog -t outputs.

Would it be possible to include fan speeds from hplog -f outputs?

```
ID     TYPE        LOCATION      STATUS  REDUNDANT FAN SPEED
 1  Var. Speed   Virtual         Normal     N/A     Normal   (  9)
```

**Comment by mikaku** [comment]
The output of `hplog -f` is pretty disappointing since it doesn't provide any numeric value, like the expected RPM of fans. That's the reason why such command is not supported. The value `Normal` as the `FAN SPEED` is completely unacceptable.

You might be tempted to try to enable the `ipmi` module in Monitorix and use it to gather statistics. This is the output of `ipmitool sdr` in one of my HP ProLiant ML150Gen9:

```
# ipmitool sdr
UID              | 0x01              | ok
Sys Health LED   | no reading        | ns
01-Inlet Ambient | 25 degrees C      | ok
02-CPU 1         | 40 degrees C      | ok
03-CPU 2         | disabled          | ns
04-P1 DIMM 1-4   | disabled          | ns
05-P1 DIMM 5-8   | 32 degrees C      | ok
06-P2 DIMM 1-4   | disabled          | ns
07-P2 DIMM 5-8   | disabled          | ns
08-HD Max        | 35 degrees C      | ok
09-Chipset       | 35 degrees C      | ok
10-Chipset Zone  | 29 degrees C      | ok
11-P/S 1         | disabled          | ns
12-P/S 2         | disabled          | ns
13-VR P1         | 37 degrees C      | ok
14-VR P2         | disabled          | ns
15-VR P1 Mem     | 30 degrees C      | ok
16-VR P1 Mem     | 29 degrees C      | ok
17-VR P2 Mem     | disabled          | ns
18-VR P2 Mem     | disabled          | ns
19-VR 5V         | 35 degrees C      | ok
20-VR 3.3V       | 34 degrees C      | ok
21-Megacell Max  | disabled          | ns
22-LOM           | disabled          | ns
23-LOM Zone      | 32 degrees C      | ok
24-PCI 1         | disabled          | ns
25-PCI 2         | disabled          | ns
26-PCI 3         | disabled          | ns
27-PCI 4         | 44 degrees C      | ok
28-PCI 5         | disabled          | ns
29-PCI 6         | disabled          | ns
30-PCI 1 Zone    | 28 degrees C      | ok
31-PCI 2 Zone    | 29 degrees C      | ok
32-PCI 3 Zone    | 30 degrees C      | ok
33-PCI 4 Zone    | 30 degrees C      | ok
34-PCI 5 Zone    | 29 degrees C      | ok
35-PCI 6 Zone    | 27 degrees C      | ok
Fan 1            | 28.22 percent     | ok
Fan 1 DutyCycle  | 28.22 percent     | ok
Fan 1 Presence   | 0x48              | ok
Fan 2            | disabled          | ns
Fan 2 DutyCycle  | disabled          | ns
Fan 2 Presence   | 0x00              | ok
Fan 3            | 10.98 percent     | ok
Fan 3 DutyCycle  | 10.98 percent     | ok
Fan 3 Presence   | 0x1c              | ok
Power Supply 1   | 0x00              | ok
PS 1 Presence    | 0x00              | ok
Megacell Status  | disabled          | ns
Memory Status    | 0 error           | ok
C5 P1I Bay 1     | 0x01              | ok
C5 P1I Bay 2     | 0x01              | ok
C5 P1I Bay 3     | 0x01              | ok
C5 P1I Bay 4     | 0x01              | ok
```

As you can see, fan rows provide a numeric value, but this time is just a **percentage** (!!??). So still, there is no way to get the RPM value which almost all motherboard provide.

**Comment by heps15** [comment]
`ipmitool` works for me, thanks!

RPM would be ideal, but at least the percentage gives an indication of the fan response to change in  temperature.

**Comment by mikaku** [comment]
OK, in that case I recommend you to change the value `RPM` by `percent` in the `<units>` option of `<ipmi>` section of the Monitorix configuration file.

And let me know if that suffice! :smiley:

**Comment by heps15** [comment]
Thanks, got it running.

The resolution seems a bit off compared to `hplog`, especially considering the `ipms` `Fan 1` `percent `output has 2 decimal points.

![image](https://user-images.githubusercontent.com/49585900/56213854-b9121480-6054-11e9-8f78-40661b943c73.png)

![image](https://user-images.githubusercontent.com/49585900/56213964-e52d9580-6054-11e9-8dee-aebf9e99de95.png)

Saying that, `hplog -f` only shows integers in fan percentage speeds so not sure if that would bring much benefit.

**Comment by mikaku** [comment]
Hey!, looks nice!

Yeah, I don't think that not counting the two decimals will have a noticeable impact.
Thanks.
