### ISSUE TITLE
Feature request: squid monitoring

### ISSUE THREAD

**Issue by Nybt** [mikaku/Monitorix#235]
Hello, Thanks for this good software!
I'm currently using the simple squid (no cache).
more separated data than you need, can you help?

Tue Apr 16 13:40:00 2019 - squid::squid_update: N:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0.716666666666667:0:0:0:0.233333333333333:0:0:0:0:0:0:0:0:0:0.233333333333333:0.216666666666667:0.0166666666666667:0:0
:0:0:0:0:0:52:0:0:0:0:904.533333333333:103253.333333333:0:101563.733333333:870.4:0

Tue Apr 16 13:40:00 2019 - ERROR: while updating /var/lib/monitorix/squid.rrd: /var/lib/monitorix/squid.rrd: found extra data on update argument: 870.4:0

**Comment by mikaku** [comment]
Please, provide the following information:

- Squid version.
- Your OS and architecture.
- The complete Monitorix log file of the first 5 minutes after a restart.
- The output of the following commands:
```
$ squidclient -h 127.0.0.1 mgr:counters
$ squidclient -h 127.0.0.1 mgr:info
$ squidclient -h 127.0.0.1 mgr:ipcache
$ squidclient -h 127.0.0.1 mgr:io
$ squidclient -h 127.0.0.1 mgr:storedir

**Comment by Nybt** [comment]
-Squid Cache: Version 3.5.20

-Red Hat Enterprise Linux Server release 7.6 (Maipo)
-3.10.0-957.5.1.el7.x86_64

squidclient -h 127.0.0.1 mgr:counters
HTTP/1.1 200 OK
Server: squid/3.5.20
Mime-Version: 1.0
Date: Tue, 16 Apr 2019 13:10:58 GMT
Content-Type: text/plain;charset=utf-8
Expires: Tue, 16 Apr 2019 13:10:58 GMT
Last-Modified: Tue, 16 Apr 2019 13:10:58 GMT
X-Cache: MISS from squid01
X-Cache-Lookup: MISS from squid01:3128
Via: 1.1 squid01 (squid/3.5.20)
Connection: close

sample_time = 1555420257.688878 (Tue, 16 Apr 2019 13:10:57 GMT)
client_http.requests = 11299
client_http.hits = 0
client_http.errors = 1
client_http.kbytes_in = 16706
client_http.kbytes_out = 2982893
client_http.hit_kbytes_out = 0
server.all.requests = 4387
server.all.errors = 0
server.all.kbytes_in = 2959343
server.all.kbytes_out = 15929
server.http.requests = 0
server.http.errors = 0
server.http.kbytes_in = 0
server.http.kbytes_out = 0
server.ftp.requests = 0
server.ftp.errors = 0
server.ftp.kbytes_in = 0
server.ftp.kbytes_out = 0
server.other.requests = 4387
server.other.errors = 0
server.other.kbytes_in = 2959343
server.other.kbytes_out = 15929
icp.pkts_sent = 0
icp.pkts_recv = 0
icp.queries_sent = 0
icp.replies_sent = 0
icp.queries_recv = 0
icp.replies_recv = 0
icp.query_timeouts = 0
icp.replies_queued = 0
icp.kbytes_sent = 0
icp.kbytes_recv = 0
icp.q_kbytes_sent = 0
icp.r_kbytes_sent = 0
icp.q_kbytes_recv = 0
icp.r_kbytes_recv = 0
icp.times_used = 0
cd.times_used = 0
cd.msgs_sent = 0
cd.msgs_recv = 0
cd.memory = 0
cd.local_memory = 0
cd.kbytes_sent = 0
cd.kbytes_recv = 0
unlink.requests = 0
page_faults = 0
select_loops = 1269680
cpu_time = 21.739442
wall_time = 1.054438
swap.outs = 0
swap.ins = 0
swap.files_cleaned = 0
aborted_requests = 0




squidclient -h 127.0.0.1 mgr:info
HTTP/1.1 200 OK
Server: squid/3.5.20
Mime-Version: 1.0
Date: Tue, 16 Apr 2019 13:12:08 GMT
Content-Type: text/plain;charset=utf-8
Expires: Tue, 16 Apr 2019 13:12:08 GMT
Last-Modified: Tue, 16 Apr 2019 13:12:08 GMT
X-Cache: MISS from squid01
X-Cache-Lookup: MISS from squid01:3128
Via: 1.1 squid01 (squid/3.5.20)
Connection: close

Squid Object Cache: Version 3.5.20
Build Info:
Service Name: squid
Start Time:     Tue, 16 Apr 2019 09:11:57 GMT
Current Time:   Tue, 16 Apr 2019 13:12:08 GMT
Connection information for squid:
        Number of clients accessing cache:      4
        Number of HTTP requests received:       11338
        Number of ICP messages received:        0
        Number of ICP messages sent:    0
        Number of queued ICP replies:   0
        Number of HTCP messages received:       0
        Number of HTCP messages sent:   0
        Request failure ratio:   0.00
        Average HTTP requests per minute since start:   47.2
        Average ICP messages per minute since start:    0.0
        Select loop called: 1300003 times, 11.085 ms avg
Cache information for squid:
        Hits as % of all requests:      5min: 0.0%, 60min: 0.0%
        Hits as % of bytes sent:        5min: 0.2%, 60min: 0.5%
        Memory hits as % of hit requests:       5min: 0.0%, 60min: 0.0%
        Disk hits as % of hit requests: 5min: 0.0%, 60min: 0.0%
        Storage Swap size:      0 KB
        Storage Swap capacity:   0.0% used,  0.0% free
        Storage Mem size:       216 KB
        Storage Mem capacity:    0.1% used, 99.9% free
        Mean Object Size:       0.00 KB
        Requests given to unlinkd:      0
Median Service Times (seconds)  5 min    60 min:
        HTTP Requests (All):   0.00000  0.00000
        Cache Misses:          0.00000  0.00000
        Cache Hits:            0.00000  0.00000
        Near Hits:             0.00000  0.00000
        Not-Modified Replies:  0.00000  0.00000
        DNS Lookups:           0.00000  0.00000
        ICP Queries:           0.00000  0.00000
Resource usage for squid:
        UP Time:        14410.551 seconds
        CPU Time:       22.183 seconds
        CPU Usage:      0.15%
        CPU Usage, 5 minute avg:        0.51%
        CPU Usage, 60 minute avg:       0.20%
        Maximum Resident Size: 73968 KB
        Page faults with physical i/o: 0
Memory accounted for:
        Total accounted:          669 KB
        memPoolAlloc calls:   1074678
        memPoolFree calls:    1074849
File descriptor usage for squid:
        Maximum number of file descriptors:   16384
        Largest file desc currently in use:     13
        Number of file desc currently in use:    8
        Files queued for open:                   0
        Available number of file descriptors: 16376
        Reserved number of file descriptors:   100
        Store Disk files open:                   0
Internal Data Structures:
            52 StoreEntries
            52 StoreEntries with MemObjects
            51 Hot Object Cache Items
             0 on-disk objects




squidclient -h 127.0.0.1 mgr:ipcache
HTTP/1.1 200 OK
Server: squid/3.5.20
Mime-Version: 1.0
Date: Tue, 16 Apr 2019 13:13:31 GMT
Content-Type: text/plain;charset=utf-8
Expires: Tue, 16 Apr 2019 13:13:31 GMT
Last-Modified: Tue, 16 Apr 2019 13:13:31 GMT
X-Cache: MISS from squid01
X-Cache-Lookup: MISS from squid01:3128
Via: 1.1 squid01 (squid/3.5.20)
Connection: close

IP Cache Statistics:
IPcache Entries In Use:  9
IPcache Entries Cached:  9
IPcache Requests: 4391
IPcache Hits:            4196
IPcache Negative Hits:       0
IPcache Numeric Hits:        0
IPcache Misses:          195
IPcache Retrieved A:     195
IPcache Retrieved AAAA:  0
IPcache Retrieved CNAME: 772
IPcache CNAME-Only Response: 0
IPcache Invalid Request: 0


IP Cache Contents:

 Hostname                        Flg lstref    TTL  N(b)
 cdn.redhat.com                          55    -28  1( 0)                                95.101.152.251-OK
 subscription.rhsm.redhat.com           742   1697  1( 0)                               209.132.183.108-OK
 localhost6.localdomain6          H   13935     -1  1( 0)                                           ::1-OK
 localhost6                       H   13935     -1  1( 0)                                           ::1-OK
 localhost.localdomain            H   13935     -1  1( 0)                                           ::1-OK
 localhost                        H   13935     -1  1( 0)                                           ::1-OK
 squid01                          H   13935     -1  1( 0)                                     127.0.0.1-OK
 localhost4.localdomain4          H   13935     -1  1( 0)                                     127.0.0.1-OK
 localhost4                       H   13935     -1  1( 0)                                     127.0.0.1-OK





squidclient -h 127.0.0.1 mgr:io
HTTP/1.1 200 OK
Server: squid/3.5.20
Mime-Version: 1.0
Date: Tue, 16 Apr 2019 13:14:50 GMT
Content-Type: text/plain;charset=utf-8
Expires: Tue, 16 Apr 2019 13:14:50 GMT
Last-Modified: Tue, 16 Apr 2019 13:14:50 GMT
X-Cache: MISS from squid01
X-Cache-Lookup: MISS from squid01:3128
Via: 1.1 squid01 (squid/3.5.20)
Connection: close

HTTP I/O
number of reads: 0
Read Histogram:
    1-    1:         0  0%
    2-    2:         0  0%
    3-    4:         0  0%
    5-    8:         0  0%
    9-   16:         0  0%
   17-   32:         0  0%
   33-   64:         0  0%
   65-  128:         0  0%
  129-  256:         0  0%
  257-  512:         0  0%
  513- 1024:         0  0%
 1025- 2048:         0  0%
 2049- 4096:         0  0%
 4097- 8192:         0  0%
 8193-16384:         0  0%
16385-32768:         0  0%

FTP I/O
number of reads: 0
Read Histogram:
    1-    1:         0  0%
    2-    2:         0  0%
    3-    4:         0  0%
    5-    8:         0  0%
    9-   16:         0  0%
   17-   32:         0  0%
   33-   64:         0  0%
   65-  128:         0  0%
  129-  256:         0  0%
  257-  512:         0  0%
  513- 1024:         0  0%
 1025- 2048:         0  0%
 2049- 4096:         0  0%
 4097- 8192:         0  0%
 8193-16384:         0  0%
16385-32768:         0  0%

Gopher I/O
number of reads: 0
Read Histogram:
    1-    1:         0  0%
    2-    2:         0  0%
    3-    4:         0  0%
    5-    8:         0  0%
    9-   16:         0  0%
   17-   32:         0  0%
   33-   64:         0  0%
   65-  128:         0  0%
  129-  256:         0  0%
  257-  512:         0  0%
  513- 1024:         0  0%
 1025- 2048:         0  0%
 2049- 4096:         0  0%
 4097- 8192:         0  0%
 8193-16384:         0  0%
16385-32768:         0  0%



squidclient -h 127.0.0.1 mgr:storedir
HTTP/1.1 200 OK
Server: squid/3.5.20
Mime-Version: 1.0
Date: Tue, 16 Apr 2019 13:15:33 GMT
Content-Type: text/plain;charset=utf-8
Expires: Tue, 16 Apr 2019 13:15:33 GMT
Last-Modified: Tue, 16 Apr 2019 13:15:33 GMT
X-Cache: MISS from squid01
X-Cache-Lookup: MISS from squid01:3128
Via: 1.1 squid01 (squid/3.5.20)
Connection: close

Store Directory Statistics:
Store Entries          : 52
Maximum Swap Size      : 0 KB
Current Store Swap Size: 0.00 KB
Current Capacity       : 0.00% used, 0.00% free
[monitorix.log.txt](https://github.com/mikaku/Monitorix/files/3085034/monitorix.log.txt)

**Comment by mikaku** [comment]
Thanks for this detailed information.

I'm using your information as a fake output in order to try to reproduce here the same errors, but I don't get any one.

OK, I need more information:

- Monitorix version.
- Paste here the `<squid>` section of your Monitorix configuration file.

Thanks.

**Comment by Nybt** [comment]
Thanks for the help,

- Monitorix version 3.10.1 (15-Mar-2018)

-RRDtool 1.4.8  Copyright 1997-2013 by Tobias Oetiker <tobi@oetiker.ch>
               Compiled Aug 12 2014 03:48:21

-
<squid>
        cmd = squidclient -h 127.0.0.1
        graph_0 = TCP_MISS, TCP_DENIED, TCP_REFRESH_HIT, TCP_IMS_HIT, TCP_HIT, TCP_REFRESH_MISS, TCP_MEM_HIT, TCP_NEGATIVE_HIT, TCP_CLIENT_REFRESH_MISS, TAG_NONE
        graph_1 = 200, 403, 304, 204, 302, 000, 404, 301, 206, 400
        rigid = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
        limit = 100, 100, 100, 100, 100, 100, 100, 100, 100, 100
</squid>

**Comment by mikaku** [comment]
Ah, I see the problem now.

As stated in the Monitorix [documentation](https://www.monitorix.org/documentation.html#38), the maximum values for the options `graph_0` and `graph_1` is 9. The extra values you put on each one makes that Monitorix tries to save 2 extra values, which aren't accepted by the underlying software (RRDtool).

Please, remove the extra value on each `graph_n` option and restart Monitorix.

Seeing that Monitorix wasn't warned you about that problem, I'll include a modification in order to check if the number of values defined in these options isn't greater than 9, and in that case warn to the user about that issue.

On the other hand, I saw that since you are using a newer version of Squid (3.5.x), you should know that since the 3.5 version, they no longer provide memory usage information. That's the reason why you won't see any data in the memory graph.

Check these links, for more information:

- [Some memory usage information is no longer reported by squidclient](https://access.redhat.com/solutions/3019851)
- [Changes to squid-3.5.0.1 (17 Oct 2014):](http://www.squid-cache.org/Versions/v3/3.5/ChangeLog.txt), the line that says `- Remove broken mallinfo() accounting and memory tracing`.

**Comment by Nybt** [comment]
Thank you very much for your help!
