### ISSUE TITLE
Monitorix::httpd_setup: ERROR: invalid group defined.

### ISSUE THREAD

**Issue by rolfen** [mikaku/Monitorix#237]
This is strange.

I had an older verion of monitorix working just fine. In the old http_builtin config, I can see - It is the default config:

        user = nobody
        group = nobody

I uninstalled the old version and installed Monitorix from source so that I can get the new `php-fpm` monitoring feature (nice!).

However now I have this annoying error

```
Fri Apr 19 00:56:41 2019 - Starting Monitorix version 3.11.0 (pid 7296).
Fri Apr 19 00:56:41 2019 - Loaded main configuration file '/etc/monitorix/monitorix.conf'.
Fri Apr 19 00:56:41 2019 - Initializing graphs.
Use of uninitialized value $gid in chown at /usr/bin/monitorix line 727.
Fri Apr 19 00:56:41 2019 - Generating the 'index.html' file.
Fri Apr 19 00:56:41 2019 - Monitorix::httpd_setup: ERROR: invalid group defined.
Fri Apr 19 00:56:41 2019 - Ok, ready.
Fri Apr 19 00:57:00 2019 - WARNING: HTTP built-in server not responding at 'http://localhost:8088/monitorix'.
```

I don't get it...

Then I check `/etc/group` and I figure - there is no such thing as the `nobody` group.
But there is `nogroup`.

So I update the config accordingly (`group = nogroup`) and now it works.

I think it would be more 'correct' for Monitorix HTTP server to run as group `nogroup` and user `nobody` by default.

Additional info:

```
$ uname -a
Linux two 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3 (2019-02-02) x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.8 (stretch)
Release:	9.8
Codename:	stretch
```

**Comment by mikaku** [comment]
As stated in the Monitorix web site, Debian (and its derivatives), comes with an extra configuration file in `/etc/monitorix/conf.d/`.

Please, check if that extra configuration file exists, and if so, set it up accordingly, or if you don't use it then remove it.

You my also check in the Monitorix log file, if it's actually loading such extra configuration file.

**Comment by rolfen** [comment]
Hello mikaku, thank you for your answer and for your great work which I enjoy using.

`/etc/monitorix/conf.d/` is empty!

These are the only instructions I found for installing from source - it only lists dependencies:
https://www.monitorix.org/installation.html

So I had to figure it out myself - I ran `make` and then, based on the output of `make`, I ran  `make install-systemd-all`.

It would be nice to document the correct procedure, including any Debian-specific steps for anyone who wants to install from source on Debian. If it already exists, then I missed it, please point me to it!

Thanks and cheers!

**Comment by mikaku** [comment]
Hey rolfen, in the right side of the main page there is a list of installation document for some systems, including Debian.

Anyway, glad to know to finally managed to solve it. :smiley: 

Just one request, since you wanted to test the new module `phpfpm`, please, bring me a nice graph to see how it works on a real system. :+1: 

Of course, feel free to use the option `<map>` to hide the real names of your domains being monitored.

Thanks!

**Comment by rolfen** [comment]
OK, I will test the `phpfm` module.

I do not have too much traffic on my server, but I will see what comes out of it :)

I tried to set it up yesterday, but failed to get the `phpfm` status page working for nginx and PHP7. I kept getting "unavailable" or "bad gateway" or empty responses, whatever I tried. So I seemed to reach the page but was not able to get anything useful passed through.

I enabled `ping` and `status` in `/etc/php/7.0/fpm/pool.d/www.conf` and tried either without success:

```
location = /ping {
  include fastcgi_params;
  # This is how I connect to PHP7 in my other sites and it usually works:
  fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
}
```

```
location = /ping {
  include fastcgi_params;
  fastcgi_pass 127.0.0.1:9000;
}
```

Do have any tips to get it to work?
Thank you.

**Comment by mikaku** [comment]
I'm afraid I won't bring much of help here since I use Apache, not Nginx, but I think there are plenty of tutorials on Internet to setup PHP-FPM for Nginx.

**Comment by rolfen** [comment]
Thank you!

**Comment by rolfen** [comment]
So in the meantime, I collected some data and I finally have something to show - attached as per your request.

![Screenshot from 2019-07-04 14-05-03](https://user-images.githubusercontent.com/617497/60662433-08522f00-9e65-11e9-9414-c7e1d2804617.png). 

That spike in the middle of the graph is suspect. Also 100m connections/s does not sound right. But I don't know how to investigate this.

**Comment by mikaku** [comment]
Nice shot, thank you very much!

> That level change in the middle of the graph is suspect. Also 100m connections/s does not sound right. But I don't know how to investigate this.

That change of 100m means an increase to 0.1 connections per second (1000m would mean 1 connection per second). You must read the **m** as *milli*, so 100m means 100 *milliconnections*.

I think RRDtool has an option called `--units-exponent=0` that may help you to change the default scale. In the next version of Monitorix you'll be able to include extra RRDtool options to any graph. You can use the devel version if you want to use this feature right now.
