### ISSUE TITLE
built-in server custom port issues found

### ISSUE THREAD

**Issue by nthack** [mikaku/Monitorix#239]
> monitorx version: 3.11.0
> OS: ubuntu 18.04 LTS
> install from: Apt repository from IzzySoft

> **Overview:**
> When using the built-in server with a custom port, not `8080`, can not open the website.

**Detail:**
I have found if I'm using the built-in server with a custom port `6667` (not `8080`, cause `8080` already used by docker service), I can not connect the web site via `monitorix`.
I have tried to allow the port `6667` in `ufw`, and tried to set the `monitorix` `allow_host` for `all` by the document. Doesn't work.
Finally, I stop my docker container in order to give up the port `8080`, in order to set for `monitorix`, magically, it works.
Seems it's the problem that built-in server cause. I can modify my docker service port, but I really hope the official can fix this problem (Sorry that I'm not good at this part)

Pay tribute, and have a nice day.

**Comment by mikaku** [comment]
Hi,

The HTTP built-in server in 3.11.0 version is working fine on any network port. Please, double check your firewall rules, or even better, stop your firewall for a while.

Also, make sure no other application is using the port 6667 with either `netstat -ltn` or `ss -ltn`, and finally check the Monitorix log file to see if there are error messages that can give more clues.

Let me know.
