### ISSUE TITLE
Fail2ban absolute values instead of rate 

### ISSUE THREAD

**Issue by Knudch** [mikaku/Monitorix#241]
I would like to have the fail2ban graph values in absolute current values instead.
Maybee take them from fail2ban-client status function

Knud

**Comment by mikaku** [comment]
The fail2ban values are already saved as absolute values, but the graph shows averages.

**Comment by Knudch** [comment]
After the suggested change
It works not as I wish ;)
At the moment F2B has:
sshd-auth filter has 1 ban
recidive filter has 58 ban

I would like that the graph shows these numbers and below the graph CUR would equal these numbers, also MAX

Attach the F2B window

Knud

![F2B](https://user-images.githubusercontent.com/26920074/57574495-42411f00-743a-11e9-984a-b4521a124b1c.png)

I have attached

**Comment by mikaku** [comment]
You must understand that the x-axis is the time, and the daily graph has steps of 1 minute. So if you say you have 58 bans you must know that these 58 bans have not been probably on a same minute, but during the last n minutes. For this reason, you won't see a total of 58 bans in anywhere.

**Comment by Knudch** [comment]
Yes I am perfectly aware that the Xaxis is in time
My wish is to have the absolute number of bans not the rate pr minute or sec.
And you are right the recidive filter is a result of sshd-auth filter, eg when an IP is banned 3 times by the sshd-auth (10 min bans) filter then recidive filter takes over and extend the ban time to 2 days.
There by "grows" the number of recidive bans "slowly"
Knud 

Knud

**Comment by Knudch** [comment]
That was the reason by the proposal to take ban number from fail2ban-client status <filter>

**Comment by mikaku** [comment]
```
# fail2ban-client status sendmail-reject2
Status for the jail: sendmail-reject2
|- Filter
|  |- Currently failed:	5
|  |- Total failed:	42428
|  `- File list:	/var/log/maillog
`- Actions
   |- Currently banned:	37
   |- Total banned:	1986
   `- Banned IP list:	[**notlisted**]
```

You mean using the value `Currently banned`?

This indeed will keep the value on every minute since the value would be the same gathered until it changes.

**Comment by Knudch** [comment]
yes exactly !
Some one else may prefer to have the ban rate  ban/min shown
So maybe 2 different windows.....one with the rate ban/min and one with the absolute values
I would prefer absolute values  

Knud

**Comment by mikaku** [comment]
I'm agree, but having two different windows all the time might be a little cumbersome. I'd prefer to include the option `mode` with two possible values `absolute` or  `rate`, and let the people to choose one or the other.

**Comment by Knudch** [comment]
Also a possibillity, only the code might be more "complex"

**Comment by mikaku** [comment]
Sorry, I meant uncomfortable not cumbersome. Having a second window all the time increases the number of graphs and the time to generate them.

Also, and in fact, in the `absolute` mode you can already make an idea of the rate of the last values, because depending how fast they have been, you'll see a sudden peak in the graph.

**Comment by Knudch** [comment]
I agreed with your last statement......the "angle" of rise/fall of the absolute values would give an idea of the rate ban/min.
Only problem could be the scaling, as the recidive filter is acumulateting filter with a much longer ban time, the graph's for the other filter would typical be very small and unreadble.
Would it possibel to the recidive filter with in the bottom numbers but not in the graphs ?

**Comment by Knudch** [comment]
during the "nature" of the recidive filter it would always be "rather" slow/static over time
In my F2B settings a IP caught by recidive stays there for 2 days
So it might not be interesting to have that value as a graph

**Comment by mikaku** [comment]
>  Would it possibel to the recidive filter with in the bottom numbers but not in the graphs ?

Hmm, no, all values are treated equal. But in that case, you might want to isolate the recidive value on a different fail2ban graph.

During the next days, I'll work to include gathering the values using `fail2ban-client status`.

**Comment by Knudch** [comment]
Sounds good
And yes...a separate graph......but goes a little against your opinion about a second window.

You might think a little about possibilties ;)

**Comment by mikaku** [comment]
With the last commit the new `fail2ban.pm` graph looks like this:

![fail2ban](https://user-images.githubusercontent.com/829885/57694052-0cbf5000-764b-11e9-824b-1c9ff00e0491.png)

Please, download it and let me know if it works as well for you.

**Comment by Knudch** [comment]
Looks very nice
Only in my case I have recidive filter to right, currently banned is 12 but graph line is not shown

**Comment by mikaku** [comment]
Weird.

Let it run for a while, it takes some minutes to start appearing results.

**Comment by Knudch** [comment]
30 min gone now
filter numbers has not increased in this period and recidive is still 12

**Comment by mikaku** [comment]
Make sure you have configured correctly the jail name in the Monitorix configuration file.

Also, check the Monitorix log file to see if there are some errors.

**Comment by Knudch** [comment]
you were right....misspelling of the other filters
one warning max option in 'net.pm' doesn't exist. Please consinder.....
I dont think it is related to F2B
Now graph line is shown....I still think it do average ?
![Screenshot_20190514_180609](https://user-images.githubusercontent.com/26920074/57713550-fcbb6680-7672-11e9-8cfc-d1715cd875e9.png)

**Comment by Knudch** [comment]
showing 12 in the graph now

**Comment by mikaku** [comment]
> one warning max option in 'net.pm' doesn't exist. Please consinder.....
> I dont think it is related to F2B

Right, `net.pm` is a different graph not related to `fail2ban.pm`. The message appears because your configuration file either is not updated according your current Monitorix version, or you removed excessive options that are needed (like `max`).

**Comment by Knudch** [comment]
MAX issue fixed ;)

**Comment by Knudch** [comment]
Otherwise F2B works like a champ :)
Thank you !

**Comment by Knudch** [comment]
I am quite sure some one ask if they can get the left graph as RATE and the right one as ABSOLUTE

Not me ;)

**Comment by mikaku** [comment]
> I am quite sure some one ask if they can get the left graph as RATE and the right one as ABSOLUTE

Hehe :smiley: 

OK, let's close this then.
Thanks a lot for your feedback!

**Comment by Knudch** [comment]
You are welcome....
