### ISSUE TITLE
pagespeed::pagespeed_update: ERROR: Unable to connect

### ISSUE THREAD

**Issue by ivanionut** [mikaku/Monitorix#243]
Hi,
I'm trying to configure monitorix with pagespeed but I get the following error:

```log
sh: 1: ls: Argument list too long
Sat Jun  8 10:30:02 2019 - pagespeed::pagespeed_update: ERROR: Unable to connect to 'https://user:password@www.website.com/pagespeed_global_admin/statistics'.
sh: 1: ls: Argument list too long
Sat Jun  8 10:31:00 2019 - pagespeed::pagespeed_update: ERROR: Unable to connect to 'https://user:password@www.website.com/pagespeed_global_admin/statistics'.
sh: 1: ls: Argument list too long
Sat Jun  8 10:32:01 2019 - pagespeed::pagespeed_update: ERROR: Unable to connect to 'https://user:password@www.website.com/pagespeed_global_admin/statistics'.
sh: 1: ls: Argument list too long
Sat Jun  8 10:33:00 2019 - pagespeed::pagespeed_update: ERROR: Unable to connect to 'https://user:password@www.website.com/pagespeed_global_admin/statistics'.
```

---

**my configuration: `/etc/monitorix/monitorix.conf`**

```bash
# PAGESPEED graph
# -----------------------------------------------------------------------------
<pagespeed>
        list = https://user:password@www.website.com/pagespeed_global_admin/statistics
        rigid = 0, 0, 2, 0, 0, 0, 0, 0
        limit = 1000, 1000, 100, 1000, 1000, 1000, 1000, 1000
</pagespeed>
```

What am I doing wrong?

**Comment by ivanionut** [comment]
Momentarily I solved using localhost: `list = http://user:password@localhost/pagespeed_global_admin/statistics`

But what is the problem? Am I missing some perl library to access the https or something else like that?

**Comment by mikaku** [comment]
Hi @ivanionut,

Are you using a self-signed certificate in your pagespeed website? If so, you should make sure the option `accept_selfsigned_certs` is set to `y`.

I don't know what's the cause of the error `sh: 1: ls: Argument list too long`, I think is not related to `pagespeed.pm` but to any other module. Perhaps to `du.pm`?

**Comment by ivanionut** [comment]
Hi @mikaku,
- `accept_selfsigned_certs = y` was already set by default 
- `sh: 1: ls: Argument list too long` is no longer present in the log
- at this point I keep the configuration with: `http://user:password@localhost/...`

thank you!
