### ISSUE TITLE
Bind charts are empty in Debian 10/buster

### ISSUE THREAD

**Issue by Nyut0n** [mikaku/Monitorix#244]
As the title suggests, monitoring bind servers on a Debian 10 server apparently doesn't work. All charts are empty except for 'memory usage' and 'task manager'.

We're getting the same warning spam from issue #181 and commenting the `use warnings` line in bind.pm fixes that problem, but the charts for queries and statistics remain empty. This same config used to work in Debian 8.

Is this an issue caused by the newer Perl version (v5.28.1) being used in buster?
The BIND version of the current buster testing build is 9.11.5.

Buster is nearing its stable release early next month so I'm a bit worried we'll break our monitoring :)
Cheers

**Comment by mikaku** [comment]
Hi,

> Is this an issue caused by the newer Perl version (v5.28.1) being used in buster?

I think the issue is caused by the output of Bind which has changed in recent versions. Not sure if the XML parser is also causing problems.

> Buster is nearing its stable release early next month so I'm a bit worried we'll break our monitoring :)

What's your current working Bind version?
(mine is 9.9.4, which is the default version in CentOS 7)

Thanks!

**Comment by Nyut0n** [comment]
Hi,
thanks for your reply.

> What's your current working Bind version?
> (mine is 9.9.4, which is the default version in CentOS 7)

That would be the default Bind 9.9.5 from Debian 8.

I did some investigation in the XML statistics, compared old one to new ond and found that the structure inside _statistics > server_ is different indeed.

**Bind 9.11.5**
![bind9 11](https://user-images.githubusercontent.com/38189661/59779889-972d4c00-92a8-11e9-9f91-645648b5dd0d.JPG)

**Bind 9.9.5**
![bind9 9](https://user-images.githubusercontent.com/38189661/59779890-972d4c00-92a8-11e9-8eea-28cfd6121589.JPG)

I assume that's where the chart data is read from?
Any chance to have this new Bind stats version supported in near future?

Thanks

**Comment by mikaku** [comment]
Thanks for your detailed post.

>  Any chance to have this new Bind stats version supported in near future?

I'm thinking to rewrite completely the `bind.pm` module in order to support better the version 3 of stats.

**Comment by mikaku** [comment]
@Nyut0n,

I've rewritten the way how the module bind.pm collects its data. Now it no longer uses the Perl module XML-Simple, instead it uses the Perl module XML-LibXML.

Please, download the latest version of bind.pm and let me know if everything works as expected.

Don't forget to install Perl XML-LibXML in your system.

**Comment by IzzySoft** [comment]
@mikaku Please send me a reminder to update the dependencies then with the next release, just in case – though I should see it in your SPEC as you will certainly update that :wink:

**Comment by mikaku** [comment]
Let me :memo:  this as my muscle memory is weak. :wink:

**Comment by Nyut0n** [comment]
Thanks for the efforts of rewriting bind.pm.
Unfortunately, charts are still empty here but I'm getting somewhat useful error messages now:

```
Tue Jun 25 10:49:00 2019 - Started built-in HTTP server (pid 30875).
Tue Jun 25 10:49:00 2019 - Ok, ready.
HTTPServer: You can connect to your server at http://localhost:8080/
Use of uninitialized value in sprintf at /usr/lib/monitorix/bind.pm line 839.
Use of uninitialized value in sprintf at /usr/lib/monitorix/bind.pm line 966.
Tue Jun 25 10:50:01 2019 - bind_update(): Operation "-": no method found,
        left argument in overloaded package XML::LibXML::NodeList,
        right argument has no overloaded magic at /usr/lib/monitorix/bind.pm line 338.

Tue Jun 25 10:51:00 2019 - bind_update(): Operation "-": no method found,
        left argument in overloaded package XML::LibXML::NodeList,
        right argument has no overloaded magic at /usr/lib/monitorix/bind.pm line 338.

Tue Jun 25 10:52:00 2019 - bind_update(): Operation "-": no method found,
        left argument in overloaded package XML::LibXML::NodeList,
        right argument has no overloaded magic at /usr/lib/monitorix/bind.pm line 338.

Use of uninitialized value in sprintf at /usr/lib/monitorix/bind.pm line 839.
Use of uninitialized value in sprintf at /usr/lib/monitorix/bind.pm line 966.
Tue Jun 25 10:53:00 2019 - bind_update(): Operation "-": no method found,
        left argument in overloaded package XML::LibXML::NodeList,
        right argument has no overloaded magic at /usr/lib/monitorix/bind.pm line 338.

Tue Jun 25 10:54:00 2019 - bind_update(): Operation "-": no method found,
        left argument in overloaded package XML::LibXML::NodeList,
        right argument has no overloaded magic at /usr/lib/monitorix/bind.pm line 338.

Use of uninitialized value in sprintf at /usr/lib/monitorix/bind.pm line 839.
Use of uninitialized value in sprintf at /usr/lib/monitorix/bind.pm line 966.
Tue Jun 25 10:55:00 2019 - bind_update(): Operation "-": no method found,
        left argument in overloaded package XML::LibXML::NodeList,
        right argument has no overloaded magic at /usr/lib/monitorix/bind.pm line 338.

Tue Jun 25 10:56:01 2019 - bind_update(): Operation "-": no method found,
        left argument in overloaded package XML::LibXML::NodeList,
        right argument has no overloaded magic at /usr/lib/monitorix/bind.pm line 338.

Tue Jun 25 10:57:00 2019 - bind_update(): Operation "-": no method found,
        left argument in overloaded package XML::LibXML::NodeList,
        right argument has no overloaded magic at /usr/lib/monitorix/bind.pm line 338.

Use of uninitialized value in sprintf at /usr/lib/monitorix/bind.pm line 839.
Use of uninitialized value in sprintf at /usr/lib/monitorix/bind.pm line 966.
```

I got libxml-libxml-perl installed, it should be the correct Debian package according to package info (XML::LibXML)

**Comment by mikaku** [comment]
Thanks for your quick answer.

I've been testing the new `bind.pm` on several CentOS 6 and CentOS 7 and they are working well. Keep in mind that they have old BIND versions with statistics version 2.

I've not tested it on a Fedora 30, which comes with the latest BIND (with statistics version 3). I'm gonna check it on that system to see if I can reproduce the same error messages.

**Comment by mikaku** [comment]
@Nyut0n,

Try appending `->pop->to_literal;` at the end of the line 334 in `bind.pm`, so the line should be like the following:

```
	$value = $data->findnodes('/statistics/server/counters/counter[@name="QUERY"]')->pop->to_literal;
```

Then restart Monitorix and let me know.
Thanks.

**Comment by Nyut0n** [comment]
Yep, that did something. Now I got some data in the charts.

The reason for these errors/warnings might be using DNS views. I understand that you are reading from the _default view, which doesn't exist if actual views are configured in the Bind config. So I used to replace all occurrences of `_default` with the name of a real view, like `sed -i 's/_default/extern/g' /usr/lib/monitorix/bind.pm`. This used to work, and it works again since your last fix, but these errors repeat every minute in the log:
```
Use of uninitialized value $j in concatenation (.) or string at /usr/lib/monitorix/bind.pm line 479.
Use of uninitialized value $j in concatenation (.) or string at /usr/lib/monitorix/bind.pm line 486.
Use of uninitialized value in sprintf at /usr/lib/monitorix/bind.pm line 839.
Use of uninitialized value in sprintf at /usr/lib/monitorix/bind.pm line 966.
```
It's not a big deal though. With no views configured, the log is clean as it should be.

You would have to configure your Bind server to have two different views (like internal, external) in order to reproduce these warnings I think.

Maybe in future it would be useful to add a config variable for the bind module that lets us configure the name of the view that should be monitored. 

Thanks a lot for your efforts!

**Comment by mikaku** [comment]
I can't figure out the reason of these errors.

> You would have to configure your Bind server to have two different views (like internal, external) in order to reproduce these warnings I think.

I think that i would be simpler to me if you can, please, pastebin here (or email me) the XML output of your BIND server. :wink: 

> Maybe in future it would be useful to add a config variable for the bind module that lets us configure the name of the view that should be monitored.

You're right. I'll work it.

**Comment by Nyut0n** [comment]
I see you edited your last answer. After updating that line once more, these messages are gone:
```
Use of uninitialized value in sprintf at /usr/lib/monitorix/bind.pm line 839.
Use of uninitialized value in sprintf at /usr/lib/monitorix/bind.pm line 966.
```
These are the only remaining:
```
Use of uninitialized value $j in concatenation (.) or string at /usr/lib/monitorix/bind.pm line 479.
Use of uninitialized value $j in concatenation (.) or string at /usr/lib/monitorix/bind.pm line 486.
```

Here's the XML. I've replaced production data with dummy zones. (i.e. example.org)
https://pastebin.com/KcxbuL0W

**Comment by mikaku** [comment]
> I see you edited your last answer. After updating that line once more, these messages are gone:

Yes, I realized that there is a simpler way to do it.

> Here's the XML. I've replaced production data with dummy zones. (i.e. example.org)

OK, gonna try to fix this.

**Comment by mikaku** [comment]
I'm unable to reproduce these errors :disappointed: :

```
Use of uninitialized value $j in concatenation (.) or string at /usr/lib/monitorix/bind.pm line 479.
Use of uninitialized value $j in concatenation (.) or string at /usr/lib/monitorix/bind.pm line 486.
```

I've slightly modified `bind.pm` in order to use directly your output, instead of connecting to an URL, and I also changed all `_default` strings to `extern`.

These are my versions:
- Perl v5.28.2.
- Perl-XML-LibXML 2.0132.

Just make sure your `bind.pm` is the same as in GitHub (plus your changes from `_default` to `extern`).

**Comment by Nyut0n** [comment]
After some hours of fiddling with Perl (and some headache as a result) I found the issue in `bind.pm`.

See, from line 476 you have this:
```
@i = split(',', $bind->{in_queries_list}->{$l});
  for($n2 = 0; $n2 < 20; $n2++) {
    my $j = trim($i[$n2]);
    $str = $n . "inq_$j";
    $rrdata .= ":";
    $rrdata .= defined($inq{$str}) ? $inq{$str} : 0;
}
```

It's important knowing that `$bind->{in_queries_list}->{$l}` is a comma separated list of DNS resource record types. I've added a `logger("$myself: " . $bind->{in_queries_list}->{$l});` to see the content on different systems.

It could look like this:
`Wed Jun 26 10:53:00 2019 - bind::bind_update:A, AAAA, ANY, DS, MX, NS, PTR, SOA, SRV, TXT, NAPTR, A6, CNAME, SPF, KEY, DNSKEY, HINFO, WKS, PX, NSAP`
It can also look like this:
`Wed Jun 26 10:54:00 2019 - bind::bind_update:A, AAAA, ANY, DS, MX, NS, PTR, SOA, SRV, TXT, NAPTR, CNAME, SPF, KEY, DNSKEY, HINFO, WKS, PX, NSAP`

This appears to be a list of variable length. I assume it depends on the systems configuration (i.e. is IPv6 disabled, is DNSSEC enabled). According to Wikipedia, an A6 record is some deprecated IPv6 stuff.

In your code however, you're iterating over the array from index 0 to 19, assuming it has a fixed size of 20 elements with `for($n2 = 0; $n2 < 20; $n2++)`. This causes the warning of uninitialized $j variable if the actual length of the source list is lower.

I'd recommend counting the elements of the array after the `split()` and then iterating over existing elements only. Or maybe foreach instead of a for loop?
I don't know much about Perl. I'm more of a php, ruby and JS guy. But I'm sure you can do this easily. :)

Note: Same thing is true for the other for-loops of that part of the code.

Cheers

**Comment by mikaku** [comment]
Great found!

You're right, I was (mistakenly) assuming that the options `in_queries_list`, `out_queries_list`, `server_stats_list`, `resolver_stats_list` and `cache_rrsets_list` are always filled with 20 (comma-separated) values. Next time, I'll request also your configuration file! :smiley: 

> I'd recommend counting the elements of the array after the split() and then iterating over existing elements only. Or maybe foreach instead of a for loop?

Hmm, no, `$rrdata` needs to have 20 values from each of these options, so iterating `@i` with a `foreach` loop wouldn't be useful, since I'd have to include also an stopper to 20 (if someone defined more than 20 values), and then I'd need another loop to make sure all 20 values are initialized in case someone (as you) defined less than 20 values.

I think that best and easy way to go is to initialize the undefined values *on the fly*. Just like this:

```
my $j = trim($i[$n2] || 0);
```

Please, change the affected lines with the above trick and let me know if that suffice.
Thanks.

**Comment by Nyut0n** [comment]
This works. Thanks for this simple fix.

New warnings appeared however:
`Use of uninitialized value in sprintf at /usr/lib/monitorix/bind.pm line 839.
Use of uninitialized value in sprintf at /usr/lib/monitorix/bind.pm line 966.`

It boils down to the same issue. I have added this type of mitigation to:
line 834 and 962: `$str = sprintf("%-8s", substr(trim($i[$n] || 0), 0, 8));`
line 839 and 966: `$str = sprintf("%-8s", substr(trim($i[$n + 1] || 0), 0, 8));`
(not sure if that is 100% correct there. please verify)

Now, log is clean and everything is working.

**Comment by mikaku** [comment]
> New warnings appeared however:

Strange, since these warnings belong to the `bind_cgi` function.

> (not sure if that is 100% correct there. please verify)

You are now a Perl man! :wink: 

> Now, log is clean and everything is working.

Life is beautiful.

**Comment by mikaku** [comment]
@Nyut0n,

Thank you very much for your assistance in fixing all this.
