### ISSUE TITLE
zfs charts 3.11.0-izzy1

### ISSUE THREAD

**Issue by rapesco** [mikaku/Monitorix#245]
Hello,

There seems to be a problem with ZFS charts
![q86XvcH](https://user-images.githubusercontent.com/35869574/59843914-3e21ee80-9362-11e9-9200-33d20f3c203c.png)

capacity % not showing up and read/write bandwidth is not right at all, everything is mostly idle right now,

**Comment by mikaku** [comment]
Hi,

Please:

- Pastebin the output of the command `zpool list -H <yourpool>` changing **yourpool** for every pool you have defined.
- Check the Monitorix log file to see if there are some errors.

Thanks.

**Comment by rapesco** [comment]
Hello,

> root@NVGA-01 ~ # zfs version
> zfs-0.8.1-1
> zfs-kmod-0.8.1-1
> root@NVGA-01 ~ # zfs list
> NAME                      USED  AVAIL     REFER  MOUNTPOINT
> zfs.enc-sdata            24.0G   406G      206K  /mnt/zfs.enc-sdata
> zfs.enc-sdata/sdata01      99K   406G       99K  /mnt/zfs.enc-sdata/sdata01
> zfs.enc-sdata/sdata02      99K   406G       99K  /mnt/zfs.enc-sdata/sdata02
> zfs.enc-sdata/sdata03    23.9G   406G     23.9G  /mnt/zfs.enc-sdata/sdata03
> zfs.enc-sdata/sdata04      99K   406G       99K  /mnt/zfs.enc-sdata/sdata04
> zfs.enc-storage           400G   484G      400G  /mnt/zfs.enc-storage
> zfs.enc-storage/sdata01   200K   484G      200K  /mnt/zfs.enc-storage/sdata01
> zfs.enc-storage/sdata02   200K   484G      200K  /mnt/zfs.enc-storage/sdata02
> zfs.enc-storage/sdata03   200K   484G      200K  /mnt/zfs.enc-storage/sdata03
> zfs.enc-storage/sdata04   200K   484G      200K  /mnt/zfs.enc-storage/sdata04
> root@NVGA-01 ~ # zpool list
> NAME              SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
> zfs.enc-sdata     444G  24.0G   420G        -         -     0%     5%  1.00x    ONLINE  -
> zfs.enc-storage   912G   400G   512G        -         -     0%    43%  1.00x    ONLINE  -
> root@NVGA-01 ~ # zpool list -H
> zfs.enc-sdata   444G    24.0G   420G    -       -       0%      5%      1.00x   ONLINE  -
> zfs.enc-storage 912G    400G    512G    -       -       0%      43%     1.00x   ONLINE  -
> root@NVGA-01 ~ # zpool list -H zfs.enc-sdata
> zfs.enc-sdata   444G    24.0G   420G    -       -       0%      5%      1.00x   ONLINE  -
> root@NVGA-01 ~ # zpool list -H zfs.enc-storage
> zfs.enc-storage 912G    400G    512G    -       -       0%      43%     1.00x   ONLINE  -

there are no errors in monitorix log other than http daemon connect errors which I filtered

> Mon Jun 17 02:34:51 2019 - Starting Monitorix version 3.11.0 (pid 10610).

> Mon Jun 17 02:34:51 2019 - Loaded main configuration file '/etc/monitorix/monitorix.conf'.
> Mon Jun 17 02:34:51 2019 - Loading extra configuration file '/etc/monitorix/conf.d/00-debian.conf'.
> Mon Jun 17 02:34:51 2019 - WARNING: the 'autocheck_responsiveness' option is not valid or doesn't exist. Please consider upgrading your configuration file.
> Mon Jun 17 02:34:51 2019 - Initializing graphs.
> Mon Jun 17 02:34:51 2019 - Creating '/var/lib/monitorix/system.rrd' file.
> Mon Jun 17 02:34:51 2019 - Creating '/var/lib/monitorix/kern.rrd' file.
> Mon Jun 17 02:34:51 2019 - Creating '/var/lib/monitorix/proc.rrd' file.
> Mon Jun 17 02:34:51 2019 - Creating '/var/lib/monitorix/lmsens.rrd' file.
> Mon Jun 17 02:34:51 2019 - Creating '/var/lib/monitorix/disk.rrd' file.
> Mon Jun 17 02:34:51 2019 - Creating '/var/lib/monitorix/fs.rrd' file.
> Mon Jun 17 02:34:51 2019 - Creating '/var/lib/monitorix/zfs.rrd' file.
> Mon Jun 17 02:34:51 2019 - Creating '/var/lib/monitorix/net.rrd' file.
> Mon Jun 17 02:34:51 2019 - Creating '/var/lib/monitorix/netstat.rrd' file.
> Mon Jun 17 02:34:51 2019 - Creating '/var/lib/monitorix/user.rrd' file.
> Mon Jun 17 02:34:51 2019 - Creating '/var/lib/monitorix/int.rrd' file.
> Mon Jun 17 02:34:51 2019 - Generating the 'index.html' file.
> Mon Jun 17 02:34:51 2019 - Ok, ready.
> Can't exec "nvidia-smi": No such file or directory at /usr/lib/monitorix/Monitorix.pm line 185.
> Mon Jun 17 02:35:00 2019 - Monitorix::get_nvidia_data: ERROR: 'nvidia-smi' command is not installed.
> Can't exec "nvidia-smi": No such file or directory at /usr/lib/monitorix/lmsens.pm line 324.
> Mon Jun 17 02:35:00 2019 - lmsens::lmsens_update: ERROR: 'nvidia-smi' command is not installed.
> Can't exec "nvidia-smi": No such file or directory at /usr/lib/monitorix/Monitorix.pm line 185.
> Mon Jun 17 02:36:00 2019 - Monitorix::get_nvidia_data: ERROR: 'nvidia-smi' command is not installed.
> Can't exec "nvidia-smi": No such file or directory at /usr/lib/monitorix/lmsens.pm line 324.
> Mon Jun 17 02:36:00 2019 - lmsens::lmsens_update: ERROR: 'nvidia-smi' command is not installed.
> Mon Jun 17 02:36:36 2019 - SIGTERM caught.
> Mon Jun 17 02:36:36 2019 - Exiting.
> Mon Jun 17 02:36:45 2019 - Starting Monitorix version 3.11.0 (pid 13542).
> Mon Jun 17 02:36:45 2019 - Loaded main configuration file '/etc/monitorix/monitorix.conf'.
> Mon Jun 17 02:36:45 2019 - Loading extra configuration file '/etc/monitorix/conf.d/00-debian.conf'.
> Mon Jun 17 02:36:45 2019 - WARNING: the 'autocheck_responsiveness' option is not valid or doesn't exist. Please consider upgrading your configuration file.
> Mon Jun 17 02:36:45 2019 - Initializing graphs.
> Mon Jun 17 02:36:45 2019 - Creating '/var/lib/monitorix/system.rrd' file.
> Mon Jun 17 02:36:45 2019 - Creating '/var/lib/monitorix/kern.rrd' file.
> Mon Jun 17 02:36:45 2019 - Creating '/var/lib/monitorix/proc.rrd' file.
> Mon Jun 17 02:36:45 2019 - Creating '/var/lib/monitorix/lmsens.rrd' file.
> Mon Jun 17 02:36:45 2019 - Creating '/var/lib/monitorix/disk.rrd' file.
> Mon Jun 17 02:36:45 2019 - Creating '/var/lib/monitorix/fs.rrd' file.
> Mon Jun 17 02:36:45 2019 - Creating '/var/lib/monitorix/zfs.rrd' file.
> Mon Jun 17 02:36:45 2019 - Creating '/var/lib/monitorix/net.rrd' file.
> Mon Jun 17 02:36:45 2019 - Creating '/var/lib/monitorix/netstat.rrd' file.
> Mon Jun 17 02:36:45 2019 - Creating '/var/lib/monitorix/user.rrd' file.
> Mon Jun 17 02:36:45 2019 - Creating '/var/lib/monitorix/int.rrd' file.
> Mon Jun 17 02:36:45 2019 - Generating the 'index.html' file.
> Mon Jun 17 02:36:45 2019 - Ok, ready.
> Wed Jun 19 23:34:58 2019 - SIGTERM caught.
> Wed Jun 19 23:34:58 2019 - Exiting.
> Wed Jun 19 23:34:58 2019 - Starting Monitorix version 3.11.0 (pid 21045).
> Wed Jun 19 23:34:58 2019 - Loaded main configuration file '/etc/monitorix/monitorix.conf'.
> Wed Jun 19 23:34:58 2019 - Loading extra configuration file '/etc/monitorix/conf.d/00-debian.conf'.
> Wed Jun 19 23:34:58 2019 - WARNING: the 'autocheck_responsiveness' option is not valid or doesn't exist. Please consider upgrading your configuration file.
> Wed Jun 19 23:34:58 2019 - Initializing graphs.
> Wed Jun 19 23:34:58 2019 - Generating the 'index.html' file.
> Wed Jun 19 23:34:58 2019 - Ok, ready.

**Comment by mikaku** [comment]
Hmm, looks like your ZFS version comes with extra data in the command `zpool`.

Please, pastebin the output of the command `zpool list zfs.enc-storage`.
Thanks.

**Comment by mikaku** [comment]
Please, download and use the latest `zfs.pm` in your Monitorix and let me know if the values of Capacity and Fragmentation are back again.

**Comment by rapesco** [comment]
Yes, with the modified zfs.pm "capacity" works now
![monitorix-zfs-cap](https://user-images.githubusercontent.com/35869574/59866305-f0be7500-9393-11e9-978d-0e9902d23caa.png)

Thanks!

**Comment by mikaku** [comment]
Perfect! :+1:
