### ISSUE TITLE
autocheck_responsiveness warning when auth enabled and continuous HTTP server restarts

### ISSUE THREAD

**Issue by borzaka** [mikaku/Monitorix#249]
## Description 
If I'am using the built in `auth` with `autocheck_responsiveness` enabled, the logfile populates with warnings, and the httpd log file with auth errors.
So it can't check the responsiveness of the built in HTTP server, and it keeps restarting it.
If I disable the `autocheck_responsiveness`, the server often crashes during some attacks, as stated in the [docs](https://www.monitorix.org/documentation.html#3).

## Config
```
<httpd_builtin>
        enabled = y
        host =
        port = 8080
        user = nobody
        group = nobody
        log_file = /var/log/monitorix-httpd
        hosts_deny =
        hosts_allow =
        autocheck_responsiveness = y
        <auth>
                enabled = y
                msg = Monitorix: Restricted access
                htpasswd = /var/lib/monitorix/htpasswd
        </auth>
</httpd_builtin>
```

## Error log (`/var/log/monitorix`)
```
HTTPServer: You can connect to your server at http://localhost:8080/
Tue Aug 27 13:31:00 2019 - WARNING: HTTP built-in server not responding at 'http://localhost:8080/monitorix'.
Tue Aug 27 13:31:00 2019 - Restarted HTTP built-in server (pid 18160).
```

## HTTPD error log (`/var/log/monitorix-httpd`)
```
Tue Aug 27 13:30:01 2019 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
Tue Aug 27 13:31:00 2019 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
Tue Aug 27 13:32:00 2019 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
Tue Aug 27 13:33:01 2019 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
```

## System
Debian 10 "buster"
`4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 GNU/Linux`

## Monitorix version
`Monitorix version 3.11.0` (installed from testing, further updated from GitHub master)

**Comment by mikaku** [comment]
You're right, I didn't check that feature with Basic Authentication enabled.

Since this procedure acts as a client it will require a user and a password. I believe I'll have to add two new options under `<auth>` to be able to define the default `username` and `password` when `enabled = y`.

**Comment by borzaka** [comment]
I think it's a security concern to add username and password to the config file, which is readable by group and others. But if it's the plan, then maybe auto generating the `htpasswd` based on this would be a nice feature.

Isn't there another way to check that the server is up? Maybe if it's asking for auth in the first place, than it's working.

**Comment by mikaku** [comment]
> I think it's a security concern to add username and password to the config file, which is readable by group and others.

Indeed, that would be a not recommended practice.

> maybe auto generating the htpasswd based on this would be a nice feature.

No, the username and password must be passed in text/plain, as if they where typed by the user. The server won't recognize an encrypted pair of credentials.

> Isn't there another way to check that the server is up? Maybe if it's asking for auth in the first place, than it's working.

This could be a good idea.
I'll work on this.

**Comment by mikaku** [comment]
Can you, please, check this small patch to see if it suffice?

**Comment by borzaka** [comment]
I think it's working;
- no "not responding" and restarts in the logs
- checking still working:
```
Tue Aug 27 17:24:00 2019 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
Tue Aug 27 17:25:00 2019 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
Tue Aug 27 17:26:00 2019 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
Tue Aug 27 17:27:00 2019 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
Tue Aug 27 17:28:00 2019 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
```

BTW I generated my `htpasswd` with this command:
`htpasswd -d -c /var/lib/monitorix/htpasswd monitorix`
And the file contents looks like this:
`monitorix:O.xtf5jtVSwp.`

Unfortunately the password got truncated to 8 characters during generation, so if someone knows the user, and the first 8 character of the password, that's enough to log in successfully.
So, it's looks like an encrypted credentials can work, and could be auto generated from the config, if presented.

**Comment by mikaku** [comment]
> Edit: tested with the first commit patch which contained $response = $ua->get($url);

With the latest commit it should work as well.

OK, I think we can close this issue.

**Comment by borzaka** [comment]
Tested, it works with the latest commit as well.

Thank you for the fast response and support!
