### ISSUE TITLE
ubuntu 18 CGI script not found...

### ISSUE THREAD

**Issue by fabienlege** [mikaku/Monitorix#254]
After hours of search, I can't run fresh install of monitorix on ubuntu serveur !

http://my-serv.com:0123/monitorix ==> Work great,
but when I click OK ==> 404 not found !

I've try all possible conf but nothing working :

**1. Default configuration** (base_url = /monitorix & base_cgi = /monitorix-cgi) ==> homepage found but cgi not found (404)

**2. custom configuration** (base_url = / & base_cgi = /cgi) ==> homepage found but cgi not found (404)

**3. another custom configuration** (base_url = / & base_cgi = / ==> homepage found but cgi not found 

**4. Spécial try with method 3.** : cgi not found, but if I manually add '/cgi/' in URL, CGI is found but completely fall (see screenshot)
![image](https://user-images.githubusercontent.com/2045814/65253622-3ad20680-dafb-11e9-9314-0ffa1c3170f8.png)

**Comment by mikaku** [comment]
Just follow this [HowTo](https://www.monitorix.org/doc-debian.html) of the Monitorix web site.

**Comment by fabienlege** [comment]
I've already read this page, didn't help...

**Comment by mikaku** [comment]
> I've already read this page, didn't help...

*didn't help* is too vague. Can you elaborate a bit which part of the HowTo doesn't work for you?

**Comment by fabienlege** [comment]
I've follow HowTo point by point. (install with APT).
I've install it on my webserver (ubuntu without Xserver, so I can't try to access localhost:8080). So I've only modified port and set  hosts_allow = all in /etc/monitorix/monitorix.conf and restart monitorix service

The result is described in my first post : First page work great : 
![image](https://user-images.githubusercontent.com/2045814/65255151-b0d76d00-dafd-11e9-9f3f-541c6794b707.png)

But when click OK...
![image](https://user-images.githubusercontent.com/2045814/65255275-e2503880-dafd-11e9-8685-cda5dddb65c6.png)

**Comment by mikaku** [comment]
Please, paste the complete Monitorix log.

**Comment by mikaku** [comment]
Closing due to no response for almost two months.

If you are still having problems with this issue, please add a comment and the issue can be reopened.
