### ISSUE TITLE
netstat graph no longer show's data after reboot and switching to newer kernel.

### ISSUE THREAD

**Issue by Sweepr** [mikaku/Monitorix#255]
2 day's ago netstat was collection data fine, yesterday i rebooted and started using a newer kernel, since then the netstat data isn't collection anylonger, everything else is working fine.

![image](https://user-images.githubusercontent.com/2857865/65829234-6c896100-e2a3-11e9-9e20-b4b8e93bd530.png)

OS: Centos 6.10 
Linux 2.6.32-754.23.1.el6.x86_64
Monitorix 3.11.0
Netstat -V

![image](https://user-images.githubusercontent.com/2857865/65829300-516b2100-e2a4-11e9-945a-21be6d8112c8.png)

Looking at net.pm it should reads data from "/proc/net/dev"
https://github.com/mikaku/Monitorix/blob/98ef89190b2d78d2fe6a0e3ebc2f2b3a0ac9fbab/lib/net.pm#L164

/proc/net/dev  user: root(0)/root(0) perms: 555/555/444/ 

File contains:

![image](https://user-images.githubusercontent.com/2857865/65829265-bffbaf00-e2a3-11e9-9406-ca7bd7b0bbe7.png)

Fstab:
proc                    /proc                   proc    defaults        0 0

Any idea why it's not collection data?

**Comment by Sweepr** [comment]
https://github.com/mikaku/Monitorix/blob/98ef89190b2d78d2fe6a0e3ebc2f2b3a0ac9fbab/lib/netstat.pm#L184
Command "ss -na -f inet"

working fine.

https://github.com/mikaku/Monitorix/blob/98ef89190b2d78d2fe6a0e3ebc2f2b3a0ac9fbab/lib/netstat.pm#L208
Command "ss -na -f inet6"

 working fine

**Comment by mikaku** [comment]
I've not yet updated my CentOS 6 servers with that latest kernel, since I don't see appear such update in the announce mailing list, which is something I like to wait to see before making the update.

Anyway, it looks really strange indeed.
What tells the Monitorix log file? any error?

**Comment by Sweepr** [comment]
Only this is shown in monitorix.log

![image](https://user-images.githubusercontent.com/2857865/65850183-1d4c3a80-e34e-11e9-8f80-adb889beb060.png)

Mon Sep 30 06:46:00 2019 - WARNING: unable to connect to HTTP built-in server 'http://localhost:8080/monitorix'.
Mon Sep 30 06:46:00 2019 - Restarted HTTP built-in server (pid 3816).
HTTPServer: You can connect to your server at http://localhost:8080/

**Comment by mikaku** [comment]
OK, this looks fine, let's see in another place.
Please, paste here the `<netstat>` section of your configuration file.

**Comment by Sweepr** [comment]
# NETSTAT graph                                                            # ------------------------------------------------------------------------$<netstat>
        cmd = ss                                                                   rigid = 0, 0, 0, 0, 0
        limit = 100, 100, 100, 100, 100
</netstat>

**Comment by mikaku** [comment]
OK, I see what's happening here.

You are using the `ss` command on a CentOS 6 which comes with an old version and with an output format not supported. Please use `netstat` instead in your CentOS 6.

**Comment by Sweepr** [comment]
Ok, so in the conf file i have to change "cmd = ss" to "cmd = netstat" ?

**Comment by mikaku** [comment]
Yes, then restart Monitorix and wait a few minutes to see the data appearing in graphs.

**Comment by Sweepr** [comment]
Solved:

![image](https://user-images.githubusercontent.com/2857865/65858181-a1f68300-e365-11e9-92c5-c8cbe402b3e2.png)


Thanks! @mikaku
