### ISSUE TITLE
Disk I/O Reads + Writes   does not specify the measurement scale

### ISSUE THREAD

**Issue by jairoufps** [mikaku/Monitorix#258]
i not understand which is the scale, because in the disk I / O reads you can see something like "Read + writes" is this in bytes?

**Comment by mikaku** [comment]
There are two graphs that offer disk stats in the *fs.pm* module and both graphs collect the information from the `/proc/diskstats` file. More information [here](https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats).

The first graph **Disk I/O activity** shows the sum of the values 4 and 8 (reads and writes completed). This is the count of reads + writes, it doesn't have anything to do with the size of them.

The second graph **Time spent in I/O activity** shows the sum of the values 7 and 8 (time spent reading and writing). I think this graph could rely instead on the value 13 (time spent doing I/Os  in ms). I don't know that I didn't choose that value, perhaps it was not included in the time when I created that module.

Hope that helped to clear up things.

**Comment by mikaku** [comment]
Closing due to no response for two weeks.

If you still need more information, please add a comment and the issue can be reopened.
