### ISSUE TITLE
Help Request: Installing dependencies for RHEL8/Centos8

### ISSUE THREAD

**Issue by itsthejb** [mikaku/Monitorix#261]
Hi there,

Call-out for help: recently upgraded to Centos8 and would love to continue using this tool. However, fell down on trying to locate a source for all dependencies:

```
Perl
Perl-libwww
Perl-MailTools
Perl-MIME-Lite
Perl-DBI
Perl-XML-Simple
Perl-Config-General
Perl-HTTP-Server-Simple
perl-IO-Socket-SSL
RRDtool and its Perl bindings (perl-rrdtool or rrdtool-perl)
(Optional) a CGI capable Web server (Apache, Nginx, lighttpd, etc.)
```
https://www.monitorix.org/installation.html

Didn't actually get past `Perl-Config-General`. Can anyone assist? Then perhaps could add more detailed instructions to the docs.

Thanks

**Comment by davehodg** [comment]
When you say “didn’t get past”, what does that mean?

What was the error? Did you file a bug?

Also, depending on your distro, rpms/apts might be more functional.

—
David Hodgkinson
Perl Developer. DevOps.
daveh@hodgkinson.org
+44 7768 490620

**Comment by itsthejb** [comment]
Hi,

The service:

```
● monitorix.service - Monitorix
   Loaded: loaded (/usr/lib/systemd/system/monitorix.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2019-11-13 12:27:36 CET; 1s ago
     Docs: man:monitorix(8)
  Process: 23537 ExecStart=/usr/bin/monitorix -c /etc/monitorix/monitorix.conf -p /run/monitorix.pid (code=exited, status=2)

Nov 13 12:27:35 server.lan systemd[1]: Starting Monitorix...
Nov 13 12:27:36 server.lan monitorix[23537]: Can't locate Config/General.pm in @INC (you may need to install the Config::General module) (@INC contains: /usr/>
Nov 13 12:27:36 server.lan monitorix[23537]: BEGIN failed--compilation aborted at /usr/bin/monitorix line 31.
Nov 13 12:27:36 server.lan systemd[1]: monitorix.service: Control process exited, code=exited status=2
Nov 13 12:27:36 server.lan systemd[1]: monitorix.service: Failed with result 'exit-code'.
Nov 13 12:27:36 server.lan systemd[1]: Failed to start Monitorix.
```

So yes, must install `Perl-Config-General`, [which is available for 7-series, but seemingly not 8](https://pkgs.org/download/perl-Config-General). I believe I'm lacking:

```
Perl-Config-General
Perl-HTTP-Server-Simple
```

Not being much knowledgeable regarding the Perl ecosystem, didn't know where to progress past this point.

**Comment by itsthejb** [comment]
Just tried:

```
dnf install perl perl-libwww-perl perl-MailTools perl-MIME-Lite perl-DBI perl-XML-Simple perl-IO-Socket-SSL perl-MIME-tools  http://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/p/perl-Config-General-2.61-1.el7.noarch.rpm http://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/p/perl-HTTP-Server-Simple-0.44-6.el7.1.noarch.rpm 
```

Got:

```
Error:
 Problem 1: conflicting requests
  - nothing provides perl(:MODULE_COMPAT_5.16.3) needed by perl-Config-General-2.61-1.el7.noarch
 Problem 2: conflicting requests
  - nothing provides perl(:MODULE_COMPAT_5.16.3) needed by perl-HTTP-Server-Simple-0.44-6.el7.1.noarch
 Problem 3: conflicting requests
  - nothing provides perl(MIME::Types) >= 1.28 needed by perl-MIME-Lite-3.030-16.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

I assume this is because Centos8 provides Perl v5.26.3:

```
This is perl 5, version 26, subversion 3 (v5.26.3) built for x86_64-linux-thread-multi
(with 51 registered patches, see perl -V for more detail)

Copyright 1987-2018, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

**Comment by mikaku** [comment]
Hi,

I see available the Config-General Perl module [here](https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/p/perl-Config-General-2.63-10.el8.noarch.rpm) (I don't know the difference between `dl.fedoraproject.org` and `download.fedoraproject.org`.

Anyway, I believe that you may still miss other critical modules in EPEL8 even on that repository.

This is because EPEL for CentOS 8 has a very slow pace right now since not all the maintainers are updating their packages at the same speed as others do.

As a last option, you might want to build locally `Perl-HTTP-Server-Simple` from the SRPM in EPEL.

**Comment by itsthejb** [comment]
Checking back in.

Thanks for your input. I was able to get things working with:

`dnf install monitorix perl perl-CGI perl-DBI perl-IO-Socket-SSL perl-libwww-perl perl-MailTools perl-MIME-Lite perl-MIME-tools perl-Module-Install perl-Test-Pod perl-Test-Pod-Coverage perl-XML-Simple rpm-build https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/p/perl-Config-General-2.63-10.el8.noarch.rpm`

Manually compile `perl-HTTP-Server-Simple`:

- http://download-ib01.fedoraproject.org/pub/epel/7/SRPMS/Packages/p/perl-HTTP-Server-Simple-0.44-6.el7.1.src.rpm
- `rpmbuild` that and install

👍

**Comment by mikaku** [comment]
Fantastic, thanks for your feedback.
This will help other people.
