### ISSUE TITLE
Feature Request: make Firewall setting optional in port.pm and nginx.pm

### ISSUE THREAD

**Issue by LiohMoeller** [mikaku/Monitorix#262]
We are configuring our Firewall with Puppet and this interferes with the rules/chains set up with Monitorix. We have set up the required rules on our own and it would be nice to make the setting of firewall rules/chains optional in Monitorix. It would be great if you could add a variable (enabled by default) and adjust port.pm accordingly.

**Comment by LiohMoeller** [comment]
Exactly, that's the point. We have created the chains accordingly so Monitorix is able to make use them.

**Comment by mikaku** [comment]
Please, download the latest `port.pm` from here and let me know if it works as expected.

**Comment by mikaku** [comment]
The last two commits should include support for the new option `use_external_firewall` globally.
Remember to change the location of such option in your configuration file!
