### ISSUE TITLE
Empty description on Net graph

### ISSUE THREAD

**Issue by kozlovd** [mikaku/Monitorix#264]
Monitorix 3.11 on CentOS 8.
Description of Net graph not showing. Errors in the log:
>Use of uninitialized value in split at /usr/lib/monitorix/net.pm line 403.
Use of uninitialized value in split at /usr/lib/monitorix/net.pm line 404.
Use of uninitialized value in split at /usr/lib/monitorix/net.pm line 405.
Use of uninitialized value $nd in concatenation (.) or string at /usr/lib/monitorix/net.pm line 469.
Use of uninitialized value $nd in concatenation (.) or string at /usr/lib/monitorix/net.pm line 495.

**Comment by mikaku** [comment]
Please, provide the `<net>` section of your configuration file.

**Comment by kozlovd** [comment]
Here it is:
```
<net>
        max = 10
        list = ens224
        <desc>
                My description
        </desc>
        gateway = ens224
</net>
```

**Comment by mikaku** [comment]
The configuration inside the section `<desc>` is wrong, you haven't specified the *key* for the value `My description`. You should configure it like this:

```
<net>
        max = 10
        list = ens224
        <desc>
                ens224 = My description
        </desc>
        gateway = ens224
</net>
```

**Comment by kozlovd** [comment]
Ok, thank you
