### ISSUE TITLE
Netstat via `ss` for older versions of `ss`

### ISSUE THREAD

**Issue by IzzySoft** [mikaku/Monitorix#271]
Older versions of `ss` lack the protocol column in their output. Instead, they default to "TCP only" unless advised otherwise using the `-t` (TCP) and/or `-u` (UDP) parameters. As a result, on installations having such an old version of `ss`, netstat graphs will remain empty.

This can be fixed by adding the "-tu" parameters to the `ss` call, which I successfully confirmed on one of my older ARM machines (a BananaPi running the last Bananian, ss "iproute2-ss120521"): replacing "-na" by "-naut" in the two places on "os=Linux" solved this issue for me (i.e. `ss -na -f inet` => `ss -naut -f inet`).

I've cross-checked on a machine running a newer version of `ss` (which has the protocol column visible by default; Mint 18.1, ss "iproute2-ss151103") and didn't notice any difference in the output. So as Monitorix looks for UDP and TCP only anyway, this should be fine – though some testing on other versions (especially on non-Debian machines) cannot hurt.

As requested by you, @mikaku – here is the issue to keep track of this task. Thanks!

**Comment by mikaku** [comment]
@IzzySoft, thanks for filing this issue.

I can confirm that your suggestion also works on my `ss` command (iproute2-ss190708) on a Fedora 30.

**Comment by IzzySoft** [comment]
Great, thanks! Looking at the linked commit, I now can close the tab on my end (which I kept open to remember I might have to patch future updates, as that's exactly my patch :smiley:)
