### ISSUE TITLE
Feature Request(s): Disk id's and naming

### ISSUE THREAD

**Issue by HarikalarKutusu** [mikaku/Monitorix#272]
First of all thank you for this excellent script. I didn't try all modules but had trouble with disks.

The problem is based on the kernel's parallel initialization process while naming block devices /dev/sda etc. I see you are trying to overcome the addressing with /dev/disk/by-path but this also does not solve all problems on my home server. Let me explain:

1) I use multitude of USB external HDD's. These devices can be plugged to different ports on the server so the addresses can change, resulting in rendering problems of the graphs. If one could use /dev/disk/by-id the problem could be solved.

2) /dev/sdx type naming is also not very meaningful between boots. It would be great if one could use <desc></desc> tags which are already implemented in other modules, so that one can name them "media disk", "backup disk" etc...

Thanks again for your efforts.

**Comment by mikaku** [comment]
> First of all thank you for this excellent script.

Glad to know you are enjoying Monitorix!

>  1. I use multitude of USB external HDD's. These devices can be plugged to different ports on the server so the addresses can change, resulting in rendering problems of the graphs. If one could use /dev/disk/by-id the problem could be solved.

Yes, this is already supported. You can use any of the different ways to identify a disk drive (by-id, by-partuuid, by-path or by-uuid). Just specify the complete path name.

Like this:

```
<disk>
    <list>
        0 = /dev/disk/by-id/ata-KINGSTON_SA400S37120G_50026B7282361714, \
            /dev/disk/by-id/ata-WDC_WD10EZEX-22MFCA0_WD-WCC6Y4EK7K3Y
    </list>
```

> 2. /dev/sdx type naming is also not very meaningful between boots. It would be great if one could use tags which are already implemented in other modules, so that one can name them "media disk", "backup disk" etc...

Currently the graph uses the device name (i.e.: `/dev/sda`) to show the disk drive. I understand that this could confuse since there is no way to know which device name corresponds to the disk defined above.

So, I'll include a new `<map>` section to be able to map any of the definitions in the `<list>` section with a name. Just like this:

```
    <map>
        ata-KINGSTON_SA400S37120G_50026B7282361714 = "media disk"
        ata-WDC_WD10EZEX-22MFCA0_WD-WCC6Y4EK7K3Y = "backup disk"
    </map>
```

As you can see, I use the `basename` of the path name because a key (the LHS of an option) in the configuration file cannot contain slashes, and other symbols. This means that if you use the `by-path` way to identify your disk drives, you won't be able to map them because there are unsupported punctuation symbols in their names (i.e. `pci-0000:00:14.0-usb-0:5:1.0-scsi-0:0:0:0`). So if you want to map your disk drive you better use a more *sane* way to identify them.

**Comment by HarikalarKutusu** [comment]
Great :)

- Added support to use '/dev/disk/by-path/' paths as device names in the 'disk'
  graph. [#37]

Well, I did try by-id (no avail) and then saw above statement in the changelog (also in documentation) and assumed only by-path is implemented. Maybe a change in the documentation can clarify this.

I just checked the logs, I had another "rouge non-disk definition" causing an error. My bad...

`ERROR: /dev/disk/by-id/: can't determine bus type (or this bus type is unknown)`

**Comment by IzzySoft** [comment]
> the configuration file cannot contain slashes

Couldn't you just str_replace them by e.g. dashes (or something else)?

**Comment by mikaku** [comment]
> Couldn't you just str_replace them by e.g. dashes (or something else)?

I'm still not sure if `ata-KINGSTON_SA400S37120G_50026B7282361714 = "media disk"` will be an accepted option in the configuration file, because of the combination of dashes and underlines in the key name.

I need to deep a bit more on this.

**Comment by mikaku** [comment]
After applying the last commit ecd7da1, I've tested two configuration types:

- using `/dev/disk/by-id`:
```
<disk>
    <list>
            0 = /dev/disk/by-id/ata-KINGSTON_SA400S37120G_50026B7282361714, /dev/disk/by-id/ata-WDC_WD10EZEX-22MFCA0_WD-WCC6Y4EK7K3Y
    </list>
    <map>
            ata-KINGSTON_SA400S37120G_50026B7282361714 = "media disk"
            ata-WDC_WD10EZEX-22MFCA0_WD-WCC6Y4EK7K3Y = "backup disk"
    </map>
```

- and using `/dev/disk/by-path`:
```
<disk>
    <list>
            0 = /dev/disk/by-path/pci-0000:00:1f.2-ata-1, /dev/disk/by-path/pci-0000:00:1f.2-ata-2
    </list>
    <map>
            pci-0000:00:1f.2-ata-1 = "media disk"
            pci-0000:00:1f.2-ata-2 = "backup disk"
    </map>
```

And both are working finely.

So, my commentaries on possible problems by punctuation symbols (at least those used in these names) seem wrong.

Please, download the latest `disk.pm` and let me know if all is working fine.

**Comment by HarikalarKutusu** [comment]
Thank you, it is perfect now :)
Tested with 11 drives in 3 groups...

**Comment by zd59** [comment]
Hello!

Thank you for this excellent utility.
I confirm that new disk.pm works excellent. Replacing it and updated monitorix.conf even do not delete older disk logs and graphs. That's great.

Best greetings.

**Comment by mikaku** [comment]
@zd59 :+1: 
Thanks for your feedback!
