### ISSUE TITLE
nginx status doesn't work - mistake in monitorix.conf

### ISSUE THREAD

**Issue by ttsrg** [mikaku/Monitorix#273]
# NGINX graph
# -----------------------------------------------------------------------------
<nginx>
        url = http://localhost/nginx_status
        port = 80
        rule = 24100
        rigid = 0, 0, 0
        limit = 100, 100, 100
</nginx>

Hello. Because you have to use url = http://localhost/nginx-status   in monitorix.conf

**Comment by mikaku** [comment]
I relied on NGINX pages like [this one](https://www.nginx.com/blog/monitoring-nginx/).
Do you have a newest NGINX document that forces to `nginx-status` over `nginx_status`?

**Comment by mikaku** [comment]
Closing due to no response for two weeks.

If you still need more information, please add a comment and the issue can be reopened.
