### ISSUE TITLE
Disk drive temperatures and health - only first disk data, other empty

### ISSUE THREAD

**Issue by zd59** [mikaku/Monitorix#276]
Hello Jordi!

Your new disk drive temperatures and health graph show only data for the first disk listed in <list>.
I tried both: list two drives in one line:
`0 = /dev/sda, /dev/sdb`

and

```
0 = /dev/sda
1 = /dev/sdb
```
On both cases the data was only for the first disk (sda), the other (sdb) had no data.
For another test, the first listed was sdb, the second was sda.
In that case the data shown was also only for a first listed (now sdb) an the second (now sda) had no data.
from monitorix log file:

> Can't exec "hddtemp": No such file or directory at /usr/lib64/monitorix/disk.pm line 247.
> Tue Apr 21 14:53:01 2020 - disk::disk_update: 'smartctl' failed to get data from '/dev/sdb' and 'hddtemp' seems doesn't exist.

Looks like monitorix uses smartctl ony for the first disk, for others hddtemp. That do not exist on my system. 

From hddtemp source page:

> Development Status: ? - Orphaned/Unmaintained 

The last source is fourteen !! years old.

**Comment by mikaku** [comment]
Make sure your disk `/dev/sdb` supports SMART technology.

Execute the same command that Monitorix uses to get statistics from the drives:

```
smartctl -A /dev/sdb
```

and let me know the results.

**Comment by zd59** [comment]
To be sure, both disks supports SMART, I already tested them.
If you carefully read my first post, you noticed, I replaced sda and sdb with each other in a monitorix.config. It is not important if sda or sdb:
When the first disk is sda and sdb second, only sda data are shown, sdb empty.
When the first disk is sdb and second is sda, only sdb data are shown, sda empty.

**Comment by mikaku** [comment]
I'm not sure if I understand correctly what you are saying, but if it matters, the following is a screen shot with the temperatures of four disk drives:

![disk01z 1day](https://user-images.githubusercontent.com/829885/79877212-4288bf00-83ec-11ea-9512-c4527a5c9021.png)

This is the configuration:

```
# DISK graph
# -----------------------------------------------------------------------------
<disk>
        <list>
                0 = /dev/sda, /dev/sdb, /dev/sdc, /dev/sdd
        </list>
[...]
```

The four disks support SMART technology and they are all reporting statistics with the `smartctl` command.

**Comment by zd59** [comment]
My deep apologize!

Checked again with  smartctl  -a /dev/sdb |grep Temp - no output
Both disks support SMART, but only sda support temperature report. The one in question is old SSD, and no temperature report.
