### ISSUE TITLE
du.pm with type files and show_gap=y fail

### ISSUE THREAD

**Issue by lours974** [mikaku/Monitorix#277]
Bonjour,
With "show_gap=y" and "du" config in monitorix.conf like:
```
344 <du>
 345     list = System , Users , MailQueue                                                                                                                                                     
 346     <desc>
 347         0 = /var/www, /var/lib/mysql, /var/log, /tmp, /
 348         1 = /home/netlogon/icones
 349         2 = /home/mail/admin/cur/, /home/mail/admin/new/
 350     </desc>
 351     <type>
 352         0 = size
 353         1 = size
 354         2 = files
```
I get :
>ERROR: while graphing .../monitorix/www//imgs/du1.1day.png: don't understand 'allvalues,UN,INF,UNKN,IF' 

I think that some code is missing in du.pm
adding this at line 386 of du.pm (without any serious code reading)

`385                 push(@DEF0, "DEF:d9=$rrd:du" . $n . "_d9:AVERAGE");
+386                 push(@CDEF0, "CDEF:allvalues=d1,d2,d3,d4,d5,d6,d7,d8,d9,+,+,+,+,+,+,+,+");                                                                                                 
387             # default type is 'bytes'
`
It seems to works 

Perhaps it's better to modify du.pm at line 428-431
Can you check the code of du.pm to apply a modification in the good way not like may awfull hack.

Thank.

**Comment by mikaku** [comment]
Yes!, you're right. :smiley: 
That's exactly what is missing.

**Comment by mikaku** [comment]
Thank you!
