### ISSUE TITLE
httpd_builtin / autocheck_responsiveness

### ISSUE THREAD

**Issue by rapesco** [mikaku/Monitorix#278]
Hello,

autocheck_responsiveness always check http://localhost:port, even if "host" value is set to listen on a specific ipv4 address.
```
<httpd_builtin>
        enabled = y
        host = 10.255.0.51
        port = 8080
        user = nobody
        group = nobody
        log_file = /var/log/monitorix-httpd
        hosts_deny =
        hosts_allow = 10.255.0.0/24
        autocheck_responsiveness = n
        <auth>
                enabled = n
                msg = Monitorix: Restricted access
                htpasswd = /var/lib/monitorix/htpasswd
        </auth>
</httpd_builtin>
```

logs

```
Sat May  2 15:18:00 2020 - WARNING: HTTP built-in server not responding at 'http://localhost:8080/monitorix'.
Sat May  2 15:19:01 2020 - WARNING: HTTP built-in server not responding at 'http://localhost:8080/monitorix'.
Sat May  2 15:20:00 2020 - WARNING: HTTP built-in server not responding at 'http://localhost:8080/monitorix'.
```

**Comment by mikaku** [comment]
Indeed, it should rely on `host` if there is a value associated to that option, otherwise only to `localhost`.

**Comment by mikaku** [comment]
Please, check if the last commit solves the situation.

**Comment by mikaku** [comment]
Closing due to no response for two weeks.

If you still need more information, please add a comment and the issue can be reopened.

**Comment by mikaku** [comment]
Closing due to no response for two weeks.

If you still need more information, please add a comment and the issue can be reopened.
