### ISSUE TITLE
Make temperature_scale=f work with gensens

### ISSUE THREAD

**Issue by sfatula** [mikaku/Monitorix#280]
For me, it does not convert in gensens, they show in Celsius. Seems to work in all the other modules that I am using.

**Comment by mikaku** [comment]
You're right, `gensens.pm` doesn't have the code to convert from Celsius to Fahrenheit.

**Comment by mikaku** [comment]
Please, confirm if the last commit solves the situation.

**Comment by sfatula** [comment]
Seems to.
