### ISSUE TITLE
Can i use Monitorix with iptables.log ?

### ISSUE THREAD

**Issue by ZerooCool** [mikaku/Monitorix#281]
Hello, i search a tool for visualized my file iptables.log.

**Comment by mikaku** [comment]
Monitorix uses `iptables` to keep track of network activity. I doesn't use any form of `iptables.log` nor this *GoAccess*.

**Comment by mikaku** [comment]
Closing due to no response for two weeks.

If you still need more information, please add a comment and the issue can be reopened.
