### ISSUE TITLE
phpfpm::phpfpm_update: ERROR: the pool '' don't has an associated URL

### ISSUE THREAD

**Issue by StephenAtty** [mikaku/Monitorix#282]
I'm running version 3.12.0 

I've configured the phpfpm module as below:

```
<phpfpm>
        <group>
                0 = local server
        </group>
        <list>
        0 = www
        </list>
        <desc>
                www = https://myserver.domain/status
        </desc>
        rigid = 0, 0, 2, 0, 0, 0
        limit = 100, 100, 100, 100, 100, 100
</phpfpm>
```

It seems to be working fine but every minute it throws this set of errors

```
Sat Jun  6 17:39:00 2020 - phpfpm::phpfpm_update: ERROR: the pool '' don't has an associated URL.
Sat Jun  6 17:39:00 2020 - phpfpm::phpfpm_update: ERROR: the pool '' don't has an associated URL.
Sat Jun  6 17:39:00 2020 - phpfpm::phpfpm_update: ERROR: the pool '' don't has an associated URL.
Sat Jun  6 17:39:00 2020 - phpfpm::phpfpm_update: ERROR: the pool '' don't has an associated URL.
Sat Jun  6 17:39:00 2020 - phpfpm::phpfpm_update: ERROR: the pool '' don't has an associated URL.
Sat Jun  6 17:39:00 2020 - phpfpm::phpfpm_update: ERROR: the pool '' don't has an associated URL.
Sat Jun  6 17:39:00 2020 - phpfpm::phpfpm_update: ERROR: the pool '' don't has an associated URL.

```
there is no mention of a pool in the documentation or in the configuration file.

**Comment by mikaku** [comment]
Yes, these messages shouldn't appear.

I see that there are 8 fixed iterations regardless the number of items in `list` which is wrong because, in your case, you only have one. Reorganizing a little bit the code will be fixed.

I'll keep you informed.
Thanks!

**Comment by mikaku** [comment]
Please, download the latest `phpfpm.pm` from GitHub and let me know if this version works as expected.

**Comment by StephenAtty** [comment]
It seems to have fixed the issue.

Graphs all running, no errors showing in the log file

**Comment by mikaku** [comment]
Perfect.
Thanks.
