### ISSUE TITLE
Feature Request: Add desc tag to disk section so you can name groups of disks

### ISSUE THREAD

**Issue by sfatula** [mikaku/Monitorix#283]
So, as an example, I have 3 zfs pools, and some other drives. So, makes sense perhaps to have 4 disks sections for temp and sector monitoring. I do that, but, it's nice to know at a glance which is which, would be nice (in the case of many people working on one machine) to be able to name the groups of disks as any other sections allow. So, each list element could have a desc element. 

Yes, I know you can figure it out. When you use /dev/disk-by-id, just takes a little time to cross reference the disks to the id name.

**Comment by mikaku** [comment]
Check the already closed #272 issue.

**Comment by sfatula** [comment]
I see it there, but it's not shown in your documentation online. I was more looking for the name of each graph, not each disk, but can simply to "Poolname Disk 1", "Poolname Disk 2", etc. That will work.

**Comment by mikaku** [comment]
You meant something like this?

```
# DISK graph
# -----------------------------------------------------------------------------
<disk>
        <list>
                0 = /dev/sda, /dev/sdb
                1 = /dev/sdc
        </list>
        <desc>
                0 = Poolname Disk 1
                1 = Poolname Disk 2
        </desc>
[...]
```
![disk](https://user-images.githubusercontent.com/829885/86770222-a5cfd800-c050-11ea-9819-0e162171e4a2.png)

**Comment by sfatula** [comment]
That's what I had preferred, yes, where Poolname Disk 1 would show up on the top graph and Poolname Disk 2 on the bottom.

**Comment by mikaku** [comment]
> where Poolname Disk 1 would show up on the top graph and Poolname Disk 2 on the bottom.

What?

**Comment by sfatula** [comment]
Ah, I didn't see it on your picture, it was below, now I see those names. That's fine, I was looking on top of the graph as the "desc" shows for example on the network traffic and usage stats page.

**Comment by mikaku** [comment]
Please, test this new feature and let me know if it works as expected.

**Comment by sfatula** [comment]
For my use, yes, it works perfectly. Thanks!!

**Comment by mikaku** [comment]
OK, thanks.
