### ISSUE TITLE
latest version -  r..963c567 : cannot load module traffact -- rogue variable "$response"

### ISSUE THREAD

**Issue by Corin-EU** [mikaku/Monitorix#289]
Due to the problem of specifying a host name for the the internal httpd server resulting in the server being continually restarted because Monitorix was checking for the server on localhost and not host_name, I upgraded from v3.12.0 to the latest r.963c567.

There is a problem in traffac.pm.

For some reason, instead of using the standard variable "$response" (as used in the other Perl modules of Monitorix) for getting the response from a web servver, the variable used is "$image" on line 381.  However when cutting and pasting to display the actual contents of the response liine if the request failed to 10 files on July 2nd, 2020 in commit af7d233, the variable name "$response" was used on line 384.

So either, all instances of the response $image should be changed to $response to be consistent and avoid such errors in future, or change $reponse on line 384 to $image.

                      if(!$image->is_success) {
                             logger("$myself: ERROR: Unable to connect to '$url'.");
     -                       logger("$myself: " . $response->status_line);
    +                       logger("$myself: " . $image->status_line);
                     }

**Comment by mikaku** [comment]
@Corin-EU,

You're right, this is a clear case of copy-paste abuse.

> So either, all instances of the response $image should be changed to $response to be consistent and avoid such errors in future, ...

Yes, I think this will be the best line to follow.
I'll fix this issue later this [busy] week I'm having.

**Comment by mikaku** [comment]
Please, download the latest version of `traffacct.pm` and let me know if it works as expected.
Thanks.

**Comment by Corin-EU** [comment]
Thank you for resolving the issue.

I have downloaded the latest r.b154c3e and I see that the $image variable has been renamed to $response for the URL request in traffact,pm.

After installing and starting up the monitorix service, there is no longer the error message about failing to load traffact.pm and the server is running correctly and  the httpd built in server can be accessed via the specified host name and the various graphs can be displayed.

Incidentally, if anybody complains about the message in the monitorix.log

     HTTPServer: You can connect to your server at http://localhost:8040/

evem though the host name is speciffied, that is a bug (hardcoded string rather than a parameterized string) coming from the underlying imported CPAN module HTTP/Server/Simple.pm file and not from Monitorix.hah

Thanks for all the work on the project!

**Comment by mikaku** [comment]
> evem though the host name is speciffied, that is a bug (hardcoded string rather than a parameterized string) coming from the underlying imported CPAN module HTTP/Server/Simple.pm file and not from Monitorix.hah

Many thanks for clarifying this. You have a keen eye.
