### ISSUE TITLE
"Network port traffic" stops collecting data.

### ISSUE THREAD

**Issue by Sweepr** [mikaku/Monitorix#291]
I'm using Monitorix 3.12.0 on Centos 7.4, i noticed that for some unknown reason the "Network port traffic" stops collecting data.

When i restart the service data starts collecting again.

What can be the reason for this behaviour?

I have no been able to reproduce this.

![afbeelding](https://user-images.githubusercontent.com/2857865/96405885-86635200-11de-11eb-82d7-a362fb6ae9a7.png)

![afbeelding](https://user-images.githubusercontent.com/2857865/96405895-8b280600-11de-11eb-91d3-1b7e7b948264.png)

**Comment by mikaku** [comment]
Hi,

Monitorix sets specific `iptables` rules for each network port defined to be able to show its network activity. These rules can be flushed out by your Linux firewall if your restarted it.

**Comment by Sweepr** [comment]
Thanks!! 

Let's see if we can upgrade Centos.  

Closing this since there's no issue then.

**Comment by mikaku** [comment]
I forgot to tell you to execute `iptables-save` (without any arguments) to see if the Monitorix rules are there.

**Comment by Sweepr** [comment]
Got it! 

:monitorix_IN_0 - [0:0]
:monitorix_IN_1 - [0:0]
:monitorix_IN_2 - [0:0]
:monitorix_IN_3 - [0:0]
:monitorix_IN_4 - [0:0]
:monitorix_IN_5 - [0:0]
:monitorix_IN_6 - [0:0]
:monitorix_OUT_0 - [0:0]
:monitorix_OUT_1 - [0:0]
:monitorix_OUT_2 - [0:0]
:monitorix_OUT_4 - [0:0]


Thanks.

**Comment by mikaku** [comment]
Perfect!
:+1:

**Comment by Sweepr** [comment]
Is there a way to restart monitorix or re-apply the ip rules because when i restart the firewall or upgrade csf the iptables are flushed and stops logging the network statistics.

**Comment by IzzySoft** [comment]
How about simply restarting the service? Something like `service monitorix restart` should be sufficient (not sure what the syntax on CentOS is). Just do that whenever you restarted the firewall or upgraded csf I'd say :wink:

**Comment by Sweepr** [comment]
@IzzySoft, ofcourse, but i don't want to manually restart a service all the time, automatically is what i want. :smile:

**Comment by IzzySoft** [comment]
> when i restart the firewall or upgrade csf

That didn't sound automatic either, which is why I assumed manual actions. To not forget the step, you could e.g. set up aliases, like `cfsup` for "upgrade csf && restart monitorix". I guess there would also be ways to configure systemd to deal with that dependency (like, whenever the firewall goes down it takes monitorix along – but then also reloads monitorix when the firewall comes up again), but why complicate things?

**Comment by Sweepr** [comment]
@IzzySoft No problem, just wondering since i ran into this issue since csf does automated upgrade , the monitorix network graph's stopped working.

But i'll have a look later, thanjs for thinking along.

**Comment by mikaku** [comment]
Sooner or later Monitorix will have to include support for `firewalld`, which seems the way to go on Fedora and RHEL-based systems, perhaps others as well.

**Comment by Sweepr** [comment]
That would be nice, i'm using CSF, i find it very comfortable in usage.

I will explore the options to reload the rules when the firewall is down/restarted/upgraded,.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Sweepr** [comment]
@mikaku  

After reading the documentation again i think i can use this to restart Monitorix upon restart of CSF:

2. To run external commands after csf configures iptables create the file:

/usr/local/csf/bin/csfpost.sh

Thanks guys for the assistance.

**Comment by mikaku** [comment]
Great find!
