### ISSUE TITLE
Graphs look weird, any reason why this could be?

### ISSUE THREAD

**Issue by Sweepr** [mikaku/Monitorix#292]
![image](https://user-images.githubusercontent.com/2857865/97113455-c056bb80-16ea-11eb-8213-968461f6ed33.png)

**Comment by mikaku** [comment]
Yeah, that's because today is a 25 hours day, and the internal .rrd structure is defined for 24 hour days.
Tomorrow everything will be fine again.

**Comment by Sweepr** [comment]
Thanks, i thought i did something wrong.
