### ISSUE TITLE
Filesystem usage not recognized

### ISSUE THREAD

**Issue by Gamoth** [mikaku/Monitorix#293]
Hello,

I have just installed and configured monitorix.
For the majority of the probes, it seems to work perfectly, however I have added some mounts and they are not recognized, they are displayed at 0.

```
<fs>
	<list>
		0 = /,/srv/nas_data,/srv/backup,/home, swap
	</list>
	<desc>
	</desc>
	<devmap>
	    /srv/nas_data = dm-3
	    /srv/backup = dm-2
	    /home = dm-6
	</devmap>
	rigid = 2, 0, 2, 0
	limit = 100, 1000, 100, 1000
	<alerts>
	</alerts>
</fs>
```

Any idea ?

**Comment by mikaku** [comment]
Hi,

Please, execute `df` and make sure that the directories you defined are really mount points of a filesystem.

**Comment by Gamoth** [comment]
Hi,
```
df
Filesystem                1K-blocks      Used Available Use% Mounted on
udev                        4002460         0   4002460   0% /dev
tmpfs                        803680     19640    784040   3% /run
/dev/mapper/chaud-system   10255636   4662924   5052040  48% /
tmpfs                       4018392         0   4018392   0% /dev/shm
tmpfs                          5120         0      5120   0% /run/lock
tmpfs                       4018392         0   4018392   0% /sys/fs/cgroup
/dev/sda1                    789904     85308    647252  12% /boot
/dev/mapper/froid1-nas    504689608 113790300 367793540  24% /srv/nas_data
/dev/mapper/froid2-backup 473726056 198865888 253327264  44% /srv/backup
/dev/mapper/chaud-journal   5095040     60264   4756248   2% /var/log
/dev/mapper/chaud-maison  153769424  46374160  99514560  32% /home
tmpfs                        803676         0    803676   0% /run/user/0
tmpfs                        803676         0    803676   0% /run/user/1000
```

**Comment by mikaku** [comment]
Can you also check in `/var/log/monitorix.log` to see if there are error messages?

**Comment by Gamoth** [comment]
I saw nothing ...

**Comment by mikaku** [comment]
I cannot help you more with the information you sent.

Pastebin your whole config file (or send me it by email) and I'll use your `df` output above to try to reproduce your problem.

**Comment by Gamoth** [comment]
Hello,

Enclosed is my complete config, it is only valid for one day even if I think there is nothing confidential.
https://nopaste.linux-dev.org/?1325167

**Comment by mikaku** [comment]
Please, pastebin all the lines from the last Monitorix start until the last line of your `/var/log/monitorix`.

**Comment by Gamoth** [comment]
https://nopaste.linux-dev.org/?1325168

**Comment by mikaku** [comment]
I've fixed the error messages:

```
...
Use of uninitialized value $text_when_all in string eq at /usr/bin/monitorix line 160.
Use of uninitialized value $text_when_all in concatenation (.) or string at /usr/bin/monitorix line 163.
Mon Oct 26 12:24:47 2020 - Generating the 'index.html' file.
Mon Oct 26 12:24:47 2020 - main::create_index: ERROR: invalid value in 'default_option_when_all' option ('').
```

This is due because you have not upgraded your `montitorix.conf`.
They are harmless though, does not affect your main problem.

**Comment by Gamoth** [comment]
Ok, how to upgrade monitorix.conf ?

I went to a 1 hour delay and I see that my disks display correctly since I restarted the service.

**Comment by mikaku** [comment]
> Ok, how to upgrade monitorix.conf ?

There isn't an automated process. You must compare the your current `monitorix.conf` with the one that comes after upgrading Monitorix.

> I went to a 1 hour delay and I see that my disks display correctly since I restarted the service.
So you mean that all is working correctly?

**Comment by mikaku** [comment]
Besides the problems of an old configuration file, the rest is working fine here.

**Comment by IzzySoft** [comment]
> There isn't an automated process. You must compare the your current `monitorix.conf` with the one that comes after upgrading Monitorix.

Wasn't that the reason we switched to using `conf.d/<your_adjustments_here>.conf` some years ago – so users should not touch the `monitorix.conf` itself but rather override what they need in their own config? That also makes it much easier to identify your own adjustments and correct them when needed.

**Comment by Gamoth** [comment]
Sorry, I used Yunohost to install your app : https://github.com/YunoHost-Apps/monitorix_ynh
Apparently this repository is not up to date in the config, right?

**Comment by mikaku** [comment]
>  Apparently this repository is not up to date in the config, right?

Right, the config there seems a bit outdated.
Anyway, having an outdated configuration file is not the source of the issues you have (had?).

**Comment by mikaku** [comment]
Closing due to no response for two weeks.

If you still need more information, please add a comment and the issue can be reopened.
