### ISSUE TITLE
unbound on FreeBSD

### ISSUE THREAD

**Issue by z-eos** [mikaku/Monitorix#302]
FreeBSD has unbound installed by default with the system, but is named `local-unbound*` so, `unbound-control` is named `local-unbound-control`

may it be possible to check, wheather unbound from packages is installed (pkg info -x unbound) and if not, then use `local-unbound-control` instead `lunbound-control` ? 

Otherwise something like `ln -s local-unbound-control unbound-control` is needed ...

**Comment by mikaku** [comment]
I'll include a new option called `cmd`, as in other graphs, that will default to `unbound-control`.

**Comment by z-eos** [comment]
sounds great
