### ISSUE TITLE
Feature Request: .htaccess via URL

### ISSUE THREAD

**Issue by DefCon-CC** [mikaku/Monitorix#307]
Hello, 
is it possible to implement a feature that MonitorIx can handle .htaccess login via URL. I would like to have something like this:

```
<apache>
        list = http://username:password@localhost/server-status?auto
        <alerts>
        </alerts>
        rigid = 0, 0, 2, 0, 0, 0
        limit = 100, 100, 100, 100, 100, 100
</apache>
```

instead of 

```
<apache>
        list = http://localhost/server-status?auto
        <alerts>
        </alerts>
        rigid = 0, 0, 2, 0, 0, 0
        limit = 100, 100, 100, 100, 100, 100
</apache>
```

**Comment by mikaku** [comment]
Hello,

I assume that by *.htaccess login* you mean the [HTTP Basic Access Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) method.

If so, this is something that should work implicitly. So your first example looks good to me, although I have not tested it.

**Comment by DefCon-CC** [comment]
Yes correct: HTTP Basic Access Authentication 
Ok I will give it a try. Will it also work if the URL uses https instead of http?

**Comment by mikaku** [comment]
> Will it also work if the URL uses https instead of http?

Yes it should work, otherwise let me know.

**Comment by DefCon-CC** [comment]
Seems that both does not work. HTTP Basic Access Auth and HTTPS. But I'm not 100% sure because of the fact that Varnish Cache is in between and also access via Lynx throws 403 error.

**Comment by mikaku** [comment]
Yeah, before using it in Monitorix make sure that the same URL works on a browser.

**Comment by mikaku** [comment]
Closing due to no response for two weeks.

If you still need more information, please add a comment and the issue can be reopened.
