### ISSUE TITLE
Feature request: Custom graphs

### ISSUE THREAD

**Issue by ru-errorist** [mikaku/Monitorix#308]
Hi! Thanks for your amazing job! Could it be somehow implemented to monitor a random service by taking parameters from output by grepping it? For example I have an output like this from the command `dummyservice status`:
```
...
Block height:                                  534
Max observed block length:                     534
...
Sync status:                                   Synced
...
```
I can assign variables:

- 'Block' via `dummyservice status | grep 'Block height' | grep -o '[0-9]*'`,
- 'Max-block' via `dummyservice status | grep 'Max observed block' | grep -o '[0-9]*'`
- 'Status' via `dummyservice status | grep 'Sync status' | grep -oE '(Synced|Unsynced|Offline)'`

With first 2 ones it would be straightforward: an interval is specified and a resulting graph would be these numbers depending on the time.

The third one could be done like a straight line with as much legend entities as it was found. In my example it would be 3 values and the graph would show how they changed in time.

This part of the config could be like this:
```
<custom>
        list = Block-values, State
        <desc>
                0 = Block height, Max block
                1 = State
        </desc>
        <type>
                0 = integer
                1 = string
       </type>
        <values>
                0 = "dummyservice status | grep 'Block height' | grep -o '[0-9]*'", "dummyservice status | grep 'Max observed block' | grep -o '[0-9]*'"
                1 = "dummyservice status | grep 'Sync status' | grep -oE '(Synced|Unsynced|Offline)'"
        </values>
        graphs_per_row = 2
</custom>
```

**Comment by mikaku** [comment]
> Hi! Thanks for your amazing job!

Glad to know you are enjoying Monitorix!

> Could it be somehow implemented to monitor a random service by taking parameters from output by grepping it?

That's what, more or less, already does the `ambsens.pm` module which even has alert capabilities.

If I understood correctly your suggestion, the only difference is that instead of configuring the command line for each case in the configuration file, you define the scripts that Monitorix will execute to retrieve the value for each case.

This is how it would be:

```
<ambsens>
        list = Block-values, State
        <desc>
                0 = bh, mb
                1 = s
        </desc>
        <units>
                0 = Text of y-axis
                1 = Text of y-axis
        </units>
        <cmd>
                bh = /path/to/script_bh.sh
                mb = /path/to/script_mb.sh
                s = /path/to/script_s.sh
        </cmd>
        <map>
                0 = Block height, Max block
                1 = State
        </map>
        <alerts>
        </alerts>
        graphs_per_row = 2
        rigid = 0
        limit = 100
</ambsens>
```

Strings are not accepted as statistics value.

**Comment by ru-errorist** [comment]
Thank you for such prompt answer! I tried on a real life example but with no success. Maybe it's all about my noob knowledge of bash and *nix systems in general. I have a proccess `coda` which gives me a following output for `coda client status`. I omitted some lines for simplicity with '...'.
```
...
Block height:                                  578
Max observed block length:                     578
...
Peers:                                         27 (35.223.47.217:8302 178.170.41.31:8302 135.181.166.45:8302 168.119.5.211:8302 161.97.150.51:8302 34.122.47.136:8302 34.121.187.223:10517 34.66.157.200:10001 135.181.158.53:8302 95.217.226.222:8302 146.148.113.15:37770 34.71.83.44:10507 161.97.134.103:8302 46.4.91.2:8302 34.123.174.31:10001 135.181.118.109:8302 94.130.69.211:59800 135.181.139.155:1025 152.32.187.189:8302 95.217.194.239:8302 144.76.98.162:32904 138.201.132.49:8302 157.90.17.64:8302 151.236.216.152:8302 37.195.124.167:8302 104.238.220.97:53292 46.4.226.240:8302)
...
```
So I wrote 3 '.sh' files for parsing values:
```
root@Ubuntu-1804-bionic-64-minimal ~ # cat mina-block-height.sh
coda client status | grep 'Block height' | grep -o '[0-9]*'
root@Ubuntu-1804-bionic-64-minimal ~ # cat mina-max-block.sh
coda client status | grep 'Max observed block' | grep -o '[0-9]*'
root@Ubuntu-1804-bionic-64-minimal ~ # cat mina-peers.sh
coda client status | grep 'Peers' | grep -oE '[0-9]+\s\(' | grep -oE '[0-9]+'
```

I've checked that the result is satisfactory:
```
root@Ubuntu-1804-bionic-64-minimal ~ # /root/mina-block-height.sh
578
root@Ubuntu-1804-bionic-64-minimal ~ # /root/mina-max-block.sh
578
root@Ubuntu-1804-bionic-64-minimal ~ # /root/mina-peers.sh
31
```

I've changed config file like so:
```
# AMBSENS graph
# -----------------------------------------------------------------------------
<ambsens>
        list = Mina daemon statistics
        <desc>
                0 = bh, mb, prs
        </desc>
        <units>
                0 = Number
        </units>
        <cmd>
                bh  = /root/mina-block-height.sh
                mb  = /root/mina-max-block.sh
                prs = /root/mina-peers.sh
        </cmd>
        <map>
                bh  = Mina current block height
                mb  = Mina max block hieght observed
                prs = Number of connected peers
        </map>
        <alerts>
        </alerts>
        graphs_per_row = 1
        rigid = 0
        limit = 100
</ambsens>
```
But the graph was empty:
![2021-01-06_15-01-00-365_brave](https://user-images.githubusercontent.com/7092693/103766570-17a0d280-5030-11eb-9453-200951423174.png)

I've looked in logs and found that `monitorix` process is not aware of `coda` process:
```
 45452  Wed Jan  6 11:42:00 2021 - ERROR: while updating /var/lib/monitorix/ambsens.rrd: /var/lib/monitorix/ambsens.rrd: Function update_pdp_prep, case DST_GAUGE - Cannot convert '' to float
 45453  ls: cannot access '/home/*': No such file or directory
 45454  Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/gensens.pm line 487.
 45455  Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/gensens.pm line 515.
 45456  /root/mina-block-height.sh: 1: /root/mina-block-height.sh: coda: not found
 45457  /root/mina-max-block.sh: 1: /root/mina-max-block.sh: coda: not found
 45458  /root/mina-peers.sh: 1: /root/mina-peers.sh: coda: not found
```

I've tried to solve it by using `sh` as [advised](https://stackoverflow.com/a/12363366):
```
# AMBSENS graph
# -----------------------------------------------------------------------------
<ambsens>
        list = Mina daemon statistics
        <desc>
                0 = bh, mb, prs
        </desc>
        <units>
                0 = Number
        </units>
        <cmd>
                bh  = sh /root/mina-block-height.sh
                mb  = sh /root/mina-max-block.sh
                prs = sh /root/mina-peers.sh
        </cmd>
        <map>
                bh  = Mina current block height
                mb  = Mina max block hieght observed
                prs = Number of connected peers
        </map>
        <alerts>
        </alerts>
        graphs_per_row = 1
        rigid = 0
        limit = 100
</ambsens>
```

But with no success and another error:
```
 45484  Wed Jan  6 11:46:00 2021 - ambsens::ambsens_update: ERROR: script 'sh /root/mina-block-height.sh' doesn't exist or don't has execution permissions.
 45485  Wed Jan  6 11:46:00 2021 - ambsens::ambsens_update: ERROR: script 'sh /root/mina-max-block.sh' doesn't exist or don't has execution permissions.
 45486  Wed Jan  6 11:46:00 2021 - ambsens::ambsens_update: ERROR: script 'sh /root/mina-peers.sh' doesn't exist or don't has execution permissions.
```

Any chance to help me with this?

**Comment by mikaku** [comment]
The first configuration looks good to me, but in the second one:

```
                bh  = sh /root/mina-block-height.sh
                mb = sh /root/mina-max-block.sh
                prs = sh /root/mina-peers.sh
```

That's not correct. Monitorix executes the command as it is, so prefixing it with another command won't work.

>  coda: not found

That's the problem.
Make sure that `coda` is in the standard `$PATH` or prefix it with its absolute pathname.

**Comment by ru-errorist** [comment]
Speaking about strings I consider treating them as a 'list' variable with a value = 1 for each of strings. In my particular case I have another script which is like:
```
root@Ubuntu-1804-bionic-64-minimal ~ # cat mina-status.sh
coda client status | grep 'Sync status' | grep -oE '(Synced|Catchup|Bootstrap|Offline|Connecting)'
```

So, the output might be only one of these words. If treating each of strings like an integer equals 1 in scenario when there was Bootstrap, Catchup and Synced statuses, the graph might be like:
![2021-01-06_15-13-11-046_brave](https://user-images.githubusercontent.com/7092693/103767862-6cdde380-5032-11eb-9ca2-ec4d04df8c06.png)

**Comment by mikaku** [comment]
You won't be able to see multiple colored values if they have the same value. Only the last one will be shown.
Anyway, the legend of the graph (`current`, `average`, `min` and `max`) will show the values for each type of string.

**Comment by ru-errorist** [comment]
They wouldn't be stacked as for one moment of time only one status can exist. If an output somehow would be like `(Synced|Catchup|Bootstrap|Offline|Connecting)`, it should be considered as misconfiguration and treated like one string also.

This is just a proposal for new type of graph or tuning 'ambient sensors'. I have no assumption how to to do it besides that I've already mentioned.
Anyway, thanks for your time and a great product!

**Comment by mikaku** [comment]
> They wouldn't be stacked as for one moment of time only one status can exist.

I see, then in that case I recommend you to configure 5 independent options each one with its own script which will return `1` or `0` depending on the state. That way you'll see a line plotted in the graph belonging to the real state at each time.

```
        <desc>
                0 = bh, mb, prs
                1 = synced, catchup, bootstrap, offline, connecting
        </desc>
        <units>
                0 = Number
                1 = State
        </units>
        <cmd>
                bh  = /root/mina-block-height.sh
                mb = /root/mina-max-block.sh
                prs = /root/mina-peers.sh
                synced = /root/mina-synced.sh
                catchup  = /root/mina-catchup.sh
                bootstrap = /root/mina-bootstrap.sh
                offline = /root/mina-offline.sh
                connecting = /root/mina-connecting.sh
        </cmd>
 ``
