### ISSUE TITLE
Feature request: process time

### ISSUE THREAD

**Issue by uri200** [mikaku/Monitorix#311]
Hey @mikaku,

Awesome project!!

We are using it to monitor some specific `process` and we are missing a way to infer if the process has been restarted. Would it be possible parse how long a process has been running and create a new graph showing when that time is less than the sample time?  This way if a process restarts, that graph would show a tick indicating there has been a restart on the service.

`ps -p {PID-HERE} -o etime`

Bona feina!!

**Comment by mikaku** [comment]
> Awesome project!!

Thanks!

I could create an additional graph in `process.pm` to show the uptime of the list of processes. This way you'll end up with a similar Uptime graph as in `system.pm`, but instead of having a single value the graph would show up to 9 uptime values.

The `process.pm` already executes the command `ps -eo pid,comm,command` to parse the process names, so it's just as simple as include the `etimes` argument to also get the elapsed time (in seconds) for each process in the list:

```
ps -eo pid,etimes,comm,command
```

Does this would suffice?

> Bona feina!!

Gràcies! :wink:

**Comment by uri200** [comment]
Thanks for your answer and sorry for the delay. 

Yes that would be good enough!

Lines that would go to 0 would mean a restart. Lines that never show up may mean a service is stuck on restart loop.

Thanks again!

**Comment by mikaku** [comment]
Ok, thanks.
I'll work on this and I'll return when I have something interesting to show you.

**Comment by jose1711** [comment]
Instead of separate graph I'd much rather see this in the same group as the other process-related graphs (CPU time, memory usage, etc.). `/proc/PID/stat` is already being read and it contains `starttime` which holds time processes started since boot which I believe can be also used. Here's a way to find out how many seconds elapsed since Firefox has started:
```
awk -v ticks="$(getconf CLK_TCK)" 'NR==1 { now=$1; next } END { printf "%9.0f\n", (now - ($20/ticks)) }' /proc/uptime RS=')' /proc/$(pgrep firefox)/stat
```
Taken with minor modification from https://stackoverflow.com/a/38740102

**Comment by mikaku** [comment]
> Instead of separate graph I'd much rather see this in the same group as the other process-related graphs (CPU time, memory usage, etc.)

I don't said to create separate module for this, I meant to create an additional graph inside `process.pm`.

> /proc/PID/stat is already being read and it contains starttime which holds time processes started since boot

Yes, that's a good way to get the same value.

**Comment by jose1711** [comment]
> > Instead of separate graph I'd much rather see this in the same group as the other process-related graphs (CPU time, memory usage, etc.)
> 
> I don't said to create separate module for this, I meant to create an additional graph inside `process.pm`.

My bad, sorry I missed that.

**Comment by mikaku** [comment]
Yeah, my only problem with this new graph is cosmetic.

I mean, `process.pm` has currently 8 graphs and are shown using a 2x4 grid (graph layouts in Monitorix are fixed). With that new graph there will be 9 graphs to show, and it will looks like some graph is missing in the last row.

Do you guys know of any new interesting metric to create the 10th graph? :sweat_smile:

**Comment by jose1711** [comment]
> my only problem with this new graph is cosmetic.

Heh, I was thinking about exactly the same. Checked the other `stat` metrics but saw nothing really interesting. Maybe something to consider: put `num_threads` and `num_processes` to the same graph (as they are somewhat related).

**Comment by mikaku** [comment]
Please download the latest `process.pm` and let me know if it works as expected.

**Comment by jose1711** [comment]
Thank you, it works. However the y-axis label is a bit strange. Says: "days" but the real unit is minutes. It looks though that days is used in min/max/current values.

![obrázok](https://user-images.githubusercontent.com/1406222/116152050-b76c9400-a6e5-11eb-91f6-328d59ac590b.png)

**Comment by jose1711** [comment]
Thank you @mikaku for your thorough explanation. I also check the `process.pm` to better understand how is the data formed. If I understand it correctly you're getting values in seconds from `ps` command and then convert them to values in days by dividing them by 86400. I am pretty sure that this is a perfect fit for server which tend to have system uptime of weeks, months or even years (if the sysadmin ignores the need for patching). But for desktop systems which normally runs only during business hours I believe minutes or hours or process uptime would make more sense. Could you please consider having an extra option (e. g. `time_unit = day (default)/hour/minute`)?

**Comment by mikaku** [comment]
@jose1711, please, download the latest `process.pm` and let me know if that's suffice.

The new option `time_unit` defaults to `day` when it's defined with any other value than `minute` or  `hour`.

**Comment by jose1711** [comment]
Thank you, tried `hour` and it works great. Would it be possible to add the same setting to `system.pm` or I should open a new issue.

**Comment by mikaku** [comment]
Thanks for testing it.
Better open a new issue referencing this one.

**Comment by jose1711** [comment]
Will do. I just noticed a weird thing.. not sure if there's something wrong with my setup but if I click the Uptime graph I get a window and graph title changes to `Number of processes`.

**Comment by mikaku** [comment]
> ... if I click the Uptime graph I get a window and graph title changes to Number of processes.

Yes, there was a typo.
Now is corrected, thanks.

**Comment by jose1711** [comment]
No word from the issue author but I believe it can be closed now. Thanks for making this a reality!

**Comment by mikaku** [comment]
Agreed.

**Comment by lorenzos** [comment]
> I mean, `process.pm` has currently 8 graphs and are shown using a 2x4 grid (graph layouts in Monitorix are fixed). With that new graph there will be 9 graphs to show, and it will looks like some graph is missing in the last row.

@mikaku Any fix for this? Is there a way I can use the configuration to hide the last uptime graph? Thanks.

**Comment by lorenzos** [comment]
Yes, that's what I see. Got no metric idea for the empty space, thanks for the quick feedback anyway 👋
