### ISSUE TITLE
phpfpm::phpfpm_update: ERROR: the pool '' don't has an associated URL.

### ISSUE THREAD

**Issue by DefCon-CC** [mikaku/Monitorix#312]
Hello,

I'm getting the error in the log "phpfpm::phpfpm_update: ERROR: the pool '' don't has an associated URL.". But I do not find an error in the configuration. The configuration is:

`
<phpfpm>

        <group>
                0 = DefCon
        </group>
        <list>
                0 = www
        </list>
        <desc>
                www = http://localhost:4080/fpm-status
        </desc>
        <map>
        </map>
        rigid = 0, 0, 2, 0, 0, 0
        limit = 100, 100, 100, 100, 100, 100
</phpfpm>
`

Output from: 

`

pool:                 www
process manager:      dynamic
start time:           28/Jan/2021:14:04:05 +0100
start since:          1042124
accepted conn:        75325
listen queue:         0
max listen queue:     3
listen queue len:     128
idle processes:       2
active processes:     1
total processes:      3
max active processes: 4
max children reached: 0
slow requests:        0
</>
`

**Comment by mikaku** [comment]
I've checked your configuration and it looks fine. I've also tested it and it works here.
Please, restart Monitorix, wait a pair of minutes and paste here the complete log file.

**Comment by mikaku** [comment]
Closing due to no response for two weeks.

If you still need more information, please add a comment and the issue can be reopened.
