### ISSUE TITLE
lmsens: Always assuming same unit is not safe

### ISSUE THREAD

**Issue by WildPenquin** [mikaku/Monitorix#315]
Hi,

I this little snag with the lm-sensors module. I'm monitoring the vdd of my gfx adapter (amdgpu; RX Vega 64). The vddgfx changes according to needs of the GPU  in the range from 0.7 ... 1.2V (or so I believe, I haven't checked). The output unit of sensors changes, if vddgfx<1:

vddgfx:      831.00 mV 

But if it is >= 1V:

vddgfx:        1.09 V

Monitorix has trouble parsing mV correctly, and the vddgfx is everywhere from 1 - 999 in the graph (while it should be in the 0.7 ... 1.2V range!

Now, any suggestions how to "fix" this? Should this be fixed on the lm-sensors side (force it so it doesn't change the unit), or should we change the lmsens module so that it parses the unit?

Either way, I don't see an easy way to fix this currently on the users side without changing code in either project, but maybe I'm missing something. Any suggestions are welcome!

**Comment by mikaku** [comment]
Hi,

Unfortunately Monitorix doesn't support changes in the unit of a sensor, so I don't see an easy way for you to manage this. I think that your best bet is trying to configure lm-sensors to have a fixed unit value.

Sorry for the inconveniences.

**Comment by WildPenquin** [comment]
Hi @mikaku!

AI believe I will ask the lmsensors folks their stance on this. Their configuration does not allow forcing / setting a unit for reporting format, unless I'm missing something (it does allow arithmetic on the raw sensor data but there is little options to format the actual output data one gets from the sensors command; actaully, it makes sense the way they've made, "sensors" is only a frontend).

As a crude workaround, I believe one could multiply the data (say, by 10 or 100) by providing an additional configuration file only when calling sensors from Monitorix and dividing this value by monitorix to get the real value.

OTOH it might make more sense to actually make another lm sensors module which would use the interface in /sys/class/hwmon/hwmon? (as it is format agnostic) or perhaps even libsensors (though I'm not sure if/how that could work), instead of parsing the sensors command output. The sensors command does have a raw mode, but even using that would need at least partly rewritten module...

p.s. After posting I noticed your comment on another issue about this same issue (with units).

**Comment by mikaku** [comment]
> I believe I will ask the lmsensors folks their stance on this.

If you succeed and if you don't mind, please let us know the way you solved it as it might help other people in the same situation.

> OTOH it might make more sense to actually make another lm sensors module which would use the interface in /sys/class/hwmon/hwmon?

Did you test the `gensens` module? it currently supports temperatures, CPU and battery values. Also I'll be glad to include support for new values.

**Comment by mikaku** [comment]
Closing due to no response for two weeks.

If you still need more information, please add a comment and the issue can be reopened.

**Comment by WildPenquin** [comment]
Hi mikaku,

Sorry for not replying, I was busy with other life duties.

I've opened a ticket at lm-sensors (as you can probably see). There I've suggested some other approaches in general, such as, should software use the raw output of `sensors -u`? Let's see what the lm-sensors folks say.

**Comment by mikaku** [comment]
Welcome back! :-)
OK, let's see what they say, and if it worth to reopen this issue.

**Comment by bachandi** [comment]
> Hi mikaku,
> 
> Sorry for not replying, I was busy with other life duties.
> 
> I've opened a ticket at lm-sensors (as you can probably see). There I've suggested some other approaches in general, such as, should software use the raw output of `sensors -u`? Let's see what the lm-sensors folks say.

Using sensors -u would ensure that the units are always constant so probably this would be a good approach in any case also for other units in lmsens.

**Comment by mikaku** [comment]
> Using sensors -u would ensure that the units are always constant so probably this would be a good approach in any case also for other units in lmsens.

The output of `sensors -u` changes a lot as it shows a value per line, so this would require a complete rewrite, unless there is another switch to keep the output as `sensors` do but showing raw values.

Any idea?

**Comment by bachandi** [comment]
Probably `sensors -j` to get json formated output would be even better as you could just let an ordinary json parser do the work.
