### ISSUE TITLE
redis using sockets (v3.13.1)

### ISSUE THREAD

**Issue by mmattel** [mikaku/Monitorix#316]
Hello @mikaku 👋 

it is possible to use a socket in the redis definition of monitorix 😃 
`list = /var/run/redis/redis-server.sock`

You may want to add this in your docs.

Please also see that there is a shift in the text output starting with `Avg` that needs correction. It shifts dependent on the number of `Cur`.
![image](https://user-images.githubusercontent.com/3321281/111922343-84f1ca80-8a99-11eb-9904-22ab9bfae449.png)

**Comment by mikaku** [comment]
This commit includes support to recognize a socket file in `list` option. The file name must end with `.sock`.
Please download the latest `redis.pm`, test it and let me know if it works as expected.

**Comment by mikaku** [comment]
Please, download the latest `redis.pm` and let me know if it works for you.

**Comment by mikaku** [comment]
Closing due to no response for two weeks.

If you still need more information, please add a comment and the issue can be reopened.
