### ISSUE TITLE
Log message not correct for redis when using socket

### ISSUE THREAD

**Issue by mmattel** [mikaku/Monitorix#318]
When using a socket instead a host:post configuration for redis, the log is spamed falsly with:

`redis::redis_update: unable to connect to port '' on host ''/var/run/redis/redis-server.sock'': Invalid argument`

This should be corrected because when using a socket, there is no port.
Means, if there is no `:port` in the definition, the check must be if you are able to connect to the socket and report that in case of issues.

When restarting monitorix, the log tells in addition:
```
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/system.pm line 9        55.
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/system.pm line 9        76.
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/system.pm line 1        034.
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/system.pm line 1        056.
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/redis.pm line 54        0.
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/redis.pm line 56        6.
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/redis.pm line 64        7.
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/redis.pm line 67        3.
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/redis.pm line 74        8.
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/redis.pm line 77        1.
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/redis.pm line 83        7.
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/redis.pm line 85        9.
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/redis.pm line 92        7.
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/redis.pm line 95        0.
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/redis.pm line 10        37.
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/redis.pm line 10        59.
Use of uninitialized value $port in concatenation (.) or string at /usr/lib/monitorix/redis.pm l        ine 192.
```
Note: pls consider that redis can have the setting to use a password to access it. This is atm not considered at all.

**Comment by mikaku** [comment]
Sockets in Redis are not supported right now.

You already have been opened the same question in issue #316.

**Comment by mikaku** [comment]
This issue ask requests solution to two problems:

> When using a socket instead a host:post configuration for redis, the log is spamed falsly with:

At the time the issue was created socket file connections were not supported.
Please, refer to #316 and test that new feature.

> Note: pls consider that redis can have the setting to use a password to access it. This is atm not considered at all.

Can you, please, provide an example of `redis.conf` configured for password authentication?

**Comment by tchavei** [comment]
I'm surprised that after 4 years nobody else tried to add redis monitoring to monitorix.

I personally use redis with password and I'm willing to help to make it work with monitorix.

Currently I have my password set as an environmental variable REDISCLI_AUTH so that redis-cli doesn't complain about supplying the password in command line. 

Please let me know what additional details would be needed to make monitorix work with password enabled redis

Thank you

**Comment by mikaku** [comment]
> I'm surprised that after 4 years nobody else tried to add redis monitoring to monitorix.

Yeah, it took some time but I merged a recent PR about this: https://github.com/mikaku/Monitorix/pull/471.

**Comment by tchavei** [comment]
Oh. I didn't noticed. Thank you very much. Two questions though:

Does redis.pm need to do any action on the database(s) hosted on redis? I'm asking because albeit the default database has an index of '0', there are cases (like mine) where the database's index is '1'. If monitorix does access the database, I'd suggest to add a 'db_index' field to the config so the user can choose another index if not using '0'

The second question is rather related to release. Currently I'm on 3.16 (installed through pacman). Obviously my version still doesn't have the merged pr. Will you release a new version soon?

Thank you kindly for your time and patience in keeping monitorix updated and a great sys admin tool.

Cheers
Tony

**Comment by mikaku** [comment]
> Does redis.pm need to do any action on the database(s) hosted on redis?

No, I just send the command `info` to get the stats (see below). Perhaps this command assumes the index 0 but let you pass it a different number as an argument. Is that possible? Let me know if this command accepts a number (the index) as an argument and I would add the option `db_index` as you suggested.

https://github.com/mikaku/Monitorix/blob/75543468b151cde978e683c98a6c5ce347cb7d33/lib/redis.pm#L247

> Will you release a new version soon?

Due to mature of Monitorix, I only release a new version each year (if needed) except if there is a critical bug that needs to be fixed. In you case, you can safety overwrite your current `redis.pm` with the new one here at GitHub. This won't break anything.

> Thank you kindly for your time and patience in keeping monitorix updated and a great sys admin tool.

I appreciate your kind words.

**Comment by tchavei** [comment]
Hi.

In that case the db_index seems irrelevant because info pulls all stats. Here's what I get from redis-cli:

```
# Server
redis_version:7.4.2
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:b648dcb34d0d916f
redis_mode:standalone
os:Linux 6.14.6-arch1-1 x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll
atomicvar_api:c11-builtin
gcc_version:11.4.0
process_id:9
process_supervised:no
run_id:de2e7b7a76f1892af0a3c3392751b3c7017a1f9b
tcp_port:6379
server_time_usec:1747922793372676
uptime_in_seconds:49102
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:3092329
executable:/opt/redis-stack/bin/redis-server
config_file:
io_threads_active:0
listener0:name=tcp,bind=*,bind=-::*,port=6379
# Clients
connected_clients:4
cluster_connections:0
maxclients:10000
client_recent_max_input_buffer:20480
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
pubsub_clients:0
watching_clients:0
clients_in_timeout_table:0
total_watched_keys:0
total_blocking_keys:0
total_blocking_keys_on_nokey:0
# Memory
used_memory:214850496
used_memory_human:204.90M
used_memory_rss:266055680
used_memory_rss_human:253.73M
used_memory_peak:234347112
used_memory_peak_human:223.49M
used_memory_peak_perc:91.68%
used_memory_overhead:3820096
used_memory_startup:1290048
used_memory_dataset:211030400
used_memory_dataset_perc:98.82%
allocator_allocated:219903360
allocator_active:251396096
allocator_resident:257884160
allocator_muzzy:0
total_system_memory:67260420096
total_system_memory_human:62.64G
used_memory_lua:412672
used_memory_vm_eval:412672
used_memory_lua_human:403.00K
used_memory_scripts_eval:15488
number_of_cached_scripts:6
number_of_functions:0
number_of_libraries:0
used_memory_vm_functions:32768
used_memory_vm_total:445440
used_memory_vm_total_human:435.00K
used_memory_functions:192
used_memory_scripts:15680
used_memory_scripts_human:15.31K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.13
allocator_frag_bytes:27026912
allocator_rss_ratio:1.03
allocator_rss_bytes:6488064
rss_overhead_ratio:1.03
rss_overhead_bytes:8171520
mem_fragmentation_ratio:1.24
mem_fragmentation_bytes:51228072
mem_not_counted_for_evict:1536
mem_replication_backlog:0
mem_total_replication_buffers:0
mem_clients_slaves:0
mem_clients_normal:28184
mem_cluster_links:0
mem_aof_buffer:1536
mem_allocator:jemalloc-5.3.0
mem_overhead_db_hashtable_rehashing:0
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0
# Persistence
loading:0
async_loading:0
current_cow_peak:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:11494
rdb_bgsave_in_progress:0
rdb_last_save_time:1747922755
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
rdb_saves:591
rdb_last_cow_size:1826816
rdb_last_load_keys_expired:0
rdb_last_load_keys_loaded:49049
aof_enabled:1
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:0
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_rewrites:14
aof_rewrites_consecutive_failures:0
aof_last_write_status:ok
aof_last_cow_size:1843200
module_fork_in_progress:0
module_fork_last_cow_size:0
aof_current_size:52817318
aof_base_size:50746305
aof_pending_rewrite:0
aof_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0
# Stats
total_connections_received:909
total_commands_processed:9046671
instantaneous_ops_per_sec:338
total_net_input_bytes:711499382
total_net_output_bytes:62614295
total_net_repl_input_bytes:0
total_net_repl_output_bytes:0
instantaneous_input_kbps:27.48
instantaneous_output_kbps:2.32
instantaneous_input_repl_kbps:0.00
instantaneous_output_repl_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_subkeys:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:1613
evicted_keys:0
evicted_clients:0
evicted_scripts:0
total_eviction_exceeded_time:0
current_eviction_exceeded_time:0
keyspace_hits:443928
keyspace_misses:50203
pubsub_channels:0
pubsub_patterns:0
pubsubshard_channels:0
latest_fork_usec:5917
total_forks:605
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
total_active_defrag_time:0
current_active_defrag_time:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:813
dump_payload_sanitizations:0
total_reads_processed:1233034
total_writes_processed:1232115
io_threaded_reads_processed:0
io_threaded_writes_processed:0
client_query_buffer_limit_disconnections:0
client_output_buffer_limit_disconnections:0
reply_buffer_shrinks:866
reply_buffer_expands:14
eventloop_cycles:1711016
eventloop_duration_sum:266879469
eventloop_duration_cmd_sum:57893839
instantaneous_eventloop_cycles_per_sec:56
instantaneous_eventloop_duration_usec:255
acl_access_denied_auth:0
acl_access_denied_cmd:0
acl_access_denied_key:0
acl_access_denied_channel:0
# Replication
role:master
connected_slaves:0
master_failover_state:no-failover
master_replid:8adb9e1de4c351f8b8c9c23eaa85d7dcab9f2daf
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:8613458
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0
# CPU
used_cpu_sys:57.688424
used_cpu_user:193.509784
used_cpu_sys_children:43.484401
used_cpu_user_children:401.411360
used_cpu_sys_main_thread:53.235472
used_cpu_user_main_thread:193.331135
# Modules
module:name=ReJSON,ver=20808,api=1,filters=0,usedby=[search],using=[],options=[handle-io-errors]
module:name=bf,ver=20805,api=1,filters=0,usedby=[],using=[],options=[]
module:name=RedisCompat,ver=1,api=1,filters=0,usedby=[],using=[],options=[]
module:name=search,ver=21015,api=1,filters=0,usedby=[],using=[ReJSON],options=[handle-io-errors]
module:name=redisgears_2,ver=20020,api=1,filters=0,usedby=[],using=[],options=[]
module:name=timeseries,ver=11205,api=1,filters=0,usedby=[],using=[],options=[]
# Errorstats
errorstat_NOAUTH:count=813
# Cluster
cluster_enabled:0
# Keyspace
db1:keys=48993,expires=2,avg_ttl=14166414,subexpiry=0
```

I will replace my redis.pm ASAP and report back.

Thank you

**Comment by tchavei** [comment]
Ok. Replaced the redis.pm file but redis graph remains at 0 although no error in the log file. 

I know it's reading the config because I changed the 'pass' keyword to 'password' and it immediately complained about uninitialized variable. 

Maybe I messed up my config file?

```
<redis>
        list = 0.0.0.0:6379
        rigid = 0, 0, 0, 0, 0, 0
        limit = 1000, 1000, 1000, 1000, 1000, 1000
        user = default
        pass = xyz
</redis>
```

Not sure what else I could be missing...?

**Comment by mikaku** [comment]
Hmm, I assume you have only one configuration file. If you are unsure, check the log file to see if Monitorix is loading an extra configuration file.

The snippet you pasted looks good to me.
Let's see what says on this the author of the auth code.

@abqcheeks can you, please, take a look to this?

**Comment by tchavei** [comment]
I checked the `/etc/monitorix/conf. d` and it's empty.

Log file `/var/log/monitorix`  shows this:

```
Thu May 22 16:18:00 2025 - Starting Monitorix version 3.16.0 (pid 1326186).
Thu May 22 16:18:00 2025 - Loaded main configuration file '/etc/monitorix/monitorix.conf'.
Thu May 22 16:18:00 2025 - Initializing graphs.
Thu May 22 16:18:01 2025 - Generating the 'index.html' file.
Thu May 22 16:18:01 2025 - Started HTTP built-in server (pid 1326289).
Thu May 22 16:18:01 2025 - Ok, ready.
ERROR: Can't get value of subfeature temp3_min: I/O error
ERROR: Can't get value of subfeature temp3_max: I/O error
Thu May 22 16:18:01 2025 - WARNING: the HTTP built-in server has authentication disabled.
HTTPServer: You can connect to your server at http://localhost:8080/
```

The sensor error seems unrelated to this (if you have an idea of how to remove it, I appreciate it) . No other error can be seen.

I also checked what redis / perl packages I have installed:

```
3 aur/perl-redisdb-parser 2.23-1 (+0 0.00) (Installed)
    Redis protocol parser for RedisDB)
2 aur/perl-redisdb 2.57-1 (+0 0.00) (Installed)
    Perl extension to access redis database (RedisDB)
1 aur/perl-redis 2.000-2 (+1 0.00) (Installed)
    Perl binding for Redis database
```

I should mention my redis is dockerized but port 6379 is exposed to the host so it should be irrelevant (unless redis.pm is trying to access some files externally)

Out of ideas right now.

**Comment by abqcheeks** [comment]
@tchavei I don't see anything wrong with your config.  Your test of using a bad password eliminated a lot of possible problems from consideration.  Maybe insert a debug line after line 262 (the "removed DOS format" line):
`                logger("$myself: 'info' result: $data");
`
That should tell us what it's getting back from the "info" command

**Comment by tchavei** [comment]
Hello.

Indeed, providing the wrong password throws this in log file:

```
Thu May 22 18:41:08 2025 - redis::redis_update: AUTH Failed with '0.0.0.0:6379': -WRONGPASS invalid username-password pair or user is disabled.
Thu May 22 18:41:08 2025 - ERROR: while updating /var/lib/monitorix/redis.rrd: /var/lib/monitorix/redis.rrd: expected timestamp not found in data source from N
```

Changing redis.pm as suggested yields the correct info in logs! 

```
Thu May 22 18:48:09 2025 - redis::redis_update: 'info' result: +OK
$6450
# Server
redis_version:7.4.2
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:b648dcb34d0d916f
... 
```
I removed the rest as I already posted the info previously.

So apparently it's working but the data isn't passing to the graph itself?

**Comment by tchavei** [comment]
Update

It somehow started working! I have no explanation for it. I changed no configuration. I've restarted the service with each experiment I posted here and the last thing was adding the debug line.

I'm puzzled and afraid of removing that line now 😂

What a mystery

**Comment by mikaku** [comment]
@abqcheeks, thank you for chiming in.
