### ISSUE TITLE
Allow using sensors (lm_sensors) for gpu[n] key

### ISSUE THREAD

**Issue by jose1711** [mikaku/Monitorix#320]
Currently `gpu0`..`gpu8` in `lmsens` only accept value of `ati` or `nvidia`. My integrated GPU (Ryzen Vega) reports the temperature through `lm_sensors` - see `edge` in the example below.

```
$ sensors
ucsi_source_psy_USBC000:001-isa-0000
Adapter: ISA adapter
in0:           0.00 V  (min =  +0.00 V, max =  +0.00 V)
curr1:         0.00 A  (max =  +0.00 A)
 
nvme-pci-0900
Adapter: PCI adapter
Composite:    +32.9°C  (low  =  -0.1°C, high = +76.8°C)
                       (crit = +79.8°C)
 
amdgpu-pci-0a00
Adapter: PCI adapter
vddgfx:        1.18 V  
vddnb:       993.00 mV 
edge:         +36.0°C  
power1:      1000.00 uW 
 
zenpower-pci-00c3
Adapter: PCI adapter
Tdie:         +47.5°C  (high = +95.0°C)
Tctl:         +47.5°C  
```

Therefore it would be great if `monitorix` allows to define an alternative for situations where GPU temperature shows up in `lm_sensors`.

**Comment by mikaku** [comment]
I've added support to be able to get the temperature from the output of `lm_sensors`. To do it, you need to prefix with `lmsensors:` the temperature name of your graphical card that appears in such output. Just like this:

```
<lmsens>
        <list>
                ...
                gpu0    = lmsensors:edge
        </list>
```

Please, download the latest `lmsens.pm` and let me know if it works for you.

**Comment by jose1711** [comment]
Thank you for this quick fix, works perfectly! Closing.
