### ISSUE TITLE
Cant open Interface 

### ISSUE THREAD

**Issue by masterhacka** [mikaku/Monitorix#321]
Hi there,

I can‘t access the interface: Client sent an HTTP request to an HTTPS server.
With HTTPS I get the following error: {"error":"The required authorization heads were not present in the request."}

what can I do?

**Comment by mikaku** [comment]
I don't recognize such error messages.
You didn't provide any information at all on what tools are you using to get such errors.

**Comment by masterhacka** [comment]
I have installed Pterodactyl on Debian 10. After that I followed these instructions to install Monitorix: https://www.google.de/amp/s/www.howtoforge.de/anleitung/monitorix-berwachungssoftware-unter-debian-10-installieren-und-konfigurieren/amp/

**Comment by mikaku** [comment]
I don't know that Pterodactyl is, sorry.

I suggest you to:

1. check the Monitorix log file to see if there are error messages.
2. execute `systemctl status monitorix` to see if Monitorix is running successfully.
3. execute `ss -ltnp` to see if Monitorix web server listening on the desired network port.

Also, you can test if Monitorix is running correctly by using a simple text browser like `lynx` or `elinks`:
`elinks http://localhost:8080/monitorix/`

**Comment by masterhacka** [comment]
I think I fixed the issue. But there is another Problem: 
![Uploading 41DD2817-4CB8-442A-929E-40108DA3F987.jpeg…]()

**Comment by mikaku** [comment]
This is just a permission problem.
Check the permissions in `/var/lib/monitorix/www/imgs/` directory.

**Comment by masterhacka** [comment]
How can I set it correctly? I am new to this sorry

**Comment by mikaku** [comment]
You didn't provide any information at all, again. It's difficult to help you.

It depends if you are using the default Monitorix HTTP built-in server or a third-party web server (Apache, Nginx, etc.).

If you are using the default HTTP built-in server, the permissions should be good out of the box. Instead, if you disabled the built-in HTTP server in Monitorix, and you are using an external web server to see the Monitorix graphs, then such directory must have enough write permissions to let the user under the web server is running be able to create files there.

**Comment by jose1711** [comment]
> How can I set it correctly? I am new to this sorry

I checked the installation instructions on the webpage you provided and it seems they want you to enable built-in http server. It still would be nice if you could share your part of `monitorix.conf` (`sed -n '1,/graph_enable/p' /etc/monitorix/monitorix.conf | grep -Ev '^(#|$)'`), then under `root`:
```
systemctl stop monitorix
monitorix -c /etc/monitorix/monitorix.conf -d all -n
# wait at least a minute
ctrl-C
# remove sensitive data (if any) and post output here
systemctl start monitorix
```

**Comment by mikaku** [comment]
Closing due to no response for two weeks.

If you still need more information, please add a comment and the issue can be reopened.
