### ISSUE TITLE
Add option to read fan values from nbfc (for notebooks)

### ISSUE THREAD

**Issue by jose1711** [mikaku/Monitorix#325]
NBFC is a cross-platform solution for more modern laptops which are not supported by `lm_sensors`. List of supported notebook models can be found at https://github.com/hirschmann/nbfc/tree/master/Configs. In order to work a running `nbfc` service needs to be running, then the fan status can be queried or config options can be set via `nbfc` command.
This is how the output of `status` command looks on my system:
![obrázok](https://user-images.githubusercontent.com/1406222/114855318-1c6ee280-9de6-11eb-879e-1583df48b7d1.png)

It would be great if `monitorix` supports getting of these values as for some systems this may be the only way how to read fan speeds.

**Comment by jose1711** [comment]
And perhaps a more generic approach (`cmd` as in `ambsens.pm`) would be welcome - since for instance it's quite common to hook up an external fan to GPIO pins a Raspberry Pi and read out RPMs from PWM pulses (https://blog.driftking.tw/en/2019/11/Using-Raspberry-Pi-to-Control-a-PWM-Fan-and-Monitor-its-Speed/#Reading-RPM-Signal).

**Comment by mikaku** [comment]
I don't have any package named `nbfc` in my Fedora system so I'm afraid it will be difficult for me to test your solution.
Other than that, have you check if your laptop supports IPMI?

**Comment by jose1711** [comment]
I understand IPMI as a server-only feature, tried installing `ipmiutil` and got `Can't find SMBIOS address entry point.` Therefore I believe my hw lacks these capabilities.

Note that I am not exactly happy I need to install `mono` runtime just to get an information about fan speed. Arch Linux's [`PKGBUILD`](https://aur.archlinux.org/packages/nbfc/) is only a handful of commands that run some `mono` commands. In any case I can perhaps help with testing - just drop me a PM and I can setup an SSH account for you (regular user rights are enough to take a reading).

**Comment by mikaku** [comment]
I think I could add fan support to `gensens.pm` which already supports the following values: temperatures, CPU scaling frequencies and battery status. This graph takes the values by reading directly the contents of a file (without any parsing).

So you just need to create a `cron` script to periodically fetch the fan values using `nbfc` and redirect them to a file:

```
$ nbfc status -f | grep "Current fan speed" | awk '{print $NF}' > /tmp/current.fan
$ nbfc status -f | grep "Target fan speed" | awk '{print $NF}' > /tmp/target.fan
```

Then, in the `<gensens>` section you'd create the following setup:

```
<gensens>
        <list>
                0 = fan0, fan1
        </list>
        <title>
                0 = Fan
        </title>
        <desc>
                fan0 = /tmp/current.fan
                fan1 = /tmp/target.fan
        </desc>
        <unit>
                fan0 = 1
                fan1 = 1
        </unit>
        <map>
                fan0 = Current
                fan0 = Target
        </map>
        <alerts>
        </alerts>
        rigid = 0
        limit = 100
</gensens>
```

**Comment by jose1711** [comment]
Thank you, Jordi. That would certainly work, however there's this aesthetic things that.. if we already have a dedicated graph showing temperatures and fans why have it blank and instead use a separate section for it.
 
![obrázok](https://user-images.githubusercontent.com/1406222/118642264-6e3acc00-b7db-11eb-8aaa-83b58840ca4e.png)

**Comment by mikaku** [comment]
> ... if we already have a dedicated graph showing temperatures and fans why have it blank and instead use a separate section for it.

This is a dedicated lm_sensors graph. If you think you can pass-through the output of `nbfc` to the lm_sensors then you're done. Otherwise, you need a different graph.

**Comment by jose1711** [comment]
I hear what you're saying. What would you say to adding a new option to specify a custom `sensors` command that could wrap (or emulate) the real one. I made a really simple example called `sensors2`:
```
#!/bin/bash
echo "fan0: $(nbfc status | awk '/Current fan speed/{print $NF}') RPM"
exec sensors
```

Then I modified `lmsens.pm` to support a new option `sensors_cmd` which could override the default `sensors`: https://github.com/jose1711/Monitorix/commit/b80138c7098e6278cdddebe27b54faa772c54462

and of course updated the config:
```
<lmsens>
        sensors_cmd = /usr/bin/sensors2
        <list>
        fan0 = fan0
..
```

Now I get the values in (slightly hacked) `LM-sensors` graph:
![obrázok](https://user-images.githubusercontent.com/1406222/118727046-78d48000-b832-11eb-8923-0f98fa665b4f.png)

**Comment by mikaku** [comment]
That's a great idea, I'll work in this new `cmd` option for `lmsens.pm`, which will default to `sensors` if no value is specified (too keep backwards compatibility).

**Comment by mikaku** [comment]
Please, check the latest `lmsens.pm` which adds support for the new `cmd` option.

**Comment by jose1711** [comment]
Thank you @mikaku, I can confirm that `cmd` is working! 

here is one thing though - not exactly important but I'll share anyway: `nbfc` reports fan values as percentage (100 % = full power), `monitorix` only understands RPM values. But it's just about the name of the axis, so not sure if you want to plan any changes to it.

**Comment by mikaku** [comment]
I think I could create a prefix in the Fan values to specify between `rpm:` or `percent:`, being the former optional since it's the default value (to keep backwards compatibility).

Following your example above, it would be something like this:

```
<lmsens>
        sensors_cmd = /usr/bin/sensors2
        <list>
        fan0 = percent:fan0
..
```

If Monitorix detects the `percent:` prefix it will limit the scale of the graph from 0 to 100 and set the y-axis title as **Percent (%)**.

**Comment by jose1711** [comment]
> I think I could create a prefix in the Fan values to specify `rpm:` or `percent:`, being the former optional since it's the default value (to keep backwards compatibility).

Thank you, that sounds great.

**Comment by mikaku** [comment]
Hmm, I realized that it could be cases with mixed RPM and percentage fans and so it would generate a confuse graph.

So, I think it's better to keep the y-axis as `RPM` and, in the case that a fan has the prefix `percent:`, just add the symbol `%` right after its value.

**Comment by mikaku** [comment]
Check the latest `lmsens.pm`.

**Comment by jose1711** [comment]
Thank you, tested and '%' in the fan label works for me.

**Comment by mikaku** [comment]
Thanks, closing.

**Comment by jose1711** [comment]
Thank YOU very much for implementing this!
