### ISSUE TITLE
How to reference sensors when name is not unique?

### ISSUE THREAD

**Issue by jose1711** [mikaku/Monitorix#327]
`Sensors` command on one of my systems shows:
```
ucsi_source_psy_USBC000:002-isa-0000
Adapter: ISA adapter
in0:           0.00 V  (min =  +0.00 V, max =  +0.00 V)
curr1:         0.00 A  (max =  +0.00 A)

iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +67.0°C  

BAT0-acpi-0
Adapter: ACPI interface
in0:           7.60 V  

ucsi_source_psy_USBC000:001-isa-0000
Adapter: ISA adapter
in0:           0.00 V  (min =  +0.00 V, max =  +0.00 V)
curr1:         0.00 A  (max =  +0.00 A)

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +58.0°C  (high = +105.0°C, crit = +105.0°C)
Core 0:        +57.0°C  (high = +105.0°C, crit = +105.0°C)
Core 1:        +57.0°C  (high = +105.0°C, crit = +105.0°C)
Core 2:        +57.0°C  (high = +105.0°C, crit = +105.0°C)
Core 3:        +57.0°C  (high = +105.0°C, crit = +105.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +58.0°C  (crit = +95.0°C)
```

As can be observed in the output above both `in0` and `temp1` are not-unique. How should I refer to them in `lmsens` section? Currently it seems that last one wins.

**Comment by mikaku** [comment]
You can't do it in Monitorix, this is something you must change in the LM_sensors output.

Fortunately this was already covered in #131 (as [this](https://www.monitorix.org/faq.html#Q125) FAQ states).

**Comment by jose1711** [comment]
Thank you, that indeed helped. Maybe.. since this question tends to repeat itself - can you consider adding a note to the documentation?

**Comment by mikaku** [comment]
Now with the FAQ and the added note I hope that people will find it easier.  :smiley:

**Comment by jose1711** [comment]
Thank you! Closing.
