### ISSUE TITLE
Add short info what is the standard port and url to https://www.monitorix.org/

### ISSUE THREAD

**Issue by soerendip** [mikaku/Monitorix#329]
I installed the program a while ago and it is still running on my server, however, I forgot the port and path to access it. Now, I cannot find that information on that web page. https://www.monitorix.org/ 

Would be nice to have it as one of the first things after the installation. I am sure it is somewhere obvious.

**Comment by Saentist** [comment]
what about 
```netstat -lpnt | grep monitorix```
or read config file in /etc/monitorix ?

**Comment by mikaku** [comment]
Yes, besides the suggestions from @Saentist, you can read the [documentation](https://www.monitorix.org/documentation.html#3) to know that the default network port is 8080.

**Comment by soerendip** [comment]
Yes, of course.

**Comment by mikaku** [comment]
I think I could change the second part of the second paragraph in the homepage of the website to something like this:

*Monitorix includes its own HTTP server built in (which is listening by default on port 8080/TCP) to see the statistics graphs, so you aren't forced to install a third-party web server to use it.*

Do you think that would suffice?

**Comment by soerendip** [comment]
I appreciate that you take my suggestion into account. I think the complete URL http://localhost:8080/monitorix would be best as it is specific.

________________________________

**Comment by mikaku** [comment]
I see, perhaps something like this?

**Monitorix includes its own HTTP server built in (which is listening by default on port 8080/TCP) to see the statistics graphs, so you aren't forced to install a third-party web server to use it. Just point your browser to `http://localhost:8080/monitorix`.*

**Comment by soerendip** [comment]
Looks fantastic.

**Comment by mikaku** [comment]
OK, changes are made.
Thanks.
