### ISSUE TITLE
Respect max number of nvidia cards value also for CPU and memory usage

### ISSUE THREAD

**Issue by bachandi** [mikaku/Monitorix#330]
The {max} variable already used for the temperature legend should also be used for CPU and memory usage legend.

https://github.com/mikaku/Monitorix/blob/0ed93455e243fd15ec03010084b22dac32435055/lib/nvidia.pm#L567

**Comment by mikaku** [comment]
Please, download the latest `nvidia.pm` and let me know if it appears as expected.
Thanks.

**Comment by bachandi** [comment]
Works perfect. Thanks
