### ISSUE TITLE
Add time_unit for uptime graph (`system.pm`)

### ISSUE THREAD

**Issue by jose1711** [mikaku/Monitorix#331]
It would be nice if uptime graph inside `System load average and usage` supports a `time_unit` as specified in #311. This would be useful for systems that are normally running only couple hours a day (desktops/notebooks).

**Comment by mikaku** [comment]
Please, download the latest `system.pm` and let me know if it fits your needs.

**Comment by jose1711** [comment]
Thank you, works perfectly! Closing.
