### ISSUE TITLE
nvidia-smi has also fan information. It would be nice to have that also as graph in the nvidia info.

### ISSUE THREAD

**Issue by bachandi** [mikaku/Monitorix#333]
https://github.com/mikaku/Monitorix/blob/9b28b53374fe39038b55d34d6d6c200348de42d3/lib/nvidia.pm#L199

**Comment by jose1711** [comment]
I like the idea. Here's how it looks on my system:
![obrázok](https://user-images.githubusercontent.com/1406222/119048643-cc280900-b9bf-11eb-8727-45ceca2bb25e.png)

Also note that according to `nvidia-smi` man page:
![obrázok](https://user-images.githubusercontent.com/1406222/119048752-f1b51280-b9bf-11eb-88df-93fa7656ba88.png)
