### ISSUE TITLE
After installing monitorix each time I enable ufw no "accept" rule is working

### ISSUE THREAD

**Issue by bigretromike** [mikaku/Monitorix#336]
I tried both repo version and *.deb version, but I end up with both version doing the same.
It could be a UFW issue, but this start to happend just after installing monitorix.

Each time I enable ufw that got "allow" rules for ssh/www/dns the connection is blocked.

Is monitorix compatible with UFW ?

**Comment by mikaku** [comment]
What is UFW?

**Comment by Saentist** [comment]
> What is UFW?

https://help.ubuntu.com/community/UFW

**Comment by mikaku** [comment]
> https://wiki.ubuntu.com/UncomplicatedFirewall

Uncomplicated? OK

Monitorix adds some `iptables` rules for each port defined in order to be able to gather traffic statistics and accounting. These rules are completely safe and doesn't deny or block any network packet.

You can see these added rules by executing `iptables -nxvL | grep monitorix`.

**Comment by bigretromike** [comment]
@mikaku 
I saw it added rules via iptables, which is fine - and needed, but after installing monitorix while having UFW enabled it entire firewall get messed up and deny any incoming connection.

@Saentist 
That is the answer I was looking for to see, I switched to pure iptables just to use monitorix and not get nuked at internet ;-)

I think I can close the issue, if it would be a good use to "ufw is not supported" then people reopen it
