### ISSUE TITLE
Safari password manager does not recognise the authentication method.

### ISSUE THREAD

**Issue by bachandi** [mikaku/Monitorix#337]
It would be nice if the safari password manager would be usable with the authentication method. At the moment we always have so manually select the password.
This is probably related to the method the password is requested.

**Comment by mikaku** [comment]
The [Basic Access Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) is a well-known standard HTTP method.
The fact that it is not working on a specific browser is really related to Monitorix?

**Comment by mikaku** [comment]
IIRC, the concept of *logout* does not exist in Basic Authentication, you just need to point your browser to somewhere in the same host where you don't have access. Also, just closing the browser is enough to lose the access credentials.
