### ISSUE TITLE
cmd in ambsens should be able to have arguments

### ISSUE THREAD

**Issue by bachandi** [mikaku/Monitorix#343]
https://github.com/mikaku/Monitorix/blob/1d855aa04c9e858844c602cbb8a8c4dd9e17497b/lib/ambsens.pm#L181
At the moment it is not possible to pass arguments to scripts in the "cmd" arguments of ambsens. It would be really useful to being able to passt command line arguments as it is possible in other "cmd" options like libvirt.

**Comment by mikaku** [comment]
Not a bad idea, in the mean time you can symlink each script with a different name and use that name to execute a third script with specific arguments.

```
<ambsens>
        list = Ambient Temperature
        <desc>
                0 = at1
                1 = at2
        </desc>
        <units>
                0 = Celsius
        </units>
        <cmd>
                at1 = /usr/bin/script_at1.sh
                at2 = /usr/bin/script_at2.sh
        </cmd>
        ...
```
`# ln -s /usr/bin/script_generic.sh /usr/bin/script_at1.sh`
`# ln -s /usr/bin/script_generic.sh /usr/bin/script_at2.sh`

script_generic.sh
-----------------------

```
#!/bin/bash

name=$(basename $0)

case "$name" in

	"script_at1.sh")
		echo exec script1.sh arg1 arg2
		;;
	
	"script_at2.sh")
		echo exec script2.sh arg3 arg4 arg5
		;;
esac
```

**Comment by bachandi** [comment]
Nice idea for the moment.
