### ISSUE TITLE
Why are the units handled only in powers of 10?

### ISSUE THREAD

**Issue by bachandi** [mikaku/Monitorix#346]
https://github.com/mikaku/Monitorix/blob/ac1dda2b1907616c996dc1de99bf8d5348476f66/lib/gensens.pm#L155-L158
Is there a reason for handling the units only in powers of 10? The values could also be in different units like from 0 to 255. 
Couldn't this be switched to a normal division of the value by the unit? 

```
$unit = $gensens->{unit}->{$str} || 0;
$val /= $unit if $unit > 0;
```
This should work like the old version but be more versatile to different scalings.

**Comment by mikaku** [comment]
> Is there a reason for handling the units only in powers of 10?

Not actually. I can't remember an specific reason for this. Perhaps I was using values only in powers of 10 while testing and I ended-up focusing the code for them.

> Couldn't this be switched to a normal division of the value by the unit?

Yes of course.
A normal multiplication would be more natural though. The problem is that this would break backwards compatibility.

**Comment by bachandi** [comment]
> Yes of course.
> A normal multiplication would be more natural though. The problem is that this would break backwards compatibility.
Indeed but I don't think braking backwards compatibility for this is worth it.
