### ISSUE TITLE
Axis scaling for first ipmi graph is off.

### ISSUE THREAD

**Issue by bachandi** [mikaku/Monitorix#351]
When using `rigid` 0 the first ipmi graph has a suboptimal scaling. The others scale nicely but the first one.
First impi graph has too much space on top of the highest data points (rigid 0):
![ipmi0 1hour](https://user-images.githubusercontent.com/62039342/134985493-7bf288a0-e6a8-4a2c-8145-6d546f9d4e9e.png)
Somehow this only affects the first graph.

And it is not possible to just set fixed axis for the first graph as impi.pm only allows a single `rigid` value for all graphs. May this could be changed to have an array of `rigid` and `limit` value as in other classes?
https://github.com/mikaku/Monitorix/blob/41c14beba6168c6f34082c8924261cd6fea59059/lib/ipmi.pm#L364

**Comment by mikaku** [comment]
Hmm, it looks like this module only admits a unique value for `rigid` and `limit` options for all the graphs.

Please, try moving the line 364 to just above the line 378 and then change the two zeros by `$n`. Your code should look like this:

```
        }

        $n = 0;
        while($n < scalar(my @sl = split(',', $ipmi->{list}))) {
                if($title) {
                        if($n == 0) {
                                push(@output, main::graph_header($title, $ipmi->{graphs_per_row}));
                        }
                        push(@output, "    <tr>\n");
                }
                for($n2 = 0; $n2 < $ipmi->{graphs_per_row}; $n2++) {
                        last unless $n < scalar(my @sl = split(',', $ipmi->{list}));
                        if($title) {
                                push(@output, "    <td>\n");
                        }
                        @riglim = @{setup_riglim($rigid[$n], $limit[$n])};
                        undef(@tmp);
                        undef(@tmpz);
                        undef(@CDEF);
```

and let me know if it now works as expected.

**Comment by bachandi** [comment]
Sadly it does not help. The first plot still has the strange axis scaling the after your change also the second.

Before (rigid=0, limit=10):
<img width="640" alt="Bildschirmfoto 2021-09-29 um 17 36 56" src="https://user-images.githubusercontent.com/62039342/135302113-2c3aa2dd-3bb0-455c-a9ee-759ae762e0c5.png">

After (rigid=0, limit=10):
<img width="640" alt="Bildschirmfoto 2021-09-29 um 17 36 06" src="https://user-images.githubusercontent.com/62039342/135302080-649b3522-945d-4610-9c51-06a43a933dae.png">

**Comment by mikaku** [comment]
Please, paste the configuration of your `<ipmi>` and let me know what exactly do you want to see in the first graph.

Have you read the section `rigid and limit values` in the documentation?

**Comment by bachandi** [comment]
I have set it to:
```
rigid = 0
limit = 10
```
I just want automatic axis range scaling. So a reasonable y-axis range. I would expect the first ipmi plot to have an upper axis value of about 13-14 Volts and not 20 Volts. 
I don't actually want the `limit` value but without it (only rigid = 0) in the ipmi config, the y-axis of all plots start at 0 (with the upper value correctly scaled except for the first plot) so I just set it to an arbitrary number. 
With this setting all plots except the first one scale the y-axis correctly.

**Comment by mikaku** [comment]
>  I would expect the first ipmi plot to have an upper axis value of about 13-14 Volts and not 20 Volts.

With `rigid = 2` and `limit = 14` you can set a top on the y-axis scaling. But it will be fixed regarding the values in graph.

Y-axis scaling is made automatically by RRDtool depending the on the values plotted. There are different options in RRDtool to tune your graphs [here](https://oss.oetiker.ch/rrdtool/doc/rrdgraph.en.html). You can include any number of RRDtool options in the Monitorix option `rrdtool_extra_options` to help to tune your graphs.

**Comment by bachandi** [comment]
Thanks for the hint with `rrdtool_extra_options`. "--alt-autoscale" did the trick but it distorts other plots I will just set it to a fixed axis range.

**Comment by mikaku** [comment]
> Any reason why there is only one rigid settings for all ipmi plots?

The option `rigid` accepts a list of values separated by comma. Each value belongs to its corresponding graph.
In the following example, the first graph will have a `rigid` value of 2 and the second graph 0.

```
rigid = 2, 0
```

**Comment by bachandi** [comment]
Yes but I think your fix is missing in ipmi.pm to actually use these list values and not just the first one:
https://github.com/mikaku/Monitorix/issues/351#issuecomment-929954806

**Comment by mikaku** [comment]
> Yes but I think your fix is missing in ipmi.pm to actually use these list values and not just the first one.

Ah yes, I don't remember the reason why is like that. Probably a bug coming from the graph that I reused it to create this one.
