### ISSUE TITLE
Memory leak in ipmi.pm

### ISSUE THREAD

**Issue by bachandi** [mikaku/Monitorix#356]
When having ipmi plots enabled monitorix starts to increase its memory consumption continuously after some time:
<img width="570" alt="Bildschirmfoto 2021-10-09 um 16 07 17" src="https://user-images.githubusercontent.com/62039342/136661824-e4ba088c-ba4b-43d2-9414-c3393f0fcec4.png">

Without the ipmi plots the memory consumption is stable with minor fluctuations:
<img width="571" alt="Bildschirmfoto 2021-10-09 um 11 41 53" src="https://user-images.githubusercontent.com/62039342/136661827-95565a6f-f418-4258-b187-a78c17e23969.png">

The memory consumption keeps increasing and does not seem to stop. I could not figure out the reason as I am not so familiar with perl memory management. Any idea why this happens? I tried disabling some ipmi plots but did not succeed in fixing the problem. Also it is a bit random when it begins to increase some times directly after launch some times it takes 1-2 hours but when it is increasing it does not stop anymore.

**Comment by mikaku** [comment]
I've never seen a memory leak issue in Monitorix. In fact, I think that it's pretty unlikely to see as it relies on the interpretation of Perl language.

>It is probably related to a memory leak in my perl version.

Yes, that seems more reasonable.
Thanks.
