### ISSUE TITLE
System memory allocation plot should have consistent byte units.

### ISSUE THREAD

**Issue by bachandi** [mikaku/Monitorix#362]
The memory units should be consistent. At the moment the title has decimal units and the y-axis labels binary byte units. 
It would be nice to have consistent decimal units.

<img width="640" alt="Bildschirmfoto 2021-11-16 um 13 41 14" src="https://user-images.githubusercontent.com/62039342/141987427-b886bf42-c86c-4c36-b7dc-2a7695f1bb9e.png">

**Comment by mikaku** [comment]
Sorry, I don't understand your suggested change.

According to the [RRDtool Documentation](https://oss.oetiker.ch/rrdtool/doc/rrdgraph.en.html), the option `--base` must be set to 1024 if we are graphing memory values (as they are represented as KiB, MiB, GiB, etc.):

```
[-b|--base value]

If you are graphing memory (and NOT network traffic) this switch should be set to
1024 so that one Kb is 1024 byte. For traffic measurement, 1 kb/s is 1000 b/s.
```

**Comment by bachandi** [comment]
After looking through the system.pm code the numbers are consistent. I thought the title to be actually MB instead of MiB. But as the plot labels don't mention MiB and GiB this could also be considered consistent.

**Comment by bachandi** [comment]
It is still a bit confusing that the title says `MB` instead of `MiB` and also the axis labels do not mention that this has binary units. 

How about changing the title to `MiB` instead of `MB`? 
For RRDTool I didn't find any option to display the base value somehow in the graph or use `Ki`, `Mi`, `Gi` as units in case of base 1024.

Alternatively axis labels and title could be switched to SI units.
