### ISSUE TITLE
Health and usage monitor for amdgpu devices.

### ISSUE THREAD

**Issue by bachandi** [mikaku/Monitorix#367]
A health and usage monitor for amdgpu devices would be nice to have.

Using the hwmon interface of the amdgpu driver I would propose to add something like this:
<img width="573" alt="Bildschirmfoto 2021-12-08 um 08 44 38" src="https://user-images.githubusercontent.com/62039342/145168999-2f091205-d115-48d0-978f-4273f5066f1d.png">

**Comment by mikaku** [comment]
I see some points that should be fixed:

1. the values in `list` must be treated as a simple key of information or description, it should not be, in any case, a necessary complement to other values, like in `sensors`. I mean, the paths in `sensors` must be absolute. In fact, this is not even covered in the man page you wrote.

Something like this:

```
<amdgpu>
	<list>
		0 = amd-w6800, amd-wx5100
	</list>
[...]
	<sensors>
		amd-w6800 = /dev/device/gpu_busy_percent, /dev/device/mem_busy_percent, ...
		amd-wx5100 = /dev/device/gpu_busy_percent, /dev/device/mem_busy_percent, ...
	</sensors>
```

2. Forcing to put `N/A` if the sensor doesn't exist seems a bit tricky. I'd prefer to omit the value but still respecting the position in the list with a comma. What do you think?
3. I see some indentation problems, but is not critical and can be fixed later once merged.

**Comment by mikaku** [comment]
What is the purpose of the following lines?

- https://github.com/mikaku/Monitorix/blob/a2008d488e39437fe689f15227b7154a005ba5f9/lib/amdgpu.pm#L248
- https://github.com/mikaku/Monitorix/blob/a2008d488e39437fe689f15227b7154a005ba5f9/lib/amdgpu.pm#L262

**Comment by bachandi** [comment]
> What is the purpose of the following lines?
> 
> * https://github.com/mikaku/Monitorix/blob/a2008d488e39437fe689f15227b7154a005ba5f9/lib/amdgpu.pm#L248
> * https://github.com/mikaku/Monitorix/blob/a2008d488e39437fe689f15227b7154a005ba5f9/lib/amdgpu.pm#L262

You are right, that is a bit superfluous. Sorry I missed it, it was a copy & paste regression from:
https://github.com/mikaku/Monitorix/blob/3bb03e983bc855214aa636311846e14d71f273fe/lib/disk.pm#L271

Also nvme.pm has these lines. As they don't do anything they could just be removed everywhere?

**Comment by mikaku** [comment]
Yeah, I figured it was related to a copy & paste. I'll remove them.

> Also nvme.pm has these lines. As they don't do anything they could just be removed everywhere?

Same.
Thanks!

**Comment by bachandi** [comment]
Thanks.

**Comment by mikaku** [comment]
@bachandi, you last commit made me think that I misunderstood those `if` lines as they format was not correctly indented.
These lines must be read it in inverse order.

I'll will revert my previous commit and will include again these lines with a correct indentation.

**Comment by bachandi** [comment]
Yes sorry. Was just about to push the changes. Either use my PR#372 or reject it and commit it your self. The formatting was a bit misleading when just looking at the lines.

**Comment by mikaku** [comment]
Yes, I've just saw your #372. Go to merge it right now.
Thank you very much, and sorry for the confusion.

**Comment by bachandi** [comment]
Thanks.
