### ISSUE TITLE
Perl version on CentOS 7 seems to have an issue with a recent change to `lib/du.pm`

### ISSUE THREAD

**Issue by hummeltech** [mikaku/Monitorix#378]
I discovered this while adding basic sanity checking in #377

I believe this is where the issue is coming from, it seems to have been introduced in #353:
https://github.com/mikaku/Monitorix/blob/cb1802e26e559d365ca9d310fea4e40977fffcd4/lib/du.pm#L71

The `Perl` version is `v5.16.3`:

Here is a snippet from the output (full output can be found [here](https://github.com/hummeltech/Monitorix/runs/4613288549?check_suite_focus=true)):
```
 Variable "@min" is not imported at lib/du.pm line 105 (#1)
    (W misc) With "use strict" in effect, you referred to a global variable
    that you apparently thought was imported from another module, because
    something else of the same name (usually a subroutine) is exported by
    that module.  It usually means you put the wrong funny character on the
    front of your variable.
    
	(Did you mean &min instead?)
Variable "@max" is not imported at lib/du.pm line 106 (#1)
	(Did you mean &max instead?)
Variable "@min" is not imported at lib/du.pm line 131 (#1)
	(Did you mean &min instead?)
Variable "@max" is not imported at lib/du.pm line 135 (#1)
	(Did you mean &max instead?)

syntax error at lib/du.pm line 71, near "$info{"
```

**Comment by mikaku** [comment]
Nice found!, looks like older Perl versions don't like this kind of hash references to a scalar variable.
@bachandi,  better use `${$info}{$key}`.

**Comment by mikaku** [comment]
@hummeltech, I've just patched `du.pm` in order to use a more portable Perl code.
The errors should be gone now.

**Comment by hummeltech** [comment]
Thanks, [that](https://github.com/hummeltech/Monitorix/actions/runs/1616131597) seems to have resolved the issue!

**Comment by hummeltech** [comment]
Thanks @mikaku!
