### ISSUE TITLE
Fail2Ban stats stopped working

### ISSUE THREAD

**Issue by yarik2720** [mikaku/Monitorix#379]
Fail2Ban stats are empty, but at least at one of them there are bans now

OS: Ubuntu 16.04 LTS
Monitorix version: 3.13.1
Fail2ban version: 0.11.1

monitorix config:
```
# FAIL2BAN graph
# -----------------------------------------------------------------------------
<fail2ban>
	list = Web, Security
	<desc>
		0 = [nginx-http-auth], [wordpress-hard], [wordpress-soft], [mysqld-auth]
		1 = [sshd]
	</desc>
	graphs_per_row = 2
	graph_mode = absolute
</fail2ban>
```

fail2ban enabled jails:
```
fail2ban-client status
Status
|- Number of jail:      5
`- Jail list:   mysqld-auth, nginx-http-auth, sshd, wordpress-hard, wordpress-soft
```
Monitorix log:
```
Can't exec "fail2ban-client": No such file or directory at /usr/lib/monitorix/fail2ban.pm line 153.
Can't exec "fail2ban-client": No such file or directory at /usr/lib/monitorix/fail2ban.pm line 153.
Can't exec "fail2ban-client": No such file or directory at /usr/lib/monitorix/fail2ban.pm line 153.
Can't exec "fail2ban-client": No such file or directory at /usr/lib/monitorix/fail2ban.pm line 153. 
```
After editing 153 line of fail2ban.pm file to use command from full location path `/usr/local/bin/fail2ban-client` stats became work. Why using fail2ban-client without path failed? I able to use it without entering full path
```
# whereis fail2ban-client
fail2ban-client: /usr/local/bin/fail2ban-client /usr/share/man/man1/fail2ban-client.1
```

**Comment by mikaku** [comment]
> Why using fail2ban-client without path failed?

Monitorix uses the default `$PATH` in your system. Your user 'root' has that extra path probably because it was been configured in `.bashrc` or `.bash_profile`.

If you don't know how to fix this in your system, try modifying the init script that starts/stops Monitorix.

**Comment by mikaku** [comment]
Closing due to no response for two weeks.

If you still need more information, please add a comment and the issue can be reopened.
