### ISSUE TITLE
Feature Request for MongoDB Support

### ISSUE THREAD

**Issue by jacobamey** [mikaku/Monitorix#38]
Hi Jordi,

Any chance of getting some MongoDB monitoring support added to Monitorix?

More then willing to be a test dummy :-)

**Comment by mikaku** [comment]
Hi,

I've been working on this in the past weeks and this is what I have right now:

![mongodb](https://cloud.githubusercontent.com/assets/829885/21845698/e826aa74-d7f3-11e6-83cd-19e0de248906.png)

The new `mongodb.pm` module supports monitoring of unlimited number of MongoDB servers, either locally or remotely.

That module uses the command `serverStatus` to gather overall statistics of each MongoDB server. It collects the following information:

- uptime (**not plotted in graph, useful?**)
- Asserts (the sum of all of them)
- backgroundFlushing
   - average_ms
   - last_ms
- connections
   - current
   - totalCreated
- dur (**not plotted in graph, useful?**)
   - commits
   - journaledMB
   - writeToDataFilesMB
- extra_info (**not plotted in graph, useful?**)
   - heap_usage_bytes
   - page_faults
- globalLock (**not plotted in graph, useful?**)
   - globalLock.currentQueue
   - globalLock.activeClients
- network
   - bytesIn
   - bytesOut
   - numRequests
- opcounters
   - insert
   - query
   - update
   - delete
   - getmore
   - command
- metrics.document
   - deleted
   - inserted
   - returned
   - updated

That module is also able to monitor an unlimited number of databases per each MongoDB server. It uses the command `dbStats` to gather statistics of each one. It collects the following information:

- collections
- objects (**not plotted in graph, useful?)
- dataSize
- storageSize
- numExtents
- indexes
-fileSize

In the screen shot attached you can see the statistics of a *very-low activity* local MongoDB server, and the statistics of a database called `Test1`. If more databases are monitored they will appear stacked at the end.

Thoughts?

**Comment by mikaku** [comment]
This is done in 0fdc7f2f6008d65113e505aa5e8e33f34f00375c.

**Comment by aularon** [comment]
Hello,
When will a new version that includes this be released?
Thanks!

**Comment by mikaku** [comment]
@aularon,

I have no specific schedule for every version, so I can't tell you when it will be released.
I'd like to include some new things in the current devel version before releasing it.

**Comment by riddhik84** [comment]
I configured Mongodb graph and when I open the url I am able to see the mongodb tables. However, I see no data in the graphs. Do I need to configure username, password of the db also on monitorix.conf file?

I have installed mongodb and monitorix on the same linux box.

Below the configuration:
<mongodb>
	list = localhost
	max_db = 1
	<desc>
		<localhost>
			host = 127.0.0.1
			db_list = <dbname>
		</localhost>
	</desc>
	rigid = 0, 0, 0, 0, 0, 0, 0, 0
	limit = 100, 100, 100, 100, 100, 100, 100, 100
</mongodb>

**Comment by mikaku** [comment]
You should specify in the option `db_list =` the database name(s) that you want to monitor.

**Comment by riddhik84** [comment]
Yes I have specified it.
I changed it like below and then restarted service but does not work.

<mongodb>
	list = localhost
	max_db = 1
	<desc>
		<localhost>
			host = <IP address of the mongo db.. not 127.0.0.1>
			port = 27017
			db_list = <mydbname>
		</localhost>
	</desc>
	rigid = 0, 0, 0, 0, 0, 0, 0, 0
	limit = 100, 100, 100, 100, 100, 100, 100, 100
</mongodb>

Where can I specify credentials like username and password to connect to mongodb?

**Comment by riddhik84** [comment]
I have removed the formatting because somehow it does not allow me to post with formatting

**Comment by riddhik84** [comment]
```
<mongodb>
	list = localhost
	max_db = 1
	<desc>
		<localhost>
			host = dbIP
			port = 27017
			db_list = dbname
		</localhost>
	</desc>
	rigid = 0, 0, 0, 0, 0, 0, 0, 0
	limit = 100, 100, 100, 100, 100, 100, 100, 100
</mongodb>

```

**Comment by mikaku** [comment]
I'm afraid the only options I implemented were `host`, `port` and `db_list`, I'm sorry.

I'll include in my ToDo list to add the options `username` and `password`, but you should create a new issue for this, and leave this issue closed as it is.

Meanwhile, and as workaround, I think you could hack the `port` option like this:

```
port = "27017  --username <username>  --password <secret>"
```

I hope that helped you.

**Comment by riddhik84** [comment]
```
<mongodb>
	list = localhost
	max_db = 1
	<desc>
		<localhost>
			host = dbIP (not 127.0.0.1)
			port = "27017 --username=username --password=password"
			db_list = dbname
		</localhost>
	</desc>
	rigid = 0, 0, 0, 0, 0, 0, 0, 0
	limit = 100, 100, 100, 100, 100, 100, 100, 100
</mongodb>
```
Updated like this in my conf file.. .. and will check if that works. 

Also I will raise another issue for this.

**Comment by mikaku** [comment]
> Updated like this in my conf file.. .. and will check if that works.

OK, just let me know.

> Also I will raise another issue for this.

Perfect! :+1:

**Comment by riddhik84** [comment]
I went thru all the stats in serverStatus output of MongoDB. I find below also useful in graph if possible:

```
**globalLock (not plotted in graph, useful?)**
globalLock.currentQueue
globalLock.activeClients

```
Can I raise separate issue for that?

**Comment by mikaku** [comment]
> Can I raise separate issue for that?

Yes, of course, but please be as much detailed as possible of how to gather this statistic value.
Thanks.
