### ISSUE TITLE
Why is the graph_name config option special?

### ISSUE THREAD

**Issue by bachandi** [mikaku/Monitorix#383]
I could not find any documentation why the `graph_name` option is treated special when reading config files from `conf.d`. I tried to rearrange the plots via a local config file but only manage to get duplicated plots. 

https://github.com/mikaku/Monitorix/blob/dccf48bad59bffe5c69b531fa66f35f7b9fd82f0/monitorix.cgi#L292-L295

Why is the graph_name config option special?

Or is this used to add custom pm-files without having to write also all the others?

**Comment by mikaku** [comment]
Hmm, those lines should be commented as in `monitorix`:

https://github.com/mikaku/Monitorix/blob/7d3f2383ee816f4092ff63cb7780a0bcc7b3d549/monitorix#L604-L609

**Comment by bachandi** [comment]
So `graph_name` is also actually meant to behave the same as the other options, right?

**Comment by mikaku** [comment]
Thanks.
