### ISSUE TITLE
Directory usage and disk temp shows as 0 when not accessible or when offline

### ISSUE THREAD

**Issue by H-Sachse** [mikaku/Monitorix#399]
I noticed that the directory usage and disk temperature graphs treat a time period when no data is available, e.g. because the disk/directory is missing or when the computer is offline as 0 instead of nan.
this makes the graphs behave strangely, showing dips in the curves.

**Comment by mikaku** [comment]
Can you, please, paste an image to see that effect?

**Comment by H-Sachse** [comment]
There you go:
![image](https://user-images.githubusercontent.com/67382933/153908984-41cd2c43-b9bc-4dc0-9120-35b02b304f24.png)
![image](https://user-images.githubusercontent.com/67382933/153909385-e6eb85b7-b047-4cdd-baa4-eaab687c960d.png)
On Friday 11th I took the drive enclosure offline to add a 3rd disk.

And here's one for the drive temps from another system, which I had just enabled:
![image](https://user-images.githubusercontent.com/67382933/153911625-9ce343f8-7773-4582-b41b-b6d8a233cf63.png)
sda is present, sdb is not there. I'd expect a nan for the missing drive.

**Comment by mikaku** [comment]
I guess the two upper graphs are correct and the third is missing the values of /dev/sda.
Please, paste here your current `<disk>` section so I can see the options you have defined.

**Comment by H-Sachse** [comment]
Here's the graphs with some directories unavailable:
![image](https://user-images.githubusercontent.com/67382933/154123816-9f31e23f-a3a2-47ab-a8e9-a3205e015237.png)
I suppose it is `du`'s fault for stating a zero size even if the directory doesn't exist or the symlink given in the argument is dead. All the "directories" given are symlinks into different mounts.

and with an fs unavailable:
![image](https://user-images.githubusercontent.com/67382933/154123884-adfd6f2a-fd97-473f-884d-0e14b74a4725.png)
is `df` used for the fs usage graphs?

**Comment by H-Sachse** [comment]
I just saw that the log is full of:
```
Tue Feb 15 18:24:01 2022 - du::du_update: ERROR: '/media/recordings/2015' is not a directory
Tue Feb 15 18:24:01 2022 - du::du_update: ERROR: '/media/recordings/2016' is not a directory
Tue Feb 15 18:24:01 2022 - du::du_update: ERROR: '/media/recordings/2017' is not a directory
Tue Feb 15 18:24:01 2022 - du::du_update: ERROR: '/media/recordings/2018' is not a directory
Tue Feb 15 18:24:01 2022 - du::du_update: ERROR: '/media/recordings/2019' is not a directory
```
so monitorix knows that the directory is unavailable, but the usage still shows as "0" and not as "nan"

**Comment by mikaku** [comment]
I think that you want that `du.pm` module have the `use_nan_for_missing_data` option that other modules (like `disk.pm`, `ipmi.pm`, `nvme.pm`, etc.) have.

**Comment by H-Sachse** [comment]
> I think that you want that `du.pm` module have the `use_nan_for_missing_data` option that other modules (like `disk.pm`, `ipmi.pm`, `nvme.pm`, etc.) have.
Is there a reason this is not the default behaviour?

**Comment by mikaku** [comment]
>  is df used for the fs usage graphs?

Yes.

> so monitorix knows that the directory is unavailable, but the usage still shows as "0" and not as "nan"

Apply the following patch and let me know if it works for you:

```
--- du.pm	2022-02-17 12:32:46.057899699 +0100
+++ du.pm.new	2022-02-17 12:11:01.845863689 +0100
@@ -164,6 +164,7 @@
 	my $rrd = $config->{base_lib} . $package . ".rrd";
 	my $du = $config->{du};
 	my $args = $du->{extra_args} || "";
+	my $use_nan_for_missing_data = lc($du->{use_nan_for_missing_data} || "") eq "y" ? 1 : 0;
 
 	my @dirs;
 
@@ -194,7 +195,7 @@
 		foreach my $i (split(',', $du->{desc}->{$e})) {
 			my $line;
 
-			$dirs[$e][$e2] = 0 unless defined $dirs[$e][$e2];
+			$dirs[$e][$e2] = ($use_nan_for_missing_data ? (0+"nan") : 0) unless defined $dirs[$e][$e2];
 			$str = trim($i);
 			if(-d $str) {
 				if($type eq "size") {
@@ -221,7 +222,7 @@
 	$e = 0;
 	while($e < scalar(@disk_list)) {
 		for($n = 0; $n < 9; $n++) {
-			$dirs[$e][$n] = 0 unless defined $dirs[$e][$n];
+			$dirs[$e][$n] = ($use_nan_for_missing_data ? (0+"nan") : 0) unless defined $dirs[$e][$n];
 			$rrdata .= ":" . $dirs[$e][$n];
 		}
 		$e++;
```

It works here:
![Untitled](https://user-images.githubusercontent.com/829885/154473796-83a05717-9dc2-4e55-849d-ffaeeed23954.png)

```
Thu Feb 17 12:37:00 2022 - du::du_update: ERROR: '/home/ace' is not a directory
Thu Feb 17 12:37:00 2022 - du::du_update: ERROR: '/home/gene' is not a directory
Thu Feb 17 12:37:00 2022 - du::du_update: ERROR: '/home/paul' is not a directory
Thu Feb 17 12:37:00 2022 - du::du_update: ERROR: '/home/peter' is not a directory
```

**Comment by H-Sachse** [comment]
The graph is working, the line stops after I unmounted the drive. But the values in the legend are still showing the last value, not nan.
![image](https://user-images.githubusercontent.com/67382933/154539937-64db5cea-4cb8-4299-b7b9-5dcf9367bc2d.png)
The same setting would be good to have for the fs graphs as well.

**Comment by H-Sachse** [comment]
The values in the legend only turn to nan after the plot lines have gone out of view
![image](https://user-images.githubusercontent.com/67382933/154547356-ab0e2112-6d68-4a99-ae13-2eb92de37356.png)
![image](https://user-images.githubusercontent.com/67382933/154547464-360a7e45-2c13-4709-aa23-e2404747a20f.png)

**Comment by mikaku** [comment]
Monitorix is saving `NaN` values, I'm not sure why RRDtool is behaving this way.

```
Fri Feb 18 11:19:00 2022 - du::du_update: N:12:4:35268:4:5536:NaN:NaN:NaN:NaN:NaN:NaN:NaN:NaN:NaN:NaN:NaN:NaN:NaN
```

**Comment by H-Sachse** [comment]
OK, so that would mean raising a ticket with the rrdtool folks.
Could you add the `use_nan_for_missing_data` option into fs.pm as well?
Then I'll close this.

**Comment by H-Sachse** [comment]
Just checked https://github.com/mikaku/Monitorix/commit/544152cd37779a474007f51d3fe22f792729ac00, and it is working as expected.
Thanks for the quick fixes.

**Comment by mikaku** [comment]
> Just checked https://github.com/mikaku/Monitorix/commit/544152cd37779a474007f51d3fe22f792729ac00, and it is working as expected.

Perfect, thanks for your feedback.
I'll leave this issue opened until I push the last commit (documentation updates).
