### ISSUE TITLE
Problem with chrony graphs when using more than 1 server 

### ISSUE THREAD

**Issue by karlusy** [mikaku/Monitorix#408]
The problem shows up when you use more than 1 server on the list in the chrony options.
Only the last server graphs look OK... the others show up with one of the 
sub-graphs replaced by a graph from the server next in the list. See attached image:

<img width="571" alt="monitorix-chrony" src="https://user-images.githubusercontent.com/3807840/156015101-6c273045-a44d-44b4-91d3-af69a6936d73.png">

I've seen this behaviour on Monitorix 3.14 on CentOS 7.9 and Ubuntu 18.04.6, and Monitorix 3.10 on FreeBSD 13.0

**Comment by mikaku** [comment]
@karlusy, please apply the patch that I've just pushed and let me know if this fixes the problem.

By the way, it's a pity to see a so outdated Monitorix version in the latest FreeBSD.

**Comment by karlusy** [comment]
It's working!!
Amazing support 🥇 
Problem solved in less than 20 minutes!

**Comment by mikaku** [comment]
Thanks!
