### ISSUE TITLE
Support for relative resource urls

### ISSUE THREAD

**Issue by m1h4** [mikaku/Monitorix#410]
As far as I am able to tell, Monitorix cannot be configured to use relative urls for resource references (like graphs):

```html
<img src="http://raspberrypi.local/monitorix/imgs/system3.1day.svg" border="0">
```

By looking at the code here: https://github.com/mikaku/Monitorix/blob/master/monitorix.cgi#L312 we can see that, even if an empty `url_prefix_proxy` is provided and no `HTTP_HOST` env variable is present, we will get something like `http://<base_url>` as the url prefix for all resources.

This prevents use case like when one is accessing their server through multiple hostnames (in my case, I access the server using a local hostname `raspberrypi.local` but also through a tor hidden service address via a tor browser). Depending on which `url_prefix_proxy` I set, either one or the other access method will not work properly since absolutely-referenced resources will not want to load.

Is there a particular reason why relative urls are not used in general?

**Comment by mikaku** [comment]
Excuse me if I misunderstood your question, but this works for me:

<https://www.fibranet.cat/monitorix/imgs/system1z.1day.png>

**Comment by m1h4** [comment]
Yes, that would work. I've updated my question with more precise details. If one is using an generally publicly accessible host name then just using that as the `url_prefix_proxy` would work. But in my case I use a tor hidden service url via a tor-enabled browser which I only use when necessary (when not on the home network). It would work if set as the `url_prefix_proxy` address but it would then require me to always access via tor, even if on the home network.

**Comment by m1h4** [comment]
Thank you for responding to my queries, I've now investigated in more detail what role HTTP_* env variables play and what the Monitorix implementation is doing - it is ok.

I'v managed to debug the issue and why I was not seeing the expected result:

My Nginx site config was missing the `proxy_set_header` parameter:

```
    location /monitorix/ {
        proxy_pass              http://127.0.0.1:8090/monitorix/;
        proxy_set_header        Host $host;
    }
```

I wrongly assumed that by default the Host header would just be forwarded as-is.

The originally confusing part to me was that, without having `url_prefix_proxy` set, I was seeing urls like

```html
<img src="http://127.0.0.1:8090/monitorix/imgs/system3.1day.svg" border="0">
```

in the outputted html and assuming this was because of https://github.com/mikaku/Monitorix/blob/master/monitorix.cgi#L317. I was overlooking the port number which uncovers what was really happening: it was the replaced Host header by the default Nginx proxy_pass config https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy#passing-request-headers. Originally I assumed that this was because the env vars were empty and are used for something else.

Thanks again! We can close this issue as far as I'm concerned (even though the original issue of relative urls can still stand).

**Comment by mikaku** [comment]
Thanks for such a detailed description of what happening there. This might help other Nginx users in the future.

> [...] even though the original issue of relative urls can still stand).

What exactly relative URLs are for you?
Can you put an example of what URL you'll like to see?

**Comment by m1h4** [comment]
If we look at the page source of the graphs page we can see how resources are referenced by absolute urls:

```html
<!DOCTYPE html>
<html>
    <head>…</head>
    <body bgcolor="000000" vlink="#888888" link="#888888">
        <center>
            <font face="Verdana, sans-serif" color="FFFFFF">
                <table cellspacing="5" cellpadding="0" width="1" bgcolor="888888" border="1">
                    <tbody>
                        <tr>…</tr>
                         <tr>
                             <td bgcolor="333333">
                                 <a href="javascript:void(window.open('http://raspberrypi.local/monitorix/imgs/system1z.1day.svg','','width=897,height=365,scrollbars=0,resizable=0'))">
                                      <img src="http://raspberrypi.local/monitorix/imgs/system1.1day.svg" border="0">
                                  </a>
                                  <a href="javascript:void(window.open('http://raspberrypi.local/monitorix/imgs/system2z.1day.svg','','width=895,height=362,scrollbars=0,resizable=0'))">
                                      <img src="http://raspberrypi.local/monitorix/imgs/system2.1day.svg" border="0">
                                  </a>
                              </td>
                              <td valign="top" bgcolor="333333">
                                  <a href="javascript:void(window.open('http://raspberrypi.local/monitorix/imgs/system3z.1day.svg','','width=895,height=362,scrollbars=0,resizable=0'))">
                                      <img src="http://raspberrypi.local/monitorix/imgs/system3.1day.svg" border="0"></a>
                                  <a href="javascript:void(window.open('http://raspberrypi.local/monitorix/imgs/system4z.1day.svg','','width=895,height=362,scrollbars=0,resizable=0'))">
                                      <img src="http://raspberrypi.local/monitorix/imgs/system4.1day.svg" border="0">
                                  </a>
                                  <a href="javascript:void(window.open('http://raspberrypi.local/monitorix/imgs/system5z.1day.svg','','width=895,height=362,scrollbars=0,resizable=0'))">
                                      <img src="http://raspberrypi.local/monitorix/imgs/system5.1day.svg" border="0">
                                  </a>
                              </td>
                          </tr>
                      </tbody>
                  </table>
  …
```

instead of relative ones:

```html
<!DOCTYPE html>
<html>
    <head>…</head>
    <body bgcolor="000000" vlink="#888888" link="#888888">
        <center>
            <font face="Verdana, sans-serif" color="FFFFFF">
                <table cellspacing="5" cellpadding="0" width="1" bgcolor="888888" border="1">
                    <tbody>
                        <tr>…</tr>
                         <tr>
                             <td bgcolor="333333">
                                 <a href="javascript:void(window.open('../imgs/system1z.1day.svg','','width=897,height=365,scrollbars=0,resizable=0'))">
                                      <img src="../imgs/system1.1day.svg" border="0">
                                  </a>
                                  <a href="javascript:void(window.open('../imgs/system2z.1day.svg','','width=895,height=362,scrollbars=0,resizable=0'))">
                                      <img src="../imgs/system2.1day.svg" border="0">
                                  </a>
                              </td>
                              <td valign="top" bgcolor="333333">
                                  <a href="javascript:void(window.open('../imgs/system3z.1day.svg','','width=895,height=362,scrollbars=0,resizable=0'))">
                                      <img src="../imgs/system3.1day.svg" border="0"></a>
                                  <a href="javascript:void(window.open('../imgs/system4z.1day.svg','','width=895,height=362,scrollbars=0,resizable=0'))">
                                      <img src="../imgs/system4.1day.svg" border="0">
                                  </a>
                                  <a href="javascript:void(window.open('../imgs/system5z.1day.svg','','width=895,height=362,scrollbars=0,resizable=0'))">
                                      <img src="../imgs/system5.1day.svg" border="0">
                                  </a>
                              </td>
                          </tr>
                      </tbody>
                  </table>
  …
```

which would avoid the need to properly resolve the base url at page-generation time by offloading the url resolution to the user's browser.

**Comment by mikaku** [comment]
Please, check the latest commit and let me know if it works for you.
Don't forget to add the new option in your configuration file:

```
enable_relative_urls = y
```

**Comment by m1h4** [comment]
Yep, it works! I've already tested the relative urls by just commenting out those lines in my install of Monitorix and it worked fine.

Thanks for addressing this!

**Comment by mikaku** [comment]
Perfect!
