### ISSUE TITLE
nvidiagpu: Function update_pdp_prep, case DST_GAUGE - Cannot convert '[N/A]' to float

### ISSUE THREAD

**Issue by Danct12** [mikaku/Monitorix#415]
I'm currently using a NVIDIA GeForce 1050 Ti with driver version 510.54 under Arch Linux.

After I configured Monitorix to use the new nvidiagpu module, this is what shows up in the logs:
```
ERROR: while updating /var/lib/monitorix/nvidiagpu.rrd: /var/lib/monitorix/nvidiagpu.rrd: Function update_pdp_prep, case DST_GAUGE - Cannot convert '[N/A]' to float
```

This is what I have in the config file now:
```
<nvidiagpu>
        <list>
                0 = GPU-UUID
        </list>
        rigid = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
        limit = 100, 100, 100, 100, 100, 100, 100, 100, 100, 100
        use_nan_for_missing_data = y
        gap_on_all_nan = y
        show_current_values = y
        <map>
                GPU-UUID = GTX 1050 Ti
        </map>
        <alerts>
                coretemp_enabled = n
                coretemp_timeintvl = 0
                coretemp_threshold = 1
                coretemp_script = /path/to/script.sh
                memorytemp_enabled = n
                memorytemp_timeintvl = 0
                memorytemp_threshold = 1
                memorytemp_script = /path/to/script.sh
        </alerts>
</nvidiagpu>
```

**Comment by bachandi** [comment]
I suspect it is related to your `nvidia-smi` version printing `[N/A]` instead of `N/A` for non existent values. 

Would you mind testing this patch?

```diff
diff --git a/lib/nvidiagpu.pm b/lib/nvidiagpu.pm
index 8f852fa..1766358 100644
--- a/lib/nvidiagpu.pm
+++ b/lib/nvidiagpu.pm
@@ -191,7 +191,7 @@ sub nvidiagpu_update {
                                        if(scalar(@tmp) > 1) { # To catch missing devices
                                                for(my $n_sensor = 0; $n_sensor < scalar(@tmp); $n_sensor += 1) {
                                                        my $val = trim($tmp[$n_sensor]);
-                                                       if($val ne "N/A") {
+                                                       if($val !~ /N\/A/) {
                                                                if(substr($val, 0, 1) eq "P") {
                                                                        $val = substr($val, 1);
                                                                }
```

**Comment by Danct12** [comment]
The patch you sent seems to have fixed the issue, I don't see the error in the log anymore and actual data now shows up.

![Screenshot_20220321_023816](https://user-images.githubusercontent.com/19162768/159179765-7c848b3d-3702-428d-83f7-935cb331084a.png)

On a unrelated note, memory temperature and power draw doesn't seem to be supported by my GPU according to `nvidia-smi -q`.

**Comment by bachandi** [comment]
> The patch you sent seems to have fixed the issue, I don't see the error in the log anymore and actual data now shows up.

Great to hear. Thanks for testing.

> On a unrelated note, memory temperature and power draw doesn't seem to be supported by my GPU according to `nvidia-smi -q`.

Yes, sadly not all Nvidia cards support those values.

**Comment by mikaku** [comment]
> I did not consider any other return values than N/A when adding this module. So this patch should fix the issue and is the better approach incase nvidia has even more versions of N/A.

I see, thanks.
