### ISSUE TITLE
Trying to add support for amavis Module Mail::SPF

### ISSUE THREAD

**Issue by nurbles** [mikaku/Monitorix#419]
Hello, I'm VERY new to monitorix and I'm not a perl programmer (though I've had small successes with copy/mimic of perl code.)

After installing monitorix and looking at the graphs produced by mail.pm, I noticed that the SPF graph was flat, despite the many, many SPF entries in my mail log.  So I looked at my log and found these distinct entries (I removed all of the stuff at the end of the messages with IP address'n'stuff):

```
   Apr 20 11:24:23 mail policyd-spf[31718]: prepend Received-SPF: Pass (mailfrom) identity=mailfrom;
   Apr 20 14:40:37 mail policyd-spf[59459]: 550 5.7.23 Message rejected due to: access neither permitted nor denied.
   Apr 20 15:04:51 mail policyd-spf[62775]: prepend X-Comment: SPF skipped for whitelisted relay -
   Apr 20 15:10:07 mail policyd-spf[63817]: prepend Received-SPF: Permerror (mailfrom) identity=mailfrom;
   Apr 20 17:57:00 mail policyd-spf[20367]: prepend Received-SPF: Softfail (mailfrom) identity=mailfrom;
   Apr 20 18:33:30 mail policyd-spf[25007]: prepend Received-SPF: Pass (helo) identity=helo;
   Apr 21 10:37:48 mail policyd-spf[36163]: prepend Received-SPF: None (mailfrom) identity=mailfrom;
   Apr 21 11:38:54 mail postfix/spawn[54847]: warning: command /usr/bin/policyd-spf exit status 120
```
I noticed that mail.pm was only looking for lines with `/policy-spf/` or that included `/ SPF /`, neither of which matched mine.  My first thought was that a 'd' was missing from the first pattern, `/policyd-spf/`, which would then match my lines, but that was wrong because the specific counter lines don't match mine, either.  So I tried making this change (the amavis block is my new code):

```
   # postfix-policyd-spf-perl
   if(/policy-spf/) {
           if(/: pass/) {
                   $spf_pass++;
           } elsif(/: none/) {
                   $spf_none++;
           } elsif(/ action=550 /) {
                   $spf_fail++;
           } else {
                   # There one line per spf check, so it gets here, we'll consider it is a so
                   $spf_softfail++;
           }
   # amavis Module Mail::SPF
   } elsif(/policyd-spf/) {
           if(/: Pass/) {
                   $spf_pass++;
           } elsif(/: None/ || / SPF skipped/) {
                   $spf_none++;
           } elsif(/ 550 /) {
                   $spf_fail++;
           } elsif(/: Softfail/) {
                   # Softfail or anything else...
                   $spf_softfail++;
           } else {
                   $spf_none++;
           }
   # for other SPF handlers (smf-spf)
   } else {
           if(/ SPF none/) {
                   $spf_none++;
           } elsif(/ SPF pass/) {
                   $spf_pass++;
           } elsif(/ SPF softfail/) {
                   $spf_softfail++;
           } elsif(/ SPF fail/) {
                   $spf_fail++;
           }
   }
```
The final else in my code block was an attempt to figure out what I did wrong, because only the _SoftFail_ track on the graph is showing any values, despite the bulk of the SPF lines in my log matching `/: Pass/`:  [Example SPF Graph (zoomed)](https://www.svalli.com/files/SPF.png)

So, I'm hoping that a perl expert will see what I've done wrong and perhaps this change might be incorporated in to the code (once it works correctly [smile]) so that an update won't erase my local work.

**Comment by nurbles** [comment]
It appears that my added code actually _does_ work correctly. I was trying to figure out how to debug the mail.pm module (quite unsuccessfully) and during the process I restarted monitorix several times and one of those seems to have "fixed" the issue I had with only softfail being counted. While I cannot prove this, I believe that changing the mode from graph to text, restarting monitorix, trying a few reports then switching back to graph and restarting again is when it started working.

So, if one of the perl/git masters is interested in adding support for the amavis Mail::SPF module, I think my code (after a small amount of clean-up) will work. Though there may be a better way to implement support for one out of multiple, but similar, services.

**Comment by mikaku** [comment]
Your code looks fine to me:

```
   # amavis Module Mail::SPF
   } elsif(/policyd-spf/) {
           if(/: Pass/) {
                   $spf_pass++;
           } elsif(/: None/ || / SPF skipped/) {
                   $spf_none++;
           } elsif(/ 550 /) {
                   $spf_fail++;
           } elsif(/: Softfail/) {
                   # Softfail or anything else...
                   $spf_softfail++;
           } else {
                   $spf_none++;
           }
```

You only need to say if the final `else` is actually necessary or not.

> I was trying to figure out how to debug the mail.pm module (quite unsuccessfully) ...

The best way to debug Monitorix is using the argument `-d` and starting it in foreground mode:

```
# monitorix -c /etc/monitorix/conf.d/local.conf -d all -n
```

Since Monitorix will be running in foreground, all messages will be output in your terminal instead the log file. Also, you'll see more verbosity on every minute because it will output all the values collected and being saved for every single graph you have enabled. You can press `Ctrl-C` at any time to stop the process.

**Comment by nurbles** [comment]
Thanks for the debugging tip, that will be VERY helpful next time I try to dig into one of these modules. (smile)

Once I saw that my code was working, I changed it to this:  (Sorry, the tabs got converted into spaces when I copied)
```
  # amavis Module Mail::SPF
  } elsif(/policyd-spf/) {
    if(/: Pass/) {
      $spf_pass++;
    } elsif(/: None/ || / SPF skipped/) {
      $spf_none++;
    } elsif(/ 550 /) {
      $spf_fail++;
    } else {
      # /: Softfail/ or anything else, so consider as a soft fail
      $spf_softfail++;
    }
```
Now I'm seeing all of the categories counted.

**Comment by mikaku** [comment]
Thanks.
