### ISSUE TITLE
raspberrypi default config incorrect path to vcgencmd

### ISSUE THREAD

**Issue by H-Sachse** [mikaku/Monitorix#420]
The default value for cmd for the vcgencmd binary is no longer correct.
For stretch, buster and bullseye, vcgencmd is located in /usr/bin/

**Comment by mikaku** [comment]
> The default value for cmd for the vcgencmd binary is no longer correct.

Yes, it's time to update this old path.

**Comment by mikaku** [comment]
Actually the path was changed in `monitorix.conf`, not in `raspberrypi.pm`.
