### ISSUE TITLE
process customization  - Help needed

### ISSUE THREAD

**Issue by Eldadc** [mikaku/Monitorix#423]
Hi,

I was struggling with configuration and some manuals on the internet but still did not manage to customize my process graph.
My main goal is monitor a specific process on my server and of course to monitor it with graph and also in silently mode from my CI .
I want to display my process activity in a graph , simple graph.
I think my big challenge is to display a summery report on my CI server , or at least to parse a summery text file for results?
Any help will be appreciated.

Thanks

**Comment by Eldadc** [comment]
Hi,

Thanks for the quick response.
I am trying to monitor a specific process , I have edit the configuration file and add new process name to the list ,and restarted the service. I have not edit the process.pm file , since I didn't understand the propose of this file.
How can I check if process is monitor ?
Where Can I find a man on How to create a custom report for a specific process.

**Comment by Eldadc** [comment]
Hi,

Thanks for the info , that's more clear.

1. Once I created my own conf.d for my processes , How Can it be reflected on a graph ?
2. I can not distinguish which lines to which process in the Active process graph ? Below is an example.

<process>
	<list>
		0 = httpd, sshd, ntpd, mysqld, proftpd, clamd, imap, sendmail, named, smbd , MyProcess
                1 = java
	</list>
	<desc>
		httpd = Apache
		imap = Dovecot
		named = Bind
                Process = MyProcess
	</desc>
	rigid = 2, 0, 0, 0, 0, 0, 0, 0
	limit = 100, 1000, 1000, 1000, 1000, 1000, 1000, 1000
</process>

**Comment by Eldadc** [comment]
Hi,

configuration file.

<process>
	<list>
		0 = httpd, sshd, ntpd, mysqld, proftpd, clamd, imap, sendmail, named, smbd, Myprocess
             </list>
	<desc>
		httpd = Apache
		imap = Dovecot
		named = Bind
                ControlProcess =Myprocess
	</desc>
	rigid = 2, 0, 0, 0, 0, 0, 0, 0
	limit = 100, 1000, 1000, 1000, 1000, 1000, 1000, 1000
</process>

**Comment by Eldadc** [comment]
Hi,

My configuration file, I did not edit the default syntax , just added new process.

```
<process>
	<list>
		0 = httpd, sshd, ntpd, mysqld, proftpd, clamd, imap, sendmail, named, smbd, processname
                </list>
	<desc>
		httpd = Apache
		imap = Dovecot
		named = Bind
                MyProcess = processname
	</desc>
	rigid = 2, 0, 0, 0, 0, 0, 0, 0
	limit = 100, 1000, 1000, 1000, 1000, 1000, 1000, 1000
</process>

```

**Comment by mikaku** [comment]
> 0 = httpd, sshd, ntpd, mysqld, proftpd, clamd, imap, sendmail, named, smbd, processname

As stated in the [manpage](https://www.monitorix.org/manpage.html#29), the maximum number of processes allowed per group is 10.

You must either create a new group (e.g: `1`) and include there your process name or substitute one of the default process names by yours.

**Comment by Eldadc** [comment]
Hi

Ok , I correct this settings. BTW I am using 3.12 version.

In your screen shot you sent , It displays a process statistics page , In my version there is no such report , just "Active processs"

1. Do I need to create such report or there is another issue un my settings ?

Thanks

**Comment by mikaku** [comment]
> In your screen shot you sent , It displays a process statistics page , In my version there is no such report , just "Active processs"
>
>    Do I need to create such report or there is another issue un my settings ?

The screen shot I sent you was and example of the module you are setting (`process.pm`). The graph called **Active processes** is a graph that belongs to a different module (`system.pm`).

Please, read the documentation and explore all the screen shots in the web site to familiarize on how Monitorix works.

**Comment by Eldadc** [comment]
Hi,

I am sorry that I am loading you with my issue , Thanks for your patience.
It seems the process statistics report doesn't exists in my report.

Thanks

**Comment by mikaku** [comment]
I don't understand, sorry.

Following your example and what you want to have, your should create a config like this:

```
<list>
	0 = httpd, sshd, ntpd, mysqld, proftpd, clamd, imap, sendmail, named, smbd
	1 = processname
</list>
```

I hope that helped you.

**Comment by Eldadc** [comment]
Hi,

I have reinstalled the app , new without changing default configuration.
The process satistics is missing.

Thx

**Comment by mikaku** [comment]
> I have reinstalled the app , new without changing default configuration.
The process satistics is missing.

Sure, the `process.pm` module comes disabled by default. You need to enable it to get the graphs:

```
<graph_enable>
[...]
        process         = y

```
