### ISSUE TITLE
Azure DevOps - Report generation

### ISSUE THREAD

**Issue by Eldadc** [mikaku/Monitorix#424]
Hi,

Question Please:
Is it possible to create reports to be reflected on azure devops reports.
Is it possible to create a report in plain text in order to parse results ?

Thanks

**Comment by mikaku** [comment]
Yes, with `curl` you should get the HTML page with all the values.

**Comment by mikaku** [comment]
Closing due to no response for two weeks.

If you still need more information, please add a comment and the issue can be reopened.
