### ISSUE TITLE
mysql credentials not customizable

### ISSUE THREAD

**Issue by maiestro** [mikaku/Monitorix#425]
In the mysql configuration, even if there are other login data, only the default login (user/secret) is used.

```
# MYSQL graph
# -----------------------------------------------------------------------------
<mysql>
        conn_type = host
        list = localhost
#       list = /var/lib/mysql/mysql.sock
        <desc>
                localhost = 3306, monitorix, monitorixpw
        </desc>
        rigid = 0, 2, 0, 0, 0, 0
        limit = 100, 100, 100, 100, 100, 100
</mysql>
```

**Expected behavior:**
Monitorix should connect to mysql with user: monitorix and password monitorixpw

instead a connection is attempted with user: user and password: secret

**Comment by mikaku** [comment]
Check the log file to see if your Monitorix is loading an extra configuration file that might override your configuration.
I think that Debian package includes an extra file called `conf.d/00-debian.conf`.

**Comment by mikaku** [comment]
Additionally, read this [FAQ](https://www.monitorix.org/faq.html#Q107) which will help you to have a proper Monitorix configuration.
