### ISSUE TITLE
Feature Request: Manual Trigger Emailing of Dashboard

### ISSUE THREAD

**Issue by khcassidy** [mikaku/Monitorix#429]
Hello,

I would like to propose a feature to allow the manual triggering of the emailing of a dashboard from the command line.
I have limited access to some of the systems I am monitoring, allowing certain batch files to trigger the mailing of reports for viewing on a different system would be useful. I currently have the daily automatic emailreports sent to my email. However I would like to trigger this from the command line/bash script at will using the configured email server settings in the monitorix conf file for email server. For example sometimes I like to see the hourly graph in relation to the daily performance statistics. or I want to examine the results of a process at adhoc times or review).

Ideally the command line would take the variables of:
hourly
 or daily
 or weekly
 or monthly
or yearly
maybe email address.
For my needs the All Graphs would be perfect but I can imagine people may want to choose specific graph(s) to send.

(Sorry if this is already possible but I have had trouble finding out how)

Really like the tool, thanks for all your efforts.

**Comment by mikaku** [comment]
Hello,

Yes, I think this is related to #322.

**Comment by mikaku** [comment]
@khcassidy, please download the latest version of `monitorix` as stated in my last post in #322.
I think we can close this issue and continue the conversation in #322.
