### ISSUE TITLE
Feature request: System/Process stats

### ISSUE THREAD

**Issue by doguz2509** [mikaku/Monitorix#434]
I would like to get status as it coming from top/htop/atop
Particular I interest in selected processes measurement
```
<top>
   <processes>
       0 - wild_char_process_patttern (Example: procc_name*)
   </processes>
</top>
```

**Comment by mikaku** [comment]
The `process.pm` module already shows process stats.

**Comment by mikaku** [comment]
Closing due to no response for two weeks.

If you still need more information, please add a comment and the issue can be reopened.
