### ISSUE TITLE
monitorix build on riscv64

### ISSUE THREAD

**Issue by abhishekwalia33** [mikaku/Monitorix#436]
Hi,
I am trying to install Monitorix on riscv64 based platform as per mentioned in README I installed all the prerequisites and then I Tried to build from source bellow is the steps:

log ;
monitorix-3.10.0# make install-systemd-all
Installing script and modules...
install -p -d "/usr/bin"
install -p -m755 monitorix "/usr/bin/monitorix"
install -p -d "/var/lib/monitorix"
install -p -d "/var/lib/monitorix"
install -p -d "/var/lib/monitorix/www"
install -p -d "/var/lib/monitorix/www/cgi"
install -p -dm777 "/var/lib/monitorix/www/imgs"
install -p -m755 monitorix.cgi "/var/lib/monitorix/www/cgi/monitorix.cgi"
install -p -m644 logo_bot.png "/var/lib/monitorix/www/logo_bot.png"
install -p -m644 logo_top.png "/var/lib/monitorix/www/logo_top.png"
install -p -m644 monitorixico.png "/var/lib/monitorix/www/monitorixico.png"
install -p -d "/etc/monitorix"
install -p -m644 monitorix.conf "/etc/monitorix/monitorix.conf"
install -p -d "/etc/monitorix/conf.d"
install -p -d "/etc/logrotate.d/"
install -p -m644 docs/monitorix.logrotate "/etc/logrotate.d/monitorix"
install -p -d "/etc/sysconfig"
install -p -m644 docs/monitorix.sysconfig "/etc/sysconfig/monitorix"
install -p -d "/usr/lib/monitorix"
install -p -m644 lib/apache.pm "/usr/lib/monitorix/apache.pm"
install -p -m644 lib/apcupsd.pm "/usr/lib/monitorix/apcupsd.pm"
install -p -m644 lib/bind.pm "/usr/lib/monitorix/bind.pm"
install -p -m644 lib/chrony.pm "/usr/lib/monitorix/chrony.pm"
install -p -m644 lib/disk.pm "/usr/lib/monitorix/disk.pm"
install -p -m644 lib/du.pm "/usr/lib/monitorix/du.pm"
install -p -m644 lib/emailreports.pm "/usr/lib/monitorix/emailreports.pm"
install -p -m644 lib/fail2ban.pm "/usr/lib/monitorix/fail2ban.pm"
install -p -m644 lib/fs.pm "/usr/lib/monitorix/fs.pm"
install -p -m644 lib/ftp.pm "/usr/lib/monitorix/ftp.pm"
install -p -m644 lib/gensens.pm "/usr/lib/monitorix/gensens.pm"
install -p -m644 lib/hptemp.pm "/usr/lib/monitorix/hptemp.pm"
install -p -m644 lib/HTTPServer.pm "/usr/lib/monitorix/HTTPServer.pm"
install -p -m644 lib/icecast.pm "/usr/lib/monitorix/icecast.pm"
install -p -m644 lib/int.pm "/usr/lib/monitorix/int.pm"
install -p -m644 lib/ipmi.pm "/usr/lib/monitorix/ipmi.pm"
install -p -m644 lib/kern.pm "/usr/lib/monitorix/kern.pm"
install -p -m644 lib/libvirt.pm "/usr/lib/monitorix/libvirt.pm"
install -p -m644 lib/lighttpd.pm "/usr/lib/monitorix/lighttpd.pm"
install -p -m644 lib/lmsens.pm "/usr/lib/monitorix/lmsens.pm"
install -p -m644 lib/mail.pm "/usr/lib/monitorix/mail.pm"
install -p -m644 lib/memcached.pm "/usr/lib/monitorix/memcached.pm"
install -p -m644 lib/mongodb.pm "/usr/lib/monitorix/mongodb.pm"
install -p -m644 lib/Monitorix.pm "/usr/lib/monitorix/Monitorix.pm"
install -p -m644 lib/mysql.pm "/usr/lib/monitorix/mysql.pm"
install -p -m644 lib/net.pm "/usr/lib/monitorix/net.pm"
install -p -m644 lib/netstat.pm "/usr/lib/monitorix/netstat.pm"
install -p -m644 lib/nfsc.pm "/usr/lib/monitorix/nfsc.pm"
install -p -m644 lib/nfss.pm "/usr/lib/monitorix/nfss.pm"
install -p -m644 lib/nginx.pm "/usr/lib/monitorix/nginx.pm"
install -p -m644 lib/ntp.pm "/usr/lib/monitorix/ntp.pm"
install -p -m644 lib/nut.pm "/usr/lib/monitorix/nut.pm"
install -p -m644 lib/nvidia.pm "/usr/lib/monitorix/nvidia.pm"
install -p -m644 lib/pagespeed.pm "/usr/lib/monitorix/pagespeed.pm"
install -p -m644 lib/phpapc.pm "/usr/lib/monitorix/phpapc.pm"
install -p -m644 lib/port.pm "/usr/lib/monitorix/port.pm"
install -p -m644 lib/process.pm "/usr/lib/monitorix/process.pm"
install -p -m644 lib/proc.pm "/usr/lib/monitorix/proc.pm"
install -p -m644 lib/raspberrypi.pm "/usr/lib/monitorix/raspberrypi.pm"
install -p -m644 lib/serv.pm "/usr/lib/monitorix/serv.pm"
install -p -m644 lib/squid.pm "/usr/lib/monitorix/squid.pm"
install -p -m644 lib/system.pm "/usr/lib/monitorix/system.pm"
install -p -m644 lib/tc.pm "/usr/lib/monitorix/tc.pm"
install -p -m644 lib/traffacct.pm "/usr/lib/monitorix/traffacct.pm"
install -p -m644 lib/user.pm "/usr/lib/monitorix/user.pm"
install -p -m644 lib/varnish.pm "/usr/lib/monitorix/varnish.pm"
install -p -m644 lib/verlihub.pm "/usr/lib/monitorix/verlihub.pm"
install -p -m644 lib/wowza.pm "/usr/lib/monitorix/wowza.pm"
install -p -m644 lib/zfs.pm "/usr/lib/monitorix/zfs.pm"
install -p -d "/var/lib/monitorix/reports"
install -p -m644 reports/ca.html "/var/lib/monitorix/reports/ca.html"
install -p -m644 reports/de.html "/var/lib/monitorix/reports/de.html"
install -p -m644 reports/en.html "/var/lib/monitorix/reports/en.html"
install -p -m644 reports/it.html "/var/lib/monitorix/reports/it.html"
install -p -m644 reports/nl_NL.html "/var/lib/monitorix/reports/nl_NL.html"
install -p -m644 reports/pl.html "/var/lib/monitorix/reports/pl.html"
install -p -m644 reports/zh_CN.html "/var/lib/monitorix/reports/zh_CN.html"
install -p -d "/var/lib/monitorix/usage"
Installing manpages...
install -p -d "/usr/share/man/man5"
install -p -m644 man/man5/monitorix.conf.5 "/usr/share/man/man5/monitorix.conf.5"
install -p -d "/usr/share/man/man8"
gzip -9 "/usr/share/man/man5/monitorix.conf.5"
install -p -m644 man/man8/monitorix.8 "/usr/share/man/man8/monitorix.8"
gzip -9 "/usr/share/man/man8/monitorix.8"
Installing docs...
install -p -d "/usr/share/doc/monitorix"
install -p -m755 docs/monitorix-alert.sh "/usr/share/doc/monitorix/monitorix-alert.sh"
install -p -m755 docs/htpasswd.pl "/usr/share/doc/monitorix/htpasswd.pl"
install -p -m644 Changes "/usr/share/doc/monitorix/Changes"
install -p -m644 COPYING "/usr/share/doc/monitorix/COPYING"
install -p -m644 README "/usr/share/doc/monitorix/README"
install -p -m644 README.FreeBSD "/usr/share/doc/monitorix/README.FreeBSD"
install -p -m644 README.nginx "/usr/share/doc/monitorix/README.nginx"
install -p -m644 README.OpenBSD "/usr/share/doc/monitorix/README.OpenBSD"
install -p -m644 README.NetBSD "/usr/share/doc/monitorix/README.NetBSD"
install -p -m644 docs/monitorix-lighttpd.conf "/usr/share/doc/monitorix/monitorix-lighttpd.conf"
install -p -m644 docs/monitorix-apache.conf "/usr/share/doc/monitorix/monitorix-apache.conf"
Installing systemd service...
install -p -d "/etc"
install -p -d "/usr/lib/systemd/system"
install -p -m644 docs/monitorix.service "/usr/lib/systemd/system/monitorix.service"

$ /usr/bin/monitorix -c /etc/monitorix/monitorix.conf
Can't locate object method "new" via package "Config::General" at /usr/bin/monitorix line 463.

I am getting this "**Can't locate object method** "  error ,please help me out how to resolve this error and why I am getting this error.

Thanks
Abhishek

**Comment by abhishekwalia33** [comment]
I installed monitorix successfully by folllowing  commands :

$monitorix-3.14.0  make install-systemd-all

but after install i am getting bellow error when i am running the bellow command
monitorix-3.14.0# /etc/init.d/monitorix 
**/etc/init.d/monitorix: line 32: /lib/init/vars.sh: No such file or directory**

why this vars.sh not coming after installed monitorix please help me out.

**Comment by mikaku** [comment]
> $ /usr/bin/monitorix -c /etc/monitorix/monitorix.conf
Can't locate object method "new" via package "Config::General" at /usr/bin/monitorix line 463.

Installing Monitorix in this way might need to satisfy dependencies manually.

> I installed monitorix successfully by folllowing commands :
$monitorix-3.14.0 make install-systemd-all

if you installed Monitorix for a system that uses `systemd`, why aren't you using the command `systemctl` to start Monitorix?
The script in `/etc/init.d/monitorix` must be placed there as part of another installation you did before.

The command `systemctl start monitorix` should suffice.

Since this type of installation is not very common, please, right after the above command check the Monitorix log file to see any error messages.

**Comment by abhishekwalia33** [comment]
thanks ,it is working with the command **"systemctl start monitorix"**

again thank you... for support.
