### ISSUE TITLE
lm sensors - display min / max/ avg

### ISSUE THREAD

**Issue by anayrat** [mikaku/Monitorix#439]
Hello,
I wonder if I miss something, is it normal to only have current value in lm sensors graph?
![image](https://user-images.githubusercontent.com/6862220/192969397-6907db86-353d-436e-9de0-f6f7d7e18c67.png)

It could be useful to have min / max / avg as other graph.
Regards,

**Comment by mikaku** [comment]
Yes, it's just a matter of lack of space.
This module is capable of showing a big number of metrics:

```
Up to 16 core keys (from core0 to core15).
Up to 2 mb keys (mb0 and mb1).
Up to 4 cpu keys (from cpu0 to cpu3).
Up to 9 fan keys (from fan0 to fan8).
Up to 12 volt keys (from volt0 to volt11).
Up to 9 gpu keys (from gpu0 to gpu8). 
```

All this makes really difficult to combine with a more detailed information like appear in other graphs, that's the reason why it shows one only numeric value.

Hopefully, the plotted lines should help you to find the min and max peaks.
Sorry for the inconveniences.

**Comment by anayrat** [comment]
Make sense, I understand. Thanks for your answer :)
