### ISSUE TITLE
remove ipv6 (OR ipv4) graphs completely

### ISSUE THREAD

**Issue by rrrevin** [mikaku/Monitorix#447]
Is there an option to remove any/all ipv6 graphs completely? I've disabled IPv6 on my system, but "some" applications insist on opening an ipv6 port anyway.

I'd like to remove the following graph and items in it's entirety..
conversely, there may be some who'd like to remove the ipv4 as well.
![image](https://user-images.githubusercontent.com/49560189/208256635-6255276c-7c47-45cd-b8a7-0711dbf0a39e.png)

**Comment by mikaku** [comment]
No, the layout of IPv4 and IPv6 graphs is fixed. Removing the IPv6 context would require a complete new layout.

Anyway, I don't see the point here. Thanks to IPv6 graphs you are detecting that some applications are still receiving IPv6 requests.

Monitorix will only show IPv6 statistics if your kernel has IPv6 enabled.
