### ISSUE TITLE
Mongo 6 does not seem to be supported by Monitorix

### ISSUE THREAD

**Issue by ollie2a** [mikaku/Monitorix#451]
Following the introduction of Mongo 6 ; the mongo shell has been replaced by mongosh and it looks like the monitoring and diagnostics have changed.

**Comment by mikaku** [comment]
I don't have an installation of MongoDB version 6, so I'm unable to see the changes.
Can you, please, show what arguments changed in the command `mongo` and what is the new output?

**Comment by ollie2a** [comment]
`mongo` is not available anymore in MongoDB 6 and has been replaced by `mongosh` however the input seems to be similar but output must be different since even doing a symbolic link between `mongo` and `mongosh` does not seem to resolve the issue.

**Input**
`mongosh --eval "printjson(db.serverStatus())"`

**Output**

[mongodb.txt](https://github.com/mikaku/Monitorix/files/10841115/mongodb.txt)

Might be something to do with this potentially .. i did not take time to investigate the script : 

https://www.mongodb.com/community/forums/t/mongosh-json-output/116389

**Comment by mikaku** [comment]
I could include the new option `cmd` in the `<mongodb>` configuration to let the user choose the proper command for the version of MongoDB what he is using. But there is still the change in the extra argument.

This module (`mongodb.pm`) calls two times this command:

The first one with this argument: `$cmd .= "--eval \"printjson(db.serverStatus())\"";` and the second one with `$cmd .= "--eval \"printjson(db.stats(1))\" $db";`

You already have noted that the argument in the second call, if used with the command `mongosh` must be changed to `$cmd .= "--eval \"EJSON.stringify(db.stats(1),null,' ')\" $db";`.

But what about the argument in the first call? it will work in both commands as it is right now?

**Comment by ollie2a** [comment]
it seems to be the same for both commands - EJSON wrap the fields with double quote and also transform some internal Long(xxx) values into the number equivalent. In addition the fields are automatically followed by a column rather than space + column which needs to be updated (e.g `"uptime": 1232312` instead of `"uptime" : 12323212`. There might be more elegant way to do this but the one enclosed seems to work for me. 

[mongodb.txt](https://github.com/mikaku/Monitorix/files/10865564/mongodb.txt)

**Comment by mikaku** [comment]
Thanks, this helped me a lot.

I've included three new options in the `<mongodb>` configuration to let user choose the proper command depending on the MongoDB version, and also, the two `eval` strings:

For MongoDB versions before 6 you would configure it like this:
```
# MONGODB graph
# -----------------------------------------------------------------------------
<mongodb>
        list = localhost
        max_db = 1
        cmd = mongo
        cmd_db_serverstatus = "--eval \"printjson(db.serverStatus()),printjson(db.stats(1))\""
        cmd_db_stats = "--eval \"printjson(db.stats(1))\""
        <desc>
        ...
```

and for MongoDB version 6 (and hopefully more) you would configure it like this:
```
# MONGODB graph
# -----------------------------------------------------------------------------
<mongodb>
        list = localhost
        max_db = 1
        cmd = mongosh
        cmd_db_serverstatus = "--eval \"EJSON.stringify(db.serverStatus(),null,' ')\""
        cmd_db_stats = "--eval \"EJSON.stringify(db.stats(1),null,' ')\" $db"
        <desc>
        ...
```

Please, check the following `mongodb.pm` and let me know if it works in your MongoDB version 6.
Don't forget to adjust your configuration file accordingly.

[mongodb.txt](https://github.com/mikaku/Monitorix/files/10870258/mongodb.txt)

**Comment by ollie2a** [comment]
working 👍

**Comment by mikaku** [comment]
Thank you very much.
