### ISSUE TITLE
Debian 11. HTTP starting only on localhost

### ISSUE THREAD

**Issue by Deepcuts** [mikaku/Monitorix#453]
Hello,

Been using Monitorix for a long time on a rusty Ubuntu 14.04 and I recall it was a breeze to setup.
Trying now to set it up on a fresh Debian 11 and have some issues.
apt installs a pretty old version so I got the latest 3.15.0 and make install-systemd-all
Generated the htpasswd with  htpasswd -d -c /var/lib/monitorix/htpasswd myuser

The issue is that the HTTP server does not start on the IP I setup. It only starts on localhost.
```
Tue Apr  4 05:45:19 2023 - Starting Monitorix version 3.15.0 (pid 29905).
Tue Apr  4 05:45:19 2023 - Loaded main configuration file '/etc/monitorix/monitorix.conf'.
Tue Apr  4 05:45:19 2023 - Loading extra configuration file '/etc/monitorix/conf.d/00-debian.conf'.
Tue Apr  4 05:45:19 2023 - Initializing graphs.
Tue Apr  4 05:45:19 2023 - Generating the 'index.html' file.
Tue Apr  4 05:45:19 2023 - Started HTTP built-in server (pid 29924).
Tue Apr  4 05:45:19 2023 - Ok, ready.
HTTPServer: You can connect to your server at http://localhost:8080/

```

The HTTP part of monitorix.conf

```
<httpd_builtin>
        enabled = y
        host = Public.IP
        port = 8080
        user = nobody
        group = nogroup
        log_file = /var/log/monitorix-httpd
        hosts_deny =
        hosts_allow =
        autocheck_responsiveness = y
        <auth>
                enabled = y
                hosts_deny = all
                msg = Monitorix: Restricted access
                htpasswd = /var/lib/monitorix/htpasswd
        </auth>
</httpd_builtin>
```

I am clueless at this point as to why it does not want to listen on the specified IP.
I also have commented out the user and group from conf.d/00-debian.conf to no avail.
Tried even with user and group as root (just as a test) and still `HTTPServer: You can connect to your server at http://localhost:8080/`

Any hints please?

**Comment by mikaku** [comment]
Hello,

The message `HTTPServer: You can connect to your server at http://localhost:8080/` is shown by the [Perl HTTP Server Simple](https://metacpan.org/pod/HTTP::Server::Simple) module that Monitorix uses as the web server.

I have checked in its [source code](https://metacpan.org/dist/HTTP-Server-Simple/source/lib/HTTP/Server/Simple.pm#L626-635) and I'm afraid that this is a fixed message that always says `localhost` regardless of the IP where it is bound.

I've tested it here on a Fedora 36 and it works:

```
<httpd_builtin>
        enabled = y
        host = 192.168.1.11
        port = 8080
...
```

```
# netstat -ltnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 192.168.1.11:8080       0.0.0.0:*               LISTEN      78006/monitorix-htt 
...
```

**Comment by Deepcuts** [comment]
Thank you for taking your time to reply mikaku.

Indeed, I was fooled by the message.
Everything works great.
