### ISSUE TITLE
Too verbose /var/log/monitorix-httpd - http access log lines should not be added by default, 

### ISSUE THREAD

**Issue by slrslr** [mikaku/Monitorix#454]
Hello,
when i open monitorix 3.15.0 page on Debian 11 and see the graphs and then switch to other web browser tab (Firefox ESR), monitorix still refreshing the inactive page every like 1.5 minutes and it means writing like [38 full log lines](https://bin.disroot.org/?9091bfa58a08c9cb#HnfsjECvBAjzibWtwXe2YcDq2L5fSozusSNBUT63ZXYg)) of text into /var/log/monitorix-httpd

It is around 1000 log lines and 140kB per hour. 24000 lines and 3MB+ per day.
-> using available iops, wearing down SSD and using non insignificant space

Ideas:
- log only 1 access log entry each 1.5 minute or log errors and authentication success (not entire http access log), unless user enable logging of accesses (new configurable option disabled by default?) - disabling logging into monitorix-httpd file entirely may not be good, since user may want to monitor failed auth attempts using fail2ban and similar (ideal would be if failed attempts are only invalid credentials entered not just random bot access to password protected page).

- monitorix fails to start if i set read only (immutable) the monitorix-httpd file (chattr +i /var/log/monitorix-httpd), maybe it can still be made to start, just not write anything

- [detect that the tab is inactive](https://www.ecosia.org/search?q=web+developer+detect+inactive+browser+tab+crossplatform) and pause refreshing until tab is activated

**Comment by mikaku** [comment]
> monitorix fails to start if i set read only (immutable) the monitorix-httpd file (chattr +i /var/log/monitorix-httpd), maybe it can still be made to start, just not write anything

If you don't want to log anything (which is the same as setting the log file as immutable), just unset the option `log_file`.

> detect that the tab is inactive and pause refreshing until tab is activated

Definitely not.

> log only 1 access log entry each 1.5 minute or log errors and authentication success (not entire http access log), unless user enable logging of accesses (new configurable option disabled by default?) -

Monitorix should always log all requests regardless if they are failed or successful. The browser needs to do several requests in order to complete the HTML received previously. It is important to be able to see all requests in order to track any future problem.

I can include a new option called `log_successful_requests` (set to `n` by default) to be able to disable logging successful requests. This way you will see failed requests only in your log.

This should reduce a lot the size of your log file.

**Comment by mikaku** [comment]
@slrslr, apply this patch to your local Monitorix and, please, let me know if it works as expected.

**Comment by slrslr** [comment]
> @slrslr, apply this patch to your local Monitorix and, please, let me know if it works as expected.

Yes, when i use yours changed file /usr/lib/monitorix/HTTPServer.pm code and set:

```
<httpd_builtin>
...
        log_file = /var/log/monitorix-httpd
        log_successful_requests = n
...
```

restart service, it stop logging access lines into /var/log/monitorix-httpd so that works, even i think it is better to log only errors/notices by default, because:

> It is around 1000 log lines and 140kB per hour. 24000 lines and 3MB+ per day.
> -> using available iops, wearing down SSD and using non insignificant space

not by default waste resources. Thank you for the modification.

**Comment by mikaku** [comment]
Thank you very much.
