### ISSUE TITLE
FS graph not showing some disk

### ISSUE THREAD

**Issue by vatprcyq** [mikaku/Monitorix#456]
I have a SSD mountpoint is /miku
but set at monitorix not graphing at FS graph.
Config:
# FS graph
# -----------------------------------------------------------------------------
<fs>
        <list>
                0 = /, swap, /miku
        </list>
        <desc>
        </desc>
        <devmap>
 /miku = /dev/sdb
        </devmap>
        rigid = 2, 2, 2
        limit = 1000, 1000, 1000
        <alerts>
        </alerts>
</fs>
df output:
df
文件系统          1K的块    已用      可用 已用% 挂载点
udev             1979456       0   1979456    0% /dev
tmpfs             399744    6608    393136    2% /run
/dev/sda1      121499304 5602932 109678340    5% /
tmpfs            1998712       4   1998708    1% /dev/shm
tmpfs               5120       0      5120    0% /run/lock
/dev/sdb        15466496   41380  14887484    1% /miku
tmpfs              32000     276     31724    1% /var/cache/fontconfig
tmpfs             399740       0    399740    0% /run/user/1000

![image](https://github.com/mikaku/Monitorix/assets/25144151/2b11ebba-b65b-4302-9c3b-9520f66e79ba)

**Comment by vatprcyq** [comment]
config:
<fs>
        <list>
                0 = /, swap, /miku
        </list>
        <desc>
        </desc>
        <devmap>
 /miku = /dev/sdb
        </devmap>
        rigid = 2, 2, 2
        limit = 1000, 1000, 1000
        <alerts>
        </alerts>
</fs>

**Comment by vatprcyq** [comment]
<fs>
        <list>
                0 = /, swap, /miku
        </list>
        <desc>
        </desc>
        <devmap>
 /miku = /dev/sdb
        </devmap>
        rigid = 2, 2, 2
        limit = 1000, 1000, 1000
        <alerts>
        </alerts>
</fs>
![image](https://github.com/mikaku/Monitorix/assets/25144151/51352c2e-6629-4821-8491-51718dd69821)

**Comment by vatprcyq** [comment]
![image](https://github.com/mikaku/Monitorix/assets/25144151/7bd17320-a74b-4a5f-bcfb-8385f0150676)

**Comment by vatprcyq** [comment]
> (if you want to know how to format your messages correctly, just click the Markdown icon at the right-bottom corner of your message.)
> 
> Please, provide the output of the command `df`, just to make sure there is a `/miku` mount point.

➜  tianyi df /miku
文件系统         1K的块  已用     可用 已用% 挂载点
/dev/sdb       15466496 41824 14887136    1% /miku

**Comment by vatprcyq** [comment]
> (if you want to know how to format your messages correctly, just click the Markdown icon at the right-bottom corner of your message.)
> 
> Please, provide the output of the command `df`, just to make sure there is a `/miku` mount point.

文件系统          1K的块    已用      可用 已用% 挂载点
udev             1979456       0   1979456    0% /dev
tmpfs             399744    6704    393040    2% /run
/dev/sda1      121499304 5605168 109676104    5% /
tmpfs            1998712       4   1998708    1% /dev/shm
tmpfs               5120       0      5120    0% /run/lock
/dev/sdb        15466496   41856  14887104    1% /miku
tmpfs              32000     276     31724    1% /var/cache/fontconfig
tmpfs             399740       0    399740    0% /run/user/1000

**Comment by mikaku** [comment]
Hm,, did you see any error in the logfile?

Please, restart Monitorix, wait 5 minutes and paste here the resulting logfile right after your restarted Monitorix.

**Comment by mikaku** [comment]
You have an extra configuration file:

```
 Wed Jun 21 00:24:31 2023 - Loading extra configuration file '/etc/monitorix/conf.d/00-debian.conf'.
```

Make sure this file don't has a `<fs>` section that is overwriting your settings in `monitorix.conf`.

Please, learn how to configure Monitorix reading [this FAQ](https://www.monitorix.org/faq.html#Q107)

**Comment by mikaku** [comment]
If you don't need this file just remove it, and make sure it won't be installed again on a new release.

**Comment by mikaku** [comment]
If you have segfaults it mostly means you mixed library versions and now you have a broken system.
This has nothing to do with Monitorix.

**Comment by mikaku** [comment]
Sorry, I can't help you here.
You should seek for assistance in Debian community.
