### ISSUE TITLE
CSS Blocked

### ISSUE THREAD

**Issue by Vctrsnts** [mikaku/Monitorix#457]
Hi,

I install monitorix on GNU/Debian stable and working perfect, but when select one option ( day, week, etc.. ) the page is white not black when I select the black theme.

I watch the logs of Firefox and see this message:

`Blocked loading mixed active content http://my.ip.of.server/monitorix/css/black.css`

This error is in monitorix 3.15.0 and when I use old version ( 3.12 ) working perfect without error.

Where is the problem??

Thanks

**Comment by Saentist** [comment]
Is there a same problem in incognito tab?

**Comment by mikaku** [comment]
Make sure you restarted Monitorix after changing to black theme in your configuration file.
Also, as suggested by @Saentist, reset the memory cache of your Firefox.

Just let us know.

**Comment by Vctrsnts** [comment]
> Is there a same problem in incognito tab?

Hi,
In incognito tab work perfect.
Is a mistery think...

**Comment by Vctrsnts** [comment]
> Make sure you restarted Monitorix after changing to black theme in your configuration file. Also, as suggested by @Saentist, reset the memory cache of your Firefox.
> 
> Just let us know.

I reset the cache of firefox and open with the same problem.

The config file is the same that I use in the older version ( 3.12 ) not change anything and with the old version work perfect.

Only update the version: 3.12 to 3.15

**Comment by mikaku** [comment]
You said:

> ... the page is white not black when I select the black theme.

How did you change the theme without modifying the config file?

**Comment by Vctrsnts** [comment]
> You said:
> 
> > ... the page is white not black when I select the black theme.
> 
> How did you change the theme without modifying the config file?

No. In the config file:

```
title = "Monitorix"
hostname = Server
theme_color = black
refresh_rate = 150
iface_mode = graph
enable_zoom = y
netstats_in_bps = n
disable_javascript_void = n
temperature_scale = c
show_gaps = n
global_zoom = 1
max_historic_years = 1
accept_selfsigned_certs = y
image_format = PNG
enable_parallelizing = y
include_dir = /etc/monitorix/conf.d
```

**Comment by mikaku** [comment]
Do you access to this server from another remote server using Multihost feature?

**Comment by Vctrsnts** [comment]
> Are you using the Monitorix Multihost feature from another server to see the graphs of this server?

No

I have to servers but acces the "monitorix" with 2 diferents ip's:

- server one --> ip one --> monitorix config one
- server two --> ip two --> monitorix config two

server one is unaware of the existence of server two.

**Comment by mikaku** [comment]
Please, paste an screen shot to see exactly what's your problem.

**Comment by Vctrsnts** [comment]
> Please, paste an screen shot to see exactly what's your problem.

<a href='https://postimg.cc/xNnq4ZWy' target='_blank'><img src='https://i.postimg.cc/xNnq4ZWy/Screenshot-2023-07-14-15-38-28.jpg' border='0' alt='Screenshot-2023-07-14-15-38-28'/></a>

See the image?

Thanks for all

**Comment by mikaku** [comment]
What means `Blocked loading mixed active content http://my.ip.of.server/monitorix/css/black.css`?

Please, check the same page using a different browser and also Firefox without any restriction.

**Comment by mikaku** [comment]
It looks like your server has a misconfiguration using HTTPS and Firefox is blocking part of the contents received.

https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox

This has nothing to do with Monitorix.
You need to fix your web server.

**Comment by Vctrsnts** [comment]
Many thanks for everything.

Now it works correctly.

And sorry for thinking that the problem was in monitorix.

Again, thanks for everything.
