### ISSUE TITLE
PostgreSQL permissions

### ISSUE THREAD

**Issue by Clover2k** [mikaku/Monitorix#458]
I'm trying to enable PostgreSQL statistics on monitorix, I created a user and grant pg_monitor and pg_read_all_data rights but it doesn't work... however if I assign administrator rights like the postgres user it works.

Exactly what rights are needed? or does it really need administrator rights?

**Comment by mikaku** [comment]
@Clover2k, are you using the latest Monitorix version 3.15.0?
(latest Monitorix version fixes what it seems to me the same as in the issue #384).

**Comment by Clover2k** [comment]
Here was the trick!
I had installed version 3.14.0-1 from the ubuntu repositories, installing the latest version 3.15.0 using the deb file from the official site solved the problem.

I also revoked the pg_read_all_data permission which seems to be unnecessary, pg_monitor is enough for it to work.

many thanks mikaku
