### ISSUE TITLE
Processes statistics, memory usage

### ISSUE THREAD

**Issue by DSmidge** [mikaku/Monitorix#459]
Hi, I have a problem with Memory usage tracking in Process statistics. As I understand the command "ps -eo pid,comm,command | grep php-fpm" is used for getting the data. So I used "ps -eo size,pid,user,comm,command --sort -size | awk '{ hr=$1/1024 ; printf("%13.2f Mb ",hr) } { for ( x=4 ; x<=NF ; x++ ) { printf("%s ",$x) } print "" }' | grep php-fpm" that I found online that shows the memory usage.

The result is ~ 20b Mb (I assume the command means B and not b):
49.55 Mb php-fpm8.1 php-fpm: pool www
45.04 Mb php-fpm8.1 php-fpm: pool www
39.24 Mb php-fpm8.1 php-fpm: pool www
38.86 Mb php-fpm8.1 php-fpm: pool www
38.04 Mb php-fpm8.1 php-fpm: pool www
37.07 Mb php-fpm8.1 php-fpm: pool www
36.79 Mb php-fpm8.1 php-fpm: pool www
34.62 Mb php-fpm8.1 php-fpm: pool www
 7.32 Mb php-fpm8.1 php-fpm: master process (/etc/php/8.1/fpm/php-fpm.conf)

But in the graph it fluctuates between 1 GB and 4 GB. I always thought there is something wrong with my php-fpm configuration but I am not sure anymore.
apache2 = command says 500 Mb, but in the graph it says 50 GB
mariadb = command says 1200 Mb but in the graph it shows 800 MB
clam = command says 1400 Mb and the graph shows 1400 MB

The value for System load average and usage, Memory allocation, Used is 3 GB. And is not fluctuating as the php-fpm process.
I believe the total Usage must be right and that there is a problem with the Processes statistics.

The installed version is 3.15.0, running on Ubuntu 22.04.

**Comment by DSmidge** [comment]
A looked into https://github.com/mikaku/Monitorix/blob/master/lib/process.pm and "man proc" and found that Monitorix is displaying virtual memory: https://serverfault.com/questions/138427/what-does-virtual-memory-size-in-top-mean
I think it wold be better to use "ps -eo pid,size,comm,command | grep php-fpm". As stated in "man ps": size = memory size in kilobytes.

**Comment by mikaku** [comment]
> As I understand the command "ps -eo pid,comm,command | grep php-fpm" is used for getting the data.

No, this is only used to check if the process is actually running:

https://github.com/mikaku/Monitorix/blob/ffaa2b4d00f55895836096933b85cabdbc834f96/lib/process.pm#L58-L59

Process' data is gathered from different places.

> A looked into https://github.com/mikaku/Monitorix/blob/master/lib/process.pm and "man proc" and found that Monitorix is displaying virtual memory:

According the following lines, Monitorix is using the value in the RSS field from the `/proc/<PID>/stat` file:

https://github.com/mikaku/Monitorix/blob/ffaa2b4d00f55895836096933b85cabdbc834f96/lib/process.pm#L112-L115

Why do you think Monitorix is displaying virtual memory?
(don't let the variable name `$v_mem` fool you).

Example
---
![process_mem](https://github.com/mikaku/Monitorix/assets/829885/a2ef0ece-b3e7-458e-a302-592654eaef3c)

Using `top` here to have a list of processes sorted by their RSS value (`RES` column).

```
# top -b -n 1 -o RES 
top - 18:08:04 up 2 days,  7:56,  1 user,  load average: 0.16, 0.14, 0.16
Tasks: 254 total,   1 running, 253 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4.6 us,  3.1 sy,  0.0 ni, 92.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   7763.1 total,    783.3 free,   4034.7 used,   2945.1 buff/cache
MiB Swap:   2048.0 total,   1944.2 free,    103.8 used.   3187.0 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
    876 clamscan  20   0 2227044   1.3g   7936 S   0.0  17.5   1:57.01 clamd
    999 mysql     20   0 4516684 403840  15836 S   0.0   5.1   2:50.14 mysqld
 819232 root      20   0  267068 146404  11440 S   0.0   1.8   0:01.68 MailScanner: wa
 843504 root      20   0  266140 145440  11440 S   0.0   1.8   0:01.34 MailScanner: wa
 827585 root      20   0  266176 145376  11440 S   0.0   1.8   0:01.61 MailScanner: wa
 848266 root      20   0  265920 145188  11440 S   0.0   1.8   0:01.46 MailScanner: wa
 851280 root      20   0  261312 143744  11292 S   0.0   1.8   0:01.23 MailScanner: wa
   1410 root      20   0  233904  66828  13856 S   0.0   0.8  12:03.78 /usr/bin/monito
    562 root      20   0  170456  63932  57884 S   0.0   0.8   0:40.96 systemd-journal
    709 grmilter  20   0  810348  61968   7384 S   0.0   0.8   0:09.00 milter-greylist
    848 named     20   0  467500  60468   7600 S   0.0   0.8   1:38.03 named
 373175 apache    20   0  580180  59716  22648 S   0.0   0.8   0:20.39 php-fpm
    880 apache    20   0  580444  59584  22324 S   0.0   0.7   0:20.33 php-fpm
   7511 apache    20   0  579268  59540  22568 S   0.0   0.7   0:04.22 php-fpm
    882 apache    20   0  578420  59436  22168 S   0.0   0.7   0:22.14 php-fpm
    884 apache    20   0  578180  59280  22236 S   0.0   0.7   0:15.74 php-fpm
    881 apache    20   0  578148  59052  22136 S   0.0   0.7   0:15.78 php-fpm
  55376 apache    20   0  577156  58788  21852 S   0.0   0.7   0:01.38 php-fpm
 336552 apache    20   0  577160  58488  21720 S   0.0   0.7   0:01.80 php-fpm
   3278 apache    20   0  575108  57352  22428 S   0.0   0.7   0:02.91 php-fpm
 338787 apache    20   0  577088  57272  22624 S   0.0   0.7   0:01.32 php-fpm
 558927 apache    20   0  577164  56856  21996 S   0.0   0.7   0:01.31 php-fpm
 623798 apache    20   0  575112  54952  22140 S   0.0   0.7   0:00.70 php-fpm
   7598 apache    20   0  573064  54344  21672 S   0.0   0.7   0:00.88 php-fpm
 559020 apache    20   0  573064  52972  22140 S   0.0   0.7   0:04.94 php-fpm
 351871 apache    20   0  498232  51316  19580 S   0.0   0.6   0:00.90 php-fpm
    819 root      20   0 2417772  49948  25040 S   0.0   0.6  23:38.20 fail2ban-server
 625179 apache    20   0  494140  47532  19800 S   0.0   0.6   0:00.87 php-fpm
   3008 apache    20   0  565972  47472  22656 S   0.0   0.6   0:06.25 php-fpm
   1554 apache    20   0 2711796  43560  11036 S   0.0   0.5   1:19.46 httpd
 529258 apache    20   0  561788  41364  22696 S   0.0   0.5   0:09.45 php-fpm
   2935 apache    20   0 2580656  39936  11052 S   0.0   0.5   1:17.17 httpd
    883 apache    20   0  559708  38872  22432 S   0.0   0.5   0:23.59 php-fpm
   1553 apache    20   0 2515128  36868  11076 S   0.0   0.5   1:29.23 httpd
   1552 apache    20   0 2515128  36856  11084 S   0.0   0.5   2:00.24 httpd
  54829 apache    20   0 2515120  36536  11080 S   0.0   0.5   1:27.32 httpd
 326396 apache    20   0 2580656  35556  10912 S   0.0   0.4   0:29.24 httpd
    812 root      20   0  470820  34768  26012 S   0.0   0.4   0:09.54 php-fpm
 326859 apache    20   0 2515120  33980  10788 S   0.0   0.4   0:31.75 httpd
 326861 apache    20   0 2580656  33968  10788 S   0.0   0.4   0:32.65 httpd
 326858 apache    20   0 2515120  33712  10788 S   0.0   0.4   0:28.68 httpd
 326463 apache    20   0 2515120  33520  10788 S   0.0   0.4   0:27.95 httpd
 326594 apache    20   0 2515120  33304  10788 S   0.0   0.4   0:28.81 httpd
 363394 apache    20   0  552584  33304  22892 S   0.0   0.4   0:05.68 php-fpm
 326462 apache    20   0 2580656  33008  10788 S   0.0   0.4   0:27.95 httpd
[...]
```

As you can see, if we get the values from the column RES (which corresponds to RSS), the total memory used matches[^1] with the graph above:

[^1]: There are small differences because the graph shows average values taken some minutes before I executed the command lines.

```
# top -b -n 1 -o RES | grep httpd | awk '{sum+=$6;} END{print sum;}'
574044
# top -b -n 1 -o RES | grep MailScanner | awk '{sum+=$6;} END{print sum;}'
754264
# top -b -n 1 -o RES | grep fail2ban-server | awk '{sum+=$6;} END{print sum;}'
50276
# top -b -n 1 -o RES | grep mysqld | awk '{sum+=$6;} END{print sum;}'
403840
# top -b -n 1 -o RES | grep proftpd | awk '{sum+=$6;} END{print sum;}'
10440
[root@www ~]# top -b -n 1 -o RES | grep clamd | awk '{sum+=$6;} END{print sum;}'
1.3[g]
# top -b -n 1 -o RES | grep imap | awk '{sum+=$6;} END{print sum;}'
105708
# top -b -n 1 -o RES | grep sendmail | awk '{sum+=$6;} END{print sum;}'
14056
[root@www ~]# top -b -n 1 -o RES | grep named | awk '{sum+=$6;} END{print sum;}'
60204
# top -b -n 1 -o RES | grep /usr/bin/monito | awk '{sum+=$6;} END{print sum;}'
66828
```

All the values look consistent with `top`.

**Comment by DSmidge** [comment]
Hi,

thank you for responding to my issue.

Here are my screenshots - from System load average and usage:
![Screenshot 2023-10-15 215616](https://github.com/mikaku/Monitorix/assets/3962487/1a8bf7ff-28d7-4426-b85d-061538fa645a)

And from Processes statistics:
![Screenshot 2023-10-15 215639](https://github.com/mikaku/Monitorix/assets/3962487/ef65149d-f83c-4a80-b560-3de4126fe617)

I assume that the memory used (red) 1st graph should be larger or equal to the memory usage in process statistics?
But that is not the case in my case. :) Actual usage by php-fpm is around 250 MB, but the graph shows around 3000 MB.

But in "top" I get:
![Screenshot 2023-10-15 215813](https://github.com/mikaku/Monitorix/assets/3962487/224e6b1c-674c-4a67-b681-4012c9aa30c3)
So that is 40% of total memory which is around 3000 MB. So your graphs seems correct.

Sorry for the false report.

**Comment by DSmidge** [comment]
Closed.
