### ISSUE TITLE
Wrong voltage unit of the motherboard sensors (lm-sensors)

### ISSUE THREAD

**Issue by ostasevych** [mikaku/Monitorix#461]
Hi! I found that the volts for motherboard in lm-sensors group represents  a wrong unit value and consequently represented mistakenly on the chart.

Please, have a look at this chart:
![image](https://github.com/mikaku/Monitorix/assets/5199030/41bdfdf6-80ae-459d-a1d6-23e9e252fbd4)
So, the Y axis shows Volts, and the Vcore value is estimated sometimes in mV, and sometimes in V what confuses the rendering engine, I suppose:
![image](https://github.com/mikaku/Monitorix/assets/5199030/a7afa779-a7c3-45f2-9d37-9124e03211a0)
![image](https://github.com/mikaku/Monitorix/assets/5199030/593ead1f-0423-4b86-97f9-ad6e7851a8a2)
 
My suggestion is to show in V, but not in the mV.

**Comment by mikaku** [comment]
Have check if It is possible to configure `lm_sensors` to force always to show the Volts with the same unit?

**Comment by mikaku** [comment]
Closing due to no response for two weeks.

If you still need more information, please add a comment and the issue can be reopened.
