### ISSUE TITLE
Graphs erroring out

### ISSUE THREAD

**Issue by Coyne159** [mikaku/Monitorix#468]
Hi, Im running monitorix on a jetson nano orion running ubuntu 20.04.6. When I load up the web UI it all works until where its supposed to show the graphs and I get this error. "ERROR: while graphing /var/lib/monitorix/www//imgs/system1.1day.png: the first entry to fetch should be after 1980 (-80680) ERROR: while graphing /var/lib/monitorix/www//imgs/system1z.1day.png: the first entry to fetch should be after 1980 (-80680)  ERROR: while graphing /var/lib/monitorix/www//imgs/system2.1day.png: the first entry to fetch should be after 1980 (-80680) ERROR: while graphing /var/lib/monitorix/www//imgs/system2z.1day.png: the first entry to fetch should be after 1980 (-80680)." When I look in the folder there's nothing, but if I run sudo apt update its fixes it until I restart it and this is a problem because it gets rebooted a lot. Also where this is going to be deployed I will not have an internet connection.

**Comment by mikaku** [comment]
Make sure your system date is up to date by running the command `date`. These type of devices might come without any internal clock and so on every new boot the system date starts at zero seconds, which corresponds to January 1, 1970.

If that's your case, you might want to set the date at boot to something like January 1, 2024:

```
# date -s "Jan 01 2024 00:00"
```

**Comment by Coyne159** [comment]
ok that fixed it thank you .
