### ISSUE TITLE
Request : port feature with ipv6

### ISSUE THREAD

**Issue by Tarjaizaid** [mikaku/Monitorix#67]
Hello,

The "port" feature make graph with iptables (monitorix_*) (ipv4), the ipv6 (ipv6tables) graph not support.

Could You add this feature ?

Thanks
Tarjaizaid

**Comment by mikaku** [comment]
Please, check the new code (`lib/ports.pm` and `/lib/Monitorix.pm`) and let me know if that works as expected.

Thanks.

**Comment by Tarjaizaid** [comment]
Hello,

Thanks for your work.

i've tested the feature.

When i've restart monitorix, i've this errors :

Sat Feb 21 17:48:20 2015 - Exiting.
Sat Feb 21 17:48:23 2015 - Starting Monitorix version 3.6.0 (pid 1214).
Sat Feb 21 17:48:23 2015 - Loaded main configuration file
'/etc/monitorix/monitorix.conf'.
Sat Feb 21 17:48:23 2015 - Loading extra configuration file
'/etc/monitorix/conf.d/00-debian.conf'.
Sat Feb 21 17:48:23 2015 - Loading extra configuration file
'/etc/monitorix/conf.d/50-perso.conf'.
Use of uninitialized value in concatenation (.) or string at
/usr/lib/monitorix/Monitorix.pm line 317.
Use of uninitialized value in concatenation (.) or string at
/usr/lib/monitorix/Monitorix.pm line 318.
Sat Feb 21 17:48:23 2015 - Initializing graphs.
Use of uninitialized value in concatenation (.) or string at
/usr/lib/monitorix/port.pm line 144.
Use of uninitialized value in concatenation (.) or string at
/usr/lib/monitorix/port.pm line 144.
Use of uninitialized value in concatenation (.) or string at
/usr/lib/monitorix/port.pm line 144.
Use of uninitialized value in concatenation (.) or string at
/usr/lib/monitorix/port.pm line 144.
Use of uninitialized value in concatenation (.) or string at
/usr/lib/monitorix/port.pm line 146.
Sat Feb 21 17:48:23 2015 - Generating the 'index.html' file.
Sat Feb 21 17:48:23 2015 - Started built-in HTTP server (pid 1240).
Sat Feb 21 17:48:23 2015 - Ok, ready.
Sat Feb 21 17:48:23 2015 - WARNING: the built-in HTTP server has
authentication disabled.

And, when we use all6 option, i've this error :

ip6tables v1.4.14: unknown option "--sport"
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.4.14: unknown option "--sport"
Try `ip6tables -h' or 'ip6tables --help' for more information.

Thx

2015-02-16 18:02 GMT+01:00 Jordi Sanfeliu <notifications@github.com>:

**Comment by mikaku** [comment]
Can you please paste the `<port>` section of your configuration file?

**Comment by Tarjaizaid** [comment]
<port>
        max = 9
        rule = 24000
        list = 5565,5560,5555,4000
        <desc>
                5555   = Test1,    udp, in, 0, 1000
                5560   = Test2,    tcp, in, 0, 1000
                5565   = Test3,    tcp, in, 0, 1000
                4000   = TEST6, tcp6,in,0,1000
        </desc>
        graphs_per_row = 3
</port>


2015-02-21 18:18 GMT+01:00 Jordi Sanfeliu <notifications@github.com>:

**Comment by Tarjaizaid** [comment]
And, in monitorix log file, i've many log with

Use of uninitialized value in concatenation (.) or string at
/usr/lib/monitorix/port.pm line 209.
Use of uninitialized value in concatenation (.) or string at
/usr/lib/monitorix/port.pm line 210.

2015-02-21 18:43 GMT+01:00 Sylvain Tgz <tarjaizaid@gmail.com>:

**Comment by mikaku** [comment]
OK, I've just used the same '<port>' section you pasted above and I've not got any of the error messages you also pasted above. All is working finely.

Please, make sure you upgraded correctly your 3.6.0 version to the latest commit of master branch (not only the `port,pm` module).

Thanks.

**Comment by Tarjaizaid** [comment]
Hello,

Sorry, i've only copy lib/ports.pm and /lib/Monitorix.pm.

After copy the repostory, error "Use of uninitialized value in
concatenation" isn't present.

If i use all6 option, i've always this error :
ip6tables v1.4.14: unknown option "--sport"

thx


2015-02-23 10:07 GMT+01:00 Jordi Sanfeliu <notifications@github.com>:

**Comment by mikaku** [comment]
`iptables` requires a specific protocol when using source port numbering. So, `all` and `all6` are no longer valid protocol names in that graph, instead, use `tcp` or `tcp6` and `udp` or `udp6`.

Thanks.
