### ISSUE TITLE
Port.pm doesn't wait if iptables is locked by another process

### ISSUE THREAD

**Issue by atika** [mikaku/Monitorix#73]
Hi. I found this in my monitorix logs (Ubuntu trusty) :

```
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Use of uninitialized value within @i_in in concatenation (.) or string at /usr/lib/monitorix/port.pm line 278.
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/port.pm line 278.
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/port.pm line 278.
Use of uninitialized value in concatenation (.) or string at /usr/lib/monitorix/port.pm line 278.
```

**Comment by mikaku** [comment]
Hi,

Can you please tell me your `iptables` version?

Thanks.

**Comment by atika** [comment]
Hi,
It's ``iptables v1.4.21`` on ``Ubuntu Trusty 14.04``. I having the same problem on my scripts failing when Iptables was used by another process, I have added the ``--wait`` option, it seems to work now.

**Comment by mikaku** [comment]
Please, check the last commit and let me know if it works as expected.
Thanks.

**Comment by atika** [comment]
Hi. I have updated all files and I no longer have the error messages in the logs. It's seem to work. I do not know if I can test something else or run the script manually. Thanks.
I have another message in the logs, I create a new issue for it.

**Comment by mikaku** [comment]
OK, let's close this one.
