### ISSUE TITLE
What is the performance hit by installing monitorix ?

### ISSUE THREAD

**Issue by changwuf31** [mikaku/Monitorix#75]
Hi, monitorix looks lightweight and simple. 

Anyway, I wonder how much of a performance hit if say I use it to monitor mysql instance ? 

How are the metrics sent, if I'm using to monitor around 20 servers ? I mean, is monitorix using a distributed system (client actively send metrics and data to the server ?) or is it centralized (server is the one who actively request data from client ?)

And what if I'm adding and removing server, will the main server recognize the new server and the deleted server ?

**Comment by mikaku** [comment]
Hi changwuf31,

> Anyway, I wonder how much of a performance hit if say I use it to monitor mysql instance ?

Monitorix connects to a MySQL server on every minute and it just issue the commands `show global status` and `show variables`. I haven't experienced any performance degradation on none of my servers.

> How are the metrics sent, if I'm using to monitor around 20 servers ?

If you are using the `Multihost` feature you need to install Monitorix on every server, and currently, it's your local browser who connects to each remote server to get the graphs. This is not the best approach and will change in the future to centralize in one server the graph collecting.

Please, read http://www.monitorix.org/faq.html#Q112 to know more about the `Multihost` feature.

Thanks.

**Comment by changwuf31** [comment]
@mikaku 
Thanks for the detailed explanation :+1:
