### ISSUE TITLE
Problem with URL

### ISSUE THREAD

**Issue by atika** [mikaku/Monitorix#76]
I have a problem accessing Monitorix configured with built-in server, it worked before, I don't know is a issue or not. The problem is URLs are malformed.

__Command line__

```shell
./monitorix.cgi mode=localhost graph=_system1 when=day color=black
```
I get Images URLs like this : ```http:////imgs/system1.1day.png```

__And from the webpage__

```
http://127.0.0.1:8080/cgi/monitorix.cgi?mode=localhost&graph=_system1&when=1day&color=black
```

I get Images URLs like this : ``http://127.0.0.1//imgs/system1.1day.png``

__My Config:__
```
base_dir = /var/lib/monitorix/www/
base_lib = /var/lib/monitorix/
base_url = /
base_cgi = /cgi

<httpd_builtin>
    enabled = y
    host =
    port = 8080
    user = nobody
    group = nobody
    log_file = /var/log/monitorix-httpd
    hosts_deny =
    hosts_allow =
    <auth>
        enabled = y
        msg = Monitorix: Restricted access
        htpasswd = /var/lib/monitorix/.htpasswd
    </auth>
</httpd_builtin>
```
And changing ``host`` seem to do nothing…
I use an ssh tunnel: __127.0.0.1:9090 <-> remote:8080__

**Comment by atika** [comment]
Ok sorry, I searched a moment, and I just found where the problem are, just after posting my message. I am using a Local HTTP Proxy and I don't know what's happening with, it started to made mistakes.
The problem with command line still persists (just for the url, not for page and image generation), and for the webpage, URL are now like this : ```http://127.0.0.1:9090//imgs/system3.1day.png``` (double slash) but work on the browser

**Comment by mikaku** [comment]
Hi,

Yes, I've been making some tests here and all is working fine with the same configuration as you:

```
base_dir = /var/lib/monitorix/www/
base_lib = /var/lib/monitorix/
base_url = /
base_cgi = /cgi
```

And with command line `./monitorix.cgi mode=localhost graph=_system1 when=day color=black` all images have a good prefix `http://127.0.0.1//imgs/system1z.1day.png`. Yes, there is a double slash and that's because `monitorix.cgi` adds an extra slash just in case you forgot to add it in the configuration file. Is not a problem at all because multiple slashes in a path are automatically discarded.

Thanks.

**Comment by atika** [comment]
Hi, 
Thanks for you reply. 
From the command line I still have no hostname set : ```http:////imgs/system1.1day.png```
__I just added this option and it works:__ ```url_prefix_proxy```. I think, and sorry for my lack with Perl, is that monitorix.cgi try to compose an URL if ```url_prefix_proxy```doesn't exists, with environments variables ```$ENV{HTTP_HOST}```, who are empty from the command line.

**Comment by mikaku** [comment]
This code in `monitorix.cgi` should default to `http://127.0.0.1` in command line execution:

``` Perl
$config{url} = ($config{url_prefix_proxy} || "");
if(!$config{url}) {
        $config{url} = ($ENV{HTTPS} || ($config{httpd_builtin}->{https_url} || "n") eq "y") ? "https://" . $ENV{HTTP_HOST} : "http://" . $ENV{HTTP_HOST};
        $config{hostname} = $config{hostname} || $ENV{SERVER_NAME};
        if(!($config{hostname})) {      # called from the command line
                $config{hostname} = "127.0.0.1";
                $config{url} = "http://127.0.0.1";
        }
}
```

`$config{hostname}` will be empty because `$ENV{SERVER_NAME}` is probably not defined in command line, so the assignments inside the `if(!($config{hostname})) {` will be executed.

At least, it works for me.

``` Perl
$ perl -e 'printf $ENV{SERVER_NAME} . "\n";'
```

Returns nothing.

**Comment by atika** [comment]
The reason is ```hostname``` is defined in my config file, and with the first line url is set to ```http://``` (empty url) (```$ENV{HTTP_HOST}``` doesn't exist) and did not enter on the last ```if```

**Comment by mikaku** [comment]
Why do you have defined the `hostname` option if you want to execute Monitorix from the command line?

**Comment by atika** [comment]
There was an option for the hostname, I set the hostname... :)  I connect to Monitorix from the browser but I wanted also to generate graph images from the command line and send them to an other host to have an overview. The purpose of this option is  to compose an url for images ?
But the ```url_prefix_proxy``` option resolved my problem, just I had to take a look at the code.
The initial problem when image was not displayed was that when my proxy is active, the server_name environment variable just display the hostname and suppress the port…

**Comment by mikaku** [comment]
The purpose of the `hostname` option is the ability to identify (and hide) the real host name of the server your are monitoring.

If that option prevents you to have a correct output from the command line, then I'd suggest you to have different configuration files; one to be used by Monitorix under normal circumstances, and another one to be used by when you execute it from the command line.

Regards.
