### ISSUE TITLE
hptemp fails to parse a temperature reading from 'hplog -t' because of a white space difference

### ISSUE THREAD

**Issue by hitgub** [mikaku/Monitorix#78]
The new Proliant DL380p Gen8 servers have introduced several new temperature sensors. 

For some reason *hplog* will output some readings of the sensors with one less white space. 
Monitorix is too sensitive to this difference and fails to process *hptemp*. 

A sample of the output is found here:
http://pastebin.com/k2giCm9J

When not using the shifted readings (4,5,6,7) *hptemp* is working fine. 
Please, fix this white space sensitivity. 

ps. Issue has been reported to HP also, maybe they will fix this non-consistent formatting between sensors.

**Comment by mikaku** [comment]
Thanks hitgub, as we have commented on IRC the best way is to rethink how Monitorix parses the `hplog` output.

I'll work on this and will submit a new version for testing as soon as possible.
Regards.

**Comment by mikaku** [comment]
hitgub,

Please, download the latest `hplog.pm` version from the master branch and let me know if that really fixes the problem.

Thanks.

**Comment by hitgub** [comment]
Problem solved, works as expected with the shifted lines, case can be closed, thank you again. :)
