### ISSUE TITLE
Wrong y axis title on apcupsd Time left graph

### ISSUE THREAD

**Issue by pr0ser** [mikaku/Monitorix#82]
apcupsd "Time left" graph has normally Minutes as the title for y axis, but when clicking the graph to get larger version the y axis title changes to "Volts". Should the larger graph also have the same title? This happens in 3.6.0 version.

![apcupsd05z 1day](https://cloud.githubusercontent.com/assets/11365982/6542056/741e24c6-c4f5-11e4-868f-b9a0c9456e22.png)

**Comment by mikaku** [comment]
pr0ser, you're right :-)

I'll fix that typo right now.
Thank you very much for your feedback!
