### ISSUE TITLE
Can't disable nvidia monitoring

### ISSUE THREAD

**Issue by skibbipl** [mikaku/Monitorix#83]
Hello,
I'm using debian packaged monitorix 3.7.0. Config data is configured to point ```/etc/monitorix/monitorix.conf```. I decided to put my specific config into ```/etc/monitorix/conf.d/00-debian.conf```. I've disabled nvidia in my custom config file, but the problem is that nvidia plugin is still generating following errors:
```
Can't exec "nvidia-smi": No such file or directory at /usr/lib/monitorix/Monitorix.pm line 177.
Monitorix::get_nvidia_data: ERROR: 'nvidia-smi' command is not installed.
```
Here is excerpt from ```monitorix.conf```:
```
<graph_enable>
        ....
        lmsens          = n
        nvidia          = n
        ....
</graph_enable>

```
And this is my ```00-debian.config```:
```
<graph_enable>
        ...
        lmsens          = y
        nvidia          = n
        ....
</graph_enable>
```
Why monitorix is constantly trying to access nvidia data? How to disable nvidia monitoring completely?

**Comment by mikaku** [comment]
Hello skibbipl,

This is because you have included the option `gpu0` in the `<list>` block of the `lmsens` graph, which is saying to Monitorix that you want to monitor your NVIDIA graphics card.

**Comment by skibbipl** [comment]
Thanks for clarification, but this means that monitorix is ignoring settings in my custom ```00-debian.conf``` file. In main config I have ```gpu0``` in ```lmsens``` graph, but I commented it out in my custom config. Shouldn't monitorix use the ```lmsens``` list from my custom config instead combining both lists?

**Comment by mikaku** [comment]
I'll take a look to it.
In the meatime what if you leave in blank such option:

```
        gpu0 =
```

**Comment by skibbipl** [comment]
Blank value seems to be working fine! Thanks!

**Comment by mikaku** [comment]
skibbipl, just for your information.

When Monitorix loads extra configuration files it only modifies the options that it finds in these extra configuration files. So, in your case, since it was unable to find the option `gpu0` it ended up using its original value in the main configuration file.

**Comment by skibbipl** [comment]
So if I want to disable an option enabled in original config file I just need to put an empty value to it?

**Comment by mikaku** [comment]
Exactly :)
