### ISSUE TITLE
Support of Postgresql

### ISSUE THREAD

**Issue by keyermann** [mikaku/Monitorix#84]
Hi,

Is there a way to support PostgreSql ?

Thank for your work !

**Comment by mikaku** [comment]
keyermann,

Yeah, I've it in my TODO list for some time but that's something I can't work now because I'm pretty busy at work lately.

I'd really like to have a new PostgreSQL graph for the next Monitorix version.
We could use this open issue to dump useful information (links, documents, etc.) when creating such graph.

Thanks.

**Comment by ingsoc** [comment]
Would be a welcome addition. +1

**Comment by lippling** [comment]
+1

**Comment by bluegroper** [comment]
another +1

**Comment by jordandcarter** [comment]
+1

**Comment by bluegroper** [comment]
Might be some useful background info.
https://wiki.postgresql.org/wiki/Monitoring

**Comment by fj11** [comment]
+1

**Comment by pejirout** [comment]
Would me much appreciated. +1

**Comment by Josue-T** [comment]
+1

**Comment by mikaku** [comment]
I've a new server which have PostgreSQL 11 installed on.
So I'll be able to start playing with it and develop the new 'pgsql.pm' module.

**Comment by mikaku** [comment]
OK, this is a screen shot of what will be the final aspect, probably:

![pgsql](https://user-images.githubusercontent.com/829885/103358041-f6cb0100-4ab4-11eb-9fbe-d37ced593821.png)

These values are global, which means that they represent the sum of the same values of all the databases in the PostgreSQL server where I'm doing the tests. I hope it's a fairly complete graph.

Any thoughts?

I plan to also include a way to be able to get an independent set of graphs for each database.

**Comment by mikaku** [comment]
This is, hopefully, the definitive graph which also includes statistics of three databases:
![pgsql](https://user-images.githubusercontent.com/829885/103643230-9cb6b980-4f54-11eb-99a7-1c10e36bd3b0.png)
