### ISSUE TITLE
wowza graphs not counting bandwidth correctly

### ISSUE THREAD

**Issue by bsyd** [mikaku/Monitorix#86]
wowza.pm contains 
```perl
$str = $e . $e2 . "msginbytes";
$msginbytes = $entry->{MessagesInBytesRate} - ($config->{wowza_hist}->{$str} || 0);
$msginbytes = 0 unless $msginbytes != $entry->{MessagesInBytesRate};
$msginbytes /= 60;
$config->{wowza_hist}->{$str} = $entry->{MessagesInBytesRate};

$str = $e . $e2 . "msgoutbytes";
$msgoutbytes = $entry->{MessagesOutBytesRate} - ($config->{wowza_hist}->{$str} || 0);
$msgoutbytes = 0 unless $msgoutbytes != $entry->{MessagesOutBytesRate};
$msgoutbytes /= 60;
$config->{wowza_hist}->{$str} = $entry->{MessagesOutBytesRate};
```
This is incorrect as it supposes that MessagesInBytesRate and MessagesOutBytesRate are counters.
In fact these are gauge values.  So these lines should be changed in 
```perl
$str = $e . $e2 . "msginbytes";
$msginbytes = $entry->{MessagesInBytesRate};
$config->{wowza_hist}->{$str} = $entry->{MessagesInBytesRate};

$str = $e . $e2 . "msgoutbytes";
$msgoutbytes = $entry->{MessagesOutBytesRate};
$config->{wowza_hist}->{$str} = $entry->{MessagesOutBytesRate};
```

**Comment by mikaku** [comment]
bsyd,

You're right. I've modified the code to treat MessagesInBytesRate and MessagesOutBytesRate as gauge values.

I've also removed the suffix `/s` in all these values and also in the y-axis label.

Please, test the new code in `wowza.pm` and let me know if that's what you expected.
Thanks.

**Comment by bsyd** [comment]
It looks OK for me, but why did you trash the "bits/s" logic ?

**Comment by mikaku** [comment]
Because it no longer means values/s since the values are saved and showed as they were collected. If you think that values/s would be better then I can re-introduce the division by 60.

Let me know.

**Comment by bsyd** [comment]
the values are bytes/second as currently delivered by the applications.  There is no need to divide by 60 (the values are already by seconds), but showing them as bit/s (configurable) like in the rest of the graphs is a plus.

**Comment by mikaku** [comment]
I see, OK, let me reintroduce all this code.

**Comment by mikaku** [comment]
Let me know if we can close this issue, so I can focus on #87.

**Comment by bsyd** [comment]
at first sight yes.
