### ISSUE TITLE
data collection stops when wowza config contains a missing application

### ISSUE THREAD

**Issue by bsyd** [mikaku/Monitorix#87]
I see this in the logs.
```
Can't use an undefined value as an ARRAY reference at /usr/lib/monitorix/wowza.pm line 555.
Can't use an undefined value as an ARRAY reference at /usr/lib/monitorix/wowza.pm line 555.
Can't use an undefined value as an ARRAY reference at /usr/lib/monitorix/wowza.pm line 555.
Thu Mar 26 20:19:00 2015 - wowza_update(): Not a HASH reference at /usr/lib/monitorix/wowza.pm line 341.
```
It happens for me when the last defined application (in the list after the wowza url in monitorix.conf) has been shutdown whitin wowza and returns no value in the connectionscount http call.

I don't know if the order is important (does this happen with less applications defined or if the stopped application is not last in the list ?) but data collection is dead after that.

**Comment by bsyd** [comment]
it also happens when the shutdown application is not last in the list and when there is less than 8 applications defined.

**Comment by bsyd** [comment]
simple test : add an inexistant application to the list.

**Comment by bsyd** [comment]
line numbers changed since the last commit, so here is the impacted code : 
```
Fri Mar 27 10:07:00 2015 - wowza_update(): Not a HASH reference at /usr/lib/monitorix/wowza.pm line 336.
```
```perl
    336                                         if(ref($entry->{ApplicationInstance}->{Stream}) eq "ARRAY") {
    337                                                 $instance = $entry->{ApplicationInstance}->{Stream}[0];
    338                                         } else {
    339                                                 $instance = $entry->{ApplicationInstance}->{Stream};
    340                                         }
```

**Comment by bsyd** [comment]
I changed the configuration to just one existing application, and this message comes every minute in the log.
So I will close this bug and open a new one with an updated title.

**Comment by mikaku** [comment]
OK
