### ISSUE TITLE
wowza shutdown applications are skipped. rrds garbled.

### ISSUE THREAD

**Issue by bsyd** [mikaku/Monitorix#89]
Sometimes wowza applications can be shut down (unloaded, automatically or manually).
When this happens, they disappear from the connectioncounts result.
This results in a garbled database, where the numbers are put in the wrong lines.

exemple `monitorix.conf` : 
```
<wowza>
        list = http://videostream.indostreamserver.com:8086/connectioncounts
        <desc>
                http://videostream.indostreamserver.com:8086/connectioncounts = unknown1, surautv, unknown2, tvmelayu
        </desc>
        rigid = 0, 0, 0, 0, 0
        limit = 100, 100, 100, 100, 100
</wowza>
```
Result : `surautv` numbers go in `unknown1`, and `tvmelayu` numbers go in `surautv`.

The correct result should be zero/null/NaN values for `unknown1` and `unknown2`, and the numbers correctly inserted at their [0-7] offset, mapped to the list defined in the configuration.

**Comment by mikaku** [comment]
I'll be out this weekend, so I'll take a look at it Monday.
Thanks.

**Comment by bsyd** [comment]
Take your time. I understand, I do the same.  I have a family.

Sydney.

**Comment by mikaku** [comment]
Sydney,

The last commit should fix this.
Just let me know, thanks.

**Comment by bsyd** [comment]
No, it still skips `unknown1` in the example given above (first argument in the list).

**Comment by mikaku** [comment]
It works for me now. The non-existent application now is appearing zero values while the rest is working normally.

**Comment by bsyd** [comment]
![image](https://cloud.githubusercontent.com/assets/3646417/6895694/2915e504-d6e3-11e4-90a4-8184bb4004f4.png)

does not seem good for me

**Comment by mikaku** [comment]
Since I'm using an external Wowza server, the only way for me to simulate an Application shutdown is just changing it to a non-existent name, but I'm not sure if that's the best way.

**Comment by bsyd** [comment]
That's what I do with the config listed in the first post.  Please try that config.
It uses your usual external server.

**Comment by mikaku** [comment]
(I'm now using the same config line, let's run it for a while)
I hate asking this but, did you restarted Monitorix after applying the last commit?

**Comment by mikaku** [comment]
![image](http://i.imgur.com/XHkfd8F.png)

Looks good here.

**Comment by bsyd** [comment]
yes, I restarted, and deleted /var/lib/monitorix/wowza.rrd for good measure.
Let's try again. Clean install, kept only config file.
![image](https://cloud.githubusercontent.com/assets/3646417/6898698/e994c5f8-d6fb-11e4-9636-88b7007efa48.png)
same result...
I don't know what's happening.

**Comment by bsyd** [comment]
I spotted the problem.
when I specify only one server, the results are good.
![image](https://cloud.githubusercontent.com/assets/3646417/6898779/4d18b51c-d6fc-11e4-9df7-2736eb4af861.png)
when I specify two servers, the second is not good.

**Comment by bsyd** [comment]
if you want to simulate multiple servers with the same server url, simply add a number or other garbage text at the end of /connectioncounts

**Comment by mikaku** [comment]
Ah thanks!, I was struggling with it :)

**Comment by mikaku** [comment]
Last commit should fix this.

**Comment by bsyd** [comment]
I confirm.
Closing bug.

**Comment by bsyd** [comment]
reopening.
I now got an error when switching configuration back to one server.
```
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/wowza.pm line 661.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/wowza.pm line 662.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/wowza.pm line 778.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/wowza.pm line 779.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/wowza.pm line 875.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/wowza.pm line 876.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/wowza.pm line 967.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/wowza.pm line 968.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/wowza.pm line 1059.
Use of uninitialized value in multiplication (*) at /usr/lib/monitorix/wowza.pm line 1060.
```

**Comment by bsyd** [comment]
closing again. there was a typo in my config.

**Comment by mikaku** [comment]
OK, thanks anyway.
