### ISSUE TITLE
support for Network UPS Tools (NUT) using upsc

### ISSUE THREAD

**Issue by frollic** [mikaku/Monitorix#95]
the command will output a set of values about the UPS and the batteries:

[root@boxs ~]# upsc powerwalker@localhost
battery.charge: 100
battery.voltage: 26.90
battery.voltage.high: 26.00
battery.voltage.low: 20.80
battery.voltage.nominal: 24.0
device.type: ups
driver.name: blazer_usb
driver.parameter.pollinterval: 2
driver.parameter.port: auto
driver.parameter.synchronous: no
driver.version: 2.7.3
driver.version.internal: 0.11
input.current.nominal: 5.0
input.frequency: 49.9
input.frequency.nominal: 50
input.voltage: 229.7
input.voltage.fault: 229.7
input.voltage.nominal: 230
output.voltage: 229.7
ups.beeper.status: enabled
ups.delay.shutdown: 30
ups.delay.start: 180
ups.load: 4
ups.productid: 5161
ups.status: OL
ups.type: offline / line interactive
ups.vendorid: 0665
[root@boxs ~]# 

powerwalker is the name of the UPS defined in NUT, and you can monitor 
UPSes on other hosts as well (<> localhost).

**Comment by mikaku** [comment]
I'll check if the values are similar to those collected from `apcupsd`, so I could use that graph as base during the development.

Thanks.

**Comment by mikaku** [comment]
I've created a new `nut.pm` module that collects almost the same information as the `apcupsd.pm` module but using the `upsc` command line.

Please, download it and let me now if it works as you expected.
Thanks.

**Comment by frollic** [comment]
Thnx!

How should I use it ? 
Simply replace the apcupsd.pm with this one ?

**Comment by mikaku** [comment]
No, just download the new `nut.pm` module and update your current `monitorix.conf` accordingly.

Please, take a look to the commit (above) to see the files that has been touched.
Regards.

**Comment by frollic** [comment]
Seems to work just fine!

![nut](https://cloud.githubusercontent.com/assets/7432497/8677627/6ac515ea-2a50-11e5-9c61-feae5c3cd1a7.jpg)

**Comment by mikaku** [comment]
Seems like your UPS lacks of some statistical data, anyway, looks nice.
I'll correct the shift in the values of the two main graphs.
Thanks.
