### ISSUE TITLE
Support of Exim4

### ISSUE THREAD

**Issue by g6323117** [mikaku/Monitorix#96]
Any possibility of supporting Exim4?

Maybe pflogsumm (Postfix) --> eximstats (Exim4)?

Thanks!!

**Comment by mikaku** [comment]
Hi,

As long as Exim4's `eximstats` give the same valid and consistent information than Sendmail's `mailstats` and Postfix's `pflogsumm.pl`, I don't see any reason why it couldn't be supported.

**Comment by g6323117** [comment]
Hi,
Here are some documentation, usage and sources of eximstats.
I'm pretty sure that it can output valid and consistent information just like mailstats.
I'm not that good at Perl, but I'm willing to help.
Let me now if you need a hand.

http://www.exim.org/exim-html-current/doc/html/spec_html/ch-exim_utilities.html#SECTmailstat
https://github.com/Exim/exim/blob/master/src/src/eximstats.src
http://manpages.ubuntu.com/manpages/vivid/en/man8/eximstats.8.html
http://www.inmotionhosting.com/support/email/exim/view-summary-of-mail-from-exim-mail-log
https://documentation.cpanel.net/display/ALD/View+Mail+Statistics+Summary

**Comment by mikaku** [comment]
Could you, please, pastebin (or send to me via email) the output of the `eximstats` command?
I need to figure out how it looks on a real environment with real data.

Make sure to hide all the sensible information.
Thanks.

**Comment by Comarco** [comment]
Hi, 
any progress was done on this ?
Still need some help with eximstats output ?

**Comment by mikaku** [comment]
@Comarco,

Hey, well ... it is currently in low priority because I need to figure out how it looks the output of the `eximstats` command.

Perhaps you might paste that information or send it to me by email.
Just let me know.

**Comment by Comarco** [comment]
On a very low activity server it looks like this
http://pastebin.com/QKcCKVSj

**Comment by mikaku** [comment]
Thanks for the log.
It looks like the must interesting part is in the top:

```
Grand total summary
-------------------
                                                                  At least one address
  TOTAL               Volume   Messages Addresses     Hosts      Delayed       Failed
  Received            2531KB       1050                   2     219 20.9%    435 41.4%
  Delivered           1677KB        615       615         2
  Rejects                            12                   1
```

I've some questions:
- It's possible to have the same report but more oriented to script than for human?
- It's possible to have a report of the current mail queue? (number of messages currently on queue and total size of the queue?

Thanks.

**Comment by mantaalex** [comment]
i don't know the answear for your first question but the second one is:
running this command on the server:
/usr/sbin/exim -bp

gives output:

4d  1.2K 1Ka6u5-00032Z-Eb <from@example.com>
          to@example.com

62h  1.2K 1KaRH0-0007QZ-B5 <from@example.com>
          to@example.com

3h   22K 1KbLHr-0004ev-An <from@example.com>
          to@example.com

for example

**Comment by mikaku** [comment]
@mantaalex,

So far, `exim -bp` is working and Monitorix is parsing correctly its output, which means that the two Queue graphs are showing good information.

Now it's time to start parsing the file `mainlog`, and also the output of `eximstats`.

**Comment by mikaku** [comment]
@mantaalex 

Please, when you're available, email me the output of the following command:

```
eximstats -h0 -ne -nr -nt -t0
```

**Comment by mantaalex** [comment]
i sended you mail note that it has errors:
eximstats /var/log/exim/mainlog -h0 -ne -nr -nt -t0 Failed to read -h0: No such file or directoryFailed to read -ne: No such file or directoryFailed to read -nr: No such file or directoryFailed to read -nt: No such file or directoryFailed to read -t0: No such file or directory Exim statistics from 2019-02-17 03:14:45 to 2019-02-20 20:00:01

but i mailed you the result i guess its the same as you had i'm off to my work you may look for your self ;) grz

**Comment by mikaku** [comment]
Sorry, i missed the log file in the command line, probably the entire command line should be:

```
`eximstats -h0 -ne -nr -nt -t0` /path/to/mainlog
```

**Comment by mantaalex** [comment]
Hey np can you check locally on my phone this is harder to do 😉 

Jordi Sanfeliu <notifications@github.com> schreef op 20 februari 2019 21:37:45 CET:
>Sorry, i missed the log file in the command line, probably the entire
>command line should be:
>
>```
>`eximstats -h0 -ne -nr -nt -t0` /path/to/mainlog
>```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mikaku/Monitorix/issues/96#issuecomment-465744335

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by mantaalex** [comment]
[root@gsi2 ~]# eximstats -h0 -ne -nr -nt -t0 /var/log/exim/mainlog

Exim statistics from 2019-02-17 03:14:45 to 2019-02-21 19:08:01

Grand total summary
-------------------
                                                                  At least one address
  TOTAL               Volume   Messages Addresses     Hosts      Delayed       Failed
  Received             175MB      12366                 258      19  0.2%     36  0.3%
  Delivered            174MB      12332     12332        35
  Rejects                           634                 151
  Temp Rejects                        2                   2

Time spent on the queue: all messages
-------------------------------------

Under   1m    12355  99.9%   99.9%
       15m        2   0.0%   99.9%
       30m        1   0.0%   99.9%
        1h        1   0.0%   99.9%
        3h        1   0.0%  100.0%
Over    1d        6   0.0%  100.0%

Time spent on the queue: messages with at least one remote delivery
-------------------------------------------------------------------

Under   1m      102  95.3%   95.3%
       15m        2   1.9%   97.2%
       30m        1   0.9%   98.1%
        1h        1   0.9%   99.1%
        3h        1   0.9%  100.0%

[root@gsi2 ~]#
and its fast this command

**Comment by mikaku** [comment]
Format correctly the output, or send me it directly to me.
Thanks.
